### ISSUE TITLE
Performance of Block Settings on every page load without caching

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#1005]
This was reported in https://github.com/woocommerce/woocommerce/issues/24590

Blocks requires certain settings/data to function, and this needs to be present anywhere a block may be used (so admin and frontend, regardless of user type). This is output to JSON inline on every page load.

This can be problematic if doing large queries such as getting terms, and counting post types.

Currently, the JSON is generated in Assets.php here:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/Assets.php#L86-L123

Most of this is harmless, with the exception of:

1. get_terms - this is querying all categories in the store and generating links for each.
2. wp_count_posts - less intensive but could still be cached.

We should look at either caching this data, using APIs instead as needed instead of grabbing data that may not be used, or making some of this conditonal.

**Comment by nerrad** [comment]
With the `wcSettings` refactor and the introduction of `AssetDataRegistry`.  We can refactor things so that block data is added by specific blocks needing it instead of via the legacy `Assets`.  I think this will surface the need for handling how we surface whether data is already registered (i.e. already has `terms`, or a `post count`, or maybe there's a set of core data that can just be indicated as "required" by a block).
