### ISSUE TITLE
Global Styles for Order Confirmation Summary Block

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#10118]
Support:

- Colours
- Typography

![Screenshot 2023-07-06 at 12 47 12](https://github.com/woocommerce/woocommerce-blocks/assets/90977/430a20c2-7d25-4846-acac-fd4bded775c7)

The unknown for this block is how to deal with the 2 variations in text here. There is a label (uppercase) as well as a value (bold). Can we style both separately without inner blocks? @nielslange?

**Comment by nielslange** [comment]
> The unknown for this block is how to deal with the 2 variations in text here. There is a label (uppercase) as well as a value (bold). Can we style both separately without inner blocks? @nielslange?

@mikejolley Based on the screenshot, we're dealing with `th` and `td`. To control the font width, we'd need the Typography settings. AFAIK, they only support the following elements at this time:
- Text
- Links
- Headings
- Captions
- Buttons

Apart from using inner blocks, we could propose individual styling of table elements in Gutenberg, or we could change `th` into a headline and `td` into a paragraph, div or span, so that we can apply different styles to these elements.

**Comment by mikejolley** [comment]
@nielslange Its not a table. It's just a list with a span and a strong element.

**Comment by nielslange** [comment]
> @nielslange Its not a table. It's just a list with a span and a strong element.

Thanks for clarifying this. Unfortunately, this does not change the outcome as we can only style the elements if they would live in separate inner blocks.
