### ISSUE TITLE
Order Summary Options

### ISSUE THREAD

**Issue by yachzo** [woocommerce/woocommerce-gutenberg-products-block#10173]
## What do you like about the Cart & Checkout blocks?
Its great to have an alternative to the shortcode, and the layout is better out of the box.
## What do you think is missing from the Cart & Checkout blocks?
I would like to see an option to turn off product descriptions in the order summary panel. Also, digital wallets aren't working with square. It may be on their end though.

**Comment by tarhi-saad** [comment]
We don't have the option to add/remove checkout fields. But, it is on our radar to add some interfaces (both user and code based) for achieving this functionality. We don't have a specific timeline for this because there're a lot of things that are still unknown, but we expect more updates during the months as we tackle this issue.

For the time being, I'm going to close this issue because there's nothing actionable we can do on it. Thank you for your feedback.
