### ISSUE TITLE
Inconsistent New Install behaviour for templates when using block themes

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#10530]
Original report:

https://wordpress.org/support/topic/woocommerce-blocks-checkout-by-default-after-updating-to-8-0/

New installs sometimes have a block based checkout page rather than a shortcode based checkout page. It is not yet clear if this affects all installs, or is a race condition. 

Migration on init:
https://github.com/woocommerce/woocommerce-blocks/blob/5c99f331cf3a42339f7326eded47612b40e7ee3d/src/BlockTemplatesController.php#L82

Install on init:
https://github.com/woocommerce/woocommerce/blob/106e15f74a20e45cec9b92dd150c5c18c2c0f9a8/plugins/woocommerce/includes/class-wc-install.php#L254C42-L254C55

If this is confirmed to be a race condition, we can look into skipping migration when `WC_Installing` is true.

cc @wavvves @ralucaStan

**Comment by eoinsav** [comment]
This happened last week (Thu, Aug 10th) to one of our partner sites on WordPress.com Business, which has an existing WooCommerce store set up and working.

It appears to have been triggered by an update to WooCommerce 8.0.1. It switched the Cart and Checkout pages from shortcode to Templates with the Cart and Checkout Blocks.

This caused a bit of a cascade of issues on the site.

p9MPsk-2WF-p2#comment-28306

**Comment by ralucaStan** [comment]
I've moved this to the current cycle. We have a lot of reports on it. @wavvves do you think you can take a look?

**Comment by ralucaStan** [comment]
There is a mention from a merchant who did not do a new install p1692102519465489/1691665009.939589-slack-C01DT6U03HC

**Comment by wavvves** [comment]
@mikejolley when you mention skipping migration, it is actually postponing it (not marking the has_migrated options) right?

Whether it is the root cause or not, I think this would be a useful failsafe mechanism to have, as pages might not exist yet and doesn't really make much sense attempting the migration on a request that is installing WC

**Comment by mikejolley** [comment]
@wavvves yes, postpone if WC is installing using the constant I mentioned.

**Comment by joshuatf** [comment]
It does seem likely that this is a race condition where `maybe_migrate_content` is possibly being run before WC pages have been created.

>This happened last week (Thu, Aug 10th) to one of our partner sites on WordPress.com Business, which has an existing WooCommerce store set up and working.

It's still unclear to me how this would happen.  I would imagine this site already had checkout and cart pages created.  Was this possibly due to a theme including a template file?

https://github.com/woocommerce/woocommerce-blocks/blob/5c99f331cf3a42339f7326eded47612b40e7ee3d/src/BlockTemplatesController.php#L82

This hook feels a little greedy to me as it's run on every single page despite being migratory in nature.  Is it possible to only run this during migration (update) or theme switch?

Some possible candidate hooks include `woocommerce_updated` and `switch_theme`.  The former would resolve the race condition if that's the root problem.  The `WC_INSTALLING` constant that @mikejolley mentioned is a good solution as well, though I'd lean slightly towards reducing how often this logic is hit and avoid using that constant as check if possible since it would defer these updates until the next request.

**Comment by wavvves** [comment]
I am now able to recreate this locally, on update and clean installs. The problem resides on saving the template customization, after a WP-CLI install/update, so migration actually runs but somehow doesn't save anything (I'm now debugging the reason for that). This happens on a normal request, since I have a fix in place to postpone it on WP/WC installs/updates, WP-CLI requests, maintenance mode on, etc.

I also agree choosing the timings for migration would be a better option, though there is no significant overhead on running on init, since it relies on autoloader options, so quick in-memory checks skips the migration. I would do it as a properly tested enhancement in the future, since we're pressed by time to fix it. Also changing that into a hooks solution, without extensive testing might introduce other bugs. For now we need to make sure migrations run and run properly.

**Comment by joshuatf** [comment]
>I would do it as a properly tested enhancement in the future, since we're pressed by time to fix it.

I think a quick fix is fine if we have one, but depending on what that fix is, it may require an equal amount of testing as switching to different hooks.  Also, if we defer the migration until the next request, this also has potential for unintended side effects.

If that turns out to be the case, I'd push for the correct implementation to avoid punting technical debt down the road.
