### ISSUE TITLE
New block theme templates override templates that are in the theme

### ISSUE THREAD

**Issue by carolinan** [woocommerce/woocommerce-gutenberg-products-block#10595]
## Describe the bug

WooCommerce 8+ includes new templates for block themes for the cart, checkout, and order confirmation, as described here:
https://developer.woocommerce.com/2023/08/08/woocommerce-8-0-0-released/

The new templates replace HTML block templates that are included in block themes.
Up until 8.0, a block theme could include a page template with the name page-cart.html, and that template would be assigned to the cart page according to the template hierarchy. The page-cart.html would be used on the front and in the Site Editor.

In 8.0, the template from the plugin is used, not the theme template. **This is a breaking visual change for existing websites because a different template and header template part is now loaded.**

In 8.0, it is also not possible to open the page from Admin > Pages, and re-assign the old theme template, because it does not open the block editor; it opens the Site Editor with the plugin **template**.

From testing, it seems like renaming the template from page-cart.html to cart.html works. But this is not expected. cart.html is not a template that is part of the template hierarchy; if this is the correct solution, it needs to be very clearly documented. And as a developer, I would appreciate a full list of what template maps to what, including the product archives, taxonomy, search, etc.

This is also a problem because a developer can change the template file name in the theme, but not all users will be able to repair their site by changing the template file name themselves.

(I am opening this issue here and not in the WooCommerce main repository because I believe any change needs to be first developed and tested as part of this plugin?.)

## To reproduce
Install and activate a block theme that has templates for the cart or checkout page.
The easiest way would be to activate Twenty Twenty-Three but add a new blank page-cart.html file inside the templates folder.
Then view the cart on the front and confirm that the plugin template is loaded.

## Expected behavior

I expect the theme templates to be used.

## Environment

WordPress version 6.3.0
WooCommerce Version 8.0.1
With and without WooCommerce Blocks development version, current trunk.

**Comment by mikejolley** [comment]
With the introduction of a dedicated template for both Cart and Checkout, the hierarchy has changed so that `checkout` has the upmost priority. I did experiment with supporting the previous page template through the use of the following:

```
	public function page_template_hierarchy( $templates ) {
		if ( $this->is_active_template() ) {
			$page_template_slug = 'page-' . $this->get_slug() . '.php';
			$page_template_index = array_search( $page_template_slug, $templates, true );

			if ( false !== $page_template_index ) {
				unset( $templates[ $page_template_index ]);
			}

			$templates = array_merge(
				[
					$page_template_slug,
					$this->get_slug() . '.php'
				],
				$templates
			);
		}
		return $templates;
	}
```

This did cause the page to pull in the contents of `page-checkout.html` from the theme, however, on the editing side it is more confusing because when you **edit** the `Cart` template, you see the template from the plugin, not the page template from the theme. You also get duplicates:

![Screenshot 2023-08-16 at 14 27 46](https://github.com/woocommerce/woocommerce-blocks/assets/90977/99cc8c04-c102-4249-b20d-28f0fc3c6fc7)

Since the pages are merely acting as placeholders here, I think it would be best to document the change rather than attempt to manipulate the page template hierarchy. As mentioned in the report, switching the theme template from `page-checkout.html` to `checkout.html` prevents the duplication and also overrides the plugin version of the template which is what is needed here. 

> From testing, it seems like renaming the template from page-cart.html to cart.html works. But this is not expected. cart.html is not a template that is part of the template hierarchy

It has been injected into the first position of the hierarchy. I believe the intention is to eventually deprecate and remove the cart and checkout "pages" and just support the template, but due to the complexities of supporting Block based and non Blocked based themes, this cannot yet happen. The page will act as a placeholder for the time being. There is a separate discussion needed (@wavvves @ralucaStan) to see if the pages should be completely hidden from view to avoid merchant confusion.

I am looking into the possibility of improving the migration routine to handle the content from the theme and move it into a customised template for cart/checkout because this use-case was missed.

**Comment by webmandesign** [comment]
Is there any way I can revert/remove/bypass this new functionality? Including removing the new "Cart", "Checkout", "Order confirmation" from Site Editor templates list and related template parts list?

The thing is I tried to port these templates to my theme, but have found issues:

1. The page title section in my theme pulls featured image from the post/page and as _I can no longer edit the Cart and Checkout page the old way, I can not set featured image for the page_. (Plus I would love to use the flexibility of custom templates my theme provides.)

2. The design of these new layouts doesn't match the rest of the WooCommerce elements in my theme. I am using `<!-- wp:woocommerce/legacy-template {"template":"XY"} /-->` approach in theme's WooCommerce templates, so basically effectively mismatching the design with these new blocks.  
Using legacy templates allows me to match the design of WooCommerce to my theme easily with the help of [a plugin I've created just for this purpose](https://wordpress.org/plugins/wc-theme-integration/).

3. I can not seem to be able to edit things in these templates. I get the lock icon everywhere. Is this normal or am I doing something wrong?
  
![wc8-cart](https://github.com/woocommerce/woocommerce-blocks/assets/2456735/f59cb593-0be0-4ef8-b97f-f755f128df9e)

So, this functionality is not mature enough for my needs now and I would appreciate to be able to use the previous Cart and Checkout page functionality in my block theme if possible. Thanks for any advice.

**Comment by ralucaStan** [comment]
Bringing in @pmcpinto for awarness

**Comment by mikejolley** [comment]
@webmandesign Are you not able to replace the cart/checkout blocks with a shortcode block instead? The cart and checkout shortcodes are still functional.

**Comment by ralucaStan** [comment]
> I can not seem to be able to edit things in these templates. I get the lock icon everywhere. Is this normal or am I doing something wrong?
@webmandesign 

The locks you are seeing are from the Cart block which does not support editing its content. There are some editing options if you select the Cart block;

> So, this functionality is not mature enough for my needs now and I would appreciate to be able to use the previous Cart and Checkout page functionality in my block theme if possible. Thanks for any advice.

If you would like to have the previous Cart and Checkout shortcode instead of the Cart/Checkout blocks you can easily edit the template to remove and replace them:

- Go to Appearance > Editor > Templates > Checkout
- Remove the Checkout block
- Insert the Shortcode block and write inside it [woocommerce_checkout]
- Save the template
- Things should work as before

**Comment by webmandesign** [comment]
@mikejolley Thanks for the tip. Yes, that works. But does not resolve the issue with editing the actual page and setting up featured image as once I click the edit page link it brings me to Site Editor.

**Comment by webmandesign** [comment]
@ralucaStan 

> The locks you are seeing are from the Cart block which does not support editing its content. There are some editing options if you select the Cart block;

Maybe I'm expecting too much in this stage. I thought that using blocks here allow me more customization such as setting up custom colors, widths, spacing, typography, layout.

But as it is not really the case (except some customizations), currently I see these new blocks as a complication of older approach in my specific case.

> If you would like to have the previous Cart and Checkout shortcode instead of the Cart/Checkout blocks you can easily edit the template to remove and replace them:

Yes, this works. But I still experience issue as I need to edit these templates in Site Editor even for a simple thing such as changing the page title or setting up a featured image (see [my previous comment](#issuecomment-1680798771)).

Also, with older approach I had a choice to use a custom page template. My theme provides a "No page title" template which I use for Cart page and "Content only" template which I use for Checkout page. It was a matter of simple choice on the page edit screen previously. Now if I want to recreate such page layouts, I basically need to recreate them from scratch for both Cart and Checkout template in Site Editor.

**Comment by ralucaStan** [comment]
> My theme provides a "No page title" template which I use for Cart page and "Content only" template which I use for Checkout page. It was a matter of simple choice on the page edit screen previously. Now if I want to recreate such page layouts, I basically need to recreate them from scratch for both Cart and Checkout template in Site Editor.

That is correct, you need to edit the templates in order to customize them as they come with a predefined structure for a distraction-free checkout. Removing the title on these templates is possible. You can select that block and remove it. You can also add custom content in the template by inserting a new block.

**Comment by ralucaStan** [comment]
> Maybe I'm expecting too much in this stage. I thought that using blocks here allow me more customization such as setting up custom colors, widths, spacing, typography, layout.

There are customizations you can do at the block level, however, not everything is customizable in order to protect the final look and feel of the checkout blocks experience.

<img width="1249" alt="Screenshot 2023-08-16 at 17 33 41" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/1efe4816-619b-4f4a-906a-e46cf81cac1d">

**Comment by ralucaStan** [comment]
@webmandesign if you have further questions on editing the Cart and Checkout blocks I recommend using the [Discussions section](https://github.com/woocommerce/woocommerce-blocks/discussions) to ask for advice

**Comment by webmandesign** [comment]
Found another issue with this approach. If I use a shortcode to bring up the old layout, I need to use the shortcode directly in the Cart/Checkout template content in Site Editor. I can not insert these as a template part or a pattern.

I prefer using template parts as that way I don't have to edit whole templates. But having the shortcode in a template part will not render the shortcode in the Cart/Checkout template.

**Comment by ralucaStan** [comment]
> I prefer using template parts as that way I don't have to edit whole templates. But having the shortcode in a template part will not render the shortcode in the Cart/Checkout template.

@webmandesign could you please create a separate issue for this with replication steps so that we can look at it separately.

**Comment by ralucaStan** [comment]
>  prefer using template parts as that way I don't have to edit whole templates. But having the shortcode in a template part will not render the shortcode in the Cart/Checkout template.

@webmandesign I was able to successfully add the checkout shortcode in a Template part and use it on the Checkout template.

**Comment by webmandesign** [comment]
@ralucaStan Indeed, it works, when the shortcode is inserted via template part only. If you use a block pattern, shortcode is not rendered: #10643

**Comment by webmandesign** [comment]
Is there a way to disable this whole behavior with Cart and Checkout template in block themes please?

I looked at the code at https://github.com/woocommerce/woocommerce-blocks/tree/v10.9.0/src/Templates but couldn't figure out the way of disabling this via my theme code.

I really prefer setting up content of cart and checkout page with previous approach of editing the actual pages.

Can you provide info why this new approach was introduced? 
What are the benefits of having these templates in comparison to pages?
Could the blocks used in those templates work when inserted directly into a page content maybe? (Basically replicating previous behavior of shortcodes with blocks.)

**Comment by joshuatf** [comment]
>Since the pages are merely acting as placeholders here, I think it would be best to document the change rather than attempt to manipulate the page template hierarchy. As mentioned in the report, switching the theme template from page-checkout.html to checkout.html prevents the duplication and also overrides the plugin version of the template which is what is needed here.

@mikejolley Potentially naive question, but is it possible to alias `page-checkout.html` to `checkout.html` or allow this to override the placeholder checkout template?  Or would this have other repercussions?

**Comment by webmandesign** [comment]
Could Cart and Checkout template be [registered as **custom templates**](https://github.com/woocommerce/woocommerce-blocks/issues/10654#issuecomment-1683407598) instead of **templates** that replace the actual pages? #10654

**Comment by mikejolley** [comment]
> Potentially naive question, but is it possible to alias page-checkout.html to checkout.html or allow this to override the placeholder checkout template? Or would this have other repercussions?

@joshuatf I did have a quick go but it seemed to introduce conflicts. Perhaps someone else from the team could try this next week (I am AFK). cc @ralucaStan I would prefer this too.

**Comment by ralucaStan** [comment]
Sure thing, we're going to handle it in a separate ticket! Thank you @mikejolley and @joshuatf

**Comment by ralucaStan** [comment]
> I really prefer setting up content of cart and checkout page with previous approach of editing the actual pages.

Thank you for your feedback @webmandesign.

> Can you provide info why this new approach was introduced?
> What are the benefits of having these templates in comparison to pages?

Before WooCommerce 8.0 Block Themes did not include templates for the cart and checkout page; this change was introduced to allow the benefits of site editing on these pages as well. You can learn more about [Block Themes](https://developer.wordpress.org/themes/block-themes/) and their benefits in [this article](https://wordpress.org/documentation/article/block-themes/) as well.

> Could the blocks used in those templates work when inserted directly into a page content maybe? (Basically replicating previous behavior of shortcodes with blocks.)

I am not sure I understand this question correctly so if you can move it to the Discussions board that would be great. My request is to use the Discussions board so that we can keep the discussion on this issue related to the template migration issues. 

Thank you so much.

**Comment by webmandesign** [comment]
@ralucaStan Thank you for pointing these out. I'm well aware of block themes approach as I am a theme developer, currently working on a block theme and that's why I experience these issues with new WC8 Cart and Checkout templates.

As requested, I've opened a new discussion at #10703

**Comment by ralucaStan** [comment]
A fix for this was shipped in [WooCommerce 8.0.3 Fix Release](https://developer.woocommerce.com/2023/08/29/woocommerce-8-0-3-fix-release/)

**Comment by webmandesign** [comment]
@ralucaStan I'm still experiencing the same [issues](https://github.com/woocommerce/woocommerce-blocks/issues?q=is%3Aissue+author%3Awebmandesign).

I've logged a [discussion issue](https://github.com/woocommerce/woocommerce-blocks/discussions/10703) as [requested](#issuecomment-1683869402), however nothing is being discussed there, nobody chimed in. Can you explain when I should use _bug report issue_ and when I should use _discussion issue_?

From my point of view this is a buggy behavior. (There is also a new related issue #10927 reported by other user.)

**Comment by webmandesign** [comment]
@carolinan Could you please provide your input at https://github.com/woocommerce/woocommerce-blocks/discussions/10703 if you get a chance. It seems we need to discuss this in a discussion issue so it gets traction to be reconsidered. Thanks!

**Comment by ralucaStan** [comment]
Hey @webmandesign @webmandesign that is correct. As this ticket is still open, a fix for it has not been shipped yet. But don't worry, we have been spending some time on the implementation of the templates and we landed on a solution that we are currently testing in https://github.com/woocommerce/woocommerce-blocks/pull/10773; it should land in the next version of WooCommerce.

> I've logged a https://github.com/woocommerce/woocommerce-blocks/discussions/10703 as https://github.com/woocommerce/woocommerce-blocks/issues/10595#issuecomment-1683869402, however nothing is being discussed there, nobody chimed in. Can you explain when I should use bug report issue and when I should use discussion issue?

Thank you again for taking the time to start a conversation about templates. I want to assure you that all feedback you shared after the WooCommerce 8.0 has reached the team and was considered while evaluating our approach. Discussions are for everyone to join. We took some time to analyze our implementation and the feedback received and we'll be back soon with a reply to your discussion.
