### ISSUE TITLE
Number of columns on  Safari

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce-gutenberg-products-block#1063]
**Describe the bug**

With the Hand-Picked products block, on Safari it shows 3 columns for  the first row instead of 4,  then a row of 4 and then a row of 1.

**To Reproduce**

1. Add the Hand-Picked Products block to the page.
2. Select 8 products and set it to have 4 columns.
3. Check the page on Safari

**Expected behavior**

It should show 2 rows of 4 columns each.

**Screenshots**

![](http://d.wedj.at/p5r3cT+)
**Image Link**: http://d.wedj.at/p5r3cT+

**WordPress (please complete the following information):**

* Core version: 5.2.4
* WooCommerce version: 3.7.1
* WooCommerce Blocks version: from core
* Site language: EN
* Any other plugins installed: just official WooCommerce plugins

**Desktop (please complete the following information):**

* OS: MacOs
* Browser: Safari
* Version 13.0.2 (14608.2.40.1.3)

**Comment by Aljullu** [comment]
Hi @SiR-DanieL, thanks for opening the issue. From the screenshot, I think you are using Storefront as the theme, is that right? Your issue seems to be the same as this one: https://github.com/woocommerce/storefront/issues/1197, which will be fixed in the next release (https://github.com/woocommerce/storefront/pull/1217).

I will close this issue, but feel free to reopen it if I got it wrong and it's a different thing.
