### ISSUE TITLE
MANCA CODICE FISCALE

### ISSUE THREAD

**Issue by TeoMely** [woocommerce/woocommerce-gutenberg-products-block#10742]
## What do you think is missing from the Cart & Checkout blocks? 
MANCA LA POSSIBILITA' DI AGGIUNGERE IL CODICE FISCALE.
SPERO PRESTO IN UN AGGIORNAMENTO

**Comment by tarhi-saad** [comment]
> MANCA LA POSSIBILITA' DI AGGIUNGERE IL CODICE FISCALE.
SPERO PRESTO IN UN AGGIORNAMENTO

Hello @TeoMely! 👋 Appreciate you bringing this to our attention. It seems you're referencing the addition of the VAT tax code field in the Checkout Block. We recognize this limitation and are actively working towards a resolution. For more context, this has been reported in prior discussions:
https://github.com/woocommerce/woocommerce-blocks/issues/3096
https://github.com/woocommerce/woocommerce-blocks/issues/3499
https://github.com/woocommerce/woocommerce-blocks/issues/4116

I'll be marking this issue as closed since it's already on our radar. However, feel free to add any further input on the existing threads.
