### ISSUE TITLE
New Attributes Filter block powered by Interactivity API

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gutenberg-products-block#10812]
We want to explore if we can utilize the interactivity API to power the interactions on the frontend for performance gain and better UX.

The filter will live inside a wrapper container called Collection Filters which the initial draft is created https://github.com/woocommerce/woocommerce-blocks/pull/10726

So for now we're creating new experimental filter that lives in assets/js/blocks/collection-filters/inner-blocks

**Comment by dinhtungdu** [comment]
We should ensure the new block covers this issue https://github.com/woocommerce/woocommerce-blocks/issues/8608

**Comment by dinhtungdu** [comment]
Currently, in https://github.com/woocommerce/woocommerce-blocks/pull/11191, Price Filter block defines a block attribute named `filterType`, Collection Filters block uses that attribute to build the final query for fetching product collection data (attribute count, price range...) from the Store API. To make it easier to write the filter blocks, the Collection Filters block also transforms the collection data into an Interactivity API store, so filter blocks don't have to fetch any data (that's why I called them view block). This works well for the Price Filter but creates an issue for the Attribute Filter block.

Attribute Filter block doesn't only need the store data, but also the term data. This leads to two options:
- Collection Filters block fetches the term data and passes it down: We will need the Attribute Filter block to define another block attribute, Collection Filters block needs another logic to fetch term data.
- We fetch the terms inside the Attribute Filter block, violating the view block definition, and potentially making third-party developers confused.

With these options in mind, we can either:
- Abandon the current direction, and only pass the product collection data down without processing (like we're doing on the `trunk`) => this is more straightforward and clearer, hence easier for third-party developers to grasp, but the filter blocks are more complex.
- Continue transforming the product collection data in the Collection Filters block, fetching additional data in filter blocks. This makes filter block implementation simpler and easier to maintain but can be confusing.
