### ISSUE TITLE
All Products inner blocks: add support for core blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1084]
Part of #898.

We want to allow users to add `paragraph` and `heading` blocks inside the _All Products_ cards. See discussion in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1047#discussion_r337174733.

**Comment by nerrad** [comment]
I'm going to move this out of the current sprint, because there's some ongoing discussion about the direction of All Products and this may impact what blocks we make available for inner blocks.

cc @LevinMedia , when you get a chance, can you leave a comment on this. My questions to you are:

- Do you think we'll want to expose a subset of GB core blocks for use with the inner blocks on the All Products bocks? If so, what.
- What are your thoughts on moving this to the backlog until it's clearer what path we want to take here?

**Comment by mikejolley** [comment]
This may be covered now by #2481 since inner block rendering supports core blocks.
