### ISSUE TITLE
Packeta checkout page compatibility

### ISSUE THREAD

**Issue by Fenri69** [woocommerce/woocommerce-gutenberg-products-block#11009]
Hello, I use for my shipping Packeta (Zasilkovna), plugin is Packeta, but it works only with default checkout page because the new checkout page from blocks does not use the webhooks the plugin needs. Can you improve it so it works? I realy like the Block checkout theme.

**Comment by Fenri69** [comment]
It is this plugin: https://wordpress.org/plugins/packeta/

Works only when i use [woocommerce_checkout] does not work with the Checkout from Blocks.

**Comment by nielslange** [comment]
Hello @Fenri69 👋

Thanks for reaching out. Currently, it's up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

I suggest reaching informing them about the incompatibility so that they can adjust the extension accordingly. I've also created woocommerce/woocommerce#42207 so that others are aware that this extension is currently not compatible with WooCommerce Blocks. 

As there are no action items for us, I'm going to close this issue for now. But please don't hesitate to reach out again if you have more questions or suggestions.
