### ISSUE TITLE
Remove Shipping calculator settings and link to the WooCommerce admin settings

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#11010]
Context pdFofs-1qj-p2

## Problem

![image](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/4195a80b-fe3e-46eb-bba0-9cdce5ea2b93)
![image](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/b99c8a51-1bd5-4bcd-95f0-e4b419b0eca2)

## Solution
Keep merchant shipping settings in the admin only and:
– Cart block: update the Settings tab for the Shipping inner block as follows: remove shipping calculator toggle and make the block use the WC settings
– Checkout block: update the Shipping options inner block settings as follows:
remove the Calculations toggle and make the block use the WC Admin setting
– both areas will display instead something [similar to this area](https://woocheckout.files.wordpress.com/2023/09/image-1.png?w=582), but with the appropriate wording and link

**Comment by mikejolley** [comment]
The example for account settings could apply to multiple areas in WooCommerce, for example, registration, sign in pages etc. So I can see why this would need to link to a global settings page.

The options to hide shipping calculator and costs however are highly specific to cart and checkout and they certainly **do** affect appearance because they control visibility of components. It seems the only reason to keep them global is to support the classic cart and checkout in addition to blocks.

If the confusion comes from settings existing separately at global level to block level, why don't we sync them until classic options are removed, in which case the global options would be sunset?

I'm going to take this issue and work on it, I just wanted to express my thoughts beforehand because I think we should keep settings that only affect cart/checkout within the context of cart/checkout rather than link elsewhere.

**Comment by ralucaStan** [comment]
I'll think about this tomorrow @mikejolley; I'd like to ping @pmcpinto and @elizaan36 as well so that they could see your concerns.

**Comment by elizaan36** [comment]
> It seems the only reason to keep them global is to support the classic cart and checkout in addition to blocks.

These are the two problems to solve as I understand it:
- The block setting doesn't sync with admin settings
- The block setting creates a duplicate setting to the admin setting, which is confusing for the merchant.

> If the confusion comes from settings existing separately at global level to block level, why don't we sync them until classic options are removed, in which case the global options would be sunset?

One solution would be to sync the two settings, but I also feel we should avoid redundancies that will make it harder for merchants to know where to look for certain settings. In the shipping calculator use case, imo the most intuitive placement would be alongside shipping settings in the admin. Thoughts?

**Comment by pmcpinto** [comment]
I agree with Elizabeth. I assume that reviewing the Admin settings is already part of most merchants' workflow, offering better visibility for this setting.

**Comment by mikejolley** [comment]
The block level setting is immediately visible within the context of the block; you can see exactly what the setting is turning off/on and make a decision. The admin setting however needs to explain the what/where/why to give any form of context. Admin settings are bloated. In fact, I think most of the settings under "shipping options" could be moved elsewhere but thats out of scope for this discussion.
