### ISSUE TITLE
Product Gallery Thumbnails: Add View all link

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#11083]
## Describe the bug

When a product gallery has more thumbnails than the amount being displayed (set via the `Number of Thumbnails` setting) we need to add/include a link to `View all`.

This should probably link to the Lightbox/Dialog (containing all thumbnails).

@gigitux Would love to know your thoughts on the desired behavior, here 🙏 

## Screenshots
<img width="693" alt="Shaun_s_Scratchpad_–_Figma" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/78c58bba-254d-41ff-998c-ad68b0672a04">

**Comment by gigitux** [comment]
Thanks for opening this issue.

> This should probably link to the Lightbox/Dialog (containing all thumbnails).

I agree with you! Should we open the dialog even if the user has set the option "full screen when clicked" to false? I think that it makes sense since the option seems related to the Large Image.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/159cc88b-4ec4-40a7-94d9-7af5bfe4e1a1)

**Comment by danieldudzic** [comment]
> Thanks for opening this issue.
> 
> > This should probably link to the Lightbox/Dialog (containing all thumbnails).
> 
> I agree with you! Should we open the dialog even if the user has set the option "full screen when clicked" to false? I think that it makes sense since the option seems related to the Large Image.
> 
> ![image](https://user-images.githubusercontent.com/4463174/271968716-159cc88b-4ec4-40a7-94d9-7af5bfe4e1a1.png)

I agree. We'll need to adjust the dialog code accordingly.
