### ISSUE TITLE
[3.8 rc2] Reviews by Product block: add title of the product 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1111]
**Is your feature request related to a problem? Please describe.**

I am testing WC 3.8 rc2 and see that I can only see the name of the product for which I want to add a review on the page when I am selecting it. In the example below, the name of the product is `DJ Ladder - Dubstep`:

![reviews1](https://user-images.githubusercontent.com/19143190/67944731-0ad75200-fbd5-11e9-9328-d9b8bd15c16f.jpg)

However, when the product is selected, there is no way of knowing the title of the product as the review displays the username of the reviewer: 

![reviews1 2](https://user-images.githubusercontent.com/19143190/67944824-57229200-fbd5-11e9-9e02-0eadb52a0cd0.jpg)

When the page is published, it is also not clear what product the review is for:

![reviews1 3](https://user-images.githubusercontent.com/19143190/67944922-9c46c400-fbd5-11e9-89bd-16db485facac.jpg)

**Describe the solution you'd like**

It will be great to know what product the review is for. Perhaps add it under the date or between the username of the reviewer and the date. The option to display the title can be added to the sidebar along with other options:

![reviews1 4](https://user-images.githubusercontent.com/19143190/67945484-e54b4800-fbd6-11e9-8413-286ff8ab29ea.jpg)

**Describe alternatives you've considered**

No other alternatives. 

**Additional context**

No additional context. 
<hr>
Credit for this issue goes to @LCmry.

**Comment by nerrad** [comment]
A workaround would be for people to add a block with the title of the product.  Is this a must have for WC 3.8?  I'm not sure if this was intentionally excluded from the block or not.  cc @mikejolley and @jwold, oversight or intentional?

**Comment by juliaamosova** [comment]
> Is this a must have for WC 3.8?

I don't think it is a must-have for WC 3.8. IMO, it will be a good enhancement to include in the next release.

**Comment by jwold** [comment]
Thanks for the followup on this! Appreciate opening the ticket, and absolutely agree it's a bit of a challenge from a UX perspective. 

When we designed the block we knew we would be putting in this limitation, and the reason (if my memory is correct) was because technically speaking we were running into some issues with the block title not being able to easily adjust for which product it belonged to. I think it was because we'd essentially be creating two blocks together (headline and product block).

If my understanding is incorrect, and we CAN include the title, then I'll be happy to followup on here with some design updates showing options for displaying the title. 

Thanks for raising this @juliaamosova. 

cc @nerrad

**Comment by nerrad** [comment]
I personally don't think we should add the product title here.  Since the user can only select _one_ product to display reviews for, I think it would typically get used in the context of another product block (Handpicked product etc) and having a product title would be superfluous.  If the user really wanted to add a title they could simply add a header block and manually type the title (or whatever they wanted as the label).

Keep in mind, it's entirely possible this reviews block could eventually get implemented as an "inner block" on other more curated block containers in which case the atomic `ProductTitle` block would also be used.

Let's see what kind of feedback we get on this block in the wild (with WC 3.8) before we action this.  Sound okay?  cc @pmcpinto

**Comment by pmcpinto** [comment]
Sounds good to me. I 100% that probably the main use case of the reviews by product will be to be displayed within the context of a specific product, so adding the product title can be redundant.

I'm going to move this and #1112 to the Icebox until we see how folks are using it.
