### ISSUE TITLE
Store Customization > Remove placeholder from the image on the Hero Product Chessboard pattern

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11181]
Update the **Hero Product Chessboard** pattern and ensure no placeholder text is displayed on the editor side on top of the images:

<img width="1214" alt="Screenshot 2023-10-09 at 14 52 55" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/dde20cbe-cab4-4468-8faf-e79f61547965">

**Comment by albarin** [comment]
Hey @nefeline I think we cannot remove that, it's part of the cover block (unless I'm missing something).
When removing the "write title" thing it shows what you see in the image.
When removing the whole paragraph, it still shows the "write title".
<img width="1218" alt="Screenshot 2023-10-11 at 13 05 10" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/6e3521d7-008c-4c8b-8008-cfb796623330">

**Comment by tjcafferkey** [comment]
Echoing @albarin's comment above. I've also tried to replace this with the Image block but it doesn't behave the same way especially when you start scaling down responsively.

Couple of other solutions if this is a hard requirement for MVP:

1. **CSS**: Hacky solution would be to add a custom class to the patterns container and target this "Write title" element with CSS to hide it. The cons are obvious, it's a hacky solution.
2. **Variation API**: Investigate whether we can use the variation API to create a variant of this block in the Woo Blocks repo with an additional attribute to hide this text. The cons here are that it would mean us maintaining this variant in our repo for the sake of a small UI change in the editor.
3. **GB Contribution**: Contribute upstream with an option to hide this text editor side, which we would need a use-case for. Cons here are time and it might not be accepted because this only renders in the editor and not on the frontend.
