### ISSUE TITLE
Store Customization > Product Collection 5 Columns pattern: ensure the product title is a regular paragraph instead

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11186]
Update the **Product Collection 5 Columns** pattern to ensure the product title is a paragraph instead of a heading:

<img width="1251" alt="Screenshot 2023-10-09 at 17 05 48" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/e9e2ede6-e33e-4dea-ac35-468fe70ca85c">

This change is required to ensure the fonts used for bot the product title and price are the same within the Pattern Assembler.

**Comment by tjcafferkey** [comment]
@nefeline there was talk in Fridays meeting about grouping the product title & price blocks into rows rather than columns to fix the design with long title names. Was a decision made on this? If it is a yes then I can do both changes in the same PR. Thanks!

**Comment by nefeline** [comment]
> there was talk in Fridays meeting about grouping the product title & price blocks into rows rather than columns to fix the design with long title names. Was a decision made on this? If it is a yes then I can do both changes in the same PR.

I believe we agreed on using short names for the Product titles instead (there's a task for this as the outcome of that discussion to define a character limit for the product title), but TBH I think having them displayed one per line might be better as it works well for all lengths of product titles: it would be good to confirm with @verofasulo if we can proceed with this approach.

**Comment by verofasulo** [comment]
> but TBH I think having them displayed one per line might be better as it works well for all lengths of product titles

@nefeline @tjcafferkey, if we can tweak the pattern directly and wrap the price line, it's even better! However, I would still implement a character limit since AI-generated content might be unpredictable 😊

**Comment by tjcafferkey** [comment]
I don't think its easily feasible to change this block from a Heading block to a Paragraph block:

In the Product Collections block the product title is a variation of the `core/post-title` block, which is a Heading block. Having spoken to @kmanijak he said the following:

> I’m pretty sure paragraph cannot be used as a title. It won’t have required context to get post/product title. Personally I’d avoid allowing a paragraph becoming a title. It’s against semantics of this block and simply introduce another layer of complexity around already complex post title case

Another option would be to look into changing the product price block to become a Heading block so that they're at least consistent but again, I'm not sure how feasible this would be as an option.

**Comment by nefeline** [comment]
> I don't think its easily feasible to change this block from a Heading block to a Paragraph block:

> In the Product Collections block the product title is a variation of the core/post-title block, which is a Heading block. Having spoken to @kmanijak he said the following:

Just to ensure we are all on the same page, this issue is for updating the content on the pattern level, not on the block level: on the pattern level, we have more freedom to adjust the formats to our needs.

We discussed this on Slack, but porting over my comment over here as well:

Maybe an approach we can investigate is if one of the heading styles is coincident with the paragraph styles so the font type matches.

**Comment by verofasulo** [comment]
I'm getting a bit confused 😅

>I don't think its easily feasible to change this block from a Heading block to a Paragraph block:

Why does wrapping the price and having 1 line for the product name and 1 line for the price mean changing the block from a heading block to a paragraph block? Am I missing something? Thank you 🙏

**Comment by tjcafferkey** [comment]
>Why does wrapping the price and having 1 line for the product name and 1 line for the price mean changing the block from a heading block to a paragraph block? Am I missing something? Thank you 

Sorry @verofasulo, so the problem here is that because the product price is a Paragraph block, and the product title is a Heading block it means that when you cycle through selecting different font pairings, the title can take one font, and the paragraph will take the other one. Meaning they're not consistent, although it might become more obvious depending on what font pairing you select.

It was discussed on a call to make the product title a Paragraph block so that they're consistent but as described above it might not be possible.
