### ISSUE TITLE
 I cant view the payment methods on my website because I get that they are incompatible.

### ISSUE THREAD

**Issue by ninabril** [woocommerce/woocommerce-gutenberg-products-block#11217]

**Comment by jarekmorawski** [comment]
Hi there! I'm sorry you're experiencing this problem and we'll do our best to help. Can you please provide more details about the problem you're facing? How do you know the payment methods are incompatible? Did you attempt to fix the problem somehow? It'd be great if you could paste a screenshot or the contents of any error messages you're seeing. Thank you!

**Comment by ninabril** [comment]
Hello, yes now I send you what I get on the checkout page. 
I get the following message: "The following extensions may be incompatible with the block-based checkout. [Learn more(abre en una nueva pestaña)](https://woocommerce.com/document/cart-checkout-blocks-support-status/)

Mercado Pago - Checkout Personalizado
Mercado Pago - Checkout Personalizado
Mercado Pago - Checkout Pro"

**Comment by ninabril** [comment]
<img width="1190" alt="Captura de Pantalla 2023-10-12 a la(s) 12 09 48" src="https://github.com/woocommerce/woocommerce-blocks/assets/147566319/57e514d6-1b86-4a20-a809-8a20a1ac6104">

**Comment by tarhi-saad** [comment]
Hi, @ninabril! 👋 Thank you for bringing this to our attention! 🙌 the `Mercado Pago Checkout` extension isn't compatible with the Cart and Checkout Blocks.

Currently, it's up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

I suggest reaching out to inform them about the incompatibility so that they can adjust the extension accordingly. I've also created https://github.com/woocommerce/woocommerce/issues/42186 so that others know this extension is currently not compatible with WooCommerce Blocks.

As there are no action items for us, I'm going to close this issue for now. But please don't hesitate to reach out again if you have more questions or suggestions.

**Comment by ralucaStan** [comment]
@ninabril Indeed, the Mercado Pago plugin is not compatible with the Checkout block that you are using for your checkout page.

If you want to continue using the Mercado Pago extension I recommend switching back to the classic checkout provided via the shortcode block until Mercado Pago integrates with the Checkout block. 

You can do that by removing the current Checkout block and inserting the Shortcode block, with [woocommerce_checkout]. Please note that all customizations you made to the Checkout block will be lost.

<img width="456" alt="Screenshot 2023-10-13 at 13 46 47" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/6f34f2bb-e07a-4146-87df-3ca0a3a5b97f">
