### ISSUE TITLE
Implement github-action-wordpress-dependencies-report into the Woo Blocks repo

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#11239]
We should implement [github-action-wordpress-dependencies-report](https://github.com/Automattic/github-action-wordpress-dependencies-report) into the Woo Blocks repo.
It'll help detect dependency impacts on changes in PRs (meaning added/removed WP Script dependencies).

## Expected result

![image (34)](https://github.com/woocommerce/woocommerce-blocks/assets/1628454/0bd4c17e-39cd-4a3e-85b1-96c1b63055f0)

**Comment by nerrad** [comment]
Raluca brought to my attention that we do have a [`compare-assets` workflow](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/.github/compare-assets) already in the repository. However, there is room to improve this so that it reports on the size impact of those dependencies (which is done in the script referenced on this issue).
