### ISSUE TITLE
Store Customization > Featured Category Triple pattern: update the spacing between the title and the content

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11276]
Based on the feedback we received from @verofasulo on Mrk6SERPZ4KrFHSjM0a8TK-fi-6359_47173 , we need to update the spacing between the header and the content of the **Featured Category Triple** pattern (`woocommerce-blocks/featured-category-triple`):

<img width="852" alt="Screenshot 2023-10-16 at 19 52 34" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/351a3956-7bc8-4656-881a-640ce331c85f">

@verofasulo would you please let us know what is the expected spacing in this case so we can ensure we comply with the expectations for this pattern? Thanks in advance! 🙏

**Comment by verofasulo** [comment]
Hey @nefeline 👋

> would you please let us know what is the expected spacing in this case so we can ensure we comply with the expectations for this pattern?

[Here](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2103-32665&mode=design&t=yqeqiS6RvJUuEHun-4)'s you can find the pattern with the correct spacing. 😊

**Comment by albarin** [comment]
Thanks, @verofasulo, this is how it looks using the same spacing it has in the designs, 56px from the bottom and 24px between the title and the `Shop now` button. Does it look good to you?
<img width="1181" alt="Screenshot 2023-10-17 at 11 36 20" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/6382f225-1c34-4fb2-8077-26f841b659f8">

**Comment by verofasulo** [comment]
Hey @albarin! Thanks for working on it.

It looks different from the design—could you please double-check the following points?

Category name: 
- Font weight: Bold
- Font size: 33px 
- Line height: 40px

Link:
- Font weight: Bold
- Font size: 16px 
- Line height: 22px

Thank you!

**Comment by albarin** [comment]
> Hey @albarin! Thanks for working on it.
> 
> It looks different from the design—could you please double-check the following points?
> 
> Category name:
> 
>     * Font weight: Bold
> 
>     * Font size: 33px
> 
>     * Line height: 40px
> 
> 
> Link:
> 
>     * Font weight: Bold
> 
>     * Font size: 16px
> 
>     * Line height: 22px
> 
> 
> Thank you!

@verofasulo I see it's a bit different from the designs, but if we start hardcoding font sizes, line height, etc we are going back to not having wireframed patterns again and we'll have inconsistencies in the assembler and when changing themes.
What we can do is choose a different heading instead of the H4 we have now though.
cc: @nefeline @tjcafferkey

**Comment by verofasulo** [comment]
Which stylesheet are Woo patterns following?

**Comment by albarin** [comment]
> Which stylesheet are Woo patterns following?

The patterns follows the stylesheet of the active theme, check the examples below for TT3 or Tsubaki. The font sizes are different because the theme default styles are different.

| TT3 | Tsubaki |
|--------|--------|
|<img width="1026" src="https://user-images.githubusercontent.com/186112/275785242-6382f225-1c34-4fb2-8077-26f841b659f8.png" /> |  <img width="1026" alt="Screenshot 2023-10-17 at 15 53 13" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/2dc55d7c-1322-457b-b3c0-b33debe71393">|

**Comment by verofasulo** [comment]
Thanks for clarifying, @albarin!  

I think all the patterns have been designed with Tsubaki in mind, that's why I was so confused. Let's not hardcode anything, just be sure the spacing and margins are correct. 🙏 Thank you 💜
