### ISSUE TITLE
TT4: "Products by Attribute" template - Error displayed for Term Description

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11300]
## Describe the bug

The "Products by Attribute" template in the editor displays an error concerning the "Term Description." This same issue is reflected on the frontend, where the Term Description is missing.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/149786df-d574-497c-b099-f69fd8c20e1f)

## To reproduce

1. Go to the "Products by Attribute" template.
2. Observe that an error message is displayed for the "Term Description" field.
3. View it on the frontend.
4. Confirm that the Term Description is missing.

## Expected behavior

The "Term Description" should appear without any errors in both the editor and on the frontend.

**Comment by sunyatasattva** [comment]
Wanted to add that this is a problem also for the “Products by Tag” template:

<img width="664" alt="Screenshot 2023-10-19 at 14 39 49" src="https://github.com/woocommerce/woocommerce-blocks/assets/1847066/707f058d-086e-4274-9e24-ca43c4fe67a4">

(Btw, @imanish003 I edited the title and the description to say “template” instead of “block”; also, I believe the testing instructions are wrong, because you mention to add a “Products by Attribute” block, not going the “Products by Attribute” template: the block doesn't have a `core/term-description` block inside, so I think this might be a mistake).

**Comment by imanish003** [comment]
@sunyatasattva Thank you for updating the title and description. I appreciate you catching the mistake as well. I created about eight issues yesterday and may have inadvertently introduced this error while copy-pasting some of the steps between them. I've now updated the testing steps. Thank you again for bringing this to my attention 🙏🏻

**Comment by danieldudzic** [comment]
I was able to replicate the same issue with the `Product by Category` template:

<img width="1354" alt="Products_by_Category_‹_Template_‹_Editor_‹_Eyed_Coyote_—_WordPress" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/3969335a-4be2-44a0-9240-4af1234ef9a8">

**Comment by danieldudzic** [comment]
After investigating this turned out to be a bug in WP 6.4-RC2. I have now created a Trac ticket for this: https://core.trac.wordpress.org/ticket/59755

**Comment by danieldudzic** [comment]
This has now been fixed in Gutenberg and will be included in 6.4-RC3: https://github.com/WordPress/gutenberg/pull/55669
