### ISSUE TITLE
[CYS Woo Express] Hero product chessboard

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11404]
Pattern: `Hero product chessboard`.

First section:
- Review spacing between heading and subheading.
- Review spacing between subheading and cta.

Second section:
- Review spacing between title and body.
- Review spacing between single modules.

<img width="1311" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/9ab032ad-5b42-4aaf-8e79-1bc01c04a2be">

---

[Figma](https://www.figma.com/file/Mrk6SERPZ4KrFHSjM0a8TK/Customize-your-store-with-pattern-assembler?type=design&node-id=1406-127650&mode=design&t=ZBW0Ds0G26mxIowu-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/04bbaf83-ba3d-4f3b-9de8-d3e3369e8811)

**Comment by verofasulo** [comment]
I don't know what happened to this pattern, but that's the current situation:

<img width="1331" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/c0df9dbe-bfc7-427b-b849-f6c815bef2cf">

<img width="441" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/5f6e0ed4-41fc-479c-a774-6a818a6ff82b">

Could we please review it, ASAP? Thank you! 

cc @albarin @gigitux

**Comment by tjcafferkey** [comment]
>I don't know what happened to this pattern, but that's the current situation:

I think this is caused by the behaviour of the Cover block. The issue here is that the bottom row text increased in size & content. Reducing the content, or heading sizes (I've selected H6 on the second screenshot). However this issue might reappear depending on what font the user picks.

If my assumption is right I think the best thing to do is reduce the content used here, and make sure that when the content is replaced it has a character/word limit on it.

cc @albarin @gigitux 

![Screenshot 2023-11-01 at 16 23 37](https://github.com/woocommerce/woocommerce-blocks/assets/8639742/61be4313-c108-4a81-92c7-e8dc92b47e3e)

---

![Screenshot 2023-11-01 at 16 25 27](https://github.com/woocommerce/woocommerce-blocks/assets/8639742/3957f1dd-7919-4fff-a8bf-36ab2e437855)

---

![Screenshot 2023-11-01 at 16 23 54](https://github.com/woocommerce/woocommerce-blocks/assets/8639742/c176a9bd-7ac2-492c-afdc-feb7d071a1ba)
