### ISSUE TITLE
Shipping calculator link not present for guest/non logged in customers

### ISSUE THREAD

**Issue by veljkho** [woocommerce/woocommerce-gutenberg-products-block#11435]
## Describe the bug

For guests and not logged in customers, there's no visible link in the cart so they can change the shipping location and calculate the price.

## To reproduce

1. Make sure you have some shipping zone and method for United States - California
2. Make sure you have set Shop country/region as the default customer location in WooCommerce settings
3. Go to WooCommerce Settings and set the store's address to California
4. As a guest/not logged in user, visit the cart page with some product added already
5. Observe the issue, there's no link to change or add a new address to calculate shipping

## Expected behavior

The link to change an address and/or add a new address to calculate shipping should be present

## Screenshots

This is how [the link for calculating shipping](https://d.pr/i/Ooffsn) is visible when logged in
This is how [the link for calculating shipping](https://d.pr/i/s1Qp1G) is not visible when not logged in or a guest

### WordPress (please complete the following information):

-   WordPress version: 6.3.2
-   WooCommerce version: 8.2.1
-   WooCommerce Blocks version: 11.3.1
-   Site language: English
-   Any other plugins installed: Deactivated all such as MailPoet, WooCommerce Blocks..

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: latest Chrome and Firefox

## Additional context

There's an open thread on Slack # checkout-blocks-support where we confirmed a bug.

**Comment by ralucaStan** [comment]
From what I tested this regression was introduced in March by this PR by 
@tarunvijwani 
 https://github.com/woocommerce/woocommerce-blocks/pull/8141

we actually plan of revering that PR as part of this ticket https://github.com/woocommerce/woocommerce/issues/42280

**Comment by senadir** [comment]
The issue is coming from the fact that `isAddressComplete` is returning false for guests users, but it's unclear why that condition would play into showing the button.

**Comment by ralucaStan** [comment]
The issue is actually this condition https://github.com/woocommerce/woocommerce-blocks/pull/8141/files#diff-7dc2f39a4008ea330cf22465974fa6c12ef75b55d4d9e7f516411b95a402def3R34. `isAddressComplete` is correct, but the condition is missing the case where we are outside the editor and the address is incomplete because it's a guest user. 

the expected result would be to show the link to add a shipping address, in case no address field is present.
<img width="247" alt="Screenshot 2023-10-24 at 20 08 45" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/bd164fce-ec43-447c-a673-1f83d0b728df">

Instead, the component returns `null`. The code needs to be reevaluated because we can't just skip this condition. We need to know what case it was written for. And we also need to rewrite it, because if we don't return `null` then in order to display `ShippingLocation` a shipping address with at least one field needs to be passed to calculate	`const formattedLocation = formatShippingAddress( shippingAddress );`. Which might not be the case for the guest users.

@tarunvijwani could you provide some context.

**Comment by tarunvijwani** [comment]
@ralucaStan Yes, the conditions to hide the shipping calculator shouldn't be dependent on `isAddressComplete`.
I have modified the code in https://github.com/woocommerce/woocommerce-blocks/pull/11442/commits/314673ad194f773115a660a14a8bdea056649877 to check if the formatted address is present to display the shipping calculator link. 


>@tarunvijwani could you provide some context.

The previous code was written to hide the calculator if the address is empty. For empty address, we would be showing the placeholder component with `Add an address for shipping options` if we don't have shipping totals present. 

However, a guest user with default store location is an edge case we missed checking while working on the https://github.com/woocommerce/woocommerce-blocks/pull/8141/ PR.
