### ISSUE TITLE
Product Collection: Undefined array key "woocommerceAttributes" warning after migrating from Products (Beta)

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gutenberg-products-block#11437]
## Describe the bug

When testing the TT4 theme, WP 6.4 and the **Large Image Product Gallery** pattern, I discovered the following issue:

After utilizing the `Upgrade to Product Collection` link in the sidebar and saving the page, the following warnings show up on the page: `Warning: Undefined array key "woocommerceAttributes" in /srv/users/user7f63c11d/apps/user7f63c11d/public/wp-content/plugins/woocommerce-gutenberg-products-block/src/BlockTypes/ProductCollection.php on line 313`

<img width="1143" alt="Large_Image_Product_Gallery_–_Eyed_Coyote" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/953c6669-bcd8-4650-8742-463227a4da84">

## To reproduce

1. Create a new page or post.
2. Add the `Large Image Product Gallery` pattern.
3. Use the `Upgrade to Product Collection` option in the sidebar and save the page.
4. Notice the warnings on the front end.

## Additional context

I was able to reproduce the same behavior with WP 6.3 and Twenty Twenty-Three too.

**Comment by nerrad** [comment]
When there are any type of warnings reported like this, I think it should be investigated sooner rather than later to determine whether there are any user-facing problems due to the warnings. Since there is no clarity either way yet, I've bumped the priority to high. Once it's determined whether actual user functionality is affected or not you can adjust the priority as needed (_warnings should still be addressed though_).
