### ISSUE TITLE
TT4: On Sale Products block: The 'On Sale' badge is not correctly aligned when the display mode for the block is set to Wide or Full width

### ISSUE THREAD

**Issue by thealexandrelara** [woocommerce/woocommerce-gutenberg-products-block#11438]
## Describe the bug

When the display mode for the On Sale Products block is set to Wide or Full width, the On Sale badge is not correctly aligned to the image.

## To reproduce

1. Add new page or post
2. Insert the block `On Sale Products`
3. Modify the block alignment to "Wide width" or "Full width"
4. See that the Sales badge is not correctly aligned to the image.

## Expected behavior

The Sales badge should be aligned to the image.

## Screenshots

![CleanShot 2023-10-24 at 22 38 13](https://github.com/woocommerce/woocommerce-blocks/assets/20469356/0596ae98-0314-46ee-a726-8a241b5371ce)

![CleanShot 2023-10-24 at 22 38 33](https://github.com/woocommerce/woocommerce-blocks/assets/20469356/bf4a5ca6-36e7-4cf9-b9b3-b4e912025784)

### WordPress (please complete the following information):

-   WordPress version: 6.4 RC2
-   WooCommerce Blocks version: 11.4.0-dev

**Comment by nerrad** [comment]
If there are theme-specific fixes needed for this, and this is the legacy block (i.e. not powered by either Product Collections or Products (beta) blocks), make sure they are done in WooCommerce core similarly to how other default theme adjustments were done). Especially if this is TT4-specific.

Otherwise, look into what specifically is causing this misalignment and if it's due to a token defined in `theme.json` optimize towards looking for that token in a theme and adjusting the block styles accordingly (which will make this adjust better across all themes using `theme.json`).

**Comment by danieldudzic** [comment]
There's an additional issue with the `On Sale Products` block.

The Wide and Full settings only work in the editor, but not in the front end.

**Editor:**
<img width="1698" alt="Cursor_i_Edit_Page_“On_Sale_Products_block”_‹_newproductgallery_—_WordPress" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/434a83c7-f391-4b50-aae6-243f016e32c5">

Front end:
<img width="1339" alt="All_Products_–_newproductgallery" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/74eacd21-d71e-45aa-948c-5b821c540e13">

**Comment by Aljullu** [comment]
The difference comes from these lines:

https://github.com/woocommerce/woocommerce/blob/2e9c1d6e6f687449b1dddb6da40ac3026f9d52c3/plugins/woocommerce/includes/theme-support/class-wc-twenty-twenty-three.php#L37C3-L43C5

In Twenty-Twenty Three (and other WP default themes), WC core was changing the default thumbnail image size making it bigger, so the _Sale_ badge would not overflow the image because the image was big enough. Twenty-Twenty Four doesn't have the code snippet linked above and that's why the _Sale_ badge overflows.

However, a similar issue could be reproduced in any theme, adding the On Sale block to a page and setting it to display only one column. Ie, this is Storefront:

![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/4bd5b6d9-7bba-470c-bb49-f6c8e958f81f)

I'm working on a CSS fix that should fix this in all cases.
