### ISSUE TITLE
[TT4] Classic Single Product template: incorrect margins

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#11542]
## Describe the bug

The Classic Single Product template wasn't working at all before the release of [6.4-rc.3](https://wordpress.org/news/2023/11/wordpress-6-4-release-candidate-3/). Now it is showing up, but doesn't respect the global padding of the page.

This is solved in the updated template by using “Inner blocks use content width” on the containing Group block.

## To reproduce

1. Go to the Single Product Template.
2. Remove the Group and add a Classic Template block. 
3. Save and preview the page.
4. Notice that the global padding is not applied to the main content.

## Expected behavior

The template should have padding.

## Screenshots

<img width="1511" alt="Screenshot 2023-11-02 at 15 24 08" src="https://github.com/woocommerce/woocommerce-blocks/assets/1847066/eb4ae1d7-d6a4-4977-8f85-387037c92ccb">

**Comment by Aljullu** [comment]
I have been taking a look at this, but I'm not sure I understand the issue. Or, at least, I would say this behavior is expected. :thinking: 

This is what I tested:

* In the Pages template: if I add the Content block outside of the wrapping Group block, it doesn't have any margin and it looks like this:

Blocks list | Frontend
--- | ---
![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/8f55bdbe-1c5b-443b-b31d-eeb165073878) | ![Captura de pantalla feta el 2023-11-07 a les 15 34 01](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/94eb4a42-f7d8-4f85-b365-1e482538abba)

* Similarly, in the Single Product template: if I add the Product Summary block outside of the wrapping Group block, it doesn't have any margin and it looks like this:

Blocks list | Frontend
--- | ---
![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/3d2fb8bd-76c3-445d-987f-eac87e30b7cb) | ![Captura de pantalla feta el 2023-11-07 a les 15 34 11](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/400b5813-b0a0-47ff-b340-8777894ea7b4)

* Then, the same happens with the Classic Template block. In the Single Product template: if I add the Classic Template block outside of the wrapping Group, it doesn't have any margin and it looks like this:

Blocks list | Frontend
--- | ---
![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/8b4ddec6-c9bd-4f60-92b8-08eea9eead0f) | ![Captura de pantalla feta el 2023-11-07 a les 15 40 28](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/2b2d762c-b2ed-4aa4-9a46-ff842ca1f354)

I think this is the expected behavior, as the Classic Template block (and the Single Product template) behave like any other block/template.

> Remove the Group and add a Classic Template block.

Heads-up that in the default templates, the Classic Template block is added inside a Group block. I would expect users manually editing the template to do the same:

https://github.com/woocommerce/woocommerce-blocks/blob/41b8d16d89f30f0e4fe27a00f8878ad1d5fd12b6/templates/templates/single-product.html#L2-L4

@sunyatasattva what do you think?

**Comment by sunyatasattva** [comment]
Yep, makes sense. It's responsibility of the users or of the theme to address this. Closing as unplanned.
