### ISSUE TITLE
Improve readability of order note

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#11674]
## Is your feature request related to a problem? Please describe.

Currently, the values within the table on the order confirmation template are right aligned. This impacts the readability of the values. 

## Describe the solution you'd like

In https://github.com/woocommerce/woocommerce-blocks/issues/11674#issuecomment-1823174361, @elizaan36  suggested creating a new section for the order note.

## Screenshots

<table>
<tr>
<td valign="top">Current alignment:
<br><br>
<img width="1355" alt="Screenshot 2023-11-08 at 16 00 58" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/013d5bab-524f-45fe-99fc-cc02daec8781">
</td>
<td valign="top">Proposed alignment:
<br><br>
<img width="1022" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/44a7d2fc-842a-47c6-9efe-4a7f7fa08567">
</td>
</tr>
</table>

**Comment by elizaan36** [comment]
hi @nielslange Thanks for bringing this up, it doesn't look great. The order confirmation template needs some work but in the meantime rather than changing the alignment of the full table we could create a new section for the order note.

<img width="1022" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/44a7d2fc-842a-47c6-9efe-4a7f7fa08567">

Thoughts?

**Comment by nielslange** [comment]
Thanks for your reply, @elizaan36. Your design proposal sounds good. I'll update the description accordingly.
