### ISSUE TITLE
Add `pnpm` to Blocks Repository

### ISSUE THREAD

**Issue by ObliviousHarmony** [woocommerce/woocommerce-gutenberg-products-block#11797]
One of the major differences between NPM and PNPM is the way that it populates the `node_modules` directory. In the monorepo we are making use of PNPM's strictness and as a consequence developers are unable to include undeclared transitive dependencies. In [the spike PR](https://github.com/woocommerce/woocommerce/pull/41415) I had to make some changes to `package.json` in order to get it working.

Since we're going to be switching over to `pnpm` commands post-merge anyway, it seems appropriate to adopt it here, fix any dependency problems, and be able to merge cleanly.

**Comment by nerrad** [comment]
What's the potential impact of doing this pre-merge for in-progress development workflows?

**Comment by ObliviousHarmony** [comment]
> What's the potential impact of doing this pre-merge for in-progress development workflows?

PNPM is a drop-in replacement for NPM. The only difference at this point would be using `pnpm` instead of `npm`. One option could be to only make the change in CI. This would get the missing dependency errors caused by strict dependency resolution while not requiring any local developer workflow changes. The PR making this change would highlight all of those failures too.

**Comment by nerrad** [comment]
I get that it's a drop-in replacement. However, in your pull description you referred to changes you had to make to `package.json` in order to get things working. It'd be useful to document exactly _what_ changes you had to make (which the description of the other PR doesn't mention - and my browser is timing out for viewing the GH PR). You could maybe help reviewers/commenters by linking to the specific commit? Hence, this is why I'm asking what the impact is because clearly there _is_ an impact if you have to make changes in `package.json` for Woo Blocks.

Bottom-line, your issue description here is fairly vague.

**Comment by ObliviousHarmony** [comment]
That's a fair criticism @nerrad. Looking at the diff, I had to add these two items to `dependencies`:

```json
{
  "@babel/preset-react": "^7.22.3",
  "prop-types": "^15.8.1"
}
```

There may be other missing dependencies though since I only covered the build workflow. To be clear, _these are already dependencies in use_, they just aren't declared in the `package.json` file. [Here are the merge-specific commits from the spike PR](https://github.com/woocommerce/woocommerce/pull/41415/files/9afd6536e659699ea0bdf47a3fc331120dfb911d..e5557277e4668ed47dc4419eec6c1893f3d46ff2).

**Comment by ObliviousHarmony** [comment]
Given how disruptive this change would be I think it's better to just not make it and instead wait for the merge. This will allow for a clear migration guide supplemental to the change and make sure folks are already going in with the mindset of change.
