### ISSUE TITLE
Increase block editing.

### ISSUE THREAD

**Issue by Phil-Avalon** [woocommerce/woocommerce-gutenberg-products-block#11810]
## What do you think is missing from the Cart & Checkout blocks?
I am unable to remove "Country/Region" and "State/County".  How do I hide these boxes?
Also, need to rename "City to "Town".
Thanks,
Phil.

**Comment by wavvves** [comment]
Hi @Phil-Avalon, thank you for reaching out.

Regarding hiding Country and State, the only possible solution as of now is to use CSS to do it:

```
.wc-block-components-country-input,
. wc-block-components-state-input {
    display: none;
}
```

But that will only work if you set the option for "Default Customer Location", and it will restrict all customers to that setting determined value

<img width="668" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/17236129/e160af05-013b-41e5-97cf-a281b81b8b10">

Changing City to Town can be achieved by editing translations. You can do so by using one of the [many translation editing plugins available](https://wordpress.org/plugins/search/translations/).

**Comment by senadir** [comment]
Changing the label can also be done via PHP if you know the country, for example, switching the US's city to town is:

```php

add_filter(
	'woocommerce_get_country_locale',
	function( $locale ) {
		$locale['US']['city']['label'] = 'Town';
		return $locale;
	}
);
```

**Comment by Phil-Avalon** [comment]
Thanks both.
I found a good resolution was to replace the woocommerce block with the [woocommerce-checkout] shortcode.
Suddenly everything started working again.
Woocommerce Field editor now has control over which fields are shown.
Woocommerce Opening Hours and Delivery Times now requests input from the customer.
Woocomerce payment surcharge now shows the surcharge amount.
AND all items are visible once more in the emails.

I'm not sure we should be encouraging people to use the blocks just yet.
Kind regards,
Phil.

**Comment by senadir** [comment]
Thank you for the response, Phil! The Checkout block has been available for several years now, and we decided to make it default to increase adoption.

For third-party plugins, we provided extensibility for developers to extend it, and many of them did. We also worked internally and with partners to integrate the most used plugins for Checkout.

When it comes to the list you shared, WooCommerce Field Editor will be replaced by the ability to edit fields directly in the editor. WooCommerce Opening Hours and Delivery Times is not a plugin we control and is up to the developer to integrate it, customers like can create pressure on developers to integrate.

For WooCommerce payment surcharge, I'm not sure if you're referring to a plugin or via adding a surcharge via code? Adding surcharge via code still works fine, if it's a plugin, please contact the plugin developer.

Checkout block will be the flow that receives future updates and enhancements, so I'd highly suggest you contact your plugin developers for them to integrate with it so that you can use it as soon as possible.
