### ISSUE TITLE
Store Customization > Update the Footer with 3 Menus pattern and ensure the columns are unique

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#11847]
This issue is for us to explore if it's possible to update the **Footer with 3 Menus** pattern to ensure the navigation menus in each one of them are different:

<img width="708" alt="Screenshot 2023-11-20 at 17 10 50" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/125c5ed8-5aba-4c0b-9c5a-4c3ba975418f">

## Scope

- Check whether the wp:navigation block allows the display of different menus in the pattern (or any equivalent content)
- Update the pattern and ensure any content is generated during the initial store setup if needed (reach out to the relevant team to make those changes if necessary).

**Comment by gigitux** [comment]
Currently, the Footer with 3 Menus contains three instances of the navigation block. During the product review, one of the feedbacks was that having three menus with the same pages doesn't make a lot of sense (I agree).

By default, the navigation block shows all the WordPress site pages. We can't customize them from the pattern. I propose to use only one instance of the navigation block instead of three.

cc @verofasulo

**Comment by verofasulo** [comment]
Hey @gigitux 👋

I shared some thoughts in [this Slack thread](https://a8c.slack.com/archives/C053716F2H2/p1701229495243029?thread_ts=1700666170.703699&cid=C053716F2H2). 😊
