### ISSUE TITLE
Billing shipping address form change when change country from United State to Malaysia

### ISSUE THREAD

**Issue by msyahrizan** [woocommerce/woocommerce-gutenberg-products-block#11942]
Hi, please look two screenshot below, when I select Malaysia country, my billing shipping address change, country change to above street address

![Screenshot 2023-11-25 8 34 52 PM](https://github.com/woocommerce/woocommerce-blocks/assets/3821013/d3af1be4-1c0a-47bf-9dae-a8e3e52e0dd8)
![Screenshot 2023-11-25 8 34 42 PM](https://github.com/woocommerce/woocommerce-blocks/assets/3821013/10c989ad-5e19-4d7e-ac5c-a3b6f4c2c9ea)

**Comment by nielslange** [comment]
Thanks for reaching out, @msyahrizan. This issue should have been fixed with #11486, which was shipped with WooCommerce Blocks 11.6.0. On my end, the address form looks as expected when selecting Malaysia as country:

<img width="684" alt="Screenshot 2023-11-27 at 10 56 58" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/21f5c84e-3608-4bd3-8abc-96f6f379a302">

Which version of WooCommerce Blocks are you using?

**Comment by senadir** [comment]
This fix should land in WooCommerce 8.4.0, for now, you can use the Woo Blocks plugin.

**Comment by msyahrizan** [comment]
Thank you for your respond nielslange and senadir
