### ISSUE TITLE
Coupon Field not working

### ISSUE THREAD

**Issue by Sam-Futr** [woocommerce/woocommerce-gutenberg-products-block#11967]
## What do you like about the Cart & Checkout blocks?

They look relatively clean.

## What do you think is missing from the Cart & Checkout blocks?

Generally more functionality to be able to edit them, customise buttons, border thickness, layout and more.

The coupon field doesn't work very well at all. Needs some work.

![Screen Shot 2023-11-28 at 3 25 17 pm](https://github.com/woocommerce/woocommerce-blocks/assets/112921618/bf0b5b46-c1e0-41f9-a582-4f46e08883c3)

**Comment by senadir** [comment]
Hey! This might be due to the theme you're running? can you test on Twenty Twenty Four?

**Comment by JFoxUK** [comment]
I get the same with the Neve Theme. Really terrible experience.

**Comment by senadir** [comment]
@JFoxUK how would you like us to make the experience better?

**Comment by JFoxUK** [comment]
@senadir - well as you can see from the screen shot by OP, the field isn't usable at all. You can barley see a single character entered into the field.

**Comment by senadir** [comment]
I understand that, but this is an issue coming from a third party theme, we do our best to use standard HTML and items, provide sensible default styling that can adapt to most themes while still being resilient, and test with major themes.

We will look if we can fix this from our side, but this is something to highlight to the Neve Theme author.

**Comment by Sam-Futr** [comment]
@senadir I'm using Pro by Themeco (with Cornerstone), which is one of the most popular frameworks to use on WordPress alongside frameworks like Elementor. Themeco's more basic theme is called X and has one of the highest download rates in Envato, but it still uses Cornerstone page builder.

I see there is also a similar issue with the Neve Theme via @JFoxUK 

It seems clear to me there's a broader bug here that needs to be looked at and resolved.

No one uses Twenty Twenty Four or any of the default WordPress themes for websites, so I won't bother testing on that theme because it's not adding any value.

Please keep us posted.

Thanks, Sam

**Comment by ralucaStan** [comment]
> Themeco's more basic theme is called X and has one of the highest download rates in Envato, but it still uses Cornerstone page builder.

> No one uses Twenty Twenty Four or any of the default WordPress themes for websites, so I won't bother testing on that theme because it's not adding any value.

@Sam-Futr the Twenty Twenty Four is tested against the checkout flow. Because it brings minimal styling to the checkout flow it is used internally to identify issues that are present on our end.

I took a look at the Neve Theme and in their `wp-content/themes/neve/assets/css/woocommerce.min.css?ver=3.7.4` file they have this class overwriting  the styles for buttons

```css
.woocommerce-checkout main button {
    width: 100%;
}
```

A simple CSS rule disabling in the browser shows that the Neve Theme custom style is impacting the look of the coupon field
<img width="1225" alt="Screenshot 2023-12-07 at 14 40 51" src="https://github.com/woocommerce/woocommerce-blocks/assets/1628454/b1935fc9-71dc-40e5-80da-5d2b79963a3e">

My suggestion is to reach out to the theme's creator and highlight this bug https://themeisle.com/contact/.

I am going to close this ticket as there is nothing we can do on our end.
