### ISSUE TITLE
Exploration - Cart Block: What components will be needed?

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1207]
As a part of this exploration let's consider:

### What will be the components needed for the cart block mvp?

Keeping in mind the MVP will not have inner blocks initially, we still need to identify the logical units in the main cart block.  So this exploration should map out the various components and what we already have vs what needs created.

**Comment by Aljullu** [comment]
Regarding the components in the Cart block, there is a clear distinction between the _Empty Cart_ (which according to the MVP post should allow inner blocks -- is that still the case?) and the _Full Cart_ (which shouldn't).

## Empty Cart
![image](https://user-images.githubusercontent.com/3616980/69245418-0cc67c80-0ba7-11ea-9463-976dc88f38c3.png)

Inner blocks:
* Image
* Heading
* Text

## Full Cart
I listed the components I think will be necessary with a proposed path location, most of them will be under `/base/components/cart/` except some specific product components (`ProductImage`, `ProductName`, etc.) which are generic enough to be in its own folder and some other components that are shared with the checkout page.

In general, I think there is no need to use components from other packages and we can build all of them from scratch. But if we eventually end up using `@automattic/composite-checkout` for the checkout page, we might consider using their payment logos (see below). I don't think we want to use `composite-checkout`'s buttons and input fields because those components are mostly adding styles, which are not exactly the ones we want to achieve and might complicate themes styling afterwards.

![image](https://user-images.githubusercontent.com/3616980/69245439-15b74e00-0ba7-11ea-88de-f89b69551631.png)

### Shopping Cart
![image](https://user-images.githubusercontent.com/3616980/69349507-2a174b80-0c78-11ea-87df-814fa9b8015f.png)
* CartProductsTable (`/base/components/cart/products-table`)
* CartProductsTableItem (`/base/components/cart/products-table-item`)
	* ProductImage (`/base/components/product-image`)
	* ProductName (`/base/components/product-name`)
	* ProductPrice (`/base/components/product-price`)
	* ProductLowStockNotice (`/base/components/product-stock-notice`)
	* ProductDescription (`/base/components/product-description`)
	* ProductOptions (`/base/components/product-options`)
	* QuantitySelector (`/base/components/quantity-selector`)
	* RemoveItemButton (`/base/components/remove-item-button`)
* CartProductsTableItemTotalPrice (`/base/components/cart/products-table-item/total-price`)

### Totals
![image](https://user-images.githubusercontent.com/3616980/69349559-40250c00-0c78-11ea-9534-ce2a1e938da3.png)
* TotalsTable (`/base/components/totals/table`)
* TotalsTableItem (`/base/components/totals/table-item`)
* TotalsCouponCodeInput (`/base/components/totals/coupon-code-input`)

### Shipping Options
![image](https://user-images.githubusercontent.com/3616980/69349577-49ae7400-0c78-11ea-919a-3db31e849d46.png)
* ShippingOptionsList (`/base/components/shipping-options/list`)
* ShippingOptionsListItem (`/base/components/shipping-options/list-item`)

### Other
![image](https://user-images.githubusercontent.com/3616980/69349624-5763f980-0c78-11ea-9de4-8cb986e29c02.png)
* CheckoutButton (`/base/components/cart/checkout-button`)
	* For the payment logos we might consider using [these components](https://github.com/Automattic/wp-calypso/blob/master/packages/composite-checkout/src/components/payment-logos.js) from `@automattic/composite-checkout`.
![image](https://user-images.githubusercontent.com/3616980/69349648-62b72500-0c78-11ea-950f-2d9dea76191a.png)
* ContinueShoppingLink (`/base/components/cart/continue-shopping-link`)

## Editor sidebar
![image](https://user-images.githubusercontent.com/3616980/69349736-94c88700-0c78-11ea-9921-6783f8e78612.png)
* FeedbackBanner (`/components/feedback-banner`)

**Comment by nerrad** [comment]
Great list so far!

Let's also consider [`@automattic/components`](https://github.com/Automattic/wp-calypso/tree/master/packages/components/src) - Things like `Card` and `Button` could be useful here.

> I don't think we want to use composite-checkout's buttons and input fields because those components are mostly adding styles, which are not exactly the ones we want to achieve and might complicate themes styling afterwards.

I'd like to explore this reasoning a bit more.  `composite-checkout` is using emotion (css-in-js) and while it does affect how we might approach theming, I'd think we should evaluate how that would exactly affect things before discarding this approach.  While I do think we need to keep in mind current theming patterns in woo, I think we also want to consider potential future theming patterns as well - so let's not jump the gun here.  Would it be good to do an exploration around building something very simple with these components and see what is needed to apply themes?

**Comment by Aljullu** [comment]
> Let's also consider [`@automattic/components`](https://github.com/Automattic/wp-calypso/tree/master/packages/components/src) - Things like `Card` and `Button` could be useful here.

Yup, thanks for the link!

> `composite-checkout` is using emotion (css-in-js) and while it does affect how we might approach theming, I'd think we should evaluate how that would exactly affect things before discarding this approach.

I agree we shouldn't discard it because it's using CSS-in-JS, but at the same time I think we shouldn't use components from other packages if there is no benefit from it. Taking a look, for example, at the [Button](https://github.com/Automattic/wp-calypso/blob/master/packages/composite-checkout/src/components/button.js) component, it looks like it's mostly adding styles around a native `<button>` element.

For the ckeck out button, I'm not sure how much that would help us, it might even make our job harder because we will need to reset some styles and apply ours on top of the defaults. I pre-assume that might be more challenging that directly styling a `<button>` element and would make resulting styles more complex, difficulting the job of theme authors.

I agree there are some components both in `@automattic/composite-checkout` and `@automattic/components` that might be worth exploring for the Checkout block, actually that's why I delayed posting exploration conclusions in that issue until next week, so I could experiment a bit more with those components. But I couldn't find any component in the Cart block that would benefit from using `composite-checkout` as a base other than payment logos.

I identified some Cart components that might be a bit tricky because they are interactive:

* QuantitySelector: number input with plus/minus buttons.
* TotalsCouponCodeInput: includes a disclosure widget and an input box.
* ShippingOptionsList and ShippingOptionsListItem which include radio buttons.
* CheckoutButton.

When we implement them, we might consider investigating again if there are similar components that we can use as a base from other packages, but in a first exploration I couldn't find other components that would fit our use-cases and would make implementation easier instead of over-complicating things.

All other components are static content that I think shouldn't require the usage of an external package.

**Comment by nerrad** [comment]
Thanks for the explanation.  I'm still wary of avoiding adopting something simply because it doesn't _seem_ to have much benefit.  What tends to happen is we implement something from scratch (like a button) because it seems really simple, but then we realize that we want to provide a way to make a button "primary" or "secondary" in style but share similar design patterns.  Then we may realize we want to ensure there's an equal weight between primary/secondary variations... Before you know it, we've started to develop our own patterns around this "simple" component that diverges from a common design pattern adopted by other products/teams in the space.

This is one of the _foundational_ reasons why there's growing alignment around using base components for things we build so that we work with similar interfaces for modifying those components.  I'm _very_ wary of choosing the easy path of building our own implementations from scratch because it potentially makes it _harder_ for switching out styles and theming for the _entire interface_ (not just blocks) - not to mention increasing the risk of maintaining consistency in design patterns across an interface because there's different implementations of a button in multiple places.

With that said,  I do realize there's still some friction here due to the fact there's still uncertainty for _what_ package to pull an component from (`@wordpress/components`? `@automattic/components`? `@woocommerce/components`?) which is why I think it's important that part of our evaluation includes using something like codepen.io or some other tool to mock up implementing a leaf component and testing the assumptions we have about whether it's usable or not.

**Comment by Aljullu** [comment]
All good points, thanks @nerrad! One thing we should consider when deciding whether we want to use components from other packages as a base or not is whether they are intended for a similar purpose and are going in a similar direction than ours.

Some requirements our components have that I think should be shared by any component we rely on is:
* The component should try to keep dependencies as low as possible. In the button case, for example, that discarded `@wordpress/components`' button.
* The components shouldn't have an opinionated style that makes it difficult to overwrite the CSS. That was the reason that made me discard `@automattic/composite-checkout`.

Both of these requirements come from the fact that the components we need will be rendered in the user site frontend. And that's not the case for the components from the listed packages (`@wordpress/components`, `@automattic/composite-checkout`, `@automattic/components`, `@woocommerce/components`) -- please, correct me if I'm wrong!

I think, the debate is quite similar to the one we had when we split `components` and `base-components` between what was rendered in the editor and what was rendered in the frontend, because both use-cases were too different (dependencies, styles...) to meet both needs with one single component.

Summarizing, I'm all for sharing components with other WordPress and Automattic projects and I'm sure that's the way to go. But I'm also cautious to start relying on components that other projects use in their dashboards/editor pages in the frontend, because our directions might keep differing as time goes on.

> which is why I think it's important that part of our evaluation includes using something like codepen.io or some other tool to mock up implementing a leaf component and testing the assumptions we have about whether it's usable or not

That sounds like a good way to move forward. Should we create an issue for that?

**Comment by nerrad** [comment]
> That sounds like a good way to move forward. Should we create an issue for that?

👍

**Comment by nerrad** [comment]
Thanks for doing this @Aljullu, it has helped inform the breakdown of work for the cart block in the editor context 👍 I'm going to close this in favor of the new issues breaking things down.
