### ISSUE TITLE
Radio inputs shouldn't be unselectable and there should be an initial value selected

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1243]
As @senadir posted in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1237#issuecomment-557084336:

> Radio boxes shouldn’t be unselectable and also, there must always be an initial value selected, at least this is what I believe the case should be.
> 
> https://www.nngroup.com/articles/radio-buttons-default-selection/

But currently, all our blocks with radio inputs allow unselecting them. See _Featured Category_, for example:

![Peek 2019-11-22 09-39](https://user-images.githubusercontent.com/3616980/69410804-13223900-0d0c-11ea-970d-45a61493ba80.gif)

cc @joshuatf wondering if you have an opinion on that, should we proceed changing the behavior of radio inputs or should we leave them as they are now?

**Comment by nerrad** [comment]
(Copied from a comment I made in the referenced issue)

Some good points regarding accessibility here.  There's some other issues though:

- These are styled like radios but don't behave like radios - they behave more like checkboxes.
- The html structure is not using semantic html for radio selection but is divs, spans and buttons with aria attributes.  This eliminates a lot of things we get for free with semantic html - however, I understand this might be because of inconsistencies with how these can be styled across browsers.

I see that these come from components in `@woocommerce/components` (which means they live in the wc-admin repo) - so this might mean some changes might happen there.

**Comment by nerrad** [comment]
I think we need to decide here:

- if they are intended to only have one selection at a time and _must_ have a selection (we could set a default) then these should be radios.
- if they are intended to allow for multiple selections and/or have _no_ selection, then they should be checkboxes.

**Comment by senadir** [comment]
Should we move this to wc-admin repo? since the component lives there

**Comment by nerrad** [comment]
Perhaps, but it's also something we need to address in our blocks. So I'd prefer to leave here until we decide what path forward is needed.

**Comment by Aljullu** [comment]
Heads up that this issue might be fixed by this PR in wc-admin: https://github.com/woocommerce/woocommerce-admin/pull/6090.

**Comment by Aljullu** [comment]
This was fixed with https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4100.
