### ISSUE TITLE
Sale! Label not translated in WooCommerce Blocks

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gutenberg-products-block#1272]
**Describe the bug**
When adding products on a page using Gutenberg blocks, the Sale! label doesn't translate correctly, 

**To Reproduce**
1. Change WordPress language (I used Polish)
2. Create a product that is on sale
3. Install Loco Translate, and make sure the phrase `Sale!` is translated in both WooCommerce and WooCommerce Blocks:

![Screenshot](https://cld.wthms.co/9N7u9D+)
Screenshot: https://cld.wthms.co/9N7u9D

4. Open a shop / category page and observe the `Sale!` label is translated there:

![Screenshot](https://cld.wthms.co/8OA8YX+)
Screenshot: https://cld.wthms.co/8OA8YX

5. Create a new page and add there one of the Gutenblocks, i.e. Products by Category
6. Observe the word `Sale!` isn't translated there, even though it's translated in both core and Blocks plugin:

![Screenshot](https://cld.wthms.co/WYBpDx+)
Screenshot: https://cld.wthms.co/WYBpDx

**Expected behavior**
The label is translated consistently between category pages and blocks.

**Screenshots**
(see above)

**WordPress (please complete the following information):**

* Core version: 5.3
* Gutenberg version (if installed): (using core version)
* WooCommerce version: 3.8.0
* WooCommerce Blocks version: 2.5.1
* Site language: Polish (same happens in French)
* Any other plugins installed: Loco Translate

**Desktop (please complete the following information):**

* OS: OS X 10.14.6
* Browser: Chrome 78

**Comment by Aljullu** [comment]
For me this is working as expected:

![imatge](https://user-images.githubusercontent.com/3616980/73094890-d0ced100-3ee1-11ea-9293-bd066a0cd6a5.png)

![imatge](https://user-images.githubusercontent.com/3616980/73094964-ef34cc80-3ee1-11ea-8736-1a26ef829e4b.png)

I needed to load the translations into `languages/plugins/woo-gutenberg-products-block-es_ES.po`.

I also tried with the [translations from .org](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/language-packs/) and it was working as expected too:

![imatge](https://user-images.githubusercontent.com/3616980/73094343-aa5c6600-3ee0-11ea-9eaf-4663fbe1ffb0.png)

I also tried with a test site where I don't have anything dev related and was working fine directly installing the plugins via wp-admin. Both with WooCommerce only and WC + WC Blocks.

@madeincosmos could you confirm this is no longer an issue?

**Comment by dnl13** [comment]
Because of the intense of this Plugin relaying on woocomerce why not just using the translation of woocomerce that already exists ? 
Woocomerce translates "SALE!" already? 

their for you should just could change 

/src/BlockTypes/AbstractProductGrid.php > get_sale_badge_html()
Line 430:
`
 return '<span class="wc-block-grid__product-onsale">' . esc_html__( 'Sale!', 'woo-gutenberg-products-block' ) . '</span>';
`
to 
`
return '<span class="wc-block-grid__product-onsale">' . esc_html__( 'Sale!', 'woocommerce' ) . '</span>';
`
maybe this kind of handling translation could ease the use of custom translate files for woocomerce-blocks in general 

so maybe it will not neccesary to create or translate blocks all over, because translated strings comes from woocomerce 

Just thinking 

also still an issue in
Woo: 3.9.1 
Woo-Blocks: 2.5.11

**Comment by Aljullu** [comment]
Hi @dnl13, WooCommerce Blocks already uses WooCommerce translations when available, that was implemented here: #1242.

**Comment by dnl13** [comment]
then.. it's the question why it not catches the "Sale!"-Phrase  🤔

**Comment by Aljullu** [comment]
@dnl13 do you have some steps to reproduce this issue? In my [tests](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1272#issuecomment-578256260) I couldn't reproduce it, but would be happy to take a look if I can. :slightly_smiling_face:

**Comment by dnl13** [comment]
hm 
the setup is all latest updates 
WP 5.3.2
Woo 3.9.1
Woo-Blocks: 2.5.11

except the desktop
Desktop: mac 10.11.6 
Browser: chrome 79

- just create a post and insert the block 'products on sale' 
in the editor it does not translate also it did not at the frontend.
( without loco translation - i have never setup a translation for this WooBlock-Plugin) 

BUT i use also "Germanized for WooCommerce" this also adds translation maybe their is an overlap. the storefront "show products on sale on homepage" do the translation, but it's not a block :D 

first i was curious about my page setup for showing latest posts, but because the translation also not applied in the Gutenberg Editor that should not be the case.

For now i just did the quick and dirty method mentioned above but i should dig a bit deeper on whats going on their and get back with some more reliable informations  :) 
Also i did not know that the Blocks-Plugin already tries to get the translations from Woocomerce ( was guessing but not shure) 
anyway 
thanks in advance

**Comment by Aljullu** [comment]
@dnl13 thanks for the details, could you check which translations file you have under `/wp-content/languages/plugins/` (or whether they are in a different location)?

I assume you have `woocommerce-de_DE_formal.po` and `woo-gutenberg-products-block-de_DE_formal.po`, is that correct?

**Comment by dnl13** [comment]
Hey Aljullu, 
yep `woo-gutenberg-products-block-de_DE_formal.po` and also `woo-gutenberg-products-block-de_DE.po` (this is the basic german non formal translation as fallback) 
also `woocommerce-de_DE_formal.po` and a lot of `woocommerce-de_DE_formal-*md5hash*.json` but no json for `woo-gutenberg-products-block-*`. 
All files have their `*.po` pendant and are located at `/wp-content/languages/plugins/`

**Comment by Aljullu** [comment]
That was very helpful @dnl13! In the end I was able to reproduce, thank you.
