### ISSUE TITLE
Settling on the correct source for global styles.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1331]
It's a bit unclear currently in the project what should be the official source for styles (specifically colors at the moment but _could_ apply to other things too probably).  Currently we have the following potential and actual sources:

* `@woocommerce/components/build-style/style.css` (currently used in [`assets/css/editor.scss`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/css/editor.scss))
* `@automattic/color-studio` (wc-admin uses this)
* WP Editor Styles ([upcoming color palette for WordPress](https://make.wordpress.org/design/2019/11/26/proposal-a-new-color-palette-for-wordpress/))
* [Figma WordPress Foundation styles](https://www.figma.com/file/P6L7I2Iyyh2tcSw7jyELqfzV/WordPress-Foundation?node-id=812%3A337) (current WordPress styles and source for current mocks?)
* What we already have in the project ([`assets/css/abstracts`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/master/assets/css/abstracts))

For the [current cycle](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/975#workspaces/blocks-5a84601e79f97c2acc45cc58/reports/release?release=5de4fecab435b73314048e58) we're going to just go with what is in the mockups and implement some style variables for those things.

However, I think we need to start thinking about consolidating around _one_ source of truth for global styles and only override in the project as needed.  I think there's some overlap with the WooCommerce Admin project as well so @woocommerce/wc-admin I'd love some thoughts from you folks as well on this.

cc @garymurray who is going to try and pin down some things from the design side in terms of color styles.

**Comment by garymurray** [comment]
After looking into this - this is what I can see.

Currently - from what I am aware (that was shared with me via slack) we are using colours in these two ranges:

- `core-grey-light`
- `core-grey-dark`

We should be using colours from the these ranges:

- `WP Editor / Light`
- `WP Editor / Dark`

Until the new WP Editor colour palette that has been proposed is approved and in use. 

This is how the changes from using the `core-grey-light/dark` to `WP Editor Light/Dark` looks:

![colours](https://user-images.githubusercontent.com/10805911/70318241-81d8b980-1817-11ea-82fc-18d796955d54.jpg)

cc @jameskoster @josemarques @Dan-Q

**Comment by justinshreve** [comment]
I'll let the designers chime in, but I think for any WooCommerce specific brand colors (the purples), we want to use the WooCommerce colors found in `@automattic/color-studio` so that we are using a consistent color pallet across our products.

**Comment by garymurray** [comment]
@justinshreve agree - afaik the brand colors (i.e. Purple) comes from `@automattic/color-studio` but the greys used in the components all coming from the `WP Editor / Light` and `WP Editor / Dark` color range.

**Comment by Aljullu** [comment]
I would like to take this issue but would like to make sure we are all on the same page before starting:
* For gray color shades, we will be using `@wordpress/base-styles`.*
* For all other colors, we will be using `@automattic/color-studio`.

\* It was suggested to use the upcoming color palette for WordPress, but it hasn't been merged yet to Gutenberg (https://github.com/WordPress/gutenberg/pull/18701), so I think we should use Gutenberg's styles for now and they will auto-update when that PR is merged.

Once this is done, it should be safe to remove `/assets/css/abstracts/_colors.scss`.

Does that sound like a good plan @garymurray @nerrad?

**Comment by nerrad** [comment]
I'll defer to Gary on the final plan here, but from my perspective it looks good 👍

**Comment by garymurray** [comment]
I think the plan sounds right but to check @Dan-Q can you provide any insight/guidance here on the correct colour usage?

**Comment by ItsJonQ** [comment]
@garymurray / @nerrad Hi all!! 

> can you provide any insight/guidance here on the **correct** colour usage?

Good question! I don't know if there's an established "correct" way. However, I can share insights based on my experiences :)

Some form of "base" styles needs to be established - regardless if it's for an app or for many modules.
It's easiest if the base styles are a single file, or at most, a handful of files.

This is straight forward when you're just using something **directly without modification**.
Example, just using `@wordpress/base-styles`

Sometimes, we may want to combine multiple external things together:
Example, using `@wordpress/base-styles` x `@automattic/color-studio`

However, in most cases, we typically like to add/modify styles to customize things to our aesthetics and experiences.
Example:  using `@wordpress/base-styles` x `@automattic/color-studio` + custom stuff

**The last case is the most typical**.

I highly recommend optimizing for this workflow, especially if there's lack of synchronization between the app/modules and the external dependencies (e.g. slower merge cycles).

I lack the context for the `/assets/css/abstracts/_colors.scss` file... but I recommend having some sort of single file that "merges" all of the things together, like this (pseudo code below):

```scss
// @woocommerce/base-styles/colors.scss

@import "~@automattic/color-studio/dist/color-variables.scss";
@import "~@wordpress/gutenberg/colors.css";

// Add additional values here
// Or perhaps add overrides.
// Or even remapping variables, example:
// $valid-green: $studio-green-50;
```

This file then becomes the single entry point / "source of truth" for your app (in regards to colours). This technique can be replicated for other base values.

A note on colour names!

I've found that it's pretty difficult to remember which shades of blue/grey/etc... to use for certain instances.

For example, if I want a border... do I use `$core-grey-light-600`... or `700`... maybe `500`?
What colour should it be if I hover? Darker? Lighter? By how much...

This is where it's helpful to have mapped names.

So that `$core-grey-light-600`... becomes `$color-app-border`.

You may have something like this (made up values)

```scss
$color-app-border: $core-grey-light-600;
$color-app-border-hover: $core-grey-light-500;
```

This extra layer becomes much easier to read / remember.
Bonus: It also gives you extra control, as you can change those values, given certain context. e.g. Theme changes or dark mode.

Your consuming CSS doesn't need to worry about it. They just use `$color-app-border`.
The app just switches the value of `$color-app-border` given a specific context.

---

Hope this helps! <3

**Comment by Aljullu** [comment]
Loads of useful ideas, thanks @ItsJonQ!

**Comment by nerrad** [comment]
> // @woocommerce/base-styles/colors.scss

I like this idea of having an official `@woocommerce/base-styles` package, we should bring it up at the meetup @Aljullu ?  In the meantime we probably can start in our package by just consolidating the imports in a specific `.scss` file that we build from?

**Comment by Aljullu** [comment]
> I like this idea of having an official `@woocommerce/base-styles` package (published from `wc-admin`), we should bring it up at the meetup @Aljullu ?

Sure thing! It's a good opportunity to discuss this.

> In the meantime we probably can start in our repo by just consolidating the imports in a specific `.scss` file that we build from?

Right, that sounds like step 1. Once that's finished we could make a package with the colors scss file and some other scss logic (thinking on mixins, breakpoints, etc.).
