### ISSUE TITLE
Inner Block: not possible to add blocks before/after or edit as HTML when clicking on the 3 dots menu 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1392]
**Describe the bug**

Found this issue when testing `All Products` blick with `Inner blocks`. 

In `Inner Block`, it is not possible to add blocks before/after or edit as HTML when clicking on the 3 dots menu. 

**To Reproduce**

1. Create a page or a post where you can add blocks;
2. Add `All Products` block;
3. Click on the pencil icon to edit the blocks inside the preview to change the content displayed for each product within the product grid;
4. Click on 3 dots menu within the Inner Block - you will see that there is no option to add blocks either before or after or edit as HTML:

![inner3](https://user-images.githubusercontent.com/19143190/70909185-ced14280-2004-11ea-9615-6548a0b066b5.jpg)

Note that it is still possible to add blocks before or after when clicking on the plus icon between the blocks. Only WooCommerce Blocks can be added here though:

![inner2](https://user-images.githubusercontent.com/19143190/70909232-e7d9f380-2004-11ea-86ee-77d47056dfc7.jpg)

**Expected behavior**

I expected options to add blocks before/ after and option to edit block as HTML to be available when clicking on the 3 dots menu within an Inner block. 

Note that I tested a similar case with just Gutenberg blocks (non-WooCommerce blocks) and I can see that options to add blocks before/ after and option to edit block as HTML are available when clicking on the 3 dots menu within an Inner block. 

However, I am not sure what is the exact equivalent of an Inner block in Gutenberg which will behave the same as an inner block of All Products block. The closest I found is when using the “Columns” block and adding the “Media & Text” block within the 1st column. With this scenario, it is possible, for example, to insert blocks before and after the text block when clicking on 3 dots:

![columns](https://user-images.githubusercontent.com/19143190/70909449-6c2c7680-2005-11ea-9c8b-6a00cebc7e58.jpg)

**Screenshots**

See the screenshots above. 

**WordPress (please complete the following information):**

* Core version: 5.3.1
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: No

**Desktop (please complete the following information):**

* OS: macOS Catalina
* Browser: Chrome
* Version: 78.0.3904.108 (Official Build) (64-bit)

**Additional context**

Thanks to @rantoncuadrado for spotting this issue during his testing.

**Comment by nerrad** [comment]
Re "Edit as HTML" menu option: Not being able to edit as html was intentional.  Granting this ability runs the risks of users seriously messing up their content for this block and we want to provide a tight interface for better usability and functionality.

Re "Insert before" and "Insert after" menu option: I did some digging and discovered that the presence of these menu options [depends on whether the inner block supports the default block](https://github.com/WordPress/gutenberg/blob/ab8af23410f9f89f5a57064b43758b157f392d55/packages/block-editor/src/components/block-settings-menu/index.js#L82) (which in this case is the paragraph block).  Since we currently don't allow paragraph blocks in this context, these menu options don't show up.  We have an issue (#1084) that is for adding support for core blocks to this context and when we work on that it will enable support for these menu items.

I'm going to close this issue as a result of the above.  Please do re-open if you think we should look into at least adding support for the core paragraph block so that the additional menu items show up.

**Comment by juliaamosova** [comment]
Thanks for the explanation and additional research @nerrad! Make sense to close this issue now as per your comment 👍
