### ISSUE TITLE
Add Error Boundaries to the cart block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1427]
Adding Error Boundaries prevents the entire block from crashing if there are errors.  We'll need to think carefully about the following:

* Where the error boundaries are added.
* What the error boundary displays for frontend (customer of the merchant) context vs backend (editor) context.

**Comment by senadir** [comment]
Does it make sense (if possible) to render a `[cart]` shortcode if an error is detected on the frontend? I both love and hate this approach tbh 
In one side, it will prevent customers being lost if a problem arises, since we will have another template to prevent this.
In the other hand, the experience will be different, the block and template might not be styled the same, and it will require an extra reload for it to happen, so I have mixed feeling about it

**Comment by nerrad** [comment]
> Does it make sense (if possible) to render a [cart] shortcode if an error is detected on the frontend

Interesting idea, but I don't think it's something we should do. The error boundary is _mostly_ for catching _exceptional_ errors and those should generally happen most often during development or when a merchant is configuring their store. I also think that the errors this would catch would likely be thrown with the cart shortcode as well so swapping out one for the other won't be much improvement.

In light of that,  a good exercise would be to start thinking through what kind of errors might happen that the error boundary could catch?

- are there shipping related errors if the shipping method isn't configured correctly?
- would an error get thrown if there's a server side error due to a plugin/theme conflict (leading to invalid json returned from a request because of the printed php error notice in the response?)
