### ISSUE TITLE
All Products block: change product summary label

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#1442]
There's no field on the Product Editor called “Product summary”, the field it's called product short description. That label should be changed to "Product short description"

![screenshot-2019-12-23-at-15.19.42.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/24f54e46-9040-4630-90c5-6481ec6f908d)

**Comment by mikejolley** [comment]
@pmcpinto There is also no "on sale badge" or "button" in the editor :)

This is more of a "thing" than a field. In this case summary is derived from short description if set, but is not exclusive to short description, because it will use the full description (truncated to 400 chars) if that is missing.

If we must change this, how far do we go @nerrad? The blocks themselves are using "summary" naming.

**Comment by nerrad** [comment]
I mostly added this to the cooldown (current sprint) so we can deal with this issue.  I think we need to consider this from the merchant's perspective when they are picking from the block list. What will have more meaning to the merchant with the least amount of "thinking": _Product Summary_ or _Product Short Description_?  Will they care where the data is pulled from - or what specific field is attached to the data?

I like the idea of using Summary because it describes what the content is vs having to specify what it comes from (and as Mike pointed out, that content might derived from the short description field or the truncated product content depending on what's available). 

Plus, from a ui perspective, `Product Short Description` takes up more character space than `Product Summary`. This might be irrelevant when translated into different languages, but I do think it's valuable to think of ways we can label blocks that keep the char count relatively short to assist with more appealing visual layout.

**Comment by mikejolley** [comment]
👍 I prefer summary also. I will however go over the rest of the atomic block names (see some improvements we can make there), and check the API responses handle summary/short description correctly. Right now I am noticing discrepancies between the product and cart item APIs handling of this data.

**Comment by nerrad** [comment]
Maybe one place we _could_ make a change is to have the REST endpoints use `product_summary` for the field? I do like the idea of alignment with how the field is implemented (it also describes a bit better what that field is without locking it down to a specific database field?)

**Comment by mikejolley** [comment]
@nerrad I'm thinking along the same lines. Returning short, full, and a summary from both. The summary will be truncated - perhaps even taking the first paragraph since this is a product list and should not contain too much information.

**Comment by nerrad** [comment]
I like that approach, we should probably consider then how this impacts the Product Summary block (i.e. preserve what it currently renders, so whatever the new field is, it should serve the same data as what it currently serves?)

**Comment by mikejolley** [comment]
Hmm well I'm not sure about that because it would still be full 'short description' or 400 chars of the long. For where it's placed I don't think thats a great idea unless the user is entering short descriptions for real. We can add some logic to truncate more effectively if the description really is long. I think that will be this more useful, and also fit the mocks for the cart page where 'summary' is also used.

**Comment by mikejolley** [comment]
![Screenshot 2020-01-23 at 13 36 37](https://user-images.githubusercontent.com/90977/72989040-67699800-3de5-11ea-9328-c552450679c2.png)

@nerrad this is what needs to be avoided :)

**Comment by nerrad** [comment]
Oh ya, we don't want that! However, being that the block is in the wild, I'm wary about introducing changes that risk modifying the content in _existing blocks_ that may be published. Merchants might have already implemented workarounds to avoid that (modifying their content, modifying their excerpt etc.).  Also keep in mind that _we may think_ that looks ugly and is a dumb idea - but some merchant may think it's the bees-knees because it allows them to output things just the way they want (which is the whole premise of blocks).

So, to sum up:

- I agree, it'd be ideal if the default was "Product Summary" had clear expectations around what content and length of content it outputs.
- If we hadn't released any of these blocks yet, we could make changes without worrying about impact. But we have, so I think we need to consider impact on existing usages of blocks.

Options are:

- make the changes and existing blocks will be affected, but we just have to let merchants (and woo support) know what to expect. Accept that maybe not everyone will be happy about their content changing.
- Keep the existing block but change it's label to reflect what it does so that existing blocks implemented preserve the same behaviour. Introduce a _new block_ that implements the new behaviour (and is the default used in the inner block map).

I prefer the second option personally.  We could even do it incrementally, where an initial pull just changes the displayed label of the existing block (probably need to keep the existing block name/slug for back-compat though)

**Comment by pmcpinto** [comment]
> This is more of a "thing" than a field. In this case summary is derived from short description if set, but is not exclusive to short description, because it will use the full description (truncated to 400 chars) if that is missing.

Thanks for the feedback. I wasn't aware that it wasn't exclusive to the short description, in that case I think it's better to keep is as we have it now.

**Comment by mikejolley** [comment]
Option 2 adds tech debt. Let's rejig what is shown; respect short description so anyone using this already is unaffected, but apply more aggressive truncating on full descriptions because showing a 'full' description goes against the label on the block and could be considered a bug. Ideally I'd like to limit to 150 chars or extract a paragraph.
