### ISSUE TITLE
Document naming conventions for CSS classes

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1454]
We should write down some CSS naming conventions to make sure we all write CSS class names in the same way and allow contributors and theme developers to know about them.

I think we should stick to WooCommerce naming convention (https://github.com/woocommerce/woocommerce/wiki/CSS-SASS-coding-guidelines-and-naming-conventions) but stick to the prefix we are currently using (`.wc-block-`).

Thoughts?

**Comment by haszari** [comment]
Sounds like a great idea. From a quick glance at that doc, it might be better to draft our own clear standards (or update the Woo core doc). Since we're using React, we could consider basing our approach on Gutenberg project or Calypso. This doesn't contradict the Woo core doc, but it's focused on "BEM" since Woo core isn't using React directly (yet).

For reference, here's the Calypso doc: https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md

and the Gutenberg doc: https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md

Looks like the common thread through all these is [BEM](https://en.bem.info/methodology/) :)
