### ISSUE TITLE
Add api to draw attention to block settings on selecting Block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1469]
From the Checkout Block Epic:

> When the user selects the block in the block picker he should see a notification drawing his attention to the block settings

From the Cart Block Epic:

> When the user selects the block in the block picker he should see a notification drawing his attention to the block settings

In user testing we discovered a common pattern where it seemed folks weren't aware that there were additional settings in the inspector toolbar (in desktop views this is the settings in the sidebar).  

These notes are my own:

- The block settings panel only appears when a block is selected.  So it should be active when the user selects the block.
- I noticed that a number of the folks that were involved in the user testing were not regular Gutenberg users.  This is important because the block settings panel is a ui/ux thing for _every_ block, not just Cart and Checkout blocks.  If this is a significant problem, I think it should be handled at the Gutenberg core level, not just for our blocks.
- If it's decided we'll go through with this, we'll need some design work for what this notification will look like.

I think this issue should not be added to this release.

cc @pmcpinto and @garymurray .

**Comment by pmcpinto** [comment]
> I think this issue should not be added to this release.

I agree that this one can be implemented in a future release. In the usability testing the block was already inserted in the page which can somewhat influence the fact that the user doesn't notice the settings because he needs to click in the block first. In reality, all users will need to find the block in the picker so it will be selected as you mentioned and it increases the likelihood of seeing the settings.

And for first time Gutenberg users I think they'll see some instructions on how to use the block editor when they open if for the first time.

**Comment by nerrad** [comment]
I’m going to close this issue. This is more of a Gutenberg ui/ux problem as it applies to any block.
