### ISSUE TITLE
Price filter doesn't filter products based on their price with taxes

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1492]
**To Reproduce**
1. Go to _WooCommerce_ > _Settings_ > _Tax_ > _Display prices in the shop_ and select _Including Tax_. You might need to create tax rates if you hadn't done it before.
2. Create a post with an _All Products_ block and a _Price Filter_.
3. In the frontend use the price slider to select a narrow price range and notice prices are filtered as if they were not showing the tax rate.

**Screenshots & Expected behavior**
![imatge](https://user-images.githubusercontent.com/3616980/71809849-3c571880-3071-11ea-99ca-76c1399d4b0d.png)
If I select a price range of 15-16 I wouldn't expect products which are 16,5 and 17,6 (notice I have a tax rate of 10%, so they real prices are 15 and 16, that's why they are appearing).

![imatge](https://user-images.githubusercontent.com/3616980/71809902-5b55aa80-3071-11ea-83ad-6e3aa71e4228.png)
In this case, I would expect to see the album but not the cap.

**Comment by nerrad** [comment]
This is a problem with the actual query done server side.  Prices aren't necessarily saved in the db with price including tax (I'm assuming unless the option for having prices include tax is set), so when querying by the min/max range, it's just matching against prices saved with the product in the db, not prices _including_ tax.

To fix, we'd have to _reduce_ the incoming query params by the tax amount and then use that to query against products with.

**Comment by nerrad** [comment]
Alright, so this won't be a quick fix:

- prices could be saved to the db including or not included taxes.
- there may be a mix of taxable and non-taxable products in the db.

Based on those two conditions alone, if the store was configured with taxes and to display price including taxes, the following query join would be needed:

- if taxes not included in price in the db: the queried price value would need adjusted to not include tax, against products that are taxable, joined with the non-adjusted query price value  against products that are not taxable.
- if taxes _are_ included in the price saved to the db, then no adjustments to the query is needed because the price stored in the db would just be matched against the query values.

So the question is, should we try to get this in for 2.5.9 or is it something that can be marked as a known issue and done in a later iteration?

cc @mikejolley

**Comment by nerrad** [comment]
Turns out it wasn't as difficult as I thought it might be to fix so I've got a pull incoming.

**Comment by mikejolley** [comment]
This for me raises some important issues. Reliably filtering by calculated values isn't ideal, and the fixes we have to employ such as in #1501 where joining on a meta table can severely impact performance on stores with large amounts of meta data.

@nerrad I took a look at #1501 and it does look like a workaround for this, however, I am concerned by the introduction of a postmeta join on an already heavy query and I would suggest avoiding introducing this late in the release cycle for 3.9. There are also nuances to taxes which would break even with that solution in place, for example, products with different tax classes (standard rate vs reduced rate vs zero rate as an example).

I think instead we should spend a little time in a cool-down to brain storm an alternative approach (for example, introducing new lookup table columns), or consider not supporting the display of prices that differ from how they are input (if entered incl of tax, display incl of tax and vice versa). Since blocks is "new" I think we can get away with revising how this type of thing behaves in order to reduce complexity and improve performance.

**Comment by nerrad** [comment]
> Reliably filtering by calculated values isn't ideal, and the fixes we have to employ such as in #1501 where joining on a meta table can severely impact performance on stores with large amounts of meta data.

I agree here. As soon as I did the join with post meta I winced a bit.

>  I would suggest avoiding introducing this late in the release cycle for 3.9. There are also nuances to taxes which would break even with that solution in place, for example, products with different tax classes (standard rate vs reduced rate vs zero rate as an example).

I also agree.  If anything, this further supports my earlier reluctance to consider fixing this for WC 3.9.

> I think instead we should spend a little time in a cool-down to brain storm an alternative approach

On the surface, and based on your assessment, this appears to be a problem that exists in core now right?  In other words, the Pricing Filter block introduced here is exposing this problem?

I agree, we should focus on brainstorming a good approach for this and not rush it.  I'll remove from the 2.5.9 milestone and assign this for cooldown.
