### ISSUE TITLE
All Products block: improve alignment behaviour

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#1495]
**Is your feature request related to a problem? Please describe.**
In the sub-block, only the Add to cart button is aligned on toggling the 'Align buttons' option, but it might be worth it revisiting it, as other elements are aligned when put below the button.
Please also see pb22l9-5F-p2, #comment-283

**Describe the solution you'd like**
Better to be decided by the designers.

**Additional context**
Suggested by @josemarques during 3.9 testing.

**Comment by garymurray** [comment]
Brining the two screenshots of the issue here:

![screenshot-2019-12-23-at-15 03 38](https://user-images.githubusercontent.com/10805911/72254034-da5f5b80-35fa-11ea-88c9-6426e9b0b3fa.png)

If the blocks are re-ordered they then do seem to align:

![screenshot-2019-12-23-at-15 12 46](https://user-images.githubusercontent.com/10805911/72254066-eea35880-35fa-11ea-8972-078ef439856f.png)

I am not sure in this context - where someone has one image which is more landscape in orientation vs portrait that we should align all the content (description, price, button) with the one (description, price, button) that is the lowest - as this creates a disconnect between the description, price and button from the image it relates to.

Personally I feel the application/use case of using the option to align the buttons is where you perhaps have some product descriptions which take up two lines vs one line and you would prefer the buttons to remain aligned.
