### ISSUE TITLE
Products & product info are not available to editors, block cannot show live preview

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#153]
Users with role=editor or lower (author, contributor, etc) don't have the capabilities to edit/manage products or product categories, so the API doesn't let them list products. This causes the block preview to appear broken, never loading products or product categories (probably attributes too). The API response for these users is:

```
{
	"code":"woocommerce_rest_cannot_view",
	"message":"Sorry, you cannot list resources.",
	"data":{"status":403}
}
```

Should we…

- change the API to allow any logged in user to view products/product categories/attributes?
- Or should we only register the product block for admins & shop_managers (who already have permissions to see products etc)?

**Comment by claudiulodro** [comment]
Read access for logged in users sounds like the best solution. The most straightforward way of achieving this would probably be to make the changes  [in the bundled version of the products endpoint](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/includes/class-wgpb-products-controller.php) for now.

**Comment by claudiosanches** [comment]
> > change the API to allow any logged in user to view products/product categories/attributes?
> I think we should allow editors, authors, and contributors read access to product data so they can create blocks. @claudiosanches / @claudiulodro Is that possible?

This isn't simple thing to do, there's some sensitive information coming from products endpoint... When we started our REST API a long time ago has been decided to avoid expose any data in our endpoints, that's why we require high user roles to fetch any data in our REST API.

So we need to work on what data could we expose and how, this may have a huge impact on WooCommerce, since requires refactoring and changing how the REST API works, we could work with contexts like WP core does, some data is returned only when using `?context=edit` and leaving non-sensitive data to `?context=view`, this may also change how people uses our REST API too, but it's something good, since will help people creating apps.

**Comment by claudiulodro** [comment]
After discussing with @claudiosanches we have come up with a good solution. 

The authentication/capabilities limitation is going to need to be addressed in API v4 for a bunch of different endpoints. In API v4 (releasing with wc-admin) we're going to follow the way WP core does the API: the `view` context will have publicly available info (dimensions, price) and not require authentication; the `edit` context will have privileged information (download URL, etc.) and require authentication and capabilities. We will need to discuss the specifics as a team further and determine which information is privileged and which isn't.

In the meantime, a custom endpoint in this feature plugin that only returns the necessary information is going to be the way to go. @claudiosanches has volunteered to create this custom endpoint. (Thanks, Claudio!)

**Comment by claudiosanches** [comment]
I can try have this done by today, so tomorrow or in the day after, we should be able to test and release it.
