### ISSUE TITLE
Cart block - review bundlewatch file size limits

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1537]
In #1333 we temporarily bumped up the file size limit for `./build/cart-frontend.js` (60 => 100 KB). This is because in the hard-coded (temporary) test data for the cart, there's an inline product image. This is referenced in the test data and balloons out the size of the bundle significantly. 

As we complete the cart block and connect it to real store data via the API, this file limit should be reduced back down to an appropriate value.

**Comment by nerrad** [comment]
The test data should only be used when in the editor context (so should only affect editor script builds not frontend).

**Comment by haszari** [comment]
> The test data should only be used when in the editor context (so should only affect editor script builds not frontend).

To clarify - this test data is also currently used in the front end. This is temporary, until we hook cart up to real data - #1489.

**Comment by nerrad** [comment]
This can be an item done last as a part of shipping prep.

**Comment by senadir** [comment]
reviewing bundle size is not something we can do right now, there was some effort here and there to reduce bundle, I also started some discussions in #2140 #2141 #2142 and #2143 for some overall bundle enhancements, setting arbitrary limits now is not useful since we have no basis for them or how we define them, for the record, the preview data has been removed  yet the cart size is still 110kb (down from 160kb https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2134)
if this issue goal was about tracking and removing that extra weight, it can be closed, if it was about setting the limits we're comfortable with, I'd suggest leaving it for cooldown.

**Comment by nerrad** [comment]
The goal for this issue was just to review the code once we got the blocks mostly done and see if there were any quick wins for reducing bundle-size. I agree it looks like we've identified the lowest hanging fruit there and this can be closed.
