### ISSUE TITLE
WC 3.8.1 blocks by attribute hidden after attribute deleted

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-gutenberg-products-block#1610]
- Have inserted in post a block products-by-attribute and selected values.
- Saved and published post.
- Went over and deleted attribute value because I changed my mind.
- Went back to post and block is hidden, so I created new block products-by-attribute and selected another attribute.

Only last block with products can be seen in post edit screen. But if you switch from visual editor to code editor in post edit, you see two entries. First created block products-by-attribute is there and last block products-by-attribute is there too.

If a products-by-attribute block isn't longer value, it gets hidden in visual editor but still is in code and gets rendered in frontend.

This is codeview in post edit with two blocks products-by-attribute. First attribute was deletd by me:

![Bildschirmfoto 2020-01-18 um 22 33 25](https://user-images.githubusercontent.com/3390880/72670828-a8a72400-3a42-11ea-820e-47edb4b17adf.png)

This is visualview in post edit were first broken block products-by-attribute is hidden:

![Bildschirmfoto 2020-01-18 um 22 33 50](https://user-images.githubusercontent.com/3390880/72670829-acd34180-3a42-11ea-849e-2c0ae4cb411b.png)

**Comment by Aljullu** [comment]
Hi @ajgw, thanks for creating this issue! What version of WordPress are you using? Usually when a block is rendered as empty, it shows a message in the editor. That is how it looks for me after following your steps to reproduce:

![imatge](https://user-images.githubusercontent.com/3616980/72815635-395e4980-3c67-11ea-8b1a-a4ad630823d5.png)

I agree, however, the messaging could be improved stating that the attribute could not be found.

**Comment by ajgw** [comment]
@Aljullu Thats for me the same except as I described. WP 5.3.2. I expected a message on this block that term or attribute is missing but it is only hidden. Was wondering.

**Comment by nerrad** [comment]
Thanks for the report, however I'm unable to reproduce with WordPress 5.7 and the latest WooCommerce Blocks feature plugin or what is included with WooCommerce 5.2 (release candidates). I get this when following the reproduction steps:

<img width="882" alt="CleanShot 2021-04-07 at 14 23 21@2x" src="https://user-images.githubusercontent.com/1429108/113915832-3e94af00-97ad-11eb-9409-f1f12b652758.png">

Given this is consistent with what @Aljullu reported, I'm guessing this might have been an issue with Gutenberg at one point with how it handled empty rendered blocks which has since been fixed. Hence I'm going to close this issue.
