### ISSUE TITLE
Allow combining several filters in Product Grid blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1618]
[Feature request from .org feedback](https://wordpress.org/support/topic/products-by-category-and-tag/):

> Is it possible to select products by category and tag? Such as, show discount tag products for electronics category? 

Currently, all our product grids blocks only allow filtering by one topic (categories, tags, on sale...), but it might be interesting to allow filtering by several of these concepts at the same time.

**Comment by nerrad** [comment]
I think we may need some additional planning on what we want to do here. Do we want to enhance existing Product Grid blocks to allow for this, or look at adding controls to the All Products block so that it can be used for those more advanced "initial state/view" needs?  Personally I think we should invest in adding the controls to All Products...
