### ISSUE TITLE
Can't switch to Full Cart if an inner block is focused

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1627]
**To Reproduce**
1. Create a post with a _Cart_ block and switch to the _Empty Cart_.
2. Focus an inner block.
3. Click on _Full Cart_.
4. Notice the cart didn't switch to the full mode and you can only change modes if the inner blocks aren't focused.

**Screenshots**
![Peek 2020-01-22 15-51](https://user-images.githubusercontent.com/3616980/72904505-4ba3ba80-3d2f-11ea-8799-989670e871c3.gif)

**Comment by nerrad** [comment]
Hey @senadir I noticed you moved this to the "In Progress" pipeline. Just a friendly reminder to remember to assign an issue to yourself if you start working on it (just so we can tell at a glance who's taken ownership).

**Comment by senadir** [comment]
> Hey @senadir I noticed you moved this to the "In Progress" pipeline. Just a friendly reminder to remember to assign an issue to yourself if you start working on it (just so we can tell at a glance who's taken ownership).

I'm sure I did, seems it did not go through, thanks for reminding me.

**Comment by senadir** [comment]
So reporting in on what I found so far, Media + Text block seems to have similar behavior but the bug is not present in that block.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/6165348/75031697-24afe400-54a7-11ea-8bb8-d7d793075376.gif)

It seems `onClick` and `onMouseUp` events don’t register at all on the view switcher if the Cart block is not focused, other events like `onMouseDown` and `onFocus` do seem to register, but we can’t count on those events to switch view since they’re not meant to initiate that.
Another hack to fix this is to have a view switcher inside innerBlocks and somehow exclude him on save.

**Comment by nerrad** [comment]
Asked Nadir about the status on this because it was sitting in the In Progress pipeline for a bit and he said nothing changed since is final comment in here. 

I think we should _try_ to get this addressed before release, but it may have to be a known issue depending on whether we can find a suitable fix or not.

**Comment by mikejolley** [comment]
@nerrad @senadir If it helps, I traced the problem back to this line: https://github.com/WordPress/gutenberg/blob/72eca2a0730174796dac3e5f197985d8b2fba9ee/packages/block-editor/src/components/block-toolbar/utils.js#L32

This prevents the click event firing on the button.

**Comment by senadir** [comment]
@mikejolley deleting that line doesn’t seem to fix the issue so I doubt it’s the reason

**Comment by mikejolley** [comment]
@senadir ... I commented it out and didn't get the issue. Ill look again; I was also toying with some prevent defaulting on the click on our component at the time.

**Comment by mikejolley** [comment]
Ok @senadir you have to remove the line I said, then in `view-switcher/index.js` change the button click to this:

```
onClick={ () => {
								if ( document.activeElement ) {
									document.activeElement.blur();
								}
								setCurrentView( view.value );
							} }
```

That resolves it. The blur won't work without removing the line the Gutenberg,

**Comment by mikejolley** [comment]
Revisiting this, I can no longer replicate the issue with Gutenberg master, so looks to be resolved.

**Comment by nerrad** [comment]
Noice!  So we probably should give a heads up to HE about this being a problem with Gutenberg core if it comes up?

**Comment by senadir** [comment]
I managed to reproduce this with my slightly outdated GB, I will update to the latest master and see.

**Comment by senadir** [comment]
I can still reproduce this with the latest Gutenberg on master (running I'm on d3aeeec829157ff3cb48f5a59863a1f16754f38c

**Comment by mikejolley** [comment]
@senadir assume you built after updating? Chrome?

**Comment by senadir** [comment]
yes I did 
```shell
git pull
npm install
npm run build
```
on latest chrome and WordPress 5.4

**Comment by senadir** [comment]
maybe the modification for when you did the tests are still there?

**Comment by mikejolley** [comment]
OK @senadir only happens after interaction or creating new block/inner blocks. If you have the block already it doesn't happen.

**Comment by senadir** [comment]
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/6165348/78569922-301f5a80-781c-11ea-9a9e-92f42e37bb4b.gif)

it seems for me it happens for both cases, see the gif where I go to a page that already has the block in it.
