### ISSUE TITLE
Filter block on product by attribute block

### ISSUE THREAD

**Issue by golendercaria** [woocommerce/woocommerce-gutenberg-products-block#1705]
**Is your feature request related to a problem? Please describe.**
I am in a specific case where I need to generate product pages already filtered by an attribute or a category (example: tools) and on this page I would like to be able to use the sorting blocks. But, default on "All product block" i can't be define the initial filter by attribute or category. For massive website with a lot of segmentation, it will be great.

Thank

**Comment by nerrad** [comment]
Yann just to clarify a few points so I understand your question correctly:

- When you write "filter by attribute or category", are you referring to a term within a given attribute taxonomy or the attribute taxonomy?  For instance if you have a color attribute taxonomy, are you wanting to set the default results to be a specific color (i.e. blue, red, yellow)?
- when you write "generate product pages", do you mean configure route templates so that when a specific route is visited the block results are pre-populated with products matching a specific attribute or do you mean the All Products block is added to a page in the WordPress dashboard but you want the merchant to be able to set the default results returned for the products in the block settings?

If possible, I'm also interested in knowing why you wanted to use the All Products block for this approach as opposed to using the "Products by Attribute" block which is allows merchants to choose how to filter the product results shown with the block.  I'm _guessing_  you want the **default** to be customizable on page load but then allow for potential customers to change other ways the results are filtered using the filter blocks?

**Comment by golendercaria** [comment]
@nerrad i think you are understand :)

For the first point, it's exactly what i want.

For second point, imagine you are merchant sell drink, if you are a lot of product, you will want to do a few things that looks like this :
/shop-water => for display water
/shop-beer => for display beer
And on page shop-water for exemple, i would like use filter for finding sparkling water (via one attribut like type_of_water).

This is the kind of ecommerce that we are developing at the moment.

**Comment by kimmenbert** [comment]
We're currently developing a WooCommerce shop where all "category" pages will be built using regular pages, and Gutenberg blocks. The all products block and filtering blocks are a great start, and would be extremely versatile if you could set initial filters in all products block on page load.

I had to solve this by creating a custom Gutenberg block where you could set the initial filtering, then that block is used in frontend javascript to modify `wc/store/query-state`. Works okay, but would be lovely for this to be a part of the all products block.

Another usage example: You create a custom brand page, where you add an all products block, showing all the products from that brand.

**Comment by nerrad** [comment]
Thanks @kimmenbert for describing your use case. So essentially, what the big ask here is that there is the ability to set the default initial filter via either the block, or a given route on page load?

The former, is something that we could likely do as a future enhancement whereby filter blocks could have a default filter set.

The latter is something that's a bit more difficult to do but I did get a bit of a start on it [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1275).  It didn't make the cut for the initial release because there's a number of complex issues that need to be worked out.  Still, it'd be useful for not only initial route load defaults but also bookmarking filtered results.

These issues are on our radar but they are prioritized in light of other work queued up for our team. Of course we welcome any contributions folks want to make via pull requests if they have solutions that work (and we can review).

**Comment by kimmenbert** [comment]
Not sure if I completely understand the latter. But my suggestion is that there was a way to set initial query state in the block. Like a merge of the Products by attribute, on sale products and All products block, but with an extended functionality to select terms across multiple attributes, categories and other things like on-sale.

Then you would have the ability to create a specific page like Blue Levis jeans on sale:
Blue (color attribute) Levis (Brand attribute) Jeans (category) on sale (on-sale)

If adding stuff to Url query strings will be a thing then it could add all of these initial filters to the url query on the first change in filters/sorting/page frontend

**Comment by nerrad** [comment]
The request in this issue would be solved by #2373 so I'm going to close this one.
