### ISSUE TITLE
[4.0 beta1]: Filter by Price Block: results don't get updated when the slider is moved

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1715]
**Describe the bug**

Testing 4.0 beta1 pre-public release. Filter by Price Block: results don't get updated when the slider is moved. 

**To Reproduce**

1. Create a post or a page where you can add blocks;
2. Add `All Products` block on it;
3. Add `Filter by Price` block on the page / post;
4. Set up `Filter by Price` block with `Filter button` off. It doesn't matter if the `Price range` is `editable` or `text`:

![filter_by_price_wp-admin](https://user-images.githubusercontent.com/19143190/74144689-19ca9900-4bf5-11ea-9ebd-59e1033541f2.jpg)

5. Publish the post / page and try to adjust the price slider at the front-end - the slider doesn't move:

![](http://g.recordit.co/bhOgcXviX8.gif) 

**Expected behavior**

I expected for the slider to be able to move at the front-end and adjust the price. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.0 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.3
* Browser: Chrome
* Version: 80.0.3987.87 (Official Build) (64-bit)

**Additional context**

Beta 4.0 was not released to the public yet - this is found during testing the package we tagged before tagging beta and releasing it to the public.

**Comment by nerrad** [comment]
I'm unable to reproduce this in the following environments

- latest stable WooCommerce core with latest master of Woo blocks active
- latest master WooCommerce core with latest master of Woo blocks active
- latest master WooCommerce core with 2.5.12 tag of Woo Blocks active.
- 4.0.0 tag of WooCommerce core with Woo blocks feature plugin _inactive_.

Julia from your screenshot it looks like you only have _one product_ on your test site. The price filter also looks like it is defaulting to the range of $10-$20 on initial page load (likely because there's only one product).  The steps for the price filter default to $10 increments which is likely why it's not reacting to drag actions on the range selector.  Can you confirm whether you see this issue with more products in your store so the loaded price range is bigger?

**Comment by juliaamosova** [comment]
@nerrad I confirm that the issue happens only with 1 product on the site. However, do you not think that the slider should still move? Perhaps it is redundant since there is only 1 product and there is nothing to filter. I am Ok with whatever decision you/your team will take on this. Feel free to close in case you think there is no sense to have the slider move if there is only 1 product on the site.

**Comment by nerrad** [comment]
The slider isn't moving because the step size is 10. So in your case, the range between price variations for that single product is 10. That ultimately is why the slider isn't moving.  I think this is an edgecase that we don't need to handle. We could as an enhancement in future iterations of the block allow merchants to control the step size for the range but that's outside the scope of this issue :)
