### ISSUE TITLE
add_action option to be able to control the size of product image for product block

### ISSUE THREAD

**Issue by cinghaman** [woocommerce/woocommerce-gutenberg-products-block#1734]
Have add_action or filter to be able to control the size of the product image for product block separately from the default WordPress image sizes.

**Comment by nerrad** [comment]
Hi there, can you clarify exactly what block you are referring to? There are multiple blocks that could be considered a "product block". Thanks.

**Comment by cinghaman** [comment]
@nerrad Handpicked Products block
Use case: In general, for WooCommerce Shop page I have a grid of 3 elements so the default size set in Woo works correctly but for the page where I am making grid (sort of a landing page) I had 4 column blocks for which I needed to change default image size to be able to pick correct thumbnail size to not get cropped/squashed if that makes sense.

**Comment by nerrad** [comment]
Currently `HandPickedProducts` is using the `WC_Product::get_image` method which already [has this filter on it](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L1865) that you should be able to use.  Does that help?

**Comment by cinghaman** [comment]
@nerrad but wouldn't this end up affecting the normal thumbnail sizes for the Archive/shop pages too?

**Comment by nerrad** [comment]
> @nerrad but wouldn't this end up affecting the normal thumbnail sizes for the Archive/shop pages too?

Yes it would if you don't add any additional conditions to the filter callback. 

I'm making note of your request but we are being careful about what extension points we add to blocks because it's very likely we are moving more towards dynamic js driving blocks in the future. This doesn't mean that we won't ever add filters or actions in the future php side for blocks, but it's something we'll be doing deliberately (as we consider keeping support for those in the future).  In the meantime, your best bet is to try and make use of the existing filter as pointed out.

**Comment by cinghaman** [comment]
@nerrad thanks, don't mind the react/js root as long as there is a way to control/extend these blocks

**Comment by nerrad** [comment]
> don't mind the react/js root as long as there is a way to control/extend these blocks

Yes extensibility is important and something we're keeping in mind.
