### ISSUE TITLE
Cart shipping settings should not rely on each other

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1787]
Currently, we have two shipping settings that rely on each other
![image](https://user-images.githubusercontent.com/6165348/75036288-cf2d0480-54b1-11ea-9fa4-281a83689ed3.png)

Hide shipping costs depend on Shipping calculator being enabled for it to make sense, so it will be removed if the first option is off.

However, according to @mikejolley, those options should not depend on each other, and currently, in Woo, they work independently from each other, and they should continue to be so.

So this discussion is meant to see if we should have them depend on each other or not.

slack discussion for reference p1582128199452000-slack-C8X6Q7XQU

@garymurray

**Comment by garymurray** [comment]
I took a look at how these settings are working and have some input - I have mocked up the various permutations below based on the toggling of the settings:

**Permutation 1:**

Here the Shipping Calculator is enabled on the cart and the option to hide the Shipping costs is not turned on - so the shipping costs/options show on the front end. 

<img width="945" alt="Screenshot 2020-02-24 at 09 37 41" src="https://user-images.githubusercontent.com/10805911/75141639-50221100-56e9-11ea-8e7b-3d5b32dd939e.png">

**Permutation 2:**

Here, both settings are enabled - this then hides the shipping costs/options and the customer is prompted to enter their address before the shipping costs will be shown:

<img width="956" alt="Screenshot 2020-02-24 at 09 42 30" src="https://user-images.githubusercontent.com/10805911/75141972-fa9a3400-56e9-11ea-84f2-946ea0d9086a.png">

It is important to note though that from I can tell - this setting also relies on what ever the merchant has chosen under the `Default customer location` setting in WooCommerce Core:
 
<img width="690" alt="Screenshot 2020-02-24 at 09 39 18" src="https://user-images.githubusercontent.com/10805911/75141772-94151600-56e9-11ea-82a1-5fc419859698.png">

From what I can tell you have to actually set that to `No location by default` to actually get the option to hide the Shipping costs until an address is entered to work correctly - otherwise the store just defaults to the setting chosen there - i.e. default store address (which is the pre-set option) and you cannot actually hide the Shipping costs until an address is entered in the cart - making that setting somewhat null and void from what I can see. I would think that the cart setting should rather over ride that setting whereas currently that setting overrides the cart setting. 

**Permutation 3:**

Here the `Shipping calculator` has been turned off which removes the ability to do any shipping cost calculations in the cart (and in turn removes the second toggle) and the customer is informed in the cart that the Shipping costs are `Calculated at checkout`:

<img width="962" alt="Screenshot 2020-02-24 at 09 44 14" src="https://user-images.githubusercontent.com/10805911/75142095-39c88500-56ea-11ea-9582-07722cb7bc46.png">
