### ISSUE TITLE
Assess whether `store/cart/shipping-rates` should be decoupled from cart.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#1805]
Some discussion initiated by #1794 (see p1582626470029500-slack-C8X6Q7XQU) resulted in some back and forth on whether the existing `store/cart/shipping-rates` route should be coupled to the cart.

Currently it's coupled through:

- extending off of the `store/cart` route.
- using an instance `WC_Cart` to validate whether any of the items currently in the cart session need shipping (which in turn is used to determine whether any shipping rates are returned).

From some discussion we wondered whether we should decouple this endpoint and put it on `store/shipping-rates` so it could be used in more contexts (not just cart/checkout). Ideas posed were potentially back-end order creation.

Currently this issue description is just intended to capture a summary of the discussion but does not cover all points made or communicate what my stance is yet.

**Comment by mikejolley** [comment]
I'm going to suggest (and action on) closing this out (or we could move to discussions) because we've not come across an internal use case for this as of yet, and so the investment in a new endpoint is likely not worth the effort, and this would not be on the roadmap for Cart/Checkout development. Coupling this to the cart makes sense in the context of cart/checkout blocks.

> Ideas posed were potentially back-end order creation.

It's likely that if this was built into the backend (which may well happen in the future, we don't know), Store API would not provide this, since the backend would have access to more priviledged APIs. This type of functionality in a public API could likely be abused if used directly.
