### ISSUE TITLE
Adding a product from the cart empty placeholder should trigger the full cart

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1831]
**Describe the bug**
When your cart is empty, an empty cart is shown with some products bellow it, you can directly add one of them to your cart, this should trigger the cart to show your products and such, and not stay on the empty state, this means we should trigger fetching the cart from that place.

**To Reproduce**

1. Add a page with Cart
2. Make sure the cart is empty and you have products.
3. visit it and add a product directly.
4. the view stays the same (empty cart)

**Expected behavior**
the view should update.

**Screenshots**

![image](https://user-images.githubusercontent.com/6165348/75541907-01dd7c80-5a1f-11ea-913c-ddf2504960e5.png)

**Comment by haszari** [comment]
FYI @nerrad @garymurray  - do you think this is essential for this sprint, or can we trim this from scope (for cycle)? 

I think it's reasonable the way it is – it shows you three items, and the shopper might want to click add to cart for more than one item (before switching to cart view). Also, when you click add to cart, you get a "View cart" button, which allows the shopper to proceed to cart when they are ready. Perhaps we should hide or deemphasise the "your cart is empty" content at the top though.

**Comment by garymurray** [comment]
@haszari I think the best way for now is if someone adds one of those items to their cart we:

- Hide the your cart is empty content and just show the banner to "view cart"

**Comment by nerrad** [comment]
Manipulating the existing view might be just as time consuming as switching back to the full cart and loading it. I'll move this lower in the pipeline and it can be one of the last things we tackle (we'll have a better idea of time left at that point). The final component structure will be more finalized then.

**Comment by mikejolley** [comment]
I had a good look into this today to see what was possible. First off, some notes about the Empty Cart itself:

- We're using the older style SSR blocks, since All Products has not been rolled out for other pre-queried blocks yet.
- The SSR blocks are rendered with PHP and share add to cart logic with Woo core -- that means jQuery powered the Add to Cart buttons.
- Core add to cart buttons fire jQuery events when adding to cart. `added_to_cart` fires once the ajax add to cart event finishes.

I thought we could make use of the `added_to_cart` event in our Cart block and trigger an update when it's fired, however, it's not possible to listen to these events without jQuery.

https://makandracards.com/makandra/71890-events-triggered-by-jquery-cannot-be-observed-by-native-event-listeners

So this leaves us only a few options:

1. Add jQuery dependency and use it to listen for the event 💩 
2. Update core to fire native events https://developer.mozilla.org/en-US/docs/Web/API/Event/Event in additon to jQuery events
3. Replace the "new products" block and other SSR blocks with All Products - All Products uses the data stores for add to cart buttons.

2 and 3 sound viable, but 3 is longer term. I think we may want to punt this issue for this release - it's not that critical - you can still click "view cart" after adding the item to the cart.  cc @nerrad

**Comment by nerrad** [comment]
I vote punt as well. How often to customers browse the the cart page when it's empty?  It is definitely something we'll want to look into at some point but we can delay for now.

**Comment by garymurray** [comment]
Happy to punt this for now.

**Comment by nerrad** [comment]
This was implemented somewhere along the line because I can now add a product from the empty cart and the full cart is immediately loaded.
