### ISSUE TITLE
Filtering Element Specific classes

### ISSUE THREAD

**Issue by anteksiler** [woocommerce/woocommerce-gutenberg-products-block#1865]
It would great to filter these classes here to modify inside themes/plugins:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/e2c78fcc86606fad72e7672673ac0cd4951ba0d3/src/BlockTypes/AbstractProductGrid.php#L287-L292

**Comment by nerrad** [comment]
Hi there 👋 

Can you give some example use-cases that _require_ this list of classes to be filterable?

**Comment by anteksiler** [comment]
Hi @nerrad, we already have css styles for the products on the shop page. With simple layouts,  it is unnecessary to create separate css for the blocks, instead, we can just add the same classes.

**Comment by nerrad** [comment]
While I understand the convenience adding these classes in via filters presents for styling, it doesn't appear to be something _required_ to accomplish what's desired. It sounds like the goals can be accomplished by simply including block style selectors in with the theme stylesheet?

We're reluctant to add filters (or actions) server side unless there's clear demonstrable need because of the lock-in that creates for supporting those filters and actions in the future. We're still experimenting with what extensibility will look like in the future with WordPress and how that affects WooCommerce blocks. You can read more on our thoughts here in #891 

For now I'm going to close this as something we don't plan on adding soon, but it has been linked to #891 and will be considered along with the other requests. Please do add to this issue if you have further thoughts on this.
