### ISSUE TITLE
frontend.js files are loaded in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1910]
**To Reproduce**
1. Create a post with the _All Products_ block and filters blocks, for example, even though any JS-rendered block would work.
2. Open your browser devtools and switch to the network tab. There, filter by files that contain the string `frontend` in their name.
3. Reload the tab.
4. Notice the `-frontend.js` file of each block was loaded, even though that file is only used in the site frontend.

**Expected behavior**
All files named `frontend.js` are only used in the frontend, so we should avoid loading them in the editor.

**Comment by nerrad** [comment]
Just noting this is because of how we enqueue these scripts via the `render` method in the php block class. Some things to remember about this implementation:

- If there are no blocks in the editor, then anything in that method will not get invoked (important if the block _depends_ on data being registered there.)
- If there are blocks in the editor, then anything in that method _will_ get invoked (which is how frontend scripts are showing up).

We could probably do an `is_admin` check to not load frontend scripts in the editor.
