### ISSUE TITLE
All blocks are broken in master and WP 5.0

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1914]
**To Reproduce**
1. In a WP 5.0 install, try adding any block from WooCommerce Blocks to a post.
2. Notice it crashes with this error in the console: `TypeError: o is not a function`.

The issue seems to happen here:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/filters/block-list-block.js#L23

**Screenshots**
![Peek 2020-03-09 21-23](https://user-images.githubusercontent.com/3616980/76254153-3e457f80-624c-11ea-8e3e-c91990d9c422.gif)

I didn't test other versions of WordPress, which might be affected as well.

WooCommerce Blocks 2.5.14 is not affected and it works properly.

**Comment by nerrad** [comment]
We should probably see if this occurs on other more recent WP versions (WP 5.1, WP 5.2 etc). If it doesn't occur and this is only a WP 5.0 issue we might still have to address because of Woo Core minimum support but it may involve gating this particular functionality to WP 5.x+ (which I think is ensuring default attributes are set correctly on blocks - original issue triggering this is #1262... so we _may_ be able to just limit this to the all products block for wp 5.x+)?

**Comment by Aljullu** [comment]
I tested it in WP 5.1 and WP 5.2 and confirming the same happens: `master` triggers an error when adding any block while 2.5.14 works fine.

Reading #1262 and #1613 I assume it's still fine to conditionally disable that functionality for old versions of WP and make it work only on WP >=5.3. Users of old versions of WP will still see the blocks with one row by default, and when they upgrade to WP 5.3 or higher, the defaults would update.

**Comment by nerrad** [comment]
Thanks for confirming Albert and grabbing this 👍
