### ISSUE TITLE
Decide approach for component/element styles for Cart and Checkout blocks across themes and via Customizer settings.

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#1964]
Reported by @haszari in #1959.

_added by @nerrad_: This issue also has some discussion around general approach that should be taken with styling of components and elements out of the box for existing themes.  

Also, for _new themes_ (or existing themes wanting to do something specific for the blocks), what do we want to expose for design manipulation by themes/customizer?

**To Reproduce**
1. Go to the _Customizer_ and set the text color to red.
![imatge](https://user-images.githubusercontent.com/3616980/76628895-c3c37b00-653d-11ea-83d0-e816d1017ed3.png)
2. View the _Cart_ and _Checkout_ blocks.
3. Notice the _Cart_ block completely ignores the custom color, while the _Checkout_ block only applies it to specific lines (see screenshots below).

**Screenshots**
_Cart_
![imatge](https://user-images.githubusercontent.com/3616980/76629293-5532ed00-653e-11ea-926b-622ed9d862b4.png)

_Checkout_
![imatge](https://user-images.githubusercontent.com/3616980/76629239-41878680-653e-11ea-8540-6c5590106d76.png)

**Expected behavior**
Currently, the design of the _Checkout_ block looks broken because of this. We would need to decide whether we hardcode all colors and make it so they can't be overwritten by the customizer, or find a way so all text in the blocks honors the customizer color.

**Comment by nerrad** [comment]
cc @garymurray and @LevinMedia .  I think we want to be very opinionated with the block styles right?

**Comment by garymurray** [comment]
Here are the options Shopify gives for controlling font size and colours in the checkout:

<img width="284" alt="Screenshot 2020-03-16 at 10 38 55" src="https://user-images.githubusercontent.com/10805911/76748257-5a787d80-6772-11ea-9e30-d8ff8be1d700.png">

They don't allow you to control the colour of your actual font - however, in the case of WordPress - what is the theme has a dark/ish background, and we are not allowing you to change the colour of the font to a lighter colour - this would break the UX of your site - so I think we have to inherit the colours someone uses/changes things to in the Customizer?

**Comment by nerrad** [comment]
The problem we deal with here is there isn't a consistent interface we know user's will be working from in a WordPress context (literally the wild west). Shopify is able to tightly control their themes and thus offer an interface like this because they have an _enforced_ design system for their themes. WordPress doesn't (hopefully Global Styles will help this a bit).

So the fact this issue is about customizer is moot, the real issue is how a _theme_ affects those colors and styles. I think we _do_ have to inherit font colors at a minimum because of the possibility a theme might be light or dark based. But, I'm on not sure about other styles (font type, font-size, input field styling etc) because changing those can dramatically affect the "look" of the cart/checkout.

Thoughts?

**Comment by LevinMedia** [comment]
Relates to #1539 - pending an feedback in pb0Spc-oQ-p2

**Comment by Aljullu** [comment]
The issue we face with the <i>Checkout</i> block is that it uses several font colors, not only one. We can inherit the default color from the theme, but the lighter/darker shades can't be inferred from it.

The <a href="https://user-images.githubusercontent.com/3616980/76629239-41878680-653e-11ea-8540-6c5590106d76.png">example screenshot</a> shows that: we are currently inheriting the default color (which is set to red). But lighter shades are hardcoded to light gray, so they don't honor the theme color.

Some solutions we have:
<ul>
<li>Always inherit the default theme color for all elements in a block. Themes would still be able to modify the color of each element, but by default all of them would use the default theme color. We could update Storefront with our preference of colors, but the block for itself would be "font-color-neutral"</li>
<li>Hardcode all colors in the block, like it's currently done in the <a href="https://app.slack.com/client/T024FN1V2/DCE08LX7A"><i>Cart</i> block</a>.</li>
<li>Honor theme font color when possible, but keep hardcoding other font colors used in the block. This is how it's currently done in the <i>Checkout</i> block.</li>
</ul>

**Comment by LevinMedia** [comment]
>We can inherit the default color from the theme, but the lighter/darker shades can't be inferred from it.

@Aljullu Would it be possible to use opacity to achieve the other shades based on the default theme color?

**Comment by haszari** [comment]
> @Aljullu Would it be possible to use opacity to achieve the other shades based on the default theme color?

@LevinMedia That might behave strangely when the background colour is dark or colourful, I don't think that would be a practical solution.

**Comment by LevinMedia** [comment]
Been playing around with it some more, I actually thing it's a decent option. As long as the the font color is readable on the background to begin with (which it should be...) this will work. 

https://www.figma.com/file/yPo2qaVib20DJR5wN015h5/Opacity-based-color?node-id=0%3A1

I'll fiddle with it in the actual design files tomorrow.

**Comment by nerrad** [comment]
@LevinMedia sounds great! We'll also need to make sure that we keep at a minimum, a ratio of 4.5:1 color contrast as well.  I'm assuming you're considering that but just dropping this in here in case.

**Comment by Aljullu** [comment]
How could we make sure colors keep a ratio of 4.5:1 after reducing opacity? A theme might set its default color vs. background with a contrast of 4.5:1, but at the moment we decrease the opacity of the text, that contrast will get lower.

I don't think there is a perfect solution to this problem, so I'm not saying I'm against it. Just pointing out that reducing opacity of text might break accessibility in some themes.

**Comment by nerrad** [comment]
> How could we make sure colors keep a ratio of 4.5:1 after reducing opacity? 

I think the only way we could do this is via some JavaScript right?  A google search turned up this script: https://github.com/LeaVerou/contrast-ratio

**Comment by LevinMedia** [comment]
>A theme might set its default color vs. background with a contrast of 4.5:1

They shouldn't 🤞 but they might. Additionally, if a theme lets you change your colors, you could conceivable set them something way out side of that contrast ratio. The best solution here would be a checker in core WP customizer that warns you about your current settings - but that's obviously outside the scope what we're looking at here. 

If we did go the javascript manipulation route, is that something we could defer to a later release? At a minimum we'd want to ensure the default contrast ratio met 4.5:1 before any overrides or inheritances are applied. 

cc: @garymurray

**Comment by garymurray** [comment]
I think a theme should be able to control the following in order to align it with the overall design aesthetic on the site (as a starting point)

**Generally:**
- Button colour
- Button radius
- Border radius on product thumbnails

**Cart specific:**
- Colour of the `Cart Totals` card
- Shadow/no shadow on the `Cart Totals` card
- Colour of low stock and savings indicators

**Checkout specific:**
- Colour of the `Order Summary` card
- Shadow/no shadow on the `Order Summary` card

**Comment by nerrad** [comment]
@garymurray, are there things on that list that you think should be a component level style that could be toggled by the merchant?  To me - a lot of these things could be controlled at the block level and make it easier for merchants to tweak to suit not only the theme, but their own desire specifically for these blocks.  I can think of themes where the blocks inheriting the styles from the theme is just _really bad_ and it would require some custom css in the theme to fix that. Would it be better if instead of custom css, the merchant could just modify some of these things in the block inspector itself?

Another question. What is important for release? I think we need to nail down a scope with regards to styling for release.  One suggestion I have is that we target full Storefront compatibility initially for the blocks and then just do cursory fixes etc in default WP themes to make sure there's no ux breakage. 

Personally I don't think we should support customizer styling affecting the block and instead work towards putting the styling controls within the block itself (with a goal to eventual global styles support). That is something that we could iterate on after initial release?

**Comment by garymurray** [comment]
> are there things on that list that you think should be a component level style that could be toggled by the merchant? To me - a lot of these things could be controlled at the block level and make it easier for merchants to tweak to suit not only the theme, but their own desire specifically for these blocks. I can think of themes where the blocks inheriting the styles from the theme is just really bad and it would require some custom css in the theme to fix that. Would it be better if instead of custom css, the merchant could just modify some of these things in the block inspector itself?

I think to start, the theme should be able to style them to suit their design.

In future releases we could add more customisation options at the block level if we get enough feedback requests for this I feel. 

> Another question. What is important for release? I think we need to nail down a scope with regards to styling for release. One suggestion I have is that we target full Storefront compatibility (with the qualification this doesn't include customizer support) initially for the blocks and then just do cursory fixes etc in default WP themes to make sure there's no ux breakage.

Targeting full Storefront compatibility and perhaps Twenty Twenty is a good place to start for initial testing I feel. We could then test it against the other most used themes to see how it looks/works and see where/how those themes might run into issues and where/how we should work with the themes to get them to make updates to support the new blocks?

> Personally I don't think we should support customizer styling affecting the block and instead work towards putting the styling controls within the block itself (with a goal to eventual global styles support). That is something that we could iterate on after initial release? One great advantage of in block style control support is that there are some a11y tools we can get for free (warning about contrast etc).

Ultimately I agree here, I don't think we should put effort into supporting the customizer and if we do anything it would be to add extra levels of support/control at the block level. To start with though, a theme author should have some ability to ensure the blocks work well with their theme design.

**Comment by senadir** [comment]
Some technical thoughts about this:

- Themes should support us, not the other way around, we might support Storefront as a start, but moving forward we should enforce some kind of default style that won't be affected by cascading.

- For easier expandability, our specificity level should consistent and be around 1, due to the nature of theme and plugins and the ecosystem we're playing with that is simply uncontrolled, this is impossible.

- Those are brand new project and we should be able to include brand ways, one of which is CSS-in-JS.
simply hoping to write our css in a stylesheet and hoping theme would respect it and cascade won't ruin it is hard, for that our styling should be tightly coupled to our components in which themes can't easily override it *by mistake*.

- We should select and choose what to expose, Gary pointed out some things in the [comment above](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1964#issuecomment-610938467), with those things, pointed out, we can expose them as css variables, theme authors can choose *intentionally* to extend and modify those variable to things they want and link, if a theme owner does nothing, the theme simply keeps the default option.

- As we advance further, we can incorporate those changes to the global styles, either merging or using global styles variables directly, or extending them with our own, this should allow normal users to change styles with ease, without waiting for a developer.

- This is a big refactor, as such, it will take some time and thinking, there is also the possible backlash that can be mitigated by seeing how WordPress core solves those backlashes and build from there.

- For now, we can keep trying to hack around those issues in this scope, but ultimately I believe this is the most sound solution.

**Comment by garymurray** [comment]
Just to add to the above - ultimately if a theme has already provided custom styling for the things mentioned in this comment: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1964#issuecomment-610938467 (other than those specific to the cart/checkout) the cart/checkout should inherit that styling.

**Comment by Aljullu** [comment]
I'm closing this issue because everything has been fixed or it's being tracked in smaller issues:
* Heading colors: #2597.
* Text/border colors: #2745.
* Button styles: #2761.
* Font sizes: #2533.
* Dark mode input fields: #2606.

Feel free to reopen or create a new issue if I missed something. :slightly_smiling_face:
