### ISSUE TITLE
Featured Category: add color options for the title and the description sections

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#2045]
If would be great to have a color option for the text located in the title and the description sections. If we have a light background then it can cause some accessibility  issues:

![the Featured Category block](https://snipboard.io/glmeM6.jpg)

**Comment by nerrad** [comment]
Hi there 👋

Thanks for taking the time to share this idea, we really appreciate your help.  

While this is clearly a great idea, we won't be able to tackle it in the upcoming weeks as we're currently focused on finishing all the work that was identified as a priority for the next release of this plugin.  I'm going to add this to our backlog where it will be considered for future releases.

**Comment by nerrad** [comment]
This is definitely a valid feature request. On our roadmap we have plans for converting our existing blocks to use inner blocks and this would in turn mean that the various inner blocks would have the controls mentioned here. No ETA on when this will happen but since this will be covered by that work I'm going to close this issue.
