### ISSUE TITLE
Handle errors on `StripePromise` for the stripe payment method `canMakePayment` logic.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2065]
Currently `StripePromise` silently discards any errors caught by it's exception handling. The primary reason for doing this is because the only time it was throwing errors for me in my testing is when things were loaded in the editor and the stripe.js is currently _not_ loaded in the editor context.

However, we should still have error handling and maybe do something different in the editor context. Some ideas:

- if in editor context don't throw error (except if #2056 implements loading stripe.js we can't do this).
- also need to detect what type of error (i.e. if because invalid api key or api key isn't available then need to show an appropriate error on the frontend?).
- context aware error? If in frontend and not logged in as admin, show shopper friendly error. Otherwise show merchant friendly error to help with debugging?

**Comment by Aljullu** [comment]
I would like to give a shot at this next day but would need some clarification first. The issue is about exposing the errors in this `catch` block?
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/load-stripe.js#L16-L19

Or is there something else I'm missing?

Would make it sense showing an error notice in the frontend with a text depending on whether the user is an admin or not? If it's an admin we display the error returned by stripe and if it's a client we display a generic friendly text?

In the editor I think it's safe silently discarding all errors, no? There are some errors that might it be interesting to display in the editor (wrong API key, for example), but we currently don't have a UI for displaying this kind of errors in the editor and I think exposing it in the frontend is good enough, at least for the MVP.

**Comment by nerrad** [comment]
For editor context I think we're going to have to load stripe.js if we want to show the stripe elements (which is the route I think we'll have to take). So this pull should mostly be about just surfacing errors like api key etc gracefully according to the context (i.e. editor can have more information for the merchant to resolve).

> In the editor I think it's safe silently discarding all errors, no? There are some errors that might it be interesting to display in the editor (wrong API key, for example), but we currently don't have a UI for displaying this kind of errors in the editor and I think exposing it in the frontend is good enough, at least for the MVP.

With moving stripe.js loading in the editor so we can use stripe elements for the preview, I think we could get away with just console.error for any errors for the MVP (and improve error display on iterations).

Does that help?
