### ISSUE TITLE
Flow: I've inserted some products but I don't want to display the add to cart buttons

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#21]
Current prototype: todo

Sketch: todo

**Comment by GlennMartin1** [comment]
I understand this issue is closed, but it's not resolved.

Products block > block settings panel > Display title
and
Products block > block settings panel > Display price
and
Products block > block settings panel > Display Add to Cart button

- On the back end, it works.
- On the front end, these are always displayed regardless of block setting.

**Comment by jameskoster** [comment]
@GlennMartin1 this issue is superseded by https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/23
