### ISSUE TITLE
Save payment information checkbox should only be available for logged in users.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2118]
I noticed while testing in an incognito window that we currently show the save payment information checkbox for stripe even if the user is not logged in. Obviously this isn't good (unless there's logic in place to automatically create a user - which there isn't?).

I'm not sure if woo still saves payment info for anonymous users or not (subscription management?).  I'm guessing saved payment info always requires a user account.

**Comment by haszari** [comment]
Confirmed the issue, in shortcode checkout, the save checkbox is not shown when logged out:

<img width="884" alt="Screen Shot 2020-04-07 at 4 03 56 PM" src="https://user-images.githubusercontent.com/4167300/78628820-7db5c900-78e9-11ea-9f2c-c644ee083466.png">

Checkout block + stripe payment method shows the checkbox even when logged out:

<img width="867" alt="Screen Shot 2020-04-07 at 4 05 35 PM" src="https://user-images.githubusercontent.com/4167300/78628867-a50c9600-78e9-11ea-8ef2-b2ad05fb8ec4.png">

So the goal of this bug is to only show that checkbox (in Stripe payment method) if user is logged in / has an account :)

**Comment by haszari** [comment]
Question - what's the best way to detect if a user is logged in in a block context (in a payment method)?

- Could expose user info via payment method interface.
- Could add something to `wcSettings` - we have `currentUserIsAdmin` but nothing about the user.
- Could detect via page class i.e. `body.logged-in`.

**Comment by mikejolley** [comment]
There is no account creation logic yet anywhere on checkout; I imagine we will want it in in a future version (login, create account, and auto-account creation). For now, hiding checkbox will be needed.
