### ISSUE TITLE
Improve UI signal that a cart item is being removed.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2126]
Currently, when we delete a cart item, we block the item and wait until the server response for it be deleted, I think it would be better if we directly delete it from local state, the server response will confirm this by having it deleted as well, if it failed being deleted for some reason, the item will pop up again.

**Comment by nerrad** [comment]
I'm not sure we want this behaviour.  Why do you think it's better?

The problem I have with an item popping up again is because it introduces jerky ui/ux and the user is left wondering _why_ it popped up again. By disappearing right away it also gives a potentially false signal that the item is actually deleted and the user might go ahead and hit the browser back button or navigate to another page etc.

So I disagree with this approach and think we should leave as is (incorporating some signal that the item is being removed but not finished yet - maybe just adding an overlay over the entire line item that applies a greyed out effect).

**Comment by garymurray** [comment]
I think the ideal UX here is:

- Open selecting to delete/remove an item it greys (50% opacity maybe) out the item while the process is happening
- The customer should not be able to do any other action in the cart while that is taking place
- Once the process has taken place, the item is "actually" removed from the cart visually
- The customer can then continue in the cart (go back to the shop, proceed, another action)

**Comment by senadir** [comment]
> the user is left wondering _why_ it popped up again
The server should probably return an error of why it didn't delete that element, in which the Cart should handle and show like other errors, but I can see why a user might want to leave the page or advance in that moment.

**Comment by senadir** [comment]
> The customer should not be able to do any other action in the cart while that is taking place

I went with not disabling other things (like other changes to quantities or selecting other shipping methods or applying coupons) since it doesn't affect anything and the server will deal with in sync (first in first served).

I did however disable that item when it's being deleted and disabling the continue to checkout button.
