### ISSUE TITLE
Shipping Radio buttons are overlapping text in Cart block

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2191]
**Describe the bug**
In Cart block, it seems radio buttons are overlapping the text
![image](https://user-images.githubusercontent.com/6165348/78988345-98c24c00-7b28-11ea-8b52-5f39158cecdb.png)

This only happens in Cart, checkout seems to be fine.
![image](https://user-images.githubusercontent.com/6165348/78988373-a8da2b80-7b28-11ea-9f30-821e104c88ec.png)

### How to reproduce:

1. Have at least two shipping options on the same zone to trigger a select.
2. do a production build `npm run build`
3. on Cart, notice the overlap.

**Comment by senadir** [comment]
this only happens in a production build 🙃

**Comment by nerrad** [comment]
Does this happen in every browser @senadir?

**Comment by senadir** [comment]
Yes, it happens on Firefox and Safari, all production build, only cart

**Comment by senadir** [comment]
seems to be a priority issue

Dev (when it works fine):
![image](https://user-images.githubusercontent.com/6165348/79116480-804c6e80-7d80-11ea-8cb3-b09755fe61e3.png)

Prod (when it's broken):
![image](https://user-images.githubusercontent.com/6165348/79116493-8a6e6d00-7d80-11ea-82f8-b4271acc6998.png)

**Comment by senadir** [comment]
I going to temporarily move this issue to you @Aljullu and I will surface back to it later, I gave it a couple of hours but couldn't reach a desirable solution, here is my take from it:

- While the ordering of styles is the issue here, I believe it simply showed us a flaw in the way we wrote code, how you define independent styles should not be affected by that code ordering or who is included first.
- Some of our styles and classes are really confusing and are not well scoped to that block/component, take for example the `wc-block-totals__shipping-options` class that is applied to `<ShippingRatesControl>` in Cart but not in Checkout, besides needing to have the name scoped, it provides conflicting results for the underlining code, the checkbox (and related labels) have conflicting styles between `radio-control-styles` mixin and `totals-shipping-control` so we might want to unify those two.

- How we present shipping rates is different between Cart and Checkout, this result in us needing two versions of the same styles, I think the different should only be in the layout, but the styles should be the same, for reference, this is how we define a rate in checkout

https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/master/assets/js/blocks/cart-checkout/checkout/block.js#L90-L101

And this is how we define it in Cart:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/master/assets/js/base/components/cart-checkout/totals/totals-shipping-item/shipping-rate-selector.js#L10-L25

This is to accommodate for the different styles for rates in Cart and Checkout blocks

Checkout Design:
![image](https://user-images.githubusercontent.com/6165348/79121842-3074a400-7d8e-11ea-9351-f3d0155210fa.png)

Cart Design:
![image](https://user-images.githubusercontent.com/6165348/79121875-41251a00-7d8e-11ea-959e-c70fca76e7f7.png)


I think we're solving this in the way we're defining `renderShippingRatesControlOption` so no extra styles should be needed.

**Comment by Aljullu** [comment]
> - While the ordering of styles is the issue here, I believe it simply showed us a flaw in the way we wrote code, how you define independent styles should not be affected by that code ordering or who is included first.
> - Some of our styles and classes are really confusing and are not well scoped to that block/component, take for example the `wc-block-totals__shipping-options` class that is applied to `<ShippingRatesControl>` in Cart but not in Checkout, besides needing to have the name scoped, it provides conflicting results for the underlining code, the checkbox (and related labels) have conflicting styles between `radio-control-styles` mixin and `totals-shipping-control` so we might want to unify those two.

I'm all for avoiding overwriting CSS rules as much as possible, but I don't think that's 100% possible neither desirable if we keep using plain CSS instead of a CSS-in-JS solution.

A component might have some base styles that the consumer might want to overwrite. In this example, the `<RadioControl>` will have some default styles, but in the _Cart_ and _Checkout_ blocks the design is a bit different (different margins, one vs. two columns, etc.). So in some cases styles need to be overwritten.

Regarding this:

> besides needing to have the name scoped

What other name do you propose for that class?

> - How we present shipping rates is different between Cart and Checkout, this result in us needing two versions of the same styles, I think the different should only be in the layout, but the styles should be the same, for reference, this is how we define a rate in checkout

We still need some different styles because everything is rendered in one column in the _Cart_ sidebar while options might have two columns in the _Checkout_ block. Spacing is a bit different as well.

---

I created a new PR with some fixes #2208. Let me know how it looks. :+1:

**Comment by senadir** [comment]
> A component might have some base styles that the consumer might want to overwrite. In this example, the <RadioControl> will have some default styles, but in the Cart and Checkout blocks the design is a bit different (different margins, one vs. two columns, etc.). So in some cases styles need to be overwritten.

This can be solved by modifiers `--wide` `--narrow` or something similar, keeping the same namespace and overriding in a an expectable way (so that our ovverrides are declarative in the code, not depending on the scope of where they're called), this can also help us have all modifications in the same place, as it helps reason what is modifying what.

> What other name do you propose for that class?

possibly name scope it the Cart block? for those styles are only applied because of that modification, or give it a modifier class.

> CSS instead of a CSS-in-JS solution.

CSS-in-JS might not be able to fully solve this either, we use the same component in two places we should expect the same result, you can't pass different styles from the parents (at least it wouldn't make sense), this is also a case for a modifier (in this case the modifier can be a prop).

But I'm all in to switch to full JSS, so many other problems will be solved.

> I created a new PR with some fixes #2208. Let me know how it looks. 👍

Yes, I'm reviewing it, thank you for your effort, I know that if someone can solve it, it would probably be you.

**Comment by Aljullu** [comment]
> This can be solved by modifiers `--wide` `--narrow` or something similar, keeping the same namespace and overriding in a an expectable way (so that our ovverrides are declarative in the code, not depending on the scope of where they're called), this can also help us have all modifications in the same place, as it helps reason what is modifying what.
> CSS-in-JS might not be able to fully solve this either, we use the same component in two places we should expect the same result, you can't pass different styles from the parents (at least it wouldn't make sense), this is also a case for a modifier (in this case the modifier can be a prop).

Oh, right that makes a lot of sense. I'm not completely sure a solution like that would work for all components, but for the `<RadioControl>` that would be a great idea.

However, for example, the Panel needs a different left padding whether it's inside a Card or not:

_Cart:_
<img src="https://user-images.githubusercontent.com/3616980/79217987-01266b80-7e50-11ea-8c07-0d1f983ba76a.png" width="262" />

_Checkout:_
<img src="https://user-images.githubusercontent.com/3616980/79217956-f66bd680-7e4f-11ea-80a7-96ae15241717.png" width="277" />

Do you think that should be handled by a prop as well? Or just CSS is ok?

> possibly name scope it the Cart block? for those styles are only applied because of that modification, or give it a modifier class.

Currently the class name is scoped to the component where it's defined, which is a `<TotalsXYZ>` component, that's why the class starts with `wc-block-totals`. I agree the name could be improved, maybe `wc-block-totals-shipping__options`? Actually I think all components under `/totals/` could be renamed to something nicer (`<TotalsShippingItem>` could be `<ShippingTotals>`, for example). But I would avoid adding a `cart` specific class to make that component self-contained so it can be used in other components if we ever need it.

**Comment by senadir** [comment]
> But I would avoid adding a cart specific class to make that component self-contained so it can be used in other components if we ever need it.

Ideally, you might want to have the class for the shippingTotals but being passed from the cart, but this is also fine, in the future we might also let Checkout use a similar pattern.

Getting CSS to behave on a large scale is a serious challenge.
