### ISSUE TITLE
notices are pulling inconsistent styles

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2205]
**Describe the bug**
It's very subtle but I noticed that notices are pulling different fonts from the one provided by the theme

![image](https://user-images.githubusercontent.com/6165348/79140233-932a6780-7daf-11ea-993d-ed55fab3e3d6.png)

notice: 
```
-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen-Sans,Ubuntu,Cantarell,Helvetica Neue,sans-serif
```

rest of block (inherited from theme):
```
"Source Sans Pro", "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
```

my opinion is that everything should inherent styles as is, so no one should define a font, or everything should define a font so that the theme can't change it, making it consistent.

**Comment by mikejolley** [comment]
This is a WooCommerce core style specifically for Twenty Nineteen and Twenty Twenty themes. Headings are setup to use the system front, and woo core applies the heading font to notices also.

This is not within the scope of blocks - blocks reuses notice styling from woo core. Since this appears to be an intentional css rule I don't think it requires a follow up.
