### ISSUE TITLE
No validation when you created an email restricted coupon

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2235]
1. Create a new coupon 
2. In usage restriction, set allowed emails to `*@automattic.com` this should allow any a12s to place an order.
3. go to Checkout Block and place that coupon.
4. checkout with any other email (Gmail or something)
4. notice that there is no validation whatsoever and your order passes normally.
![image](https://user-images.githubusercontent.com/6165348/79361634-7885f900-7f3d-11ea-83ea-efb7f84e9c64.png)

![image](https://user-images.githubusercontent.com/6165348/79361707-93f10400-7f3d-11ea-8669-3607318dbc30.png)

**Expected behavior**
It should not allow me to finish the order, classic checkout gives this error and removes the coupon.

```
Sorry, it seems the coupon "a12s" is not yours - it has now been removed from your order.
```
![image](https://user-images.githubusercontent.com/6165348/79363973-8c7f2a00-7f40-11ea-8f5f-a0cc485d00b0.png)

**Comment by mikejolley** [comment]
Just noting, the cart class does this validation on the `woocommerce_after_checkout_validation` hook. That hook isn't compatible with new checkout because it posts all checkout data, something we cannot do afaik (?).

https://github.com/woocommerce/woocommerce/blob/3bf473517d407ae46264e0081dfeafedbcce68d6/includes/class-wc-checkout.php#L826-L864

To solve this I need to add these checks to our new API endpoint. It will work the same, but won't be able to reuse all of the core functions. 

https://github.com/woocommerce/woocommerce/blob/3bf473517d407ae46264e0081dfeafedbcce68d6/includes/class-wc-cart.php#L1448-L1491

cc @nerrad

**Comment by nerrad** [comment]
Ya I agree that's what you'll have to do @mikejolley.  My concern here is that we're duplicating logic between our blocks and core and that will have to be kept updated as things change. I think it's _really_ important we document where we're doing this kind of thing (maybe a woo core issue) and think through how core logic can be improved so we _don't have_ to do this.  For example, taking a brief look at `WC_Coupon::check_customer_coupons` - it looks like the main reason we can't use it directly is because it's adding errors as notices. It'd be _much better_ if that was refactored so that the logic in that function is moved to separate function that _returns_ any detected errors and then calling code can decide to do what it wants with them. In this case `WC_Coupon::check_customer_coupons` would call the new function and then just add the returned errors to a notice, then our blocks can call the new function to do the validation and return any errors on the endpoint.

This is a great example where Woo core needs to split out notice setting from being mixed in with processing logic and leave notice setting etc to the layer responsible for the type of incoming request.

**Comment by mikejolley** [comment]
The other reason is because `check_customer_coupons` uses $posted, which does not exist in our context.

@nerrad We should document yes, however, I think core changes can be limited in this case because (I think I've said this before) core checkout is going to be superseded by block checkout, so even if we do maintain and duplicate logic, eventually the block logic becomes the _only_ logic.

**Comment by nerrad** [comment]
> I think core changes can be limited in this case because (I think I've said this before) core checkout is going to be superseded by block checkout, so even if we do maintain and duplicate logic, eventually the block logic becomes the only logic.

Yup, good to keep in mind, but getting from here to there is still a journey that could take a while. So we want to try and keep the transition as painless as possible. If that means doing _minor_ refactors of existing core functions I think it's worth it.
