### ISSUE TITLE
Cart: demo product short description appears in the front end

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2294]
**Describe the bug**
If you have not set a Product short description in the backend for your product - on the front end it is pulling through the demo content - see screenshot below of a product with and without on the front end:

<img width="730" alt="Screenshot 2020-04-27 at 11 58 29" src="https://user-images.githubusercontent.com/10805911/80364993-c58f9680-887e-11ea-9f5a-b861fa093ea8.png">

The first one there has one set on the backend, the second one does not - in that case it should be blank rather than showing 'fake' content.

**To Reproduce**
Add a product to your cart that does not have a Product short description set - then view it on the front end.

**Expected behavior**
If a product does not have a Product short description set - none should appear in the cart/checkout.

**Comment by nerrad** [comment]
This looks like it is related to #2293 and in particular [this comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2293#issuecomment-620639773) which highlights how product _summary_ (which is what being used here) works. Essentially what is happening is the expected behaviour but it sounds like what you want here is to always just show the value of `short_description` field even if it's empty. Is that correct?

**Comment by garymurray** [comment]
Right - I just realised my mistake here - because my test site used those demo products - when I was viewing the front end of the cart to preview the cart I was expecting to actually see 'real' product description and not the demo content - but, now I realise that I was actually previewing the 'demo' content on the front end - so this makes sense.

Will close this one then as it is actually working as expected.
