### ISSUE TITLE
Cart/Checkout: Inconsistent styling

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2299]
**Describe the bug**
In Storefront specifically - the current shop shortcode does not use underlines on the product names - although they are linked. See screenshot:

<img width="265" alt="Screenshot 2020-04-27 at 12 17 10" src="https://user-images.githubusercontent.com/10805911/80366337-09839b00-8881-11ea-9bbb-1ca32285b475.png">

The cart/checkout block though uses links on the product titles - see screenshot:

<img width="291" alt="Screenshot 2020-04-27 at 12 18 12" src="https://user-images.githubusercontent.com/10805911/80366462-346def00-8881-11ea-83d1-1deda4304d3e.png">

This creates inconsistencies across a site using blocks and shortcodes. I think this forms part of the much bigger styling issue/conversation that is ongoing.

**Expected behavior**
The blocks should obey and inherit the styling of my theme.

**Comment by nerrad** [comment]
Some important things to consider here:

- Why are we comparing the cart/checkout block styles with the shop styles? Shouldn't we compare apples to apples? For instance the current **shortcode cart** has underlines for product titles because they are links (whereas shortcode checkout does not because it is not a link).
- The All Products block has an underline on the product title because it is linked.
- The shop shortcode actually has the entire product info area linked (not _just_ the title) which is why the title is likely not underlined (for accessibility reasons). 

<img width="1920" alt="Image 2020-04-28 at 12 58 25 PM" src="https://user-images.githubusercontent.com/1429108/80515502-11f6d700-8950-11ea-9d4d-75c7706e23e0.png">

In my opinion the current behaviour of the cart and checkout blocks are consistent with the new pattern introduced with All Products and accessibility for having underlines on linked text and is an _improvement_ over the current shop shortcode.

My vote is to leave as is.

**Comment by haszari** [comment]
Agreed, there are arguably lots of inconsistencies when you go looking, this is a tricky area.

**Comment by garymurray** [comment]
Overall this is what I would like to see us address in the upcoming cycle. There should be some level of consistency and if we are not going to be able to update the shop shortcode to be all block based, perhaps we should be pushing fixes/changes to the the shortcodes to bring those into alignment with the blocks?

**Comment by Aljullu** [comment]
What are your thoughts on closing this issue? Some of the inconsistencies between blocks have been fixed in previous cycles and the scope of this issue seems a bit too broad/unclear to me.

If we identify new inconsistencies, I think we should create individual issues for each of them.

**Comment by nerrad** [comment]
Let's close it 👍 (as long as the specific issues in this have been addressed).
