### ISSUE TITLE
Checkout: Alignment of elements in Setup shipping options card

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2311]
**Describe the bug**
When there is not Shipping options setup - we show a prompt to get the customer to get set them up on the backend - however all the elements in the block are left aligned - I think they should all be centre aligned.

<img width="682" alt="Screenshot 2020-04-27 at 11 20 20" src="https://user-images.githubusercontent.com/10805911/80369537-574ed200-8886-11ea-9626-b3a28b60f36f.png">

**Comment by Aljullu** [comment]
I might be wrong, but I think they were initially centered and at some point placeholders became left-aligned in Gutenberg. That replicated in our blocks because we are using the same components.

For reference, this is how a placeholder looks for the image block:
![imatge](https://user-images.githubusercontent.com/3616980/80727049-858e1500-8b05-11ea-8ca9-e76560ea862a.png)

@gary centering shouldn't be difficult at all, but I would like to double-check that we want to differentiate our blocks from Gutengberg's before doing the change.

**Comment by garymurray** [comment]
I've been noticing that it appears they have shifted to left aligned as part of a change in Gutenberg perhaps.
