### ISSUE TITLE
Button placement inconsistent between cart and checkout

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gutenberg-products-block#2321]
**Describe the bug**
Proceed to Checkout is Displayed on relatively towards the top of the page irrespective of how many items in the cart there are (on mobile it floats at the bottom of the viewport) while Place order can be buried pretty far down the page:

![Screenshot 2020-04-27 at 16 08 07](https://user-images.githubusercontent.com/2207451/80383201-95a6ba00-88a3-11ea-8362-d9e3ff5fc015.png)

I'm not a designer, so maybe it has its UX considerations, but to me as a user, it seems inconsistent and I was initially surprised to not see the Place order button right below the CC card details, as it's usual with other checkout solutions.

**To Reproduce**

1. Import Storefront products
2. Add 5 or 6 items into the cart
3. Go to checkout
4. Not see the Place order.

**Comment by nerrad** [comment]
@garymurray do you want to add some direction here? To a degree some of this is due to the current behaviour when there is no short description defined for a product (and we use a truncated description instead - related to #2293 and #2294) but it's also possible for shoppers to encounter this even if that were addressed.

I'm guessing in the case of checkout this might be fine because this allows the user to see the total connected with the place order button.  However, it also means that it could end up below the browser fold in the case of a big order.

Either way, this needs some design feedback.

**Comment by garymurray** [comment]
The place order button should be directly below the Payment method section and not pushed down based on the size of the Order Summary card - from the data I saw most WooCommerce stores sell on average below 2 items per order - so the chance of them having this issue where the order total is pushed below the browser fold is low.

If we see this becoming an issue and/or it is reported - we can add an order total to the top of the Order Summary card.
