### ISSUE TITLE
Cart - "Hide shipping costs" option wording mentions checkout

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2343]
![Cart - hide shipping cost option relates to checkout.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/bda1f1ff-ce50-4d1b-9011-a96b35d29565)

I re-read this when testing to try to understand it again. I realise this is based on existing wording (and I might not understand fully). A couple of thoughts: 

- Toggling the option on and off, I notice that it hides or shows options (radio buttons, with fast/slow/tracked shipping) for the shopper to choose from. So the option name might be more `Hide shipping options until an address is selected`? When it's off, a cost is still displayed (in editor), so `Hide shipping costs` feels misleading.

- Mentioning "checkout" in the context of the cart block is confusing to me - can we remove this bit? Or does this refer to an address saved for the customer in a previous checkout, i.e. `Shipping rates will be hidden unless customer enters an address in cart or has an address saved in their account`?

**Comment by haszari** [comment]
When enable `Hide shipping costs`, I still see the radio buttons on the front end (logged out, incognito) - is this expected?

<img width="1122" alt="Screen Shot 2020-04-29 at 4 07 49 PM" src="https://user-images.githubusercontent.com/4167300/80560017-95d5bf80-8a33-11ea-9161-a91920aa8159.png">

**Comment by mikejolley** [comment]
> Mentioning "checkout" in the context of the cart block is confusing to me

You can't have one without the other, and the reason it's mentioned is because checkout may be the only time you can input your address, hence the text _during checkout_ i.e. the shipping fields on the checkout form.

**Comment by nerrad** [comment]
> When enable Hide shipping costs, I still see the radio buttons on the front end (logged out, incognito) - is this expected?

It's not just _hide shipping costs_ though. It's _hide shipping costs until an address is entered_. From your screenshot it looks like you have an address?  So it appears to be working as expected (at least from my perspective). I think the reason why you have an address even though you're logged out and incognito is because your site is probably configured to have a default customer location:

<img width="728" alt="Image 2020-04-29 at 4 35 42 PM" src="https://user-images.githubusercontent.com/1429108/80644354-848eb200-8a37-11ea-9a05-3c867d535059.png">

Is that the case here?

We had a lot of back and forth in the related issues for this specific option and setting and text used. What we have is what we decided to roll with after various iterations (see #1561 and #1943). That doesn't mean that there might not be further room for improvement, but I'd like to see what kind of feedback we get when the blocks are released before we iterate further. From my perspective the wording we currently have is a bit clearer than the _existing wording_ for shipping settings found in the global WooCommerce shipping settings tab.

I'm going to close this, let's monitor for additional feedback and see if it surfaces as a pain point for merchants.
