### ISSUE TITLE
Inconsistent use of real cart/product data in All Products vs Cart/Checkout blocks

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2363]
In the cart & checkout blocks we are using [preview data](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/previews/cart.js) to show off the blocks in a known state. This includes "fake" products and cart selections.

For other blocks, such as All Products, we're using the real product data, and even showing the admin user's real cart selections:

![All products shows real cart content in editor (inconsistent with cart_checkout).png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/82ad0dba-3710-4b22-b5b5-6582a0735391)

This is inconsistent and could be confusing. Perhaps we can come up with a standard set of rules/guidelines for how we use preview / fake data and real content / data in the editor (and any exclusions/loopholes). Then over time we can make any changes needed so the blocks are consistent in what data they display in the editor.

**Comment by nerrad** [comment]
Agreed, this is something that can probably be looked into as a part of our next cycle work.

**Comment by mikejolley** [comment]
I think the main argument(s) for preview data in cart are:

a) We don't want to load a real cart in the admin area
b) We don't want, and cannot reliably, add products to the cart for an admin user because we cannot be sure we're dealing with products simple enough to do so, or if those products will play nice in the admin context e.g. a store with only external products which cannot be added to cart.
c) We are switching between empty and full cart views. Neither can rely on the current cart state.

Products are different. We're showing real data there because the options within the block directly manipulate what products get displayed, and there is no complex state to manage.
