### ISSUE TITLE
Create new context and components to handle the add to cart form for Single Products

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2397]
The _Single Products Block_ will have some components that need to interact with each other, notably for the add to cart form. These components include:

- Variation picker, which lists available variation attributes, and matches them to a variation ID. 
- Quantity selector, which should get constraints (max) from the current product 
- Add to cart button, which uses data from the above two components to make a request to the API

We could accomplish this by grouping them into a single add to cart form component, or we could look at having a shared context so the add to cart button can get data from qty/variation picker before making a request wherever they are rendered.

If we go with context and separate Atomic blocks for this:

- Is variation picker available at all times, or only if the chosen product is variable?
- Can variation picker be limited to 1 per block?
- If the product is changed, what happens to existing blocks already added?
- Does the default innerblock template contain variation picker?
- What happens if variation picker is missing and someone adds to cart?

If the above cannot be worked out, we could instead go with a _Single Add to Cart Form block/component_ which would contain the qty selector, variation picker, and add to cart button together. The merchant would then insert these all at once, and the appearance/rendering would match the mockups. I think this would be easier to implement on our side but could lack flexibility for merchants.

@nerrad @garymurray Any preference or feedback on this?

**Comment by nerrad** [comment]
💯 to shared context approach.

I had wondered if we might be able to reuse the existing cart context provider we created for the cart. Some advantages:

- It's already wired to cart data.
- It has all the events needed for cart.
- It provides the potential for using express payment buttons (since the payment method context is available).

Then inner block components would have exposure to all the data provided by that context provider?

**Comment by mikejolley** [comment]
@nerrad I think we'll still need a separate context specific to the form requirements; not saying we can't also implement cart context, but we need one to:

- Store _selected_ qty
- Store either selected variation attributes, or selected/matched variation ID (needs exploration - this could be client side or server side code). If doing it with attributes, it could be used to trigger to variation ID match if this is needed before the add to cart event is triggered.

Then the add to cart button under this context would use those values to create the request, or use existing hooks where possible.

But there are hurdles mainly for merchant experience, see my bullets above. Some things such as add to cart would *need* the variation picker, so we need to ensure merchant cannot shoot themselves in the foot.

**Comment by nerrad** [comment]
Store selected quantity and selected variation attributes would still need to also be _read_ from the cart if the product was already added to the cart somewhere else right? That's why I think _ideally_ we implement a context that is consistently used anywhere there is potentially Add to Cart (or eventually one button purchase) functionality.

> But there are hurdles mainly for merchant experience, see my bullets above. Some things such as add to cart would need the variation picker, so we need to ensure merchant cannot shoot themselves in the foot.

Agreed, from a _block_ standpoint (the grouping of the various components), I think we may want to keep variation picker etc something that merchants might be able to reposition but not remove (as it would be dynamically aware of the the type of product).

Which also makes me wonder, since there's a variety of product types, should we have various edit context views (similar to how the cart has the full cart and empty cart views) for different product types? That way merchants can fine tune how the single product looks for the different product types and potentially we can add extensibility points for extensions to register other product types to handle? Would this be in keeping with some of the flexibility the single-product template works for themes?  If so, this does complicate the ui/ux and definitely requires design input (cc @LevinMedia as well). With that in mind, we'd have to be careful to scope what we want for i1 and plan for future iterations that might add those various editing contexts.

**Comment by mikejolley** [comment]
@nerrad to address your specific points:

> Store selected quantity and selected variation attributes would still need to also be read from the cart if the product was already added to the cart somewhere else right? 

No I don't think so. The add to cart forms don't need to be aware of what is already in the cart - you choose your options, try to add to cart, and get back a success or fail.

> Which also makes me wonder, since there's a variety of product types, should we have various edit context views (similar to how the cart has the full cart and empty cart views) for different product types?

We don't need to do this - the single product block only shows a single product, with a single type. So any blocks we surface can be built around whatever is selected. For example, if you choose a variable product, the variation picker block is available. Assuming thats possible of course. The difficulty comes when the product changes, or the product is edited outside of the context of the block. 

That's also why I said the "single add to cart" component/block would be easier; it can adjust to reflect the product type during render.

**Comment by nerrad** [comment]
Thanks Mike, that brings some great clarity for me. So what do you need here to move forward, some design work for the flow and interactions in the editor?

**Comment by garymurray** [comment]
> If the above cannot be worked out, we could instead go with a Single Add to Cart Form block/component which would contain the qty selector, variation picker, and add to cart button together. 

This sounds like the simplest approach here - both in terms of what we build and how merchants add these blocks/products to their site. If I understand correctly here and the way I see it - a merchant would add this block to their site, and pick the individual product they want to show - and it would "largely" show that product as it would appear in the the "single product page view" you would get if clicking through to view the product from the product archive page for instance.

If the merchant was to go edit that product itself, it would automatically update the block, as it would the "single product page view".

If we decide that this is the best approach in terms of building this - what are we trading off in terms of the other suggest approaches outlined in the initial comment?

**Comment by mikejolley** [comment]
> If we decide that this is the best approach in terms of building this - what are we trading off in terms of the other suggest approaches outlined in the initial comment?

- It would limit the user in terms of placement. i.e. moving the button away from the qty selector, or inserting extra content within the template
- it would prevent us replacing atomic blocks with other options. For example, perhaps we develop a swatches based variation picker which can be swapped for the regular variation picker.

These are potentially future things - we could provide these as separate atomic blocks in the future reusing the same components so it's probably not critical.

**Comment by LevinMedia** [comment]
> >If we go with context and separate Atomic blocks for this:
> 
> Is variation picker available at all times, or only if the chosen product is variable?
> Can variation picker be limited to 1 per block?
> If the product is changed, what happens to existing blocks already added?
> Does the default innerblock template contain variation picker?
> What happens if variation picker is missing and someone adds to cart?

@mikejolley - I think the shared context version makes the most sense. I like the flexibility of being able to move things around independently. These are all great questions that I don't have terrific answers for. See below. 

> >Agreed, from a block standpoint (the grouping of the various components), I think we may want to keep variation picker etc something that merchants might be able to reposition but not remove (as it would be dynamically aware of the the type of product).
> 
> Which also makes me wonder, since there's a variety of product types, should we have various edit context views (similar to how the cart has the full cart and empty cart views) for different product types? That way merchants can fine tune how the single product looks for the different product types and potentially we can add extensibility points for extensions to register other product types to handle? Would this be in keeping with some of the flexibility the single-product template works for themes? If so, this does complicate the ui/ux and definitely requires design input (cc @LevinMedia as well). With that in mind, we'd have to be careful to scope what we want for i1 and plan for future iterations that might add those various editing contexts

@nerrad I feel like we're wading into murky water here, which warrants deeper design exploration - As far as I can tell, we're basing this off the innerblock editing that was established in the All Products block - But I'm not sure if that will support this block's needs as it's currently implemented. 

I'd like to spend the rest of this week exploring and proposing a few updates to the way the innerblock editing works on the all products block. In the process of doing that, I'd like to see if I can work in ways to solve the UX problems that have been outlined above.

**Comment by mikejolley** [comment]
@LevinMedia @nerrad Regarding product types and inner blocks, I think it will be possible to select a default template per product type. 

So for instance, if you select a variable product, the default inner block template will include the variation form picker, and that picker should be fixed and non-removable because it's required. 

This is of course more complicated than a single block for add to cart form which adjusts based on product type dynamically.

**Comment by nerrad** [comment]
> Regarding product types and inner blocks, I think it will be possible to select a default template per product type.
> 
> So for instance, if you select a variable product, the default inner block template will include the variation form picker, and that picker should be fixed and non-removable because it's required.

I like this idea. One benefit of it is that it opens the door to extensibility where extensions/themes could feasibly swap in different layouts for the default templates.

**Comment by LevinMedia** [comment]
@mikejolley I'm working on a sketch for this, and will post it soon.    

Currently the way I'm thinking about it is: there's a default template for the block and it has **all the things.** The default template will inherit its styles for the inner block from the theme. The individual blocks that make up the template can be moved around and restyled, but not removed from the block. 

Whatever arrangement and styles are set in the default template is what will appear when the block is placed on a page, however the content would be filtered depending on what kind of product type you've working with. From there, the styles and arrangements could be further modified locally in that specific that specific block. 

This way we only have one default template to worry about for this block.

My current thinking is the default template would live in the "reusable blocks" screen but this might change.

**Comment by mikejolley** [comment]
> My current thinking is the default template would live in the "reusable blocks" screen but this might change.

There are 2 ways to look at this block; 

1. A single product block where each block can be setup/configured independently
2. A single product block where all single product blocks share a template

(1) is how we handled "All Products" because it kept each block self-contained. What you're proposing sounds like it's more inline with (2)?

**Comment by nerrad** [comment]
One thing to remember about "reusable blocks" in the context of Gutenberg, is that they are designed so that authors (or in our case merchants) can add a block to a page, configure it the way they want, and then _convert it to a resuable block_ which can then be re-used anywhere in other content. When this re-usable block is edited and saved, _every other place using it is updated_.  

I'm wary about creating a new pattern where we actually create and use reusable blocks from the get go. It sounds like we may want to wait until block themes and templates has matured enough to start experimenting with a _default template_ that is configured for a store when it's initially setup (that can also be edited and redistributed by themes).

**Comment by nerrad** [comment]
With that said, we could certainly pre-populate certain re-usable blocks for merchants to grab and use if they don't want to create their own - I'm just concerned about how we differentiate these pre-populated re-usable blocks from the actual block that merchants can customize - so don't take my comments above as discouragement from exploring the idea.

**Comment by LevinMedia** [comment]
>There are 2 ways to look at this block;
>
>1. A single product block where each block can be setup/configured independently
>2. A single product block where all single product blocks share a template
>
>(1) is how we handled "All Products" because it kept each block self-contained. What you're proposing sounds like it's more inline with (2)?

@mikejolley that's correct, what I was proposing was more inline with (2).

I had a number of discussions about it with the Gutenberg design team this week. it seems like "template parts" are going to be the most likely candidate for editing / saving and reusing inner blocks. However it's still a work in process.

Because of that, I think it's best if we continue forward with (1) for now. However, I'm going to make some design updates that bring the UX and UI more inline with where FSE is headed, which should put us in a better place when we're ready to allow for saving / editing and swapping these templates in a block in the future. 

With all that in mind... back to your original questions: 

> Is variation picker available at all times, or only if the chosen product is variable?

I would say only if the chosen product is variable. 

>Can variation picker be limited to 1 per block?

I think they should should be. 

One of the behaviors I wasn't to sure about in the all products block was the ability to put multiple instances of any innerblock into the template. To me it makes sense to have a fixed set of inner blocks that can be part of the template, and then only allow once instance of each in the template. If an inner block like variations requires multiple select menus, the correct number are displayed based on the products attributes. 

>If the product is changed, what happens to existing blocks already added?

For example, if you switch from a variable product to a normal product, any updates to styles and arrangement would persist, however, the variations innerblock would disappear. 

Does the default innerblock template contain variation picker?

Yes, but it would only show up if you're editing a variable product.

>What happens if variation picker is missing and someone adds to cart?

If we do it right, this should never be possible. :) 

Sorry if that whole thing was a bit of a ramble. I'm working on a post that will illustrate these concepts, along with the UX / UI updates mentioned earlier.

**Comment by mikejolley** [comment]
One thing I thought of that needs consideration; how are we going to handle PHP based form options added by extensions? For example, the product add ons extension. This adds fields to the add to cart form via the hooks and filters. If we have a form rendered in react, I'm not sure we'll be able to handle this without integration with the extension and doing something in then API especially. cc @nerrad

**Comment by nerrad** [comment]
> how are we going to handle PHP based form options added by extensions?

It's possible this will need to be done via the extension creating an atomic block that can be used with the Product block. But ya extensibility is something that hasn't been full thought through yet either for this block.

**Comment by mikejolley** [comment]
There is now a separate issue for the Add To Cart Block itself, so the questions in the op have been resolved.
