### ISSUE TITLE
Broken chip styles

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#2407]
**Describe the bug**
Chips in the editor interface are broken

**To Reproduce**
View a block such as products by category - note the chips have broken styles. 

**Expected behavior**
Compare the style of the chips in the blocks to the chips in the analytics filters. They should match. 

**Screenshots**

Expected:

<img width="351" alt="Screen Shot 2020-05-05 at 1 27 07 PM" src="https://user-images.githubusercontent.com/4500952/81113816-a83d7680-8ed5-11ea-9aa1-81901fc6afb6.png">

Observed:

<img width="777" alt="Screen Shot 2020-05-05 at 1 41 48 PM" src="https://user-images.githubusercontent.com/4500952/81114095-2f8aea00-8ed6-11ea-80e3-e755d2c84391.png">

<img width="274" alt="Screen Shot 2020-05-05 at 1 40 07 PM" src="https://user-images.githubusercontent.com/4500952/81113977-f488b680-8ed5-11ea-9c3a-f1e2d82fb2ed.png">

Gutenberg version: 8.0.0
WordPress Version: 5.4.1
WooCommerce Version: 4.1.0-rc.2

**Comment by Aljullu** [comment]
This was fixed in https://github.com/woocommerce/woocommerce-admin/pull/3993, but there wasn't a release of `@woocommerce/components` yet, so we are using a version without this fix.

Fixing #2419 will probably solve this.

**Comment by nerrad** [comment]
Since #2419 is in Current Sprint, I'm going to move this there too. It can be bumped if #2419 does _not_ fix this.

**Comment by Aljullu** [comment]
Now that it has been decided that we will not load components from the external, this is not blocked by #2419. Instead, we need to update `@woocommerce/components` to version 5.1.0 or later, but it hasn't been released yet.

Related issue in WC Admin: https://github.com/woocommerce/woocommerce-admin/issues/5006.

**Comment by senadir** [comment]
Notes from: C8X6Q7XQU-slack-p1600163121223700
- @Aljullu tried to update to 5.1.0 but failed.
- Blocks weren't registered, this is mostly due to a dependency issue missing.
- wc.components introduces `@wordpress/components` as a dependency, our build process will attempt to extract it and use `wp.icons`, `@wordpress/dependency-extraction-webpack-plugin` explicitly skips icons, this was introduced 8 months ago https://github.com/WordPress/gutenberg/blob/master/packages/dependency-extraction-webpack-plugin/lib/util.js#L36-L38
- We're running an outdated version (2.1.0), updating to 2.8.0 fixes that issue.
- All Products and several other blocks are still not loading, I'm not sure what's the issue, Cart and Checkout works fine, All products have some extra dependencies compared to Cart, `"wc-shared-context", "wc-shared-hocs", "wp-data-controls", "wp-date", "wp-primitives", "wp-viewport"` but I'm not sure what's the issue.

**Comment by budzanowski** [comment]
Updating `@woocommerce/components` to 5.1.2 fixed the problem. Closing.
![image](https://user-images.githubusercontent.com/17271089/101379814-ffb12400-38b4-11eb-8b2c-def38063de03.png)
