### ISSUE TITLE
Add Support for Express Payment Buttons in the Cart Block

### ISSUE THREAD

**Issue by anant1811** [woocommerce/woocommerce-gutenberg-products-block#2433]
**Describe the bug**

I found that Stripe is supported as per https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/master/docs/testing/cart-checkout#known-limitations

But seems Stripe's payment request buttons are not supported in the cart block yet? 

![https://d.pr/i/pY5Ta2](https://d.pr/i/pY5Ta2+) 
Full Size: https://d.pr/i/pY5Ta2

**To Reproduce**

1. Enable Payment Request buttons in Stripe. 
2. Add a product to cart
3. Go to cart page that's using the cart block 
4. You won't see the payment request button

**Expected behavior**
Payment request buttons should show on the cart page.

**WordPress (please complete the following information):**

* Core version: 5.4.1
* WooCommerce version: 4.1.0
* WooCommerce Blocks version: 2.6.0-beta3
* Site language: English
* Any other plugins installed: No

**Desktop (please complete the following information):**

* OS: MacOS Catalina, 10.15.4 
* Browser Chrome - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by nerrad** [comment]
Hi there! For the initial release of the blocks it is intentional that we wouldn't support the buttons in the cart. However, we definitely will support at some point.

cc @LevinMedia - this is something we can probably experiment with if/when we get all the mvp tasks done to see if we can pull it off for initial release. In _theory_ it should be doable because of the way things have been designed (and we're already loading the registered payment methods in the cart block for the cc images), I'm just getting on your radar because we'll need some initial design for adding the payment request buttons to the cart block.

**Comment by anant1811** [comment]
Thanks @nerrad !

**Comment by LevinMedia** [comment]
Thanks for the ping, shouldn't be to difficult to add when we get to that point 👍

**Comment by Aljullu** [comment]
@LevinMedia I have a work-in-progress of this. I copied the design from the Cart shortcode and it seems to work fine in desktop:

![cart-with-express-payment-methods](https://user-images.githubusercontent.com/3616980/89552056-f1220580-d80b-11ea-9bdc-4f9d9a279cf2.png)

However, in mobile the 'Proceed to Checkout' button is floating in a container that is sticky to the bottom. If we add the express payment methods, the container might get very tall and take much of the vertical space. Any ideas how can we solve this?

**Comment by Aljullu** [comment]
The discussion above continued in p1596729028166700-slack-C8X6Q7XQU. It was suggested to keep only the `Proceed to Checkout` button sticky while leaving the express payment methods static. The `Proceed to Checkout` button should only be sticky if its regular position is below the viewport. If it's visible, it stops being sticky.
