### ISSUE TITLE
The Place Order button in checkout block is barely visible (in editor)

### ISSUE THREAD

**Issue by anant1811** [woocommerce/woocommerce-gutenberg-products-block#2435]
**Describe the bug**

The Place Order button in checkout block is too light, barely visible:
![https://d.pr/i/PI2gSi](https://d.pr/i/PI2gSi+) 
Full Size: https://d.pr/i/PI2gSi

It looks fine on the frontend though: 
![https://d.pr/i/kriTGC](https://d.pr/i/kriTGC+) 
Full Size: https://d.pr/i/kriTGC

This was tested with a new install, using Storefront theme (no customizations). 

**WordPress (please complete the following information):**

*   Core version: 5.4.1
*   WooCommerce version: 4.1.0
*   WooCommerce Blocks version: 2.6.0-beta3
*   Site language: English
*   Any other plugins installed: No

**Desktop (please complete the following information):**

*   OS: MacOS Catalina, 10.15.4
*   Browser Chrome - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by nerrad** [comment]
@Aljullu I'm pretty sure this is likely caused by the button being disabled in the editor right? However I wonder:

- is it possible there's also theme styling at play here? I seem to recall the _disabled_ color on the frontend being slightly different than the editor context in storefront (if so, this fits with block styling consistent styles work).
- It's not immediately clear to users of the block that the styles for some interactive elements are different in the editor because of the disabled state. I wonder if we should normalize the styles across _all_ our blocks usage of `Disabled` so that the editor view is consistent with the frontend view (so basically don't have different styles for components nested in Disabled in the editor context)?

Do you think this is something that should be tackled as a part of the block styles work for this cycle? I'm not to worried about the initial blocks release of Cart and Checkout handling this.

**Comment by Aljullu** [comment]
The issue seems to be that some styles from core are leaking into the block:
![imatge](https://user-images.githubusercontent.com/3616980/81567389-8728ca00-939c-11ea-949d-abf2d19db0da.png)
They have `!important` rules which override our styles.

Some options that come to my mind:
1. Write some CSS to reset the styles from the screenshot above. That would require adding `!important` rules to our styles. I'm not a big fan of this but can't figure out any other way to reset those styles.
2. We could work-around the selector above if we convert that `<button>` into an `<a>`. In fact, that's the reason the _Cart_ `Proceed to Checkout` button is not affected by this, because it's an anchor. To me, the `Place Order` button should still be a `<button>` for semantics. We could, however, consider switching to an `<a>` in the editor context.
3. In the editor, completely replace that button with a `<div>` with the same class names so it has the same styles.
4. Explore an alternative to `<Disabled>` which also prevents interaction but doesn't add the `disabled` attribute?

I don't think there is a perfect solution here and each one has its own trade-offs. But personally I think the number 2 would be the one with the smaller impact. The con is that the element will be different depending on the context (frontend: `<button>`, editor: `<a>`), so there could be some issue with styles being applied differently, but we could minimize this with some reset styles if needed. The biggest advantage of that option is that we would not need to maintain any special code, adding `href={ isEditor ? '#' : null }` to the `<Button>` would be enough.

> - It's not immediately clear to users of the block that the styles for some interactive elements are different in the editor because of the disabled state. I wonder if we should normalize the styles across _all_ our blocks usage of `Disabled` so that the editor view is consistent with the frontend view (so basically don't have different styles for components nested in Disabled in the editor context)?

Agree with this. The issue is that the `<Disabled>` component makes all form elements get the `disabled` attribute. So that means we will need to reset the `disabled` styles in the editor. That would work for me and we can create an issue for it, but just pointing out this is a different issue than the one we are facing with the `Place order` button.

> Do you think this is something that should be tackled as a part of the block styles work for this cycle?

Yes, it would be great to get it fixed before _Cart_ and _Checkout_ release. Considering it's only affecting the editor, I don't think we should rush to fix it, but depending on the solution we choose, it might be an easy fix.

**Comment by mikejolley** [comment]
@Aljullu Do you think we should consider removing the conflicting `.button` class here and on others? I know the class is here mainly for theme support, but it's going to cause issues in admin context.

**Comment by haszari** [comment]
If the admin styles are leaking due to `!important` maybe we could also report this upstream.  I'd expect disabled buttons in the editor to look like disabled buttons in the front end (i.e. gutenberg wysiwyg).

**Comment by nerrad** [comment]
> I'd expect disabled buttons in the editor to look like disabled buttons in the front end (i.e. gutenberg wysiwyg).

I think this possibly misses the goal of what we want to do here and what makes it tricky. The WYSIWYG is intended to cover what things look like on the frontend with the button **not disabled**. The fact they are disabled in the editor is to prevent normal behaviour in the editor _not_ to give a visual indicator of what the disabled button looks like. The same consideration could apply also to inputs etc.

**Comment by mikejolley** [comment]
I think the main issue here is we are using un-prefixed classnames which conflict with WP Admin, not just Gutenberg. `.button` is too common and is used throughout the admin interface. I don't see this being fixed upstream.

**Comment by Aljullu** [comment]
> @Aljullu Do you think we should consider removing the conflicting .button class here and on others? I know the class is here mainly for theme support, but it's going to cause issues in admin context.

Ah, sorry I missed this comment. I think that's a good idea @mikejolley, we would need to update some CSS files that currently rely on that class and I would like to see how it affects some popular themes. But considering we are currently hardcoding the background and font color, the effect might be minimal so that sounds like a good approach to me. :+1:

**Comment by Aljullu** [comment]
> It's not immediately clear to users of the block that the styles for some interactive elements are different in the editor because of the disabled state.

I created an issue intended to explore ways to make form elements don't look disabled in the editor (#2487), so this issue can focus on fixing the _Place Order_ button styles.
