### ISSUE TITLE
Are cart & checkout blocks supported on (blog) posts as well as pages?

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2440]
Typical usage would have each on their own page, i.e. official store cart page and checkout page.

I can't think of a good reason why we'd want to show the cart or checkout in a post; maybe we should restrict to `Post` content type.

Currently can add cart & checkout to a post:

![Screen Shot 2020-05-08 at 1.32.26 PM.png](https://images.zenhubusercontent.com/5ddb3cb39529f10001e618e5/d4c4db14-071b-4fed-b26a-b409b4f248c9)

See also #2439

**Comment by nerrad** [comment]
Currently we don't add any restrictions. This can be visited if it becomes a problem when we see the blocks used in the wild but since it's easy to spot and fix if merchants add to posts I'm not too worried about adding logic for the restrictions for MVP. It's more than likely we'll have some improvements to how the blocks are interacted with and initial setup ux as well in future iterations.

**Comment by nerrad** [comment]
I'm going to close this because there still currently isn't any pressing need to add restrictions for where the blocks can be used.
