### ISSUE TITLE
Order date may be older than expected when shopper completes checkout a long time after starting

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2489]
When testing #2484 I noticed that one of my orders showed up as "older" (further down the list in wpadmin) than I expected.

I suspect this is because the draft order is created early in the checkout process (as part of reserving stock). Then, if the customer goes away and comes back later, then submits order, the order date is when checkout started. 

As a merchant I'd probably expect the order date to be when the order was submitted. 

I don't know if this is a bug / how serious this is. Just wanted to clarify the expected behaviour here, and note in case any merchants care about order date/time for some reason.

Not sure if this affects core / shortcode checkout - logging in blocks repo as a first step. cc @mikejolley for comment 

### To reproduce
- Add stuff to cart, view checkout, select shipping etc
- Wait some time .. maybe make an order in another browser
- Submit the order

Expected: Order to have submission date/time

Actual: Order is older than I expected :)

**Comment by nerrad** [comment]
Thanks Rua for creating this issue to document it and surface it as something we should evaluate the importance of.

> I suspect this is because the draft order is created early in the checkout process (as part of reserving stock). Then, if the customer goes away and comes back later, then submits order, the order date is when checkout started.

I think that's definitely a potential cause. With the introduction of the draft order status, orders are created much earlier in the checkout flow than the shortcode checkout. So there definitely is more potential for order _creation_ time to be much more noticeably different than the creation times one typically sees during shortcode checkout

As to severity of this issue, I think this will surface more for those doing testing like us because often we'll leave things in the cart for a while and test multiple things before finishing off purchase (or fixing buggy things where the purchase can't be completed yet).

Looking [at the code](https://github.com/woocommerce/woocommerce/blob/aa6a025526210e1d118484752da86d552c02f719/includes/class-wc-order.php#L268-L269) in the `WC_Order` class, it does appear that the date column you see in the order list table is for order creation date. Order complete, and payment complete are separate tracked dates.

So from that perspective, I don't think we want to change this timestamp. It is an accurate measure of _when the order was created_.  

I'll leave this issue open for now to await Mike's feedback, but my gut says we don't do anything (that leaves open the door for my gut being wrong :) )

**Comment by haszari** [comment]
>  Looking at the code in the WC_Order class, it does appear that the date column you see in the order list table is for order creation date. Order complete, and payment complete are separate tracked dates.

That's good news - if all this granularity is available to merchants, I don't think there's an issue.

**Comment by nerrad** [comment]
This is something we may revisit at a later date but I suspect there may be some overlap with work being done on order statuses etc as well. As far as I can tell the current behaviour is _expected_ so I'm going to close for now.
