### ISSUE TITLE
Sale price for variable product not working / different behaviour in all products block

### ISSUE THREAD

**Issue by kimmenbert** [woocommerce/woocommerce-gutenberg-products-block#2552]
In the all products block, the sale price is displayed differently for variable products. In some cases where you use third party plugins to set sale price, the original price is shown instead of sale price.

**To Reproduce**
Add a variable product, set sale price. Insert an all products block

**Expected behavior**
Behaviour is expected to be as other blocks and general WooCommerce product loop etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/4253817/82799381-42139600-9e7a-11ea-9f97-bb468b3a3c0f.png)

Freshly installed WordPress / WooCommerce / TwentyTwenty.
WP: 5.4.1
WC: 4.1.1
TwentyTwenty: 1.3

**Comment by nerrad** [comment]
Hi there!

It's a bit clear to me what the issue is. To try to reproduce, I edited a product that has variations and set a sale price on the variation which resulted in the display for the All Products block being the same as what is on the shop page (while aside from the slightly different layout of badges intentionally setup in my implementation of the All Products block):

All Products:

<img width="186" alt="Image 2020-06-09 at 10 33 27 AM" src="https://user-images.githubusercontent.com/1429108/84161050-d8c88100-aa3c-11ea-99f4-7f246c9a5939.png">

Shop Page:

<img width="373" alt="Image 2020-06-09 at 10 33 41 AM" src="https://user-images.githubusercontent.com/1429108/84161122-f0a00500-aa3c-11ea-82f9-9c459930e7d4.png">

In the above examples I'm using Storefront.

Would you be able to expand on what I should be looking for in this issue please?

**Comment by kimmenbert** [comment]
Hi, could you try with same sale price (and maybe same regular price) for all variations of this product?
