### ISSUE TITLE
All Products: notice close icon is not aligned with the text

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2558]
**To Reproduce**
1. In the _All Products_ block, add a product over its stock quantity.
2. The close icon in the notice that appears is broken in a new line.

Ideally, it should be at the top right corner.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/82884832-971bde80-9f44-11ea-99ec-b0873ea6bbac.png)

**Comment by budzanowski** [comment]
It looks like since this issue was created the design and layout in the Notice component was adjusted. It is now aligned correctly and matches the design in the package:

![image](https://user-images.githubusercontent.com/17271089/98967137-6dfc0400-250c-11eb-8b15-3102de08f730.png)

I think that we should close this without further action.
@Aljullu your thoughts?

**Comment by Aljullu** [comment]
Agree, in your screenshot it looks good. :ok_hand:
