### ISSUE TITLE
Add option to make Eircode/Postcode mandatory

### ISSUE THREAD

**Issue by Gabriel-Denys** [woocommerce/woocommerce-gutenberg-products-block#2588]
### Background
The new checkout and cart blocks are beatiful and I'd love to use them on my clients' sites.
but I can't, my clients are in Ireland and our Postcodes work a bit differently here to the rest of the world. 

Our postcodes are called Eircodes and they pinpoint a building exactly and you can type an eircode into Google Maps and it will show you the exact house.

A lot of Ireland is rural so our houses don't have numbers, and some don't have names or are simply hard to find. 

For that reason, some couriers require Postcodes (Eircodes). Which is why I think it would be so good to allow making postcodes mandatory in the gutenberg block settings!

### Feature Request
Addition of a toggle to make the postcode field mandatory

### Current Solution
I currently use the shortcode checkout, I used PHP hooks to make the Eircode mandatory for Ireland, left it optional for other countries.

**Sidenote**, is there any documentation or can you give examples of hooks & functions to modify the fields display to make some mandatory?

Thanks,
Gabriel

**Comment by mikejolley** [comment]
This shouldn't be something defined at Block level IMO, it should be part of the woo core locale to make this a required field.

I am slightly confused though because I saw a commenter state that it wasn't suitable for the opposite reason; rural addresses might. not have an eircode?

**Comment by Gabriel-Denys** [comment]
Well I understand why you say it should be in the locale, but also it depends on the courier - some require it, some don't, which is why the option would be nice. Some parcels in towns and citties can be easily delivered because the house has a house number. But in rurual areas it is more difficult as sometimes only a road name is given.

and with regards to rural addresses having eirocdes - every residential and business address that has post delivered also has an eircode. Even caravan bays have eircodes. You can see here for proof: https://www.citizensinformation.ie/en/consumer_affairs/telecommunications_and_postal_services/eircode.html

**Comment by nerrad** [comment]
Currently in the blocks plugin we have this configuration file for various locale settings related to countries:

https://github.com/woocommerce/woocommerce-gutenberg-products-block//blob/15864078373373c7c53bbb1e21e34f7822c89e0b/assets/js/base/components/cart-checkout/address-form/country-address-fields.js#L274-L279

Feasibly we could add a field requirement setting to the file and and use that to control whether the related field is required when rendering components. Then we can implement via JavaScript filters the ability to modify those requirements on the fly.

The trickiness here is that **how** we filter is important. We'll want this to be implemented in a way that if the configuration changes at all it triggers a re-render of the affected fields. For example, beyond the use-case described in this issue, I could see certain shipping options (depending on shipping company/rate requirements) enforcing certain address field requirements.

**Comment by nerrad** [comment]
We had some extensive discussion on this among our team in slack (p1597417907131900-slack-C8X6Q7XQU) and noted there's a lot of differing opinions on this not only in the history of Woo core but also among other e-commerce sites. But based on our findings we've decided this will be the action steps we'll take for now:

### 1. For Cart and Checkout blocks, we're going to make the Eircode required by default for Ireland.

While it's not considered a mandatory field by the Irish government, it is _recommended_ that it's used for e-commerce to guarantee accurate delivery (especially for non Irish shoppers delivering to Ireland). Having this required by default seems the safer option _especially_ given the Eircode has been out for a while now and there's more familiarity with it.

### Leave the Eircode requirement in Woo Core as is for now.

While this creates a divergence between the shortcode checkout flow and the new blocks checkout flow, we'd like to see how this change affects the smaller subset of users of Cart and Checkout blocks before committing to a similar change in Woo Core. Woo Core also is currently filterable and it's far likely most stores already wanting the field to be required as opposed to the default optional value have implemented the necessary changes for Woo Core flows.

### Eventually add extensibility for on the fly field modifications for Woo Cart and Checkout blocks.

There's a number of considerations we need to account for when adding this extensibility because of the impact it has in the new context. So while we eventually could implement something for this, it's not something we want to rush into.

**Comment by emcgal** [comment]
> We had some extensive discussion on this among our team in slack (p1597417907131900-slack-C8X6Q7XQU) and noted there's a lot of differing opinions on this not only in the history of Woo core but also among other e-commerce sites. But based on our findings we've decided this will be the action steps we'll take for now:
> 
> ### 1. For Cart and Checkout blocks, we're going to make the Eircode required by default for Ireland.
> While it's not considered a mandatory field by the Irish government, it is _recommended_ that it's used for e-commerce to guarantee accurate delivery (especially for non Irish shoppers delivering to Ireland). Having this required by default seems the safer option _especially_ given the Eircode has been out for a while now and there's more familiarity with it.
> 
> ### 2. Leave the Eircode requirement in Woo Core as is for now.
> While this creates a divergence between the shortcode checkout flow and the new blocks checkout flow, we'd like to see how this change affects the smaller subset of users of Cart and Checkout blocks before committing to a similar change in Woo Core. Woo Core also is currently filterable and it's far likely most stores already wanting the field to be required as opposed to the default optional value have implemented the necessary changes for Woo Core flows.
> 
> ### 3. Eventually add extensibility for on the fly field modifications for Woo Cart and Checkout blocks.
> There's a number of considerations we need to account for when adding this extensibility because of the impact it has in the new context. So while we eventually could implement something for this, it's not something we want to rush into.

This is great news. I am using Woocommerce blocks for the first time and talk about a life saver! 

My search on making the Eircodes mandatory led me to here. When do you think this option will be available? Can county also be set to required too?

**Comment by nerrad** [comment]
I'm afraid I can't give an ETA on when this will be done. We have some other higher priority things we're working on at the moment. When this is implemented we could consider offering the option for other fields to be set to required to.

**Comment by emcgal** [comment]
> I'm afraid I can't give an ETA on when this will be done. We have some other higher priority things we're working on at the moment. When this is implemented we could consider offering the option for other fields to be set to required to.

Ok thanks. Will have to try and do it myself in the meantime.

**Comment by mikejolley** [comment]
Some good news and some bad news with regards to this issue since it was created.

First off, [core still has Eircode as an optional field](https://github.com/woocommerce/woocommerce/blob/71cdb3d752ab2a467d3b9b4b76a9b80b9c6831bf/includes/class-wc-countries.php#L1070-L1078). _Blocks is doing the same._

The good news is, [Blocks was updated to use the locale data from WooCommerce core meaning it is now truly extensible](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3662).

That means Eircode can now be made required using the `woocommerce_get_country_locale` filter. 

No UI changes are needed in blocks to support this, so closing this issue out.
