### ISSUE TITLE
Not all translations are being inherited from WooCommerce core

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2604]
**Describe the bug**
We have a function in our plugin that will load translations from WooCommerce core if the translation doesn’t exist in our plugin 

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/8fd77fa6e4d8db3c7de43857cde7dfa3e22114ee/woocommerce-gutenberg-products-block.php#L193-L207

However, it seems not all strings are passing via that function, and not all of them are being inherited from WooCommerce

block:
![image](https://user-images.githubusercontent.com/6165348/83522833-2131ed00-a4d9-11ea-85a9-56d71492b7a4.png)

Shortcode
![image](https://user-images.githubusercontent.com/6165348/83522859-2abb5500-a4d9-11ea-9c33-3ca1b12676da.png)

Notice price and quantity, both have the same casing (the blocks one is uppercased using CSS)
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/abc4196d3194ea61f638c1c1691d5c87a4267dc7/assets/js/blocks/cart-checkout/cart/full-cart/style.scss#L54

**To Reproduce**

1. have Cart in two pages, a classic cart and a block cart
2. enable a new language in your website (something you slightly understand will work)
3. in the update tap, download the new language updates (for WC)
4. visit the pages, only the classic will be translated 

**Expected behavior**
for identical strings, both should be translated.

**Screenshots**

![image](https://user-images.githubusercontent.com/6165348/83523276-db295900-a4d9-11ea-99b4-b10f9e4d8bb7.png)

![image](https://user-images.githubusercontent.com/6165348/83523315-e9777500-a4d9-11ea-8762-e7ac61280d65.png)

**Comment by nerrad** [comment]
I decided to dig into this a bit because there's a number of support issues popping up in the WooCommerce forums that are related to translations not working. After spending some time investigating this, I'm closing this issue. The following is why.

The translations for JavaScript strings are tied to the **specific _built file_ the strings are found in** and the fallback for WooCommerce core is using [this function](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/woocommerce-gutenberg-products-block.php#L126) for those strings. 

I've verified that fallback is working for blocks like the All Products block which _has files currently in WooCommerce core_. The reason why no Woo Core fallback translations are being seen for the Cart and Checkout blocks is because the Cart and Checkout block built files are _not yet in WooCommerce core_. Thus, no json JED files are exported from the WooCommerce core repository.

The next version of WooCommerce core should have the Cart and Checkout files (even though the blocks themselves will not appear to users) which means that the strings should appear in GlotPress for WooCommerce core, which means if those get translated, they will show up for users (if the language pack is built for Woo Core).
