### ISSUE TITLE
Add more payment processors to your checkout feature

### ISSUE THREAD

**Issue by princewilliams102** [woocommerce/woocommerce-gutenberg-products-block#2624]
**Is your feature request related to a problem? Please describe.**
When i activated the plugin and wanted to customize my checkout page, the current payment processor i am using didnt show it was displaying go setup your payment processor.

**Describe the solution you'd like**
Id like payment processors like Rave, and coinbase to be added to the checkout process

**Describe alternatives you've considered**
i just left the checkout the way it was

**Additional context**
Add any other context or screenshots about the feature request here

**Comment by nerrad** [comment]
Hi there 👋 

Thanks for taking the time to test the preview of the new blocks and create this issue!

As noted [in the release post for the Cart and Checkout blocks](https://woocommerce.wordpress.com/2020/05/27/woocommerce-blocks-2-6-0-release-notes/), there is a limited set of payment methods available for the initial iteration of the preview. You can read more information about this in the post I linked to.

I'm going to close this issue for now because we have taken note of your request and we definitely will be encouraging more third party payment processors to integrate with the new blocks as we iterate on them.
