### ISSUE TITLE
Checkout: update design of the payment methods

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2628]
Related p2: pbIy4N-g9-p2

In order to offer better support for dark themes and to handle better the case when there are >2 payment methods, we want to redesign the payment methods section.

One payment method:
<img width="512" alt="screen-shot-2020-05-27-at-12 25 46-pm" src="https://user-images.githubusercontent.com/3616980/83740907-c672cf80-a657-11ea-8267-e241e3e1d623.png">

Two payment methods:
<img width="512" alt="screen-shot-2020-05-27-at-12 28 13-pm" src="https://user-images.githubusercontent.com/3616980/83740755-90355000-a657-11ea-8597-11f289ad2f5f.png">

Three or more payment methods:
<img width="505" alt="screen-shot-2020-05-27-at-12 36 12-pm" src="https://user-images.githubusercontent.com/3616980/83740775-94fa0400-a657-11ea-8297-7b36b50d956e.png">

**Comment by haszari** [comment]
Linking in #2157 - using merchant-defined order for payment methods, as it could be closely related.

**Comment by haszari** [comment]
Started looking at this …

I see we're using and customising/styling [Reakit Tabs component](https://reakit.io/docs/tab/) for these tabs. With the new design, we're only using "Tabs" for the 1 or 2 tab case, otherwise the component is more like an accordion. Reakit doesn't have an accordion. We'll likely want to share lots of styles between each UI mode, and behaviour too (e.g. keyboard selection etc).

I'm wondering if it's best to continue using Reakit tabs vs making a custom control that handles both modes. 

Also I'm curious how much our current Tabs component is built specifically for payment methods. I don't think it's used for anything else yet, and we've customised the styling quite a bit.

**Comment by Aljullu** [comment]
I'm not sure how the `Tabs` component works and how easy it would be to customize it so it looks like an accordion. It would be great to always use the same component no matter how many payment methods are rendered, but I acknowledge that might be too complex and it might make no sense to over-complicate a component to make it look like something else.

In case we need to create an accordion component from scratch, it might be a good idea if it internally used the [`Panel` component](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/assets/js/base/components/panel/index.js). It allows having a title and an expandable area underneath, which seems quite similar to what we need for the accordion. We would need to make sure only one of the panels is open at the same time, but besides that it might be a good fit?

**Comment by haszari** [comment]
Just putting this back in `Current Sprint` as I'm not actively working on it. PR has some baby steps but I haven't started work on the big chunk - implementing/adapting an accordion-style UI. Anyone should feel free to grab this issue :)

**Comment by budzanowski** [comment]
I think that we need to clarify some design elements here before we can continue. I am writing mostly about 3 or more payment options.
1. We have something that looks like two radio buttons selected at the same time
![image](https://user-images.githubusercontent.com/17271089/97338655-ebbfde80-1881-11eb-8003-4551dfb26022.png)
that is not a very common usage of radio buttons :) 
2. What is the state of the payment method slots when the first option is selected? Are they all closed or the last one that was selected remains open?
3. If the first option is selected and the user clicks on the radio button on the `Use a new payment method` do we autoselect one of the new payment methods or we insist that the user clicks it.

My suggestion would be to get rid of the radio at the `Use a new payment method` and leave that as a just label. That fixes for us point 1 and 3. For two I would suggest closing the payment method set up when not selected.

I have also one more suggestion that would make developing this a bit more in the agile spirit. I would split this task into two separate tasks:
1. the First task would be to implement the option at `Three or more payment methods` even for a case of just two payment methods. It still makes sense UI wise and it covers all of the scenarios. We evaluate how it works and if we decide that we still want a special case for two payment methods we move to task 2
2. implement the tabbed UI for two payment methods. Since this is a special case on top of task one we can leave it to be done last. There is a chance that we will like the 1 enough not to need this special handling.

@LevinMedia @nerrad what do you think?

**Comment by LevinMedia** [comment]
Heya @budzanowski Thanks for pointing this out! 

I'm with you on all the points above: Here's the update payment method selection area when there's a saved card. As you've suggested above - when there's a saved card, all of the additional payment methods must be radio buttons for this to make sense. 

<img width="1593" alt="Screen Shot 2020-10-30 at 4 26 55 PM" src="https://user-images.githubusercontent.com/4500952/97764747-e2768200-1acc-11eb-9b26-4f0b00aa213a.png">


I did make one small adjustment to the design when there aren't any saved cards available. In this case, when only one payment method is available, we don't need the "Select a payment method" string of text.  I've removed it from the first of the three variations of this layout below. When there are two methods, and no saved cards, we can retain the tabbed design. 

<img width="1594" alt="Screen Shot 2020-10-30 at 4 26 45 PM" src="https://user-images.githubusercontent.com/4500952/97764807-1651a780-1acd-11eb-9844-3d0f60f921fa.png">
