### ISSUE TITLE
Twenty Twenty: All Products block titles are huge

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#2629]
**To Reproduce**
1. Add an _All Products_ block.
2. Notice the title font size is too big in the editor (but it looks fine in the frontend).

**Expected behavior**
The product title font size should be smaller. 'Legacy' product grid blocks have smaller font sizes, so they can be used as a reference.

**Screenshots**
_Editor:_
![imatge](https://user-images.githubusercontent.com/3616980/83768392-00a39780-a67f-11ea-9883-0dfe7613417e.png)

_Frontend:_
![imatge](https://user-images.githubusercontent.com/3616980/83768417-0b5e2c80-a67f-11ea-8684-789344e9bc10.png)

**Comment by bobtaylor25** [comment]
Does anyone know about this?  I need your help if I can. I have the product that disappears on the home page of the site. It is well configured on Elementor Pro but no title is visible in preview. I have checked all pluggins (until the last Woocomerce update, it worked fine). Finally, I restored the old version of elementor pro and woocomerce and it works. But now, how am I going to make updates knowing this problem? I don't know anything about programming so help me if possible, here is the version I'm using now and that I won't update because of this title problem. I use in parallel crocoblocks jet pluggins but I don't have any problem, all are updated, I have no problem with that.
 Thank you very much . I've contacted also elementor pro 24/7 service and still no any replay .... I don't know why and what is this service...

<img width="838" alt="Capture d’écran 2020-06-12 à 12 17 15" src="https://user-images.githubusercontent.com/66825076/84492625-bcc81800-aca6-11ea-9bc5-0c65252f5711.png">

**Comment by Aljullu** [comment]
@bobtaylor25 I don't think we can help you with this, we are not experts of Elementor, so we can't assist you to troubleshoot this. I would suggest contacting Elementor support again or waiting for their reply. Hopefully they will contact back soon.

**Comment by bobtaylor25** [comment]
Thank you very much Albert, is not Elementor , I've  just updated by doing backups steps. So now I will update woocommerce . I will see if the problem is comming from this . All the rest of thepluggins are updated Wordpress , elementor  and elementor Pro , Jet blocks.
B rgds

________________________________
De : Albert Juhé Lluveras <notifications@github.com>
Envoyé : vendredi 12 juin 2020 13:27
À : woocommerce/woocommerce-gutenberg-products-block <woocommerce-gutenberg-products-block@noreply.github.com>
Cc : bobtaylor25 <boby_r@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [woocommerce/woocommerce-gutenberg-products-block] Twenty Twenty: All Products block titles are huge (#2629)


@bobtaylor25<https://github.com/bobtaylor25> I don't think we can help you with this, we are not experts of Elementor, so we can't assist you to troubleshoot this. I would suggest contacting Elementor support again or waiting for their reply. Hopefully they will contact back soon.

**Comment by nerrad** [comment]
I just tested with the latest version of twenty twenty and it doesn't look like the product title sizes are an issue anymore:

![Image 2020-12-15 at 12 46 29 PM](https://user-images.githubusercontent.com/1429108/102252078-9f813a00-3ed3-11eb-872f-4ce056951ef7.jpg)
