### ISSUE TITLE
Apple-pay (etc.)

### ISSUE THREAD

**Issue by StSaens** [woocommerce/woocommerce-gutenberg-products-block#2672]
Hi,
I've done a bit of testing. And so far it feels like (altough the redesign looks very much more visually pleasing) it's playing a bit of catch-up and not fundamentally different approach.

It's still (roughly) 1) collect information, 2) shipping, 3) show order, 4) choose payment, 5) pay. Pretty much barebones 1995.

I think payment providers, like Apple Pay (Android Pay, Google Wallet, Samsung Pay), are going to become much more mainstream. But as far as I can see there is no specific flow for this. Paying with Apple Pay is a very different process than the current implementation is.  People shouldn't have to fill out all kinds of fields every time at every different shop, when all the information is in their payment provider.

A more integrated solution starts at the product-page/add-to-cart button where a faster route to buy should be available. This should fundamentally integrate with the cart/checkout parts.

**Comment by nerrad** [comment]
Hi there 👋 

Thanks for your feedback!

Express payment methods in the context of the checkout (Apple Pay etc) do not require any of the additional steps to be filled out. The flow is still the same where the express payment provider collects the info and uses that for completing the order. That's why it is located at the very top of the checkout layout in the new checkout block. If the shopper clicks an express payment button they essentially complete their purchase within the context of the Express Payment.

We also have an issue (see #2433) for adding Express payment methods to the Cart block (we released the initial iteration before we could complete that).  This will restore parity for the new block with the shortcode.

The same components will also be usable in future iterations of blocks like the All Products block (and the eventual Product block we're working on).

Keep in mind what we released in this feature plugin is a preview and is not considered the finished product (which is why it isn't in WooCommerce core yet). There's still a lot of things being iterated on (you can see all the work via [this search](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues?q=is%3Aopen+is%3Aissue+label%3A%22%E2%97%BC%EF%B8%8F+block%3A+cart%22+label%3A%22%E2%97%BC%EF%B8%8F+block%3A+checkout%22) and we're continuing to create more issues as we gather feedback from users of the preview across releases of the feature plugin.

I'm going to close this issue because the points raised are covered in existing open issues but feel free to add additional thoughts in those issues or we welcome any additional feedback you'd like to give in new issues!

Thanks again!
