### ISSUE TITLE
Make Filter Products by Attribute work with Products by Category Block?

### ISSUE THREAD

**Issue by thune** [woocommerce/woocommerce-gutenberg-products-block#2749]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thune** [comment]
Filter Products by Attribute works fine with the All products block, but this is not a logical use of product filtering.  I'm using Wordpress pages with the Products by category block. This way I can customize the Woocommerce categories with a nice header etc.  I like to think that this is the purpose of the Woocommerce blocks. So, in my opinion, the normal customer behavior will be to choose the desired category first BEFORE any filtering (weight, colors, etc). It's not normal to start filtering anything before the have chosen a certain product category....in my opinion :-)

**Comment by nerrad** [comment]
Hi there 👋 

While we appreciate you sharing your idea with us (thanks!), it doesn’t fit in with our current priorities for the project. At some point we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, don't be alarmed if you don’t see any activity on this issue for a while.

We do have plans to improve how these filters work with the other blocks and there are also ideas around introducing filters for categories. Eventually, it could even be possible to modify the default state of All Products (or related grid blocks that can be attached to the filter blocks) so that they start on the loaded route with a pre-selected set of queried results (example, start with products in a given category).

So your idea is in line with some of the thinking we’ve already been putting towards things like that.

**Comment by thune** [comment]
Thanks for listening 👍
