### ISSUE TITLE
Sky Verge Order Status Manager Issue

### ISSUE THREAD

**Issue by woodey34** [woocommerce/woocommerce-gutenberg-products-block#2812]
After installing the Woocommerce Order Status Manager from Skyverge, i have found that when checking out with Woocommerce blocks checkout (V2.8.0) and Woocommerce (V4.2.2) no transactions are passed to the payment providers, and orders go straight through the receipt. The orders appear in Woocommerce->Orders but no payments are taken.

The payment providers tested were Stripe and Paypal.

WP version: 5.4.2

I also tried The Custom Order Manager from Tyche? and the same thing happens.

I can confirm that when reverting to the standard woocommerce checkout using the default shortcodre everything works as it should.

**Comment by nerrad** [comment]
Hi @woodey34 , 

The Order Status Manager allows for customizing order statuses and flows and I suspect that there could be a flow configured that won't work with the new Cart and Checkout blocks because of changes to the checkout flow in the blocks. 

We still have work to do to add extensibility to the blocks. Would you mind sharing with us what your custom flow setup is so that we can take that in consideration when we look into expanding the extensibility features in the blocks?

Thanks!

**Comment by nerrad** [comment]
Due to lack of response there's nothing actionable here so I'm going to close.
