### ISSUE TITLE
Products on sale block

### ISSUE THREAD

**Issue by hannesdorn** [woocommerce/woocommerce-gutenberg-products-block#2841]
I would like to have an option for displaying the current stock status of a product, similar to the normal product view.

**Comment by nerrad** [comment]
Hi there 👋 

Thanks for taking the time to share your desire for the Products on Sale block with us!

Adding additional information to existing product blocks is on our radar but it's not something that is prioritized at the moment. Requesting this is great though because its an indicator of what is desired for the block.

When there's more information to share about potential work on this, I'll update the issue.

**Comment by hannesdorn** [comment]
I added a hook to solve this.

```
function custom_woocommerce_blocks_product_grid_item_html($html, $data, $product)
{
    $data->availability = wc_get_stock_html($product);

    $html = "<li class=\"wc-block-grid__product\">
        <a href=\"{$data->permalink}\" class=\"wc-block-grid__product-link\">
            {$data->image}
            {$data->title}
        </a>
        {$data->badge}
        {$data->price}
        {$data->availability}
        {$data->rating}
        {$data->button}
    </li>";

    return $html;
}
add_filter('woocommerce_blocks_product_grid_item_html', 'custom_woocommerce_blocks_product_grid_item_html', 10, 3);
```

**Comment by nerrad** [comment]
Thanks @hannesdorn for your request (and for the suggested workaround in the meantime). 

This request will be possible as a part of future work migrating our existing blocks to use inner blocks so there's more control over what merchants can show in existing blocks (including things like SKU). No ETA on when that work will be done but since it's accommodated by that planning I'm going to close this issue.

Thanks again for the suggestion!
