### ISSUE TITLE
Cart/ checkout blocks not displaying product-addon data

### ISSUE THREAD

**Issue by mattymystic** [woocommerce/woocommerce-gutenberg-products-block#2876]
Cart/ checkout blocks not displaying product-addon data.  Variation data is shown by / which is much better than the current old design which is not optimised well for mobiles. Currently this plugin is not useable in its current form due to the missing product add-on options the customer selects. Even though they are not displayed on the cart/ checkout pages they still go through and are displayed on the admin orders tab just fine.

**Describe the solution you'd like**
I would love to see support for product add-ons, this will allow us to test this new layout which looks way better than the previous design. This could maybe be supported by default or even a toggle within the settings of the block.

**Describe alternatives you've considered**
Sadly the current alternative is to opt out of this block cart and checkout and default to the current original design.

**Comment by nerrad** [comment]
Thanks for leaving your feedback here @mattymystic! Just to make sure I understand correctly. Are you specifically asking about support for [this extension](https://woocommerce.com/products/product-add-ons/)?

We definitely are working on how extensions will hook into the new blocks as we iterate on them during this preview period and that's one of the extensions on our radar to use as a guide for what's needed.

Thanks so much for giving the blocks a try and identifying what is needed for you to switch to using them!

I'm going to close this issue simply because it's not something _directly_ related to this repository but rest assured closing doesn't mean we haven't heard or won't address extensibility support for product add-ons or other extensions hooking into the checkout flow. We still are keeping track of these requests (even if the issue is closed).

If I was incorrect about what you were referencing to regarding support, you can still update the issue with any additional clarification and I will see it.

Thanks again!

**Comment by Aljullu** [comment]
A small update on this issue: Product Add-Ons compatibility with Cart and Checkout blocks will now be tracked in #3138.
