### ISSUE TITLE
Make sure Woo Blocks is consistent with core for reserve stock minutes.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2882]
In WooCommerce core, the `ReserveStock:reserve_stock_for_order` method is invoked with no argument provided for the `$minutes` value:

https://github.com/woocommerce/woocommerce/blob/1194225d7191f6bb85203b766d34966fad3be09c/includes/wc-stock-functions.php#L340

Thus, the default of `60` minutes is used:

https://github.com/woocommerce/woocommerce/blob/0b3900b84a16a819d2e5e25eab73fb81df0c8547/src/Checkout/Helpers/ReserveStock.php#L69

However, in Woo Blocks, the Checkout route invokes this method with a `$minutes` argument value of 10.

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/src/StoreApi/Routes/Checkout.php#L307

Effectively, this means for blocks:

- The set value for the `woocommerce_hold_stock_minutes` option is ignored.
- If folks wanted to filter this value, they are not able to. Whereas if the default option was relied on, the `get_option` filter could be used to modify the value.

At a minimum I think we should consider aligning how we're using this in Woo Blocks so it is consistent with core usage. However, I realize there may be rationale for why we're using a lower value here that is escaping me.

cc @mikejolley - I'd love your thoughts on this.

**Comment by ObliviousHarmony** [comment]
When thinking about the `ReserveStock` class, one thing that comes to mind is how narrow the use-case is for it. Having the requirement that an order exist means that anyone who wants to use this would also need to manage their own order lifecycle. My thinking here is that it might be good to refactor this class and table a little bit to break the direct dependency on orders and add some filters there where applicable.

I'm also not sure about the continued use of the default from `woocommerce_hold_stock_minutes` as that's very specifically intended to be used when cancelling unpaid orders. Having this used for orders not created by Core's checkout seems out of place and filtering on that option to address the timeout in things not related to Core's checkout seems strange. I'd be curious to know what Mike's thoughts are on this 😄

**Comment by mikejolley** [comment]
> However, I realize there may be rationale for why we're using a lower value here that is escaping me.

Briefly (I can go in more depth tomorrow if needed) it's set to a lower, fixed value so that:

1. It definitely has a value set regardless of settings or filters
2. Stock isn't reserved indefinitely for draft orders

Having a long (hour) duration before stock is freed could have negative consequences if carts are abandoned. This is different to core on-hold usage because that requires the order to be placed first. Blocks creates a draft on checkout entry, and updates the 10 min expiry whenever a request to the API is made during checkout. It shouldn't take an hour to complete checkout?

Was this an observation or user request? If the later I'd be keen to hear the justification behind why it should be filtered. 

> Having the requirement that an order exist means that anyone who wants to use this would also need to manage their own order lifecycle.

That's correct. Core uses it after an order is placed, and blocks uses it for draft orders. Whilst this link could be removed, that would make it more difficult to track if an order is resumed and already has stock reserved. You'd need a way to link it to an order/session/cart to know this.

**Comment by morganhvidt** [comment]
Hi Mike, 

Here's my justifications. I'm working with mutiple store owners that have vastly different stores, but facing similar issues when they have very limited stock items.

Using 10 minutes (or any other amount) as fallback is great for most stores. Though should allow flexibility for the other stores.

### Case one

Let's say I'm doing point of sale today with multiple agents. The products are high value and unique, there's one of each. 1 hour reservation time.

1. An agent places Product A in cart and goes to checkout while talking to the customer.
2. They have a lenghtly discussion, 45 minutes, about his individual use case with said product.
3. The product should remain reserved for the customer, so other agents don't try to double sell.
4. The customer either buys the product with the agent or the agent removes it from cart.  Removing items should release the stock (https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2843).
5. If the agent forgets to remove the product from cart it will be released at the 1 hour mark, so other agents can try to sell the product.

That senario is not just limited to point of sales, it could be over the phone and other use cases that slips me right now. The point is it will all be possible to do this in WooCommerce with a filter.

### Case two
I'm also trying to help store owners that want their products to be reserved as soon as a product has been added to cart. The reason here is that customers have a false sense of security. They feel good that they managed to get the last stock of a product in their cart. That feeling is short lived as the product could have sold out by the time they visit the checkout. Instead they are now confused an disappointed. 

I'm currently working on a plugin that uses the `ReserveStock ` class early. It works well for the most part. I'm able to reserve stock when products are added to cart and display a countdown for the customer. 

The issue is that I'll need a filter to align the reserved stock minutes (10) on checkout with what the store owner wants to set (60 mins).

I'm pursuing this as a plugin, as I see that the setup is too opinionated to be in the core. There are many stores this would and wouldn't fit. Having access to a filter here would allow me to make the checkout progress consistent for this case.

### Thoughts
I know the `ReserveStock ` class was mainly designed for race conditions, though it's really useful for so much more. We just need a little more flexability for those who need it. I'm excitied to hear your throughts on this 😊

**Comment by mikejolley** [comment]
I'm not certain those use cases are satisfied by the filter @nerrad suggested. What you talk about is a full reserve stock (with or without an order) flow, rather than just the ability to change this filter. The _core_ issue is probably the best place to discuss that because it's a new use-case. This issue is regarding the 10 mins default timeout for regular checkouts, which I'm not totally against filtering, but it:

- needs to be separate from the core 'on hold stock' option
- needs to protect store owners from shooting themselves in the foot (e.g. so low that the reservation clears before they have had a chance to fill out the form)

Regardless of what is decided on the core side, I stand by this statement:

> Whilst this link could be removed, that would make it more difficult to track if an order is resumed and already has stock reserved. You'd need a way to link it to an order/session/cart to know this.

We need to have a method of knowing what reserved the stock. Linking to an order in the case of blocks satisfied that requirement. In your case, you'd need a way to link to a specific item in the cart somehow.

@nerrad I think we either need a new filter or should leave this hardcoded in blocks at 10 — we should leave the other implementation details to core now it's seeing wider usage beyond the blocks use-case.

**Comment by nerrad** [comment]
@morganhvidt Just so I'm clear on things...

The checkout _block_ is currently the only checkout flow that hard codes `reserve_stock_for_order` to be 10 minutes and that is done via the _internal only_ StoreApi used by the checkout block flow.

Are your use-cases describing customers using the checkout block right now, or the checkout flow that's in Woo Core?

If the former, then I don't think we want to be adding a filter in our internal only api because we still consider that _not fit for public use_ (we may need to change the api logic as we continue to iterate on the new blocks). At some point once we're confident we can publish the API we will do that but we're not there yet. Both blocks are still in preview as we iterate.

If the latter, then this definitely is something that should be discussed further in WooCommerce core as that is where this logic primarily lives now and it sounds like this has more implications than simply how our blocks are using it.

**Comment by nerrad** [comment]
Looks like this is something that is best handled in WC core so I'm closing the issue here.
