### ISSUE TITLE
Recommended way to detect WooCommerce Blocks is active?

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce-gutenberg-products-block#2909]
What is the recommended way to detect if WooCommerce Blocks (3.0 or above) is active programmatically?

I'm currently using `class_exists( '\Automattic\WooCommerce\Blocks\Package' ) && version_compare( \Automattic\WooCommerce\Blocks\Package::get_version(), '3.0.0', '>=' )`

**Comment by nerrad** [comment]
That's a good method for determining a version, but it will also be true for when this code is included in WooCommerce core as a package (which it will be for the WooCommerce 4.4 release). Thus, it will be problematic because when included as a package and the plugin is not active on a users site, things behind feature gating (including Cart and Checkout blocks) are not available.

So in combination with the version check, you'd also want to do something like this:

```
if ( ! defined( 'WC_BLOCKS_IS_FEATURE_PLUGIN' ) ) {
	define( 'WC_BLOCKS_IS_FEATURE_PLUGIN', true );
}
```

That is only defined and true when active as a plugin on a user's site and doesn't exist or is false when loading via WooCommerce core as a package.

**Comment by webdados** [comment]
Actually I just need to know if it's active (either via a plugin or via WooCommerce core) and if it's 3.0 or above, to activate my payment gateway integration class with the new checkout.

**Comment by nerrad** [comment]
> Actually I just need to know if it's active (either via a plugin or via WooCommerce core) and if it's 3.0 or above, to activate my payment gateway integration class with the new checkout.

I figured, hence my response because when Woo Blocks 3.0.0 is included as a package in WooCommerce core and the site does not have the plugin installed and active (which overrides the package in that case), then the following is true:

- `Package::get_version` will return true.
- `WC_BLOCKS_IS_FEATURE_PLUGIN` will be undefined.
- Cart and Checkout blocks will **not** be available on the site.

Hence my suggestion to also use `WC_BLOCKS_IS_FEATURE_PLUGIN` as well.

However, with that said, it does look like you can exclude the constant check as the way we've feature gated things is the extensibility api is still available, it's just the block registration server side that is gated (which means assets don't load either). So it's feasible you can still register your new gateway in that condition and it's just tied to the same feature gating. You'd want to make sure you verify that first.

**Comment by webdados** [comment]
> Cart and Checkout blocks will not be available on the site.

Why?

**Comment by nerrad** [comment]
They are currently in feature preview via the feature plugin only and we don't consider them ready for prime time yet.

**Comment by nerrad** [comment]
I'm going to close this issue because it's not directly related to development of the plugin and has nothing actionable for the plugin itself. However the conversation can continue after it's closed.
