### ISSUE TITLE
Checkout block: Payment methods not visible

### ISSUE THREAD

**Issue by happycommunity** [woocommerce/woocommerce-gutenberg-products-block#2983]
**Describe the bug**
Stripe, Google Pay and Apple Pay payment methods are not visible when using Checkout block. 
Only Paypal is visible.

**To Reproduce**
1. Choose Hello theme.
2. Install Elementor plugin.
2. Add Checkout block to checkout page.
3. Click Edit with Elementor, and click update.
4. View checkout page in incognito mode on Google Chrome, Firefox and Safari.

**Expected behaviour**
All payment methods visible and active (Paypal, Stripe, Google Pay, Apple Pay)

**Screenshots**
![image](https://user-images.githubusercontent.com/69405092/89721236-81379900-da1e-11ea-9765-6a13a08e3ed1.png)

**WordPress:**
* Core version: 5.4.2
* WooCommerce version: 4.3.1
* WooCommerce Blocks version: 3.1.0
* Site language: English
* Any other plugins installed: Elementor

**Comment by nerrad** [comment]
Thanks for taking the time to leave the issue here! Unfortunately I'm unable to reproduce. I was able to publish the page with the checkout block on the hello theme with elementor active and a widget added via Elementor and viewed all payment methods just fine:

<img width="1220" alt="Image 2020-08-10 at 7 52 35 AM" src="https://user-images.githubusercontent.com/1429108/89780033-a25fbe80-dade-11ea-866d-f0518d389fbb.png">

Chrome/Apple Pay is also available for me.

Since it looks like the block itself is rendering for you just fine, I suspect this might be a setup issue. Are you sure you have the Stripe payment method configured and active on your site?

**Comment by happycommunity** [comment]
Hi Darren, 

Thank you for your reply.

I went back to check the settings, and it's now working properly after updating the API keys.
