### ISSUE TITLE
investigate why is WP 5.4 + GB E2E test is failing and remove the skip

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2993]
In https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2990, we added an `allow_fail` for WP 5.4 + GB E2E test because it kept failing for us on main, the reasons are not clear yet, but it could be an API change.

**Comment by haszari** [comment]
I recently merged #2968 and this failed Travis build - https://travis-ci.com/github/woocommerce/woocommerce-gutenberg-products-block/jobs/370988014

I don't think it's related to the above issue - this failed on unit tests, this issue is about e2e tests. For now just adding info about this fail - i.e. the larger goal is making sure the Travis tests/build are all succeeding. Could split off a separate issue if needed (might be two different reasons/issues causing the failures).

Here's the relevant part of the transcript:

```
Creating wordpress_test ... 
2228: No such file or directory in /tmp/wordpress-tests-lib/includes/mock-mailer.php on line 2
2229[11-Aug-2020 20:47:23 UTC] PHP Fatal error:  require_once(): Failed opening required '/usr/src/wordpress/wp-includes/PHPMailer/PHPMailer.php' (include_path='.:/usr/local/lib/php') in /tmp/wordpress-tests-lib/includes/mock-mailer.php on line 2
```
