### ISSUE TITLE
Checkout Block: Improving documentation for extending with new Payment Gateways

### ISSUE THREAD

**Issue by iverok** [woocommerce/woocommerce-gutenberg-products-block#2994]
Referring to the documentation here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/docs/extensibility/payment-method-integration.md   

I've just successfully implemented this for the Vipps payment gateway, but the documentation did not explain how to integrate the new class(es) described there into the Checkout block and process itself. I've made it work by adding a static register()-method to the AbstractPaymentMethodType subclass, which I call in plugins_loaded. My method is shown below; but is this a valid/idiomatic way to do it? Would be great if this was documented in the doc above.

```
namespace Automattic\WooCommerce\Blocks\Payments\Integrations;
use Automattic\WooCommerce\Blocks\Assets\Api as AssetApi;
use Automattic\WooCommerce\Blocks\Package;

final class Vipps extends AbstractPaymentMethodType {
        ...
 public static function register() {
            $container = Package::container();
            $container->register(static::class,
                        function( $container ) {
                                $asset_api = $container->get(AssetApi::class);
                                return new static($asset_api);
                        });
            add_action( 'woocommerce_blocks_payment_method_type_registration',
                        function ($registry) {
                            $container = Package::container();
                            $registry->register($container->get(static::class ));
            });
        }

        ...
```

**Comment by nerrad** [comment]
Hi there @iverok! 

Ya you're correct we need to improve the php side registration to our docs. 

You don't **need** to use the container to register your class or include the `AssetApi` as a dependency. The AssetAPI is actually specific to the Blocks plugin assets so it won't have value for your own payment method integration. 

The only thing you really need to do aside from extending `AbstractPaymentMethodType` is to register an instance of your payment method with the payment method registry using the `woocommerce_blocks_payment_method_type_registration` hook. Just make sure you do that before `init` priority 5 fires in the WP call stack (that's where the `woocommerce_blocks_payment_method_type_registration` action fires).

I'm going to close this issue because it's not something actionable for the repository but I'm happy to answer any further questions you have.

**Comment by nerrad** [comment]
I've created #3000 as a reminder for us to improve the documentation.
