### ISSUE TITLE
Improve documentation on PHP side payment method registration

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3000]
The [documentation for PHP side payment method integration](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/docs/extensibility/payment-method-integration.md) with the Checkout block can be improved. While it includes some instructions about what hooks to implement etc, it's still vague on actual registration of new payment method integrations.

Ideally it'd be good to have an example payment method integration as a reference. The PM's we integrate in the blocks plugin are helpful but also include usage of the container etc which really isn't needed by Payment methods. Also our usage of `AssetApi` can be a bit confusing to implementers because `AssetApi` is only usable in the Blocks plugin context.

**Comment by iverok** [comment]
Thank you! I got confused by the factories and whatnot.

So basically just (tested and working)

```
add_action('plugins_loaded', function () {
           add_action( 'woocommerce_blocks_payment_method_type_registration',
                        function ($registry) {
                            $registry->register(new MY_NEW_PAYMENT_METHOD_INTEGRATION_CLASS());
            });
});
```

The only other thing I had a problem with was actually related to the Assets\Api thing because I had some trouble finding the correct dependencies for wp_register_script - $asset_api->register_script obviously didn't work. I ended up doing

```
  $dependencies = array('wc-vendors', 'wc-blocks' );
  wp_register_script($handle, $path, $dependencies,$version,true);

```

As for having an example payment integration example; maybe rewriting "cheque" or something as an 'external module' would be better, but I've attached what I think is the simplest possible implementation for the non-existing payment method Florb:

[florb-payment-integration.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/5062883/florb-payment-integration.zip)

To be loaded by doing

```
add_action('plugins_loaded', function () {
           add_action( 'woocommerce_blocks_payment_method_type_registration',
                        function ($registry) {
                            $registry->register(new  Automattic\WooCommerce\Blocks\Payments\Integrations\Florb());
            });
});
```

Except for the part that the payment method doesn't exist, this works using the default payment flow and does not require any special build environment or toolchain for the javascript.

**Comment by nerrad** [comment]
> The only other thing I had a problem with was actually related to the Assets\Api thing because I had some trouble finding the correct dependencies for wp_register_script - $asset_api->register_script obviously didn't work. I ended up doing

You shouldn't need to add the `wc-vendors` or `wc-blocks` handles as dependencies... did you find you required those? returning the handle from `get_payment_method_script_handles` should be sufficient because the payment api should take care of enqueuing the script at the right time.

You can see an example [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/src/Payments/Integrations/Stripe.php#L67-L80) (just imagine `$this->asset_api->register_script` is `wp_register_script`).

Thanks for the example plugin!

**Comment by iverok** [comment]
At the time, yes:  without those dependencies the block wouldn't load in the _editor_. The _front-end_ worked fine however. Removing my js enabled the block to load;  adding the dependencies above made everything work in the backend as well.

It must somehow have had to do with the other mistakes; I tried removing the dependencies now with everything corrected and it works just fine with zero dependencies. Thanks again!
