### ISSUE TITLE
WooCommerce Cart and checkout block not working with mollie payment

### ISSUE THREAD

**Issue by egzyy** [woocommerce/woocommerce-gutenberg-products-block#3011]
## Describe the bug
the payment method area for the customer will not be available if mollie is used instead of stripe
### WordPress (please complete the following information):
* Core version: [e.g. 5.0.3]
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: [e.g. 3.5.3]
* WooCommerce Blocks version: [e.g. 1.3.1]
* Site language:
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by nerrad** [comment]
Hi there @egzyy,

Thanks for taking the time to leave a report here in the repository. 

As noted in the [announcement post](https://woocommerce.wordpress.com/2020/05/27/available-for-testing-a-block-based-woocommerce-cart-and-checkout/), the _preview_ for the Cart and Checkout block currently supports a limited number of payment methods. Currently, as you've discovered, Mollie is not one of the supported payment methods. 

Over time we expect more payment method support will be available for the blocks. We're currently working on a page for WooCommerce.com that will be used to give the status of the blocks and serve as an up to date resource for what new support is added as our own teams and third party developers integrate their extensions with the blocks.

Since your issues is something we're already aware of and tracking, I'm going to close this issue for now.
