### ISSUE TITLE
Stripe: Payment Request Button Theme is not honored in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3033]
First reported by @haszari in #3004.

## To reproduce
1. Make sure you have the Stripe payment gateway installed.
2. Go to WooCommerce > Settings > Stripe > Payment Request Button Theme and select 'Light'.
![imatge](https://user-images.githubusercontent.com/3616980/90760600-6a2c5d00-e2e2-11ea-982c-4f9be82ec408.png)
3. Create a page and add the Checkout block.
4. Notice the theme of the express payment method button is not honored in the editor.

![imatge](https://user-images.githubusercontent.com/3616980/90760617-71536b00-e2e2-11ea-9638-e647b6d5415d.png)

## Expected behavior
Style defined in the settings should be honored: if 'Light' is selected, buttons should be light.

**Comment by nerrad** [comment]
For reference, part of the challenge here is the payment request api is browser/geographical specific, so currently the editor view is using a static image to "represent" what things will look like on the frontend for a shopper given all the express payment method conditions for offering the payment method exist. 

The flaws with this approach:

- as noted by this issue, theming isn't picked up (can be resolved by just capturing the static image for each of the themes).
- since the image isn't provided by the payment method api, it runs the risk of getting out of date should that change in the future (although the risk of that is fairly minimal because payment method brands tend to last a long time due to recognition bias).

**Comment by haszari** [comment]
> so currently the editor view is using a static image to "represent" what things will look like on the frontend for a shopper

Ah I see – maybe not worth trying to make this 100% wysiwyg. Definitely a low priority IMO.

**Comment by nerrad** [comment]
I'm going to close this because I think this is something that would be better handled by the Stripe payment extension team once we migrate the code to the extension.
