### ISSUE TITLE
Checkout: Order Received > Billing & Shipping Details not displaying if customer is logged out

### ISSUE THREAD

**Issue by Kimchi500** [woocommerce/woocommerce-gutenberg-products-block#3038]
Screenshot:
<img width="1440" alt="Screen Shot 2020-08-21 at 2 59 03 PM" src="https://user-images.githubusercontent.com/57980521/90863442-9e2a7f80-e3c1-11ea-8ccc-6e22b4e64182.png">

To reproduce:
1. Make sure you're logged out, ideally incognito/private
2. Purchase something
3. Order received page will display order information but no shipping + billing details.

Expected behavior:
<img width="1439" alt="Screen Shot 2020-08-21 at 2 59 01 PM" src="https://user-images.githubusercontent.com/57980521/90863409-8fdc6380-e3c1-11ea-98f3-770b76695f24.png">

**Comment by nerrad** [comment]
Hi there!

Currently the Checkout blocks shouldn’t be affecting anything on the Order Received route. Are you able to reproduce this with the shortcode checkout flow?

**Comment by nerrad** [comment]
I did some testing and it looks like this is happening by design in the shortcode checkout flow as well. If a WooCommerce store is configured to allow guest checkout, the billing address and shipping address is _not_ shown on the order received page. These details are only revealed to logged in users.

This isn't specifically a cart and checkout block feature so if there is any desire to change this, it'd be best to create an issue in [WooCommerce Core](http://github.com/woocommerce/woocommerce/issues/new) repository.
