### ISSUE TITLE
woo payments

### ISSUE THREAD

**Issue by jimbardim** [woocommerce/woocommerce-gutenberg-products-block#3072]
woo payments and paypal express isn't working with this plugin?

both are in the woocomerce core so why you guys haven't add this yet?

**Comment by nerrad** [comment]
Hi there!

Woo Payments and Paypal Express are not WooCommerce core functionality. Both come installed via separate plugins. It may appear they are core functionality because it's also possible for them to be installed as a part of the WooCommerce core onboarding process.

With that said, Woo Payments is in the process of being integrated.

Neither of these payment method integrations are done in this repository however so I'm going to close this issue for now.
