### ISSUE TITLE
Allow getSetting to be filterable.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3091]
A good extension method is filters, allowing getSetting (either from the server-side or JS side) to be filterable would offer huge wins for a small investment.

Note: all values passed to wcSettings are native wp values, so for the most time, they have a filter, but sometimes the user doesn't want to change the global value, only the one used in Blocks, this should allow it.

**Comment by nerrad** [comment]
I'm going to close this issue because we're describing a solution without a problem here. When we encounter a specific use case that having a filter on settings would solve we can create the issue. I'm wary of simply adding a filter because it "would offer huge wins for a small investment." What trade-offs would we be making for adding the filter? Are there other ways to solve a use-case without a filter? Are there reasons why we want to preserve the integrity and trustworthiness of the pre-filtered settings?

**Comment by senadir** [comment]
I agree, this is an old issue and was in a time when I thought filters would solve problems without giving it a deep thought.
