### ISSUE TITLE
VAT Nr Field Is Missing

### ISSUE THREAD

**Issue by MEGGAWORLD** [woocommerce/woocommerce-gutenberg-products-block#3096]
## What do you like about the Cart & Checkout blocks?
The Cart & Checkout blocks is great it looks much better than the standard Woocommerce Cart and Checkout pages.
## What do you think is missing from the Cart & Checkout blocks?
What needs to be added here is a VAT Nr field on the checkout page just like on the standard Woocommerce checkout page.
I also noticed that the Currency is not being updated in the order summary when using the extension Woocommerce Currency Converter. With the standard Checkout page it works fine!
![VAT Nr Field on standard Woocommerce Checkout page](https://user-images.githubusercontent.com/16372112/91911820-29552080-ecb2-11ea-81da-0ab177f2515d.png)
![Woocommerce Currency Converter Not Working](https://user-images.githubusercontent.com/16372112/91911852-36720f80-ecb2-11ea-981b-4805f848a4d2.png)
![Woocommerce Standard Checkout](https://user-images.githubusercontent.com/16372112/91911866-3c67f080-ecb2-11ea-8d27-fa3d1c64549b.png)

**Comment by nerrad** [comment]
Thanks for the feedback @MEGGAWORLD ! 

For the VAT number field, is that added via some custom code on your site or a WooCommerce extension? If extension would you mind sharing which one?

Currently the Cart and Checkout blocks are still in preview and we still have to work on various extensibility points for extensions to hook into to integrate with the new blocks and flow. I appreciate you sharing with us the extensions you are using and what's not working so we can use that to evaluate as we work on this.

**Comment by MEGGAWORLD** [comment]
Hello,

For the VAT number field i’m using the Woocommerce extension EU VAT Number.




Regards,
Louis

**Comment by nerrad** [comment]
Extensibility is something we're currently working on. Once we have a way for extension developers to extend the Cart and Checkout blocks we will be publicising that fairly broadly. For now, there is nothing actionable for us with this issue so I'm going to close it. Closing it does not mean that the feedback or the need has not been received, it has :) We have a process in place to review all these requests (using the `category: extensibility` label) so your taking the time to create this issue is valuable!
