### ISSUE TITLE
WooCommerce Blocks and WPML incompatibility

### ISSUE THREAD

**Issue by andrasguseo** [woocommerce/woocommerce-gutenberg-products-block#3114]
**Description**
When using WooCommerce Blocks with WPML there are a number of bugs / glitches.

Bug 1: On the cart page clicking on 'Remove Item' does not remove the item from the cart.
(Sometimes changing the language at least once on the cart page is required.)

Bug 2: On the cart page adjusting the quantity of items does not get applied / saved.

Bug 3: When changing to language 2 on the cart page, the cart contents remain in language 1. Refreshing the page or clicking on the language 2 url will "refresh" the cart and the items will show in language 2. This happens every time when changing the language.

**To recreate**

Main language: English
Second language: German

- Setup WooCommerce with WPML and WooCommerce Multilingual.
- Add and activate WooCommerce Blocks.
- Download the German translation of WooCommerce and put it in wp-content/languages/plugins. Make sure you get the filename right: woocommerce-de_DE.po / .mo
- Set up at least one additional language (German) with WPML and make the products translatable.
- Add the language switcher to the footer or as a sidebar widget to make switching between the languages easy.
- Set up the cart page with the WooCommerce Blocks plugin > Cart block.
- Create a translation for this cart page.
- Add a couple of products. Create translations for them. To make it easy to distinguish later you can add "DE" at the beginning of the product names.
- Go to the English shop page.
- Add 1-2 English products to the cart.
- Go to the English cart page.
- Note that all the products are in English. This is correct.
- Use the language switcher to switch to German.
- (Bug 3) Note that the products in the cart are still English. This is **NOT correct**.
- Refresh the page on click on German in the language switcher again. Now the products will show in German.
- Click on "Remove product" / "Artikel entfernen" in the cart product list.
- (Bug 1) Note that the product does not get removed from the cart. If you check the browser console you will probably see a 409 error. This is **NOT correct**.
- Change the quantity of one of the products.
- Note that the "Go to checkout" button changes color for a while indicating the changes are being made.
- (Bug 2) Note in the console that you get a 404 error.
- (Bug 2) Refresh the page and note that the product quantities have not changed. This is **NOT correct**.

**Screen recording**
I have created a screen recording of this which you can find here:
https://1drv.ms/v/s!Aqh6lbOjUW1TgexN6r7TiNtfAitsdQ?e=OjD5Ya

**Comment by nerrad** [comment]
Hi Andras,

Thanks for taking the time to create this issue. Without diving into too much detail into this at the moment. The cart and checkout blocks are significantly different from the shortcode based cart and checkout in that the rendering is primarily client side via JavaScript (React). This means:

- php hooks used by extensions such as WPML for swapping out translated products etc are not available for the blocks.
- localized strings are implemented using `wp.i18n` which as far as I know is something none of the current localization plugins support. 

Unfortunately, this does mean at the moment that out of the box WPML is not supported by the current Cart and Checkout blocks.

We are still working on improving the blocks and reviewing all the extensibility points to add but it's more than likely plugin and extension developers will need to explicitly support the new blocks. 

For now, there isn't anything actionable with this issue so I'm closing it, but it is something being tracked. When we have more extensibility points implemented we'll be writing documentation for developers to use to integrate more tightly with the blocks.

It's unclear whether the bugs you've reported in this issue are specific to WPML or not. Are you able to reproduce without WPML (I haven't been able to)? If so, would you mind creating separate issues so that we can be sure to track that separately.

Thanks again for your report!

**Comment by andrasguseo** [comment]
Hi @nerrad 
Thanks for your detailed answer.

The issues I have outlined above are only present when using WPML.
Everything worked well when I was using the blocks without WPML.

I hope that the code will be in a state soon where it can be made compatible with WPML. Fingers crossed.

Cheers,
Andras
