### ISSUE TITLE
Strip images from Product Summary shown on Cart

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3142]
Currently, we show product summary as is in the Cart and Checkout, sometimes this might include images, which might break the layout or design, we should look into stripping images from that place
![image](https://user-images.githubusercontent.com/6165348/93028383-8da9a580-f60b-11ea-8be0-35bda139074b.png)
![image](https://user-images.githubusercontent.com/6165348/93028391-98fcd100-f60b-11ea-9c64-d9fce545ab92.png)

**Comment by jimbardim** [comment]
here actually a better explanation to see the problem
https://ibb.co/s2ZjsT5
https://ibb.co/tcs3Lgv

**Comment by nerrad** [comment]
For the summary content here, if a product has a short description, that will be used instead of the main product description. For products with image heavy content (or rich text content) in their description, I think the solution here is to make sure they have a short description instead. From what I've seen documented so far, it looks like this store might not have any short description for its products?

@jimbardim is that the case here for you?

Generally speaking, once we get into stripping content from the product description it becomes a bit of a no sum game because there will likely always be some stores that don't like how the content is modified, or it makes the summary layout for products inconsistent. That's why I think it's more beneficial for stores to explicitly fill out the short description for their products which is _intentionally_ provided for contexts where just text is needed (as is the case here).

**Comment by senadir** [comment]
Regarding this issue, short description can accept media elements, it is the content shown below the product price, the other one (regular description) is shown below with reviews and other metadata.

>  That's why I think it's more beneficial for stores to explicitly fill out the short description for their products which is intentionally provided for contexts where just text is needed (as is the case here).

I think I agree with this sentiment, however, showing media and short description in cart and checkout is a new behavior, existing store owners are not expecting short description to show up there, forcing them to update their catalog if they have it set up that way already.

One possible solution (which I don't like) is to add a new block setting that determines if we want to show media or not, however, I don't want us to go this path of adding new options for small enhancements.

**Comment by nerrad** [comment]
> Regarding this issue, short description can accept media elements,

I completely forgot this 🤦 .  Ya so it's still a problem then.

**Comment by nerrad** [comment]
A potential workaround for stores that need something in the meantime would be to filter the content using the `woocommerce_product_get_short_description` filter slug and restrict to when `wc()->is_rest_api_request() === true`.

I haven't tested that and don't have any code snippet at the moment but thought I'd share as a possible path for stores to explore if they're really blocked by this.

**Comment by jimbardim** [comment]
@nerrad  this wont work for me because i am not coder developer or anything between, the best thing i can do is to copy some code and add it into the child theme>> functions.php and hope it will work...

so essentially someone to use the plugin this is a big issue...
event if i go and add short description on all the products this  doesn't feel like a solution coz the short description is for giving the benefits of the product while in the cart i might not want this i might want to say free shipping to entice the visitor to buy.

so it is better to not have anything there or have the option for custom text. btway same thing happens in checkout as well.

**Comment by nerrad** [comment]
While it is recognized that for a subset of users this is a legit problem, part of the difficulty with resolving this is the ambiguity around the purposes of the various field content (product short description/description) and how they are used in various places. Since it _is possible_ for stores to customize the content in these fields as a workaround (albeit not a great one dependending on the current setup of _existing stores_ wanting to use the blocks), this isn't a high priority issue for us to address at the moment. 

It looks like we're currently leaning towards the solution of stripping images from the content before outputting here but we'll likely want to have a larger conversation about the purpose of the various fields, their intended use, and whether we need something specific to the Cart & Checkout contexts.

**Comment by jimbardim** [comment]
well to me it's not working properly, i wonder which genious thought it is a good idea to not be able to change the color of the button?
it has toooo many flaws and it has along way from being perfect, it needs to atleast integrate all payment providers such as woo payments paypal express and so on

**Comment by nerrad** [comment]
I didn't write that we wouldn't address this. It's just not a high priority issue given all the other things we are working on at the moment. There's a finite amount of resources working on this project right now and we have to prioritize those resources. I fully realize that our priorities might not line up with everyone (which is an impossible task anyways).

>  which genious thought

Please refrain from snide comments. It's really unnecessary and doesn't accomplish anything. Thanks!

**Comment by jimbardim** [comment]
> I didn't write that we wouldn't address this. It's just not a high priority issue given all the other things we are working on at the moment. There's a finite amount of resources working on this project right now and we have to prioritize those resources. I fully realize that our priorities might not line up with everyone (which is an impossible task anyways).
> 
> > which genious thought
> 
> Please refrain from snide comments. It's really unnecessary and doesn't accomplish anything. Thanks!

well i am not familiar with github but i am engaging in conversation here and telling you some issues and honestly to not be able to change button color on the main button its a kinda big issue and the developers when create this should had thought stuff like this... its like to buy a theme and not be able to change the color or size or fonts..... and its ok some stuff to not work out of the box but guys its like almost a year that  this plugin is out....

and again nothing personal with you or anything like this i am just giving my honest opinion.
