### ISSUE TITLE
Checkout blocks will be confusing for final customer, and not sure if it is GPRD compilant

### ISSUE THREAD

**Issue by Lasdelicias** [woocommerce/woocommerce-gutenberg-products-block#3149]
## What do you like about the Cart & Checkout blocks?
Cart and Checkout blocks are quite cool. They look much tidier and they seem easier to understand for the customer.

## What do you think is missing from the Cart & Checkout blocks?
I´d really like being able to change the button colours so they fit the brand design. I don´t know how to code, so using CSS to do that is not an option for me.

I won´t use the checkout block right now. Usually, customers first input the billing address, and then they get the option of inputting a delivery address if it is different. Having it all the way around will be confusing for existing customers. Many of my customers are over 70 years old, and after making a big effort to have them entering their billing address first, I think they would be really pissed off if I start asking them to make things differently for no reason. They won´t probably notice about the change, and they will only realize that the payment is declined.

Those customers who choose the local pick up option will be even more confused about being forced to enter a delivery address. Believe me, customers are super dumb. They are already confused for being asked to fill their billing address and I had to place notices asking them to fill their billing address at the cart page and also on check out, and I had to make a step by step video. Even then, they keep sending me messages to let me know that they can´t find how to choose the local delivery option when they are on a mobile phone. Some times I just want to hang myself up with the telephone cord, but they are all cordless those days.

Also, the checkout block does not give the option to create an account, which is essential. It is also missing the super useful "returning customer? Click here to log in" notice

Besides, I´m not 100% sure whether this checkout block is GPRD compliant. Customer should be forced to check "I have read and agree to the website terms and conditions *", instead of only having a link to the terms and conditions. 

Finally, the payments options will be confusing for the customer. At least, they will be confusing for MY customers. I think it should display all the payment options, and then the saved card options if there if any. Otherwise, customers will think that PayPal is no longer available. I also have 2 different card payment gateways (Stripe and Square) because some times one declines the payment and the other one accepts it. The Checkout block only shows one card payment option.

**Comment by nerrad** [comment]
Hi @Lasdelicias 👋 

Thanks for taking the time to leave your feedback! 

> Usually, customers first input the billing address, and then they get the option of inputting a delivery address if it is different. Having it all the way around will be confusing for existing customers. Many of my customers are over 70 years old, and after making a big effort to have them entering their billing address first, I think they would be really pissed off if I start asking them to make things differently for no reason. They won´t probably notice about the change, and they will only realize that the payment is declined.

We have it this way because our research into ecommerce best practices indicates that showing the shipping address first and defaulting to have the billing address the same as the shipping address performs better for stores. 

Usually shipping address affects the final total if the shipping options are address dependent so this allows for instant feedback on total changes as the address is added.

> Those customers who choose the local pick up option will be even more confused about being forced to enter a delivery address. Believe me, customers are super dumb. They are already confused for being asked to fill their billing address and I had to place notices asking them to fill their billing address at the cart page and also on check out, and I had to make a step by step video. Even then, they keep sending me messages to let me know that they can´t find how to choose the local delivery option when they are on a mobile phone. Some times I just want to hang myself up with the telephone cord, but they are all cordless those days.

Are you referring to what you had to do to try and make things less confusing for your customers when the blocks were in use or is this something you had to do with the existing checkout flow?

> Also, the checkout block does not give the option to create an account, which is essential.

This is being worked on. The blocks are still in preview state. We're still iterating on them to add functionality like this.

> It is also missing the super useful "returning customer? Click here to log in" notice

This should be present, it's no longer a notice but is included inline:

<img width="685" alt="Image 2020-09-17 at 3 32 35 PM" src="https://user-images.githubusercontent.com/1429108/93518666-233e8100-f8fb-11ea-83f7-b645724c9ccf.png">

> Besides, I´m not 100% sure whether this checkout block is GPRD compliant. Customer should be forced to check "I have read and agree to the website terms and conditions *", instead of only having a link to the terms and conditions.

I'm assuming you meant GDPR compliance? If so, I don't think this has anything to do with being GDPR compliant, do you have source material I can reference?

> Finally, the payments options will be confusing for the customer. At least, they will be confusing for MY customers. I think it should display all the payment options, and then the saved card options if there if any. Otherwise, customers will think that PayPal is no longer available. 

We have saved options displayed first because typically most returning shoppers will want to pay with a payment method they've already saved with the store (if the store provides that option). We are experimenting with alternative layouts when there are multiple payment method options however.

> I also have 2 different card payment gateways (Stripe and Square) because some times one declines the payment and the other one accepts it. The Checkout block only shows one card payment option.

Currently Square is not a supported payment method for the Checkout block, but integrations are being iterated on. You can read more on the current status of the [Cart and Checkout blocks here](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) (we'll be updating that document as we improve them).

Thanks again for leaving your feedback! I'm closing this issue because we only leave issues open for things with specific things we're working on. However please feel free to respond and add any additional comments - closing the issue does not mean no one is ready and considering the feedback.
