### ISSUE TITLE
Output product classes added via woocommerce_post_class filter

### ISSUE THREAD

**Issue by rastitkac** [woocommerce/woocommerce-gutenberg-products-block#3160]
## Is your feature request related to a problem? Please describe.
It is a shame that `render_product()` function does not use `woocommerce_post_class` filter. In all woocommerce, be it on archive or single pages it is possible to add custom classes to product container based on custom meta data, but those are not output in product grid block.

## Describe the solution you'd like
Add filtered classes to `render_product()` function so that it's not needed to filter the output again via `woocommerce_blocks_product_grid_item_html` filter.

## Describe alternatives you've considered
There is a possibility to filter output of `render_product()` function via the `woocommerce_blocks_product_grid_item_html` filter, but it unnecessarily leads to redundant code (adding the classes to block filter after we already added it once).

## Additional context
`render_product()`: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/e51627c3d2df183b8c8d5947fcd28ffcf697220f/src/BlockTypes/AbstractProductGrid.php#L305-L343

`woocommerce_post_class` filter: https://github.com/woocommerce/woocommerce/blob/d7b2207e75eedb4fb89249b81dcd42133e8ca616/includes/wc-template-functions.php#L701-L710

**Comment by nerrad** [comment]
Hi @rastitkac 👋 

Thanks for taking the time to submit this issue and outline your enhancement request. Better extensibility of the blocks is definitely needed and on our radar, but we are approaching it cautiously at the moment because there is still some potential shifts that could occur in the future with how the Woo Blocks are rendered. So we don't want to add additional extensibility points only to have that change again once we've solidified on the long term approach we are going to take.

To a degree, that's why [this faq was written](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891).

I realize this might not be what you were hoping to read at this point but rest assured this issue is being tracked along with other extensibility requests and we'll be sure to consider these points when we implement any changes.

**Comment by rastitkac** [comment]
Hi @nerrad, 

Thank you for your answer. As you stated, it is not what I hoped for, but I fully understand your reasoning after reading the FAQ you pointed me to. Thus, I will use the existing filter to achieve my goal.

Best regards.
