### ISSUE TITLE
Woocommerce Block Error Message

### ISSUE THREAD

**Issue by Cbeach83** [woocommerce/woocommerce-gutenberg-products-block#3164]
Hi,

Ive been trying to fix error message in Woocommerce Blocks. 

Each time I try to add in Checkout or Cart block I receive the same error message. 

Does anyone know how to fix this issue?

Checkout Block Error

There was an error whilst rendering the checkout block. If this problem continues, try re-creating the block.

Error message: Decimal separator can't be same as thousand separator. thousandSeparator: , (thousandSeparator = {true} is same as thousandSeparator = ",") decimalSeparator: , (default value for decimalSeparator is .)

**Comment by nerrad** [comment]
Hi there, 

From the error message you reported, it appears you have your store configured to have both the decimal separator and thousands separator as the same value (`,`). You can check currency options on the WooCommerce -> Settings -> General page and make sure you have separate values for those fields. Here's a screenshot of the settings:

<img width="688" alt="Image 2020-09-20 at 7 49 02 AM" src="https://user-images.githubusercontent.com/1429108/93710652-5a3cae80-fb16-11ea-8c17-8b84c2a1b113.png">

I'm going to close this issue because this isn't a bug with the Blocks but instead a store configuration issue. It doesn't mean you can't still reply here if you have further information or questions.
