### ISSUE TITLE
Checkout issue / review

### ISSUE THREAD

**Issue by timbertactics** [woocommerce/woocommerce-gutenberg-products-block#3169]
## What do you like about the Cart & Checkout blocks?

Love the layout. The cart's descriptive items need to be bigger, older people are going to have a hard time reading what they've bought. 

I noticed when I click the credit card option for paypal, it all of the sudden makes all the images HUGE and displayed vertically down the page, takes up the whole screen. Images are the VISA, MasterCard, etc. Logo's. Needs a fix :/

All in all, I this gets 5 stars. I'll be waiting for the credit card icon image fix, as that would make many customers back out of paying for my items. 
![11](https://user-images.githubusercontent.com/71632688/93745237-6ffeb200-fbb0-11ea-9a38-62eb7fda09e0.JPG)
![12](https://user-images.githubusercontent.com/71632688/93745239-712fdf00-fbb0-11ea-8c62-39e239005f05.JPG)
![13](https://user-images.githubusercontent.com/71632688/93745240-712fdf00-fbb0-11ea-8a4c-b8a4bec18d7c.JPG)

## What do you think is missing from the Cart & Checkout blocks?

missing a option on the right side when inserting the checkout module, to automatically use same shipping address as billing "checked box" option.

**Comment by timbertactics** [comment]
Also, I believe most people use credit cards rather than paypal, so having the credit card box as default over paypal would be nice. Or the option to switch it out admin side.

**Comment by timbertactics** [comment]
so far I've figured out with my html browser editor, that the .container { width: 100%; } is either the problem or part of it. Once I set it to 500px, it downsized all the credit card images to be contained back in their box
![possible](https://user-images.githubusercontent.com/71632688/93746718-d7b5fc80-fbb2-11ea-98f8-84b6b6ec6cc3.JPG)

**Comment by timbertactics** [comment]
img.wc-block-components-payment-method-icon.wc-block-components-payment-method-icon--visa {
    width: 10%;
}

this works for 1 image, looks okay. I'll have to see how to make this change in wordpress.

**Comment by timbertactics** [comment]
.wc-block-components-payment-method-icons .wc-block-components-payment-method-icon {

    width: 10%;

}



So I had to open the page and use the live editor for my theme, and insert this into the custom css section. Since using the box labeled additional or custom css on the same screen as inserting the checkout module didnt
![66](https://user-images.githubusercontent.com/71632688/93748860-27e28e00-fbb6-11ea-8543-7822a2d3ea44.JPG)
 work.

**Comment by nerrad** [comment]
HI there @timbertactics 👋🏻

Thanks so much for taking the time to leave some feedback - much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. It does not mean that we don't note or review the feedback. Closed issues can also still be commented on.

Below I'm going to respond to some of the points you've raised:

> Love the layout. The cart's descriptive items need to be bigger, older people are going to have a hard time reading what they've bought.

Thanks! We love the layout too. It is also guided by some of our research into Cart and Checkout flows that convert well. Regarding the cart descriptive items - this is something that is influenced by the theme in use. Browsers can also be configured to enlarge font sizes for the entire viewed page (`CMD-+` for Chrome on MacOS) and the blocks by default will respect those settings. If you have older clientele viewing your sites that could be useful information to pass on to them as having the ability to make the font sizes larger for all websites being viewed in a browser is definitely something I find handy myself.


> I noticed when I click the credit card option for paypal, it all of the sudden makes all the images HUGE and displayed vertically down the page, takes up the whole screen. Images are the VISA, MasterCard, etc. Logo's. Needs a fix :/

🤔 Hmm, I'm not sure I understand how you are triggering this. When I have Paypal standard activated, it's not an option in the Cart (as per your screenshot). Do you have the Cart and Checkout blocks inserted on the same page maybe? If you could add more details about how you are triggering this behaviour that'd be helpful, it's not an issue I can can reproduce currently (it's also possible it's theme specific - what theme are you using?). 

As well, to be clear, there is no "credit card option for paypal" available for the checkout blocks currently. From your screenshots, it looks like you also have the Stripe extension active on your store, the "Credit/Debit Card" label is for the Stripe Credit Card payment method option.

Also, what version of the this plugin is installed and active on your site?

> All in all, I this gets 5 stars. I'll be waiting for the credit card icon image fix, as that would make many customers back out of paying for my items.

Thanks for the high value you've placed on the new blocks - much appreciated. We're happy to fix any bugs that surface but we first have to be able to reproduce them. Clarifying some details around this as I requested earlier will be helpful in helping us try to reproduce.  

I see in [this comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3169#issuecomment-695988916) that you mentioned you found some CSS for your theme that fixes the cards for you which is great - but out of the box it shouldn't be necessary, so it does seem to support there's some sort of theme issue in your case that has to be accounted for. We might be able to add some defensive CSS in the plugin to help protect against that if we can get the theme name for testing.

> missing a option on the right side when inserting the checkout module, to automatically use same shipping address as billing "checked box" option.

I could use some clarification on this suggested improvement. Currently the block has this behaviour:

- If the cart has no products in it that require shipping, then only the billing address form is shown.
- If the cart has products in it that require shipping, then the shipping address is shown and a checkbox input is available for using the same address entered for shipping as the billing address. This is automatically checked by default but if a shopper unchecks that input, they are able to enter a different billing address from shipping.

This was added because research we did in designing the new checkout flow supported better conversions and shopper experience with this design. It removes friction from the purchase process for shoppers that require shipping - most shoppers will have the same billing address.

With that said, we are open to feedback on these optimized defaults - can you clarify what outcome you are hoping for here? It sounds like you want to swap the forms around and have the billing address always first and instead have the shipping address hidden and default to the same as the billing address? Is that correct?

> Also, I believe most people use credit cards rather than paypal, so having the credit card box as default over paypal would be nice. Or the option to switch it out admin side.

In the latest version of the feature plugin, the tab order for the payment method options follows the order of payment methods in the WooCommerce -> Settings (page) -> Payments (tab). On the payment method settings page, you can drag and drop the order for payment methods installed on your store. The checkout block will then follow that order for the tabs.

**Comment by timbertactics** [comment]
ahhh, didn't know that about the payment options!

Also, I'm using the *Creativo theme.* Everything is up to date. Have only
paypal and stripe enabled for payments. At first install, I didn't have
these issues with the pictures, but once I deleted the page, remade it to
default, deleted default checkout and cart (separate pages) and re-added
your cart / checkout, that's when it happened.

As for the check box remark, I didn't know it was checked automatically, I
must have been tired haha.

Thank you for the awesome feedback!!

**Comment by nerrad** [comment]
Thanks for providing the theme name. It looks like it's a premium theme - unfortunately I won't be able to troubleshoot for that theme given it's a paid theme. Your best bet here would be to get support from the theme developer to see if they can help with the credit card icon size. On all the themes we test the blocks on (it's quite a few) we haven't encountered this yet. 

In the meantime it looks like you've got a workaround solution for the custom CSS you added to your site 👍🏻

**Comment by timbertactics** [comment]
Hi Darren,

https://www.timber-tactics.com

Do you know what is causing this on the checkout page? (image attached)

It's displaying "11 items" onto each product. Is this something in my theme
settings? I have no idea how to remove it.

Thank you.

,Conner

**Comment by nerrad** [comment]
Hi Connor, 

Sending a reply to a Github issue with an attachment doesn't work.  So there was no attachment. I visited your site and saw what I think you were describing happening on the checkout:

<img width="1144" alt="Image 2020-10-11 at 8 47 20 AM" src="https://user-images.githubusercontent.com/1429108/95679201-2990e780-0b9f-11eb-8622-f2868612bd11.png">

It looks like your theme doesn't have any styling for the `screen-reader-text` class. There are a number of accessibility related elements used in the blocks (and WooCommerce core) that are styled via a commonly used selector in WordPress (`screen-reader-text`) used to hide those elements only for devices that use them. 

Themes _typically_ add the styling for this class and it looks like your theme is missing the styles.

As a workaround, you can add this to the custom css for your site:

```
.screen-reader-text {
	clip: rect(1px, 1px, 1px, 1px);
	height: 1px;
	overflow: hidden;
	position: absolute !important;
	width: 1px;
	word-wrap: normal !important;
}
```

I've created an issue (#3265) to add fallback styles to Blocks for themes that aren't adding styles for `screen-reader-text`.

Also Connor, in the future, please create a new issue for things that look like a bug as opposed to just adding to the existing issue. Thanks!

**Comment by timbertactics** [comment]
I apologize for responding to this issue instead of opening a new one. As
always, you're awesome!

Thank you!
,Conner
