### ISSUE TITLE
Implement setting for switching between Cart and Checkout blocks and Shortcodes for checkout flow.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3187]
This still needs some design work, once that's done the following outcomes are aimed for.

- Merchant would access the setting on the WooCommerce -> Advanced settings page.
- Using the select input, they'd be able to switch between Blocks and Shortcode for checkout flow and code will take care of swapping out block or shortcode in page content on switching.
- There'd be a link to the relevant pages (possibly a prompt) for editing blocks when they are switched to.
- Add tracks events so we can get data on how many stores are using shortcodes vs. blocks.

Questions:

- What if people want to just implement one or the other block and not both (i.e. Cart block but not checkout block). I've seen this behaviour from folks who _can_ use the Cart block but not the Checkout block yet because Checkout block doesn't support an extension they use.
- If the above happens, and people manually change the pages - should that be reflected in the toggle in the settings somehow?

**Comment by LevinMedia** [comment]
One more question to answer, related to the first of the two question above:

- what happens if someone switches formats manually? (IE while editing the page)
- Can we keep track of what's happing on the cart and checkout pages so we can display the correct information on the settings screen?

**Comment by LevinMedia** [comment]
@nerrad Here are mockups for the addition of the new settings. 

There are two settings; one for cart and one for checkout, this allows the case where a merchant might want to use one as a block but not the other. 

**Both cart and checkout set to block:**

<img width="1790" alt="Screen Shot 2020-09-24 at 10 43 14 AM" src="https://user-images.githubusercontent.com/4500952/94180423-d6a2fa80-fe52-11ea-81fd-0300865e8beb.png">

**Both cart and checkout set to Shortcode:**

<img width="1791" alt="Screen Shot 2020-09-24 at 10 43 23 AM" src="https://user-images.githubusercontent.com/4500952/94180450-df93cc00-fe52-11ea-83b1-17141627b97e.png">

Should cart and checkout pages not be set in the section above, the links to edit the respective pages in the format section will be disabled:

<img width="1791" alt="Screen Shot 2020-09-24 at 10 43 32 AM" src="https://user-images.githubusercontent.com/4500952/94180781-647ee580-fe53-11ea-9fad-76a85fdc90cd.png">

In the case of a merchant manually changing the format of the cart or checkout blocks (IE, changing from block to shortcode or visa vera while editing the page) We should monitor for the change so that we can keep the settings on this page in sync with what's actually on the cart and checkout pages. 

The "learn more" link in the format section description should link to https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/

**Comment by nerrad** [comment]
Awesome stuff 🎉  Thanks David!

**Comment by haszari** [comment]
@LevinMedia as I start looking at how to implement this, I have a couple of thoughts on the design and how it fits in to the rest of Woo. I'll mind-dump them all here and maybe we can chat more when you're online. 

### "Recreate page" action & onboarding
- Switching between blocks <=> shortcodes for these pages is an action, i.e. it will make a change on the merchant's behalf. A button feels like a better fit than a dropdown to me; click the button, then we change the content for you (and alert if there's an issue). 
- There's already a similar action happening in a couple of other places in woo: in onboarding, the pages are automatically created (with the shortcode), and there's a remedial `Status > Tools > Create default WooCommerce Pages` action available. (See below for screenshots.)
   - Note there is also a `Page does not contain shortcode` status item too (see below) which we might want to look at while we're here.
- The dependency on the pages existing could be confusing; if the pages don't exist, then the whole `Page format` section doesn't apply. With an explicit action, we can handle this – e.g. the action includes the onboarding/page creation if needed: "ensure I have a cart page, and that it uses cart block not shortcode".
- Related to the above, I wonder if it's useful to group the settings/actions related to the pages more closely. E.g. `Page Setup > Cart page` + `Format > Cart page` are all options for the cart page, and relate closely to each other. 

<img width="938" alt="Screen Shot 2020-09-30 at 2 44 20 PM" src="https://user-images.githubusercontent.com/4167300/94635120-5edf3f00-032e-11eb-9d16-e16986599b4a.png">

<img width="998" alt="Screen Shot 2020-09-30 at 2 45 19 PM" src="https://user-images.githubusercontent.com/4167300/94635121-60106c00-032e-11eb-9cb3-1177ba634b96.png">

### Mixed/additional content on pages
How should we handle other content on the target page? E.g. if there's some extra copy or imagery around the cart or checkout block (or shortcode). Should we attempt to preserve this when switching, or should we recreate?

If we use an explicit action, based on the onboarding action, that might allow us to keep it simple and just replace with the block (or shortcode).

If the merchant has customised the content, it could be preserved as a page revision (so they can get it back if they wish).

### Another option
As an exploration, there might be a way to meld the page regeneration, status, and page selection into a single UI.  Something like this:

```
WooCommerce > Advanced > Page setup

Cart page  
- [  Cart  ] => dropdown, select a different page (or assign a page)
   - Cart page currently uses [woocommerce_cart] shortcode. Learn more. => status text
   - [  Recreate page using blocks ] => button, replaces page content with blocks (or vice versa), also handles creating a page if needed (similar to onboarding, "recreate pages" tool)
```

This is just a rough exploration! I'm keen for your ideas on how to keep this simple for merchants & support so it's super easy to see the state of the pages, and the action is simple and predictable.

**Comment by haszari** [comment]
There's a filter hook when the woo pages are declared, including the page content - [`woocommerce_create_pages`](https://github.com/woocommerce/woocommerce/blob/2c1fe4235d1177814d83c85e0a240ca8bc99fc66/includes/class-wc-install.php#L543). 

We could hook this to declare blocks content for pages, e.g. something like this:

```php
add_filter( 'woocommerce_create_pages' function( $woocommerce_pages ) {
    $woocommerce_pages['cart']['content'] = '<!-- wp:woocommerce/cart --> … <!-- /wp:woocommerce/cart -->';
    return $woocommerce_pages;
} );
```

Could be part of the solution here.

**Comment by nerrad** [comment]
Just going to leave a comment on this question while the thought is fresh in my mind:

> How should we handle other content on the target page?

Since the shortcode is a fairly straightforward pattern:

```html
<!-- wp:shortcode -->
[woocommerce_checkout]
<!-- /wp:shortcode -->
```

...and the block is similar:

```html
<!-- wp:woocommerce/checkout -->
<div class="wp-block-woocommerce-checkout is-loading"></div>
<!-- /wp:woocommerce/checkout -->
```

We should be able to swap out those specific patterns from the `post_content` value for the checkout page (and something similar for cart page). There's still some potential gotchas though:

- Is it possible that cart or checkout _shortcodes_ have arguments (in which case the pattern wouldn't work).
- Checkout and Cart blocks could have attributes if anything is changed from the default. So this means the pattern matching won't be as straightforward (should still be able to use regex though). Example:

```js
<!-- wp:woocommerce/checkout {"showCompanyField":true} -->
<div class="wp-block-woocommerce-checkout is-loading"></div>
<!-- /wp:woocommerce/checkout -->
```
- In the case where blocks _do_ have attributes, should they be stored somewhere when switching away from the block so that switching back restores those values? (Even if the answer is yes, I don't think this needs done in the initial iteration).

Alternatively, we could just save the content of the post when switching and then restore that content when switching back (which would arguably be the easiest to implement).

**Comment by haszari** [comment]
Logged a separate issue for making the status page blocks-aware cc @LevinMedia #3224. I don't think it's particularly urgent, and doesn't block this, but might be convenient to tidy that up alongside this work.

**Comment by LevinMedia** [comment]
@haszari thanks for the feedback and great catch on the new issue you logged above! Here are the decisions per our offline discussion ( Additional details at: pca54o-m8-p2 )

The settings will be included in their own section on the page per the original designs (as opposed to mixing them in with the page setup section) so that they’re less likely to be overlooked.

The settings will use select menus to match the other settings on the screen. They will also match the behavior of the other settings on the screen in that a merchant must modify a setting, the click save on the page to commit the setting (no ajax)

Should cart and checkout pages not be set in the section above, the links to edit the respective pages will be replaced with a string of text notifying the merchant to set the page in the section above.

<img width="1308" alt="Screen Shot 2020-10-02 at 11 09 47 AM" src="https://user-images.githubusercontent.com/4500952/94956721-8276c680-04a1-11eb-95cf-3fe8fa6805d6.png">

In cases where the merchant has added other content around the blocks or shortcode, we should preserve that content, and only swap the block for the shortcode, or visa versa.

**Comment by haszari** [comment]
I was assuming (hoping) that we could edit the blocks in the cart/checkout page using a combination of [`parse_blocks()`](https://developer.wordpress.org/reference/functions/parse_blocks/) and [`render_block()`](https://developer.wordpress.org/reference/functions/render_block/). However it looks like that's not going to work. 

Here's trimmed-down code for this approach:

```php
// Get the page object that we want to edit.
$page_id = wc_get_page_id( 'cart' );
$page = get_post( $page_id );

// Parse the existing content out as blocks.
$blocks = parse_blocks( $page->post_content );

// Insert a new block Pseudocode - the block structure may be incorrect.
// i.e. we would remove a shortcode [cart] block and replace with `woocommerce/cart`.
$sample_paragraph = [
	'blockName' => 'core/paragraph',
	'attrs'     => [],
	'innerHTML' => "<p>Test paragraph $random</p>",
];
$blocks[] = $sample_paragraph;

// Render out new post content.
// The problem is that this doesn't produce a Gutenberg-editable post;
// when viewed in Gutenberg all the content is in a `Classic editor` block.
$output = '';
foreach ( $blocks as $block ) {
	$output .= render_block( $block );
}

// Update the post content and save as a new revision.
$page->post_content = $output;
wp_update_post( $page );
wp_save_post_revision( $page_id );
```

I suspect the core of the problem is that the only correct way to render blocks is to use Gutenberg – i.e. JS runtime. We can't easily do this server side in a PHP hook when saving changed woo settings. 

So we'll need to think of some other ways to approach this – any ideas @nerrad ?

Here are some rough ideas:

- Include example cart & checkout page content in the blocks plugin code, and completely replace the page. Similar to "starter content" approach - we save Gutenberg output as a PHP constant/literal. We'd also need something similar for the shortcode page. We could leverage woo core/onboarding for this, store a frozen shortcode block, or just set the post content to `[woocommerce_cart]` - i.e. "classic" content. Problem: can't replace the cart/checkout within other content (i.e. support the case where the store has other content on the page).
- Invoke Gutenberg editor with a URL param or some other mechanism to make the change on the user's behalf. That would probably require core changes, and would be an unwieldy experience.
