### ISSUE TITLE
When using browser back button to return from checkout to cart, the loader remains visible on the Checkout CTA (Safari/Mac)

### ISSUE THREAD

**Issue by Shazgu** [woocommerce/woocommerce-gutenberg-products-block#3196]
## Describe the bug
When using browser back button to return from checkout to cart, the loader remains visible on the Checkout CTA. It doesn't happen if you use the 'return to cart' CTA in the form.
This happens on Safari/Mac (desktop). The problem doesn't seem to exist on Firefox/Mac (desktop).

## To reproduce
1. Navigate from cart to checkout on Safari-Mac-desktop, 
2. then use the browser's back button (or swipe gesture) to navigate back to the cart
3. Observe the loader on the button, which doesn't go away (see screenshot)

## Expected behavior
The default state of the button.

## Screenshots
<img width="1668" alt="Screenshot 2020-09-25 at 15 02 35" src="https://user-images.githubusercontent.com/71322363/94281892-1a772c00-ff47-11ea-8434-3a870619c69a.png">

### WordPress (please complete the following information):
* Core version: 4.5.2
* Gutenberg version (if installed): -
* WooCommerce version: 4.5.2
* WooCommerce Blocks version: 3.4.0
* Site language:
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: macOS 10.14.6
* Browser safari
* Version 14.0

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by nerrad** [comment]
Doesn't happen in Chrome for MacOSX either but I can confirm happens in Safari. I suspect this is due to some aggressive browser caching by Safari (the back button returns to the _exact_ state of the previous page).

This is something I've added to our list of issues to look into but currently it's lower priority in relation to other issues we have.

**Comment by thexpand** [comment]
I wrote in another GitHub issue, but I will write it here as well. This issue seems to be still happening. On mobile, try opening a product, add it to the cart with AJAX, then go back (using the back button) to the category or landing page from where you opened the product. The cart quantity is not updated, and neither is the cart itself. Even the whole widget is empty - an empty cart widget.

I tested it out on an Android device on Chrome. A website of a client has this problem. I checked the website of the OP @Shazgu and it has the exact same problem. Clearly, not solved. Why is this issue closed?
