### ISSUE TITLE
Dynamic Pricing not working

### ISSUE THREAD

**Issue by dweuste** [woocommerce/woocommerce-gutenberg-products-block#3197]
## What do you think is missing from the Cart & Checkout blocks?

The price changes in dynamic pricing are not working at the end of checkout when using the cart and checkout blocks. In attempting to test it, I'm seeing the right price markdowns, but when we receive the orders, customers have been charged full price.

**Comment by nerrad** [comment]
Hi there @dweuste 👋 !

Thanks for taking time to add some feedback. To clarify are you referring to this [dynamic pricing extension](https://woocommerce.com/products/dynamic-pricing/)?

If so, there are a number of extensions that are not yet compatible with the Cart and Checkout blocks and we're in the process of adding extensibility for extension developers to be able to integrate. 

I'm closing this issue only because we only keep issues open that have direct actionable things for us to work on, while feedback issues like yours we close and keep track of via labels and our internal tracking of requests like yours (so it's still noted). Feel free to add any additional details (or confirm my question above) as a comment on the issue if you have more to add. You can still do that even with the issue closed.

Thanks again!

**Comment by dweuste** [comment]
Yes - that's the Dynamic Pricing extension that isn't working with the new Cart & Checkout Blocks.
