### ISSUE TITLE
My thoughts of the cart & checkout blocks

### ISSUE THREAD

**Issue by completegraphics** [woocommerce/woocommerce-gutenberg-products-block#3209]

**Comment by nerrad** [comment]
HI there @completegraphics  👋🏻

Thanks so much for taking the time to leave some feedback - much appreciated! We make note of all feedback we receive and we also close issues with the feedback as active issues are used for bugs or feature/enhancements. Closing the issue does not mean that we don't note or review the feedback. Closed issues can also still be commented on.

We are working on adding extensibility points so that there's a clear path for other extensions or custom code to integrate with the new blocks. Regarding custom payment gateways, there _is_ [an extensibility API for payment methods](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) that might be of use to you if you have custom payment methods. If there's something missing with that API including what is specifically missing as a comment on this issue will be helpful for us as we continue to iterate on the extensibility for the blocks.

You can also follow along with the [status of the Cart and Checkout Blocks in this doc](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).
