### ISSUE TITLE
Move feature flag/gating system into a service class

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3211]
## Is your feature request related to a problem? Please describe.
We have a feature flag system for controlling what blocks and features are available in different builds – woo core package | feature plugin | dev build.

Our PHPUnit integration tests can't easily test different states of the feature flag right now – it's effectively hard-coded. It would be useful if we could control the state of the flag for our tests so we can test all variations of behaviour.

## Describe the solution you'd like
Refactor feature gating into mockable service class:

- Create a service class dedicated to feature gating and include that as a dependency injected in Automattic\WooCommerce\Blocks\Domain\Package. That way tests can mock the feature gating class as needed.
- The above would also keep all the logic contained for any changes we need to make when it comes to how we dynamically switch the phase on demand as needed.

Spun off from @nerrad comment here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2851#discussion_r496689445

## Describe alternatives you've considered
We could potentially control this as part of the test environment setup. For example, run a test pass for each value of the flag. Note that this would require tests to be aware of the value of the flag, and skip / tweak assertions as necessary.

**Comment by nerrad** [comment]
To be clear, I don't think this needs done explicitly for easier phpunit tests. I think it also decouples the feature flag system from being hardcoded in the bootstrap process and allows for the logic related to feature gating to be contained within it's own class. I'd also like to get away from using a PHP constant because this creates complications for programmatically/dynamically adjusting this flag on the fly (you can only define a PHP constant once in memory).
