### ISSUE TITLE
Create drag and drop custom order by method for Hand-Picked Products Block

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#324]
**Placeholder issue**

Per user feedback in the .org form, and discussions amongst the design team - Create a drag and drop order method to arrange products in the Hand-Picked Products block

**Comment by ryelle** [comment]
Just a reminder to keep slighted keyboard-only users in mind when designing this interaction– [this article](https://medium.com/@chrisjagers/keyboard-accessibility-for-reordering-items-ae5b50c6ada1) has a good example of a keyboard-accessible flow– each item needs a focus state, a "selected" state, and there needs to be some communication about how to move the items around (since we're a grid, we can probably go all 4 directions).

If the above it taken into account, it should also be easier to make it usable by screen-readers.

**Comment by jameskoster** [comment]
Is this something that we might contribute back to core in some way first? I'm thinking that other blocks might want to utilise a drag and drop interface in the future. Would it be possible to add some features to core that would help devs create a consistent drag/drop experience in their blocks?

**Comment by nerrad** [comment]
This isn't something that will be done with existing blocks. Eventually, it's likely the existing hand picked products block will be converted to using Product element blocks (as inner blocks) for rendering the content and it'll make sense at that point to introduce some sort of drag and drop reordering of products.
