### ISSUE TITLE
Integration Tracking (WC Subscriptions): Show Shipping selector when checking out multiple subscriptions and persist those values

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3241]
The second part of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3240

When you check out multiple subscription products with different billing schedules, you will create a subscription for each one of them, each with its own shipping method.
On the checkout, you can select which shipping method you will assign to each subscription, we should add this.

![image](https://user-images.githubusercontent.com/6165348/95110342-c8e45380-0735-11eb-8fde-a9f1a74aa2ec.png)

This has some design implications because we show shipping methods in a different part of the checkout block than what we have in the classic checkout.

**Comment by mikejolley** [comment]
If we use the existing shipping area, assuming subscriptions uses shipping packages we might get this for free.

**Comment by senadir** [comment]
I'm not yet sure how they do multiple shipping.
cc @james-allan Can you give us a quick overview of how WCS handles future shipping for multiple subscriptions?
- Are you doing some custom radio buttons or is some part of WC Core that you extend?
- How are you sending them to the server? is it via a custom ajax or as part of posted_meta.
- How do you save and process those values? is it part of  `WC_Subscriptions_Checkout::process_checkout`?

**Comment by james-allan** [comment]
> Can you give us a quick overview of how WCS handles future shipping for multiple subscriptions?

haha I'm not sure if a quick overview exists but I'll give it a shot. 

So when you have multiple subscriptions in your cart, if there is more than 1 shipping option and the shipping packages for those recurring carts differ to the packages in the standard cart (initial purchase cart), then the shipping options will be displayed for that recurring cart. 

I think the easiest way to explain this might be with screenshots of various setups. This isn't an exhaustive list of all options. 

1. **Multiple subscriptions with the same billing terms.** No options displayed - both products are grouped and so share the same package. When you choose an option at the top, that will also affect the chosen method down in the recurring cart section. https://d.pr/i/fyDRd2
2. **Multiple subscriptions with different billing terms (eg. 1 weekly, 1 monthly).** Because the initial cart package contains both products, and each subscription only contains 1 of the products each, then the customer has the option to choose a method for each. https://d.pr/i/qyUrL4. _Note: I'm not 100% sure that's working as intended though because I thought both recurring carts would inherit the initial cart's method given the options are the same. I'd have to check on that though._ 
3. **Multiple subscriptions with different terms and available package rates.**
     - **Two yearly subscriptions but 1 with a free trial.** The customer can choose a different shipping method for the trial but not the other yearly product. This is because the initial cart shipping packages doesn't technically doesn't contain the trial product. So the standard yearly subscription matches the initial cart packages and the trial product doesn't. Very complicated. https://d.pr/i/qyUrL4. 
     - **1 weekly and 1 yearly subscription where free shipping is only available to orders greater than $60.** The initial cart will be eligible for free shipping but only the recurring carts which have recurring totals > $60 will be eligible. https://d.pr/i/Mas556. In this example, the initial cart is $150, one of the recurring products is only $50 so is forced into the flat-rate option and the other recurring total is $100 so is eligible and so has the choice of both.


-----

> Are you doing some custom radio buttons or is some part of WC Core that you extend?

We're using our own templates. The template can be found here: https://github.com/woocommerce/woocommerce-subscriptions/blob/3.0.10/templates/cart/cart-recurring-shipping.php#L16

The logic that determines if the options or a static shipping amount is displayed is `wcs_cart_totals_shipping_html()`. 

> How are you sending them to the server? is it via a custom ajax or as part of posted_meta.

Yes, I believe it is updated via ajax and it uses the functions from WC core. 

- ajax request - https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/cart.js#L190-L218
- handling function - https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L243-L260. This function stores the chosen method in the session. We use the recurring cart key as the array index. 

For example the output of the `chosen_shipping_methods` session value would be like this:

```
Array
(
    [0] => free_shipping:3
    [2021_11_24_yearly_0] => flat_rate:11
    [2020_12_01_weekly_0] => flat_rate:11
)
```

> How do you save and process those values? is it part of WC_Subscriptions_Checkout::process_checkout?

Yep it all flows from that `WC_Subscriptions_Checkout::process_checkout()` function. 

It calls `WC_Subscriptions_Checkout::create_subscription()` for all recurring carts.
That adds the chosen shipping to the subscription method by calling `WC_Subscriptions_Checkout::add_shipping()`
Inside that function it pulls the chosen shipping method out and creates the shipping line items.

**Comment by mikejolley** [comment]
@senadir I'm not sure if Ill be able to solve this issue, but I'll start looking into how this is exposed to the cart.

**Comment by senadir** [comment]
One useful information I can give you is that WCS creates several carts for each subscription and those packages might be able to hold the shipping info.

**Comment by mikejolley** [comment]
For my reference:

- https://www.figma.com/file/n90hX6hG3wwQbYwsYsrJnj/Gutenberg-based-cart-%26-checkout?node-id=5036%3A0
- https://www.figma.com/file/n90hX6hG3wwQbYwsYsrJnj/Gutenberg-based-cart-%26-checkout?node-id=4862%3A7236

I've made some progress (merging the recurring shipping packages with main cart packages before serving the API response) but I'm struggling with how Subscriptions calls `reset_shipping()` everywhere—this is causing selections (via the API) to be lost. I might need to pick your brains @james-allan next week if I cannot progress.
