### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: #/ 

### ISSUE THREAD

**Issue by tiagonoronha** [woocommerce/woocommerce-gutenberg-products-block#327]
@ryelle A user reported this issue and while I cannot replicate it, it seems that someone else also reported it in the WordPress.org forums: https://wordpress.org/support/topic/uncaught-error-syntax-error-unrecognized-expression-4/

It's probably worth a look.

```
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 Uncaught Error: Syntax error, unrecognized expression: #/ 
at Function.fa.error (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at fa.tokenize (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at fa.compile (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at fa.select (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at fa (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at Function.fa.matches (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at Function.n.filter (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at z (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at a.fn.init.filter (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2) 
at o.goToSettingsTab (admin.min.js:2) 
fa.error @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
fa.tokenize @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
fa.compile @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
fa.select @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
fa @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
fa.matches @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
n.filter @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
z @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
filter @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
goToSettingsTab @ admin.min.js:2 
function.n.(anonymous function) @ admin.min.js:2 
goToSettingsTabFromHash @ admin.min.js:2 
function.n.(anonymous function) @ admin.min.js:2 
onInit @ admin.min.js:2 
function.n.(anonymous function) @ admin.min.js:2 
trigger @ admin.min.js:2 
function.n.(anonymous function) @ admin.min.js:2 
i @ admin.min.js:2 
o @ admin.min.js:2 
o @ admin.min.js:2 
(anonymous) @ admin.min.js:2 
i @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
fireWith @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
ready @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2 
K @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:2
```

1718337-zen

**Comment by ryelle** [comment]
This might be an issue with wc-admin, not the blocks plugin. We don't add `#/` but that plugin does – @timmyc ?

**Comment by ryelle** [comment]
There was more context in slack, that this happens when a post is edited. I can replicate the `#/` being added to the URL when editing a post with the blocks plugin active. I'm still thinking it comes from wc-admin, via the components package.

**Comment by ryelle** [comment]
This probably comes from [this call to `createHashHistory`](https://github.com/woocommerce/wc-admin/blob/master/packages/navigation/src/history.js#L9) which is pulled in via the components package (because components use navigation and the navigation helpers like `stringifyQuery`.

We could look at remove the use of `@woocommerce/components`, as currently we're only pulling in the Tag component, which would also save us from importing all of react-world-flags https://github.com/woocommerce/wc-admin/issues/1275 

Or, a better solution maybe, would be to not initialize `createHashHistory` in the package.

**Comment by jeffstieler** [comment]
+1 to not initializing `createHashHistory()` in the package. I think importing just the `Tag` component is a good thing to try as well.

**Comment by ryelle** [comment]
I should have pointed out the difficult part of "just not using createHashHistory"– we use the history to navigate pages in the components. For example - the filters use `getQuery` and `updateQueryString`, and Charts and Table use `updateQueryString`. If we don't initialize history in the navigation package, I think those would end up with a different history. Or we could have the functions that use history to accept `history` as a function parameter? 

> I think importing just the Tag component is a good thing to try as well.

We can do that once wc-admin is merged, pull it from `wc.components.Tag`, but currently the entire package is published as one. Trying to do `import { Tag } from '@woocommerce/components/src/Tag';` triggers a SyntaxError in the build process.

**Comment by ryelle** [comment]
Okay, there are two things in this issue:

1. `wc-admin` needs to change how `createHashHistory` happens, and there's an issue for that now https://github.com/woocommerce/wc-admin/issues/1433
2. We should look into importing only specific components from woo/components (especially since `wc.components` won't be available when this merges into WC core)

We won't worry about changing wc-admin from this issue, that'll be in 1433 above. For this project, let's see if just importing specific components can avoid the `createHashHistory` issue.
