### ISSUE TITLE
file_exists(): open_basedir restriction in effect 

### ISSUE THREAD

**Issue by jd4u** [woocommerce/woocommerce-gutenberg-products-block#3317]
## Describe the bug
file_exists(): open_basedir restriction in effect. File(/vendor/composer/jetpack_autoload_classmap.php) is not within the allowed path(s): (D:\www\customerDomain\)

## To reproduce
Windows Server with PHP 7.3 having open_basedir setup will create the issue with logging lots of errors in debug.log

## Expected behavior
while checking the file using file_exists provide absolute path instead of relative path.

### WordPress (please complete the following information):
* Core version: 5.5.1
* Gutenberg version (if installed): --
* WooCommerce version: 4.6.1
* WooCommerce Blocks version: 3.6.0 
* Site language: en-GB
* Any other plugins installed:

**Comment by jd4u** [comment]
Log from Debug.log file

PHP Warning:  file_exists(): open_basedir restriction in effect. File(/vendor/composer/jetpack_autoload_classmap.php) is not within the allowed path(s): (D:\www\customerDomain\) in D:\www\customerDomain\public_html\wp-content\plugins\woo-gutenberg-products-block\vendor\class-autoloader-handler.php on line 70

**Comment by senadir** [comment]
@nerrad I'm sturggling to understand this issue, is a relative path issue related to our code or an issue with [jetpack autoloader](https://github.com/Automattic/jetpack-autoloader). I'm not sure I can reproduce this, but based on the logs you provided @jd4u, I'd say it's a jetpack-autoloader thing.
So if it's a jetpack-autoloader issue, I will go ahead and move it there.

**Comment by nerrad** [comment]
Based on various results I see from searching this error on the internet it's looking to me like this is a configuration issue in the environment for `open_basedir` configuration in the php.ini file (see [this stack overflow thread for instance](https://stackoverflow.com/questions/23973368/php-open-basedir-error)).

Based on the above @jd4u, I'm going to close this issue because this is not something we can address in our repository as it looks like its a configuration issue with your environment.
