### ISSUE TITLE
Improve order of steps in mobile view of Cart Block

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-gutenberg-products-block#3352]
I like the new block!

What I see now are this parts:

1. Summary
2. Address
3. Shipping
4. Payments

Important is part Summary on top which is not in best place, because if customer changes shipping which results in different summary and may not been seen because out of view on smaller screens. At if customer submits order, customer should see summary right on top of button.

**Comment by nerrad** [comment]
Hi Adrian. Thanks for taking the time to leave some feedback.

Would you be able to share a screenshot pointing out what you are referring to please? Since various themes and viewports can affect the layout of the blocks, having a screenshot ensures we're on the same page regarding your feedback. Also to clarify, you're talking about the Cart block right?

**Comment by ajgw** [comment]
Hi @nerrad,
I am talking about cart block, right. I case of themes involved how blocks are rendered, I tried Storefront and Seedled themes. But equal which theme, if I view on mobile order summary is first part. Below I see address, shipping and so on. If I scroll down on mobile to shipping and select one and this effects summary, it is not viewable because off screen on top and anyone scrolls back top.  

A summary just before placing order button should be better.

**Comment by ajgw** [comment]
I like to mention: There is a bit unlogic in WC and so in cart block from customer view in case of Local pickup:

If customer selects Local pickup, why should customer give store his address and following that, labeling of parts and fields incl. descriptions of fields for address do not match Local pickup.

Why?

We ask customer now by default about his shipping address which we do not need if Local pickup is selected:

![Bildschirmfoto 2020-11-01 um 09 37 55](https://user-images.githubusercontent.com/3390880/97798595-c5a29180-1c27-11eb-8015-ecd383dcdca6.png)

**Comment by nerrad** [comment]
Adrian it's helpful if you avoid mixing different topics into the same issue. 

I will bring up your point about the shipping address to the team, however we're unlikely to change the behaviour because shipping method options _can_ be tied to geographical area. So the shipping address still needs entered to determine what shipping options to show (which may or may not include Local pickup - depending on how the store is configured).

If you have some additional comments related to the shipping, open a new issue dedicated to it and we can continue the conversation there.

**Comment by garymurray** [comment]
Thanks for the feedback @ajgw 

We'll add your suggestion to our list of potential future improvements we can make to the mobile view of the checkout block.

I have opened your other [comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3352#issuecomment-720055800) as a separate issue [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3677).

**Comment by nerrad** [comment]
As Gary mentioned we're tracking the feedback separately and created an issue for the other comment so I'm going to close this issue. Thanks again for taking the time to leave this feedback!
