### ISSUE TITLE
Can we make checkout page look exactly like shopify ?

### ISSUE THREAD

**Issue by theGreaterBayArea** [woocommerce/woocommerce-gutenberg-products-block#3353]
Can we make checkout page look exactly like shopify ?

**Comment by Aljullu** [comment]
Hi @vpsvpnvip, thanks for testing WooCommerce Blocks. The new design for the Checkout flow was developed with best ecommerce practices in mind in order to increase conversion and make it perform better on small devices like smartphones as well as desktop computers. If you have a suggestion of a specific item that you would like to see being changed and you can provide some rationale for the change, we would appreciate your feedback.

Notice a lot of work we did towards the Checkout block can benefit other extensions if they want to create different Checkout blocks with completely different layouts.

For now, I will proceed closing this issue, feel free to answer or open new issues if you have more specific feedback on particular items.
