### ISSUE TITLE
Additional form Fields

### ISSUE THREAD

**Issue by iturrixe** [woocommerce/woocommerce-gutenberg-products-block#3355]
Hello woocommerce blocks Team!
## What do you like about the Cart & Checkout blocks?
I really like its simplicity. I see a huge improvement. It's awesome.

## What do you think is missing from the Cart & Checkout blocks?
I think that It is missing some fields like Company Tax Number field. As well as customers Identity card Number. I think that in EU countries, It's mandatory to use them. I don't know in all EU countries but in Spain it is. It would be nice to have more options to add new form fields.
Maybe It's possible to add that kind of fields but I haven't found them yet or I don't know how to do it.
Thank you,
Sincerely,

Ion

**Comment by nerrad** [comment]
Thanks @iturrixe for taking the time to leave some feedback, it's much appreciated!

You're suggestion about including additional fields for the Checkout Block is noted and is something on our radar to implement in future iterations as we work on integrating various WooCommerce extensions. Since your requests here will be covered by that work I'm going to close this issue.

Please note that closing the issue does not mean we haven't noted your request.
