### ISSUE TITLE
PayPal is missing on the Payment method section

### ISSUE THREAD

**Issue by NaoufelTarchoul** [woocommerce/woocommerce-gutenberg-products-block#3357]
## What do you like about the Cart & Checkout blocks?
The style and design. 

## What do you think is missing from the Cart & Checkout blocks?

PayPal is what missing. When I activate Cart & Checkout blocks it disappears. It works fine on my theme's checkout, but not on yours. PayPal is a real player when it comes to payments online. You can't just ignore it. You gotta fix it as soon as possible.

**Comment by nerrad** [comment]
Hi there @naoufel-ui 👋,

Thanks for taking the time to leave some feedback!

Currently Paypal Standard is the only Paypal payment method supported by the Cart and Checkout blocks but it is on our roadmap to add support for the [Paypal Payments extension](https://woocommerce.com/products/woocommerce-paypal-payments/) sometime in the first quarter 2021. You can [bookmark this doc](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) as the source for up to date information about what the Cart and Checkout blocks support (we're keeping it up to date with changes as they are released in the feature plugin).

Since this is already something on our roadmap I'm going to close this issue but please don't take that as a signal we haven't noted your feedback.
