### ISSUE TITLE
Update the translation file with the latest JS strings

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/woocommerce-gutenberg-products-block#336]
Update the translation file with the latest JS strings

Noted in the support forums: https://wordpress.org/support/topic/translation-of-blocks-interface/

**Comment by ryelle** [comment]
According to [this ticket,](https://meta.trac.wordpress.org/ticket/3876) it seems like language packs aren't including the JS translations yet. I can bundle in the Danish and French translations for 1.3.1, those are the only two at 100%.

We should also be pushing our release to the wp.org repo earlier/more often to allow translators time to translate the "in development" strings. We can push alpha/beta/RC releases to `trunk`, then push the final version and tag it. It might make for a smoother release flow in any case.

**Comment by timwhitlock** [comment]
Thanks for looking at this. It's certainly the job of GlotPress to generate the JSON files and I know that's not quote ready yet.  

In lieu of this, I've been experimenting with generating my own JSONs but your plugin won't load them because the [wp_set_script_translations call in 1.3.0](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/v1.3.0/woocommerce-gutenberg-products-block.php#L247) is redundant. (note that `WP_Scripts::set_translations` returns false because the `'woocommerce-block'` handle isn't a registered script). As you say, the call must be made against each registered script.
