### ISSUE TITLE
embed paypal express checkout button block  in the first line(in front of woocommerce-gutenberg-products-block) of the checkout page , failed with show up in the lower left footer , why ? ?

### ISSUE THREAD

**Issue by theGreaterBayArea** [woocommerce/woocommerce-gutenberg-products-block#3374]
## Is your feature request related to a problem? Please describe.
A embed paypal express checkout button block  in the first line(in front of woocommerce-gutenberg-products-block) of the checkout page , failed with show up in the lower left footer of the checkout page , why ? ?

## Describe the solution you'd like
i need  paypal express checkout button block  in the first line(in front of woocommerce-gutenberg-products-block)
## Describe alternatives you've considered
![shopify-checkout](https://user-images.githubusercontent.com/5503064/98195387-99a34b00-1f5c-11eb-8f0a-9e569cb25194.jpg)

## Additional context

![backend](https://user-images.githubusercontent.com/5503064/98195403-a3c54980-1f5c-11eb-80f7-fd50ab0bcba2.png)
![frontend](https://user-images.githubusercontent.com/5503064/98195405-a6c03a00-1f5c-11eb-8494-3c25b83757f8.png)

**Comment by Aljullu** [comment]
Hi @vpsvpnvip, thanks for opening this issue. Could you provide us some more information in order to help us diagnose what might be the issue? We are specially interested in:

* What PayPal extension are you using and what version?
* What theme are you using and what version?
* What version of WooCommerce and WordPress do you have installed?

Notice, if there are some updates available for any of those products, I would recommend updating first in order to check whether the issue has already been fixed.

Thank you in advance.

**Comment by theGreaterBayArea** [comment]
**What PayPal extension are you using and what version?**
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout
Version: 2.1.0

**What theme are you using and what version?**
avada
V7.0.2

**What version of WooCommerce and WordPress do you have installed?**


WordPress environment
--
WordPress address (URL): |   | https://juicytoyz.com
Site address (URL): |   | https://juicytoyz.com
WooCommerce version: |   | 4.6.1
WooCommerce REST API package: |   | 4.6.1 /home/customer/www/juicytoyz.com/public_html/wp-content/plugins/woocommerce/includes
WooCommerce Blocks package: |   | 3.7.0 /home/customer/www/juicytoyz.com/public_html/wp-content/plugins/woo-gutenberg-products-block/
Action Scheduler package: |   | 3.1.6 /home/customer/www/juicytoyz.com/public_html/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler
WooCommerce Admin package: |   | 1.6.2 /home/customer/www/juicytoyz.com/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin
Log directory writable: |   | /home/customer/www/juicytoyz.com/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.5.3
WordPress multisite: |   | –
WordPress memory limit: |   | 4 GB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

**Comment by Aljullu** [comment]
Thanks for coming back with some more details @vpsvpnvip. I have been investigating this a little bit more: it looks like [PayPal Checkout](https://woocommerce.com/products/woocommerce-gateway-paypal-checkout/) doesn't support the Cart and Checkout blocks yet. It's on our radar but unfortunately I can't tell you an exact date when support will be added. You can read more about the currently supported payment methods in this documentation page:

https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/

I see you are using an HTML block as a work-around. Unfortunately, I can't provide support on that path since that's not something we support, so my suggestion would be to stick to the Cart/Checkout shortcodes for now or to use a payment method from the [list of supported ones](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/#section-2).

I will proceed closing this issue since PayPal Checkout is already on our radar. If you want, you can follow issue #2322 about adding PayPal Express support.

**Comment by theGreaterBayArea** [comment]
Can I have stripe express checkout button(apple pay , google pay) on the desktop in the first line of the check out page

**Comment by Aljullu** [comment]
Yes, that's where they should appear if you install the Stripe payment gateway. :slightly_smiling_face:
