### ISSUE TITLE
thank you hahaha

### ISSUE THREAD

**Issue by cardones** [woocommerce/woocommerce-gutenberg-products-block#3386]

**Comment by method7** [comment]
We like the much improved UX but there are still issues several issues we need to deal with. We are struggling to track users through the checkout - it seems that stripe is using inputs in a  iframe. - we haven't looked at paypal yet but tracking these workflows to the end is critical. It does baffle me that UX, accessibility and tracking are the last priority in software development.

**Comment by nerrad** [comment]
Hi @method7 

Thanks for leaving your feedback on the Cart and Checkout Blocks. Keep in mind they are still in preview, that's why we have them only available in the WooCommerce Blocks feature plugin for merchants to start trying them out and to give feedback while we continue to work on them. We do realize that not all functionality some stores and merchants need will be present.

> We are struggling to track users through the checkout 

I'm assuming you are using something like Google Analytics or some other tracking software for this? It is on our roadmap to ensure there is clear integration paths for analytics/commerce tracking software (or documentation on how to implement existing solutions).

> it seems that stripe is using inputs in a iframe.

We're using the recommended way for Stripe to be implemented using Stripe elements which is something provided by their API (and yes they use iFrames via their apis).

Also, I was about to close this issue based on the title and original comment but it looks like you aren't the original poster? In the future any feedback you have is very welcome but it'd be best to create a new issue so it doesn't get missed.

I'm going to close this issue for now, but you can feel free to respond to this comment. We have heard you but there's nothing actionable on this issue at the moment which is why it's being closed.

**Comment by method7** [comment]
hi @nerrad I appreciate your reply, thank you. We are using GTM to track users through the entire journey but we are not getting very good data form the payment options they choose - paypal / stripe so we have no idea what users are doing before they abandon. all we need to know is user interaction with fields - change events on card number, exp-date and ccv. i will start a new thread.
