### ISSUE TITLE
Customizable Place Order Button for checkout block

### ISSUE THREAD

**Issue by benecia1111** [woocommerce/woocommerce-gutenberg-products-block#3397]
## What do you think is missing from the Cart & Checkout blocks?
The ability to change the color of the "Place Order" button on the Checkout page - so that it can match the theme style of my website. I imagine this can be done with custom CSS - but I have no knowledge of how to do that, etc. Since you can change the color background of any button created, I would think this would also be a simple fix.
Alternatively, if you could send me the Custom Css to change the background color of the button to #006CFF with White Text Color - I would be extremely grateful !

**Comment by nerrad** [comment]
Hi there @benecia1111,

Thanks for taking time to leave your feedback!

You can find information on [how to customize the checkout button styles here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/theming/cart-and-checkout.md).

Beyond that, this isn't the type of support request we handle in this context. I'm going to close this issue since there's nothing actionable for us to take related to the cart and checkout blocks at the moment but your request has been heard and having the ability to customize the colors of the button in the block is something that we may consider for future iterations.
