### ISSUE TITLE
Ability to add custom fields to checkout (CPF field)

### ISSUE THREAD

**Issue by marcelxv** [woocommerce/woocommerce-gutenberg-products-block#3398]
hello, I develop stores and I'm really excited about Woo Blocks! congratulations to everyone for what has been achieved so far!

Here in Brazil we have an obligation to capture the buyer's identity document, so we need to add a new field to the standards on the checkout page, something like a form:

<p class = "form-row form-row-wide person-type-field validate-required" id = "billing_cpf_field" data-priority = "23" style = "display: block;"> <label for = "billing_cpf" class = ""> CPF & nbsp; <span class = "optional"> (optional) </span> <abbr class = "required" title = "required"> * </abbr> </label> <span class = "woocommerce -input-wrapper "> <input type =" tel "class =" input-text "name =" billing_cpf "id =" billing_cpf "placeholder =" "value =" "> </span> </p>

There is some way to enter these form fields manually (via HTML or functions.php) on the checkout page built in Woo Blocks.

**Comment by senadir** [comment]
Hello @marcelxv
Thank you for your kinds words!

Unforuntantly, we don't have the ability to add extra fields yet, we're still laying out integration interfaces for our plugin.

Adding and changing fields is something we're planning on working on.

In the meantime, I'm going to close this issue because we use issues to track active work. Closing an issue doesn't mean we're disregarding your feedback, and you can still comment on it if you want.
