### ISSUE TITLE
Mini Cart Block

### ISSUE THREAD

**Issue by scruffian** [woocommerce/woocommerce-gutenberg-products-block#3435]
When Full Site Editing launches, themes will be built from blocks. In order to support a Woo Cart in the navigation we'll need a Mini Cart block, so that users with WooCommerce sites can include the Cart in the menu.

The block will need to render `woocommerce_mini_cart()`.

**Comment by senadir** [comment]
using woocommerce_mini_cart is a workaround solution.
If we're going to build an actual mini-cart block, it should work on top of our new StoreAPI.
Currently, Full site editing plans are put on pause while we work on Cart and Checkout.

**Comment by chvillanuevap** [comment]
+1
I'm building a site using FSE, and I'm using a shortcode as a workaround for the lack of a Cart block for navigation.

**Comment by nerrad** [comment]
Work is in progress on the mini cart block via a number of different issues. You can see the related epic here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4138

**Comment by davidhealey** [comment]
The mini cart block in its current state doesn't show in the cart and checkout pages. I can understand it not showing on the cart page, but on the checkout page it is needed so that the user can return to the cart page if they want to.

At the moment the only way to get back to the cart is to press the browser's back button (assuming they have come from the cart) or to navigate to another page and then open the cart again.
