### ISSUE TITLE
Google Pay shows a generic error message for purchases of small amounts over 0,30£

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3437]
## To reproduce
In a store with the Stripe payment gateway installed and express payment methods enabled.

1. Create a product with a price of 0,18£.
1. Add two of them to your cart.
1. Go to the Checkout page that has the Checkout block.
2. Try to pay with Google Pay.
6. Notice payment fails with a generic message.
<img src="https://user-images.githubusercontent.com/3616980/99829105-27d22080-2b5c-11eb-83cf-d6ae941128aa.png" width="385" alt="Image showing the error"/>

## Expected behavior
It should show a message that clearly states why the purchase failed. When the order total is below 0,30£, it states the minimum is 0,30£. However, it fails with 0,32£ and 0,36£ too and the error message is a generic one.

**Comment by nerrad** [comment]
@mikejolley recently merged #3424 which exposed the cart totals to payment methods `canMakePayment` callbacks and it looks like that was implemented for Stripe Payment Method (cc) but not Stripe Payment Request (express payment methods).

However, it also appears there is something awry with the totals that are close to the min value - that aspect might be a new issue.

**Comment by opr** [comment]
I've just tested this on a fresh site, and it worked fine for me when using Google Pay.
- Added two items with a price of £0.18 to my cart, making the total £0.36
- Went to the checkout block and used the express payment method for Google Pay.
- Selected my shipping address and free shipping rate.
- Selected my Google pay account as the payment method.
- Successful checkout

 However, using my debit card (rather than my Google pay account) gave me a "Card declined" error. Not a generic one like the issue shows. 

<img src="https://user-images.githubusercontent.com/5656702/100639772-83a36300-332d-11eb-9731-624f203fc9b9.png" width="400" />


### Device info
Device: Google Pixel 2 XL
Android version: Android 11.

**Comment by Aljullu** [comment]
I spent some more time debugging this, these were my findings:

* I could reproduce the issue in a fresh install with WC 4.7.1, WC Blocks `trunk` and Stripe Gateway 4.5.5.
* When I changed the currency from Pound sterling to Euro or USD I got a clear error message stating that the minimum amount is `€0.50` or `$0.50`.
* I tested with the Cart shortcode and I could reproduce the issue as well.

Given that, I don't think this bug is specific to WooCommerce Blocks, so I will close it.
