### ISSUE TITLE
Block preview shows HTML markup in product title

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce-gutenberg-products-block#347]
**Describe the bug**
Products titles with HTML markup (i.e. `<small>` or `<em>` or `<br>`, etc...) - this markup should be escaped in the back-end preview.

As it presently is, the HTML markup is displayed in the back-end (bug), but not displayed in the front-end (correct).

**Comment by ryelle** [comment]
Hi @GlennMartin1 – I'm not sure if this is considered a bug, since the HTML is also not rendered in the core product list:

<img width="341" alt="screen shot 2019-01-17 at 4 01 57 pm" src="https://user-images.githubusercontent.com/541093/51348663-44d5ce00-1a71-11e9-899b-3fbc6b81ce3d.png">

@LevinMedia @jameskoster What do you think? The issue is that the preview in the editor escapes the HTML, so the preview appears like this

<img width="208" alt="screen shot 2019-01-17 at 4 03 43 pm" src="https://user-images.githubusercontent.com/541093/51348766-7a7ab700-1a71-11e9-9c1e-4743eb692517.png">

but when rendered on the frontend, the HTML is rendered, so the title has some bold

<img width="235" alt="screen shot 2019-01-17 at 4 02 36 pm" src="https://user-images.githubusercontent.com/541093/51348747-7484d600-1a71-11e9-84ae-9893ecfe4cc3.png">

This is also not a bug specific to 1.3.1, I can replicate it back to 1.2.0.

**Comment by LevinMedia** [comment]
Today I learned you can add HTML to a product title! 

@ryelle I think this differs slightly from the core product list, in that Gutenberg is trying to give you the most accurate representation of what you'll get on the front end of the site as you're editing. I think if it's not too much trouble, it would be nice to make the editor view as 1 to 1 with the published page as possible.
