### ISSUE TITLE
Enhancement: compatibility with WC Powerpack...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce-gutenberg-products-block#348]
**Describe the bug**
The block preview does not respect the preferences set in WooCommerce's Powerpack (https://woocommerce.com/products/storefront-powerpack/).

For example, in Powerpack, you can toggle the display of certain elements, etc:
![powerpack](https://user-images.githubusercontent.com/30901407/51349416-4c967200-1a73-11e9-82a1-fdb9579c1350.jpg)

Those options are not respected in the block preview.
(for example, uncheck to display the "Add to Cart"; it will remain displayed in the preview).

Being an official WooCommerce plugin, I'd assume compatibility with Powerpack.

**Comment by jameskoster** [comment]
Since WooCommerce Blocks will be doing in to core, this might be something for @tiagonoronha to add to Powerpack?

**Comment by ryelle** [comment]
Since the powerpack settings are specifically about the shop page, and don't currently apply to shortcodes inserted into posts, I actually think this isn't something we need to worry about (until we eventually look at shop templates, I suppose). I'm going to close this issue for now, but we'll keep it in mind when thinking about the extendability of shop building 👍
