### ISSUE TITLE
All Products Block does not use woocommerce_blocks_product_grid_item_html filter / Make all product loop based blocks have a consistent filter for customisation

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce-gutenberg-products-block#3483]
## Describe the bug
All Products block does not appear to run through a filter such as the woocommerce_blocks_product_grid_item_html whereas (as an example) the Best Selling Products block does.

Also just a note that I have read through this: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891 and a bunch of PRs/issues raised related to this and I'm unsure on where this is going/where it has got to currently. Is the All Products Block to replace all other product related blocks in future (and that will include options for best sellers, etc, etc)? If so what is the latest info on customising the markup (e.g. adding some text that appears on all products output by this block)?

## To reproduce

Add an All Products block and a Best Selling Products block to a page

Add this code to your theme's functions.php:

function test2( $html, $data, $product ) {
	return 'woocommerce_blocks_product_grid_item_html is being used';
}
add_filter( 'woocommerce_blocks_product_grid_item_html', 'test2', 10, 3 );

On the page you will see the All Products block does not use this but Best Selling Products does.

## Expected behavior

All WooCommerce product loop style blocks run through a filter to allow customisation consistently across product display via blocks.

### WordPress (please complete the following information):
* Core version: 5.5.3
* Gutenberg version (if installed): WP version
* WooCommerce version: 4.6.0

**Comment by Aljullu** [comment]
Hi @ninetyninew, you're right, the All Products block is different from other product loop blocks because it allows the merchant to edit its contents directly in the Gutenberg editor (using the pencil icon that appears in the toolbar on top of the block).

That means that UI-wise and internally, the All Products block is completely different from the other product loop blocks and that means its extensibility options are different too.

All Products block allows registering inner blocks, you can see the API here:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks-registry/block-components/register-block-component.js#L11-L43

This allows merchants to add/replace any inner block they want.

If you need to have several All Products blocks sharing the same layout, I would suggest making the modifications in one of them and saving it as a Reusable block.

![imatge](https://user-images.githubusercontent.com/3616980/100608487-c56fe180-330c-11eb-8b6b-0c23603c85c0.png)

Then, you can use that reusable block in as many pages as you want and any changes you do will be synced across blocks.

For now, I will proceed closing this issue since we have no plans to make the All Products block behave like the other product loop blocks. But if you feel you have something to add to #891 that hasn't been said yet, make sure to report it, so we can take informed future decisions.

**Comment by STV11C** [comment]
Hi @Aljullu , I had the same issue with the one hook available not being available for the _All Products Block_, but I understand that it works differently with the editing of the inner block within the Editor.

The one thing I would like to achieve is at least wrap the content in another `<div>` as the `<li>` is acting as the column as well as the product info container, which is not ideal for layout.

It there a way to insert some HTML before and after the `<li>` ?

If not I would suggest adding one to separate the Column from the product info wrapper.

I look forward to hearing your thoughts. Thanks.

**Comment by Aljullu** [comment]
> It there a way to insert some HTML before and after the `<li>` ?

Unfortunately, this is not possible and we don't have any plans to change the markup of the All Products block in the short term. However, would you mind sharing what you are trying to achieve that is not currently possible? I wonder if using [`::before`](https://developer.mozilla.org/en-US/docs/Web/CSS/::before) or [`::after`](https://developer.mozilla.org/en-US/docs/Web/CSS/::after) pseudo-elements would work in your case given that it's the recommended way to add an ~element~ pseudo-element for stylistic reasons.

**Comment by STV11C** [comment]
Thanks for the reply. What I want to achieve is wrapping all the product elements (Title, Img, Rating, Add To Cart button etc...) inside a div with classes to style it to match the core WooCommerce styling I have implemented. Further, I even want to wrap some of these in another div. Basically I am using a Bootstrap styled Card layout.
```
<div class="card">
  <img />
  <div class="card-body">
    -- some content -- 
  </div>
</div>
```
This way, the current LI (the column) is not affected by the additional styling and used purely to control layout... which is a very common scenario.

I have it all working great with the `woocommerce_blocks_product_grid_item_html` hook on all the another WC Blocks... just not the All Products block.

**Comment by Aljullu** [comment]
Thanks for the details @STV11C! I think your use case would be solved if we allowed adding a Group block inside the All Products block, right? That way you could wrap all elements you want inside a Group block and that would give you an extra `div` to do that kind of styling.

This is something that is in our radar, but not something that will come soon. We are currently investigating how we could leverage the WordPress core Query block to display products, and eventually that might be useful to add more customizability to some of our blocks including the All Products block. However, there are some blockers that will need to be solved first (ie: how can the Query block interact with Product filters blocks? how to change the order/pagination without a page reload?).

**Comment by pablo-sg-pacheco** [comment]
Hi,

Is there any good news about this? It was reported 3 years ago. I'm pretty sure that by now, there should be a way to use a filter like `woocommerce_blocks_product_grid_item_html` for the **All products block**.

Please, let me know

**Comment by Aljullu** [comment]
Hi there, @pablo-sg-pacheco, we are currently working on a new block named [Product Collection](https://github.com/woocommerce/woocommerce-blocks/labels/block%3A%20product%20collection) which will supersede the All Products block.

The main benefit will be performance-wise: it will be server-side rendered but, at the same time, will be dynamic in the frontend, meaning pagination, filtering, add-to-cart, etc. won't require a page reload. That new block will also allow us to centralize how several of our blocks are built, so blocks like Products on Sale, Products by Category, All Products, etc. will all be powered by the new Product Collection block. For that reason, we won't be adding new extensibility points to the All Products block.

However, we are working on making the Product Collection block extensible. Right now, I don't think there is any issue/PR you can track, but that's definitely something in our roadmap. Keep in mind, though, that extensibility in the Product Collection block will likely be different than how it worked in PHP templates, so I don't expect filters like `woocommerce_blocks_product_grid_item_html` to be supported. Instead, extensions might need to use [block hooks](https://make.wordpress.org/core/2023/10/15/introducing-block-hooks-for-dynamic-blocks/) or similar APIs to introduce their own blocks.

**Comment by pablo-sg-pacheco** [comment]
Thanks for the info,

But how are we supposed to add or change the product template on the server-side if it's not going to be a server-side hook like `woocommerce_blocks_product_grid_item_html`?

**Comment by Aljullu** [comment]
> But how are we supposed to add or change the product template on the server-side if it's not going to be a server-side hook like `woocommerce_blocks_product_grid_item_html`?

It really depends on the use case. If the goal is to add new blocks inside the product grid layout, the [Block Hooks API](https://make.wordpress.org/core/2023/10/15/introducing-block-hooks-for-dynamic-blocks/) will cover that. This means a paradigm change in extensibility: instead of filtering the entire markup in order to add a certain element, there is a specific API to add a block at a certain position. This has the benefit that makes it much easier to ensure there are no conflicts between plugins. In the past, it was very common that a plugin might filter the markup that was then used as the entry point for another plugin's filter, which might cause unexpected results.

If, for some reason, that's not enough, Gutenberg has a [`render_block` filter](https://developer.wordpress.org/reference/hooks/render_block/) which allows filtering the markup of all blocks. I would strongly suggest trying Block Hooks before recurring to `render_block`, but I wanted to mention it just in case.
