### ISSUE TITLE
Add Filter for Products data

### ISSUE THREAD

**Issue by anteksiler** [woocommerce/woocommerce-gutenberg-products-block#3495]
## Is your feature request related to a problem? Please describe.
We would like to add custom data to the Products block

## Describe the solution you'd like
Filter the data given here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/f3b2b53435ffbc9ac49215846bad08ce74c7124b/src/BlockTypes/AbstractProductGrid.php#L318

## Describe alternatives you've considered
Using the HTML filter does not work if you want to add, let's say the product category.

**Comment by Aljullu** [comment]
Hi @anteksiler, thanks for opening this issue.

> Using the HTML filter does not work if you want to add, let's say the product category.

Can you clarify what you mean here? The [filter](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/AbstractProductGrid.php#L328-L342) gets the `$product` object, so from there you should be able to extract the category.

**Comment by anteksiler** [comment]
That was just an example, I am sure there is a workaround for that. 

But let's say I want to add a button that depends on a plugin. It would be great to able to add additional data.

**Comment by Aljullu** [comment]
Thanks for following up on this @anteksiler. WooCommerce Blocks are quite different to shortcodes in how they can be extended and we acknowledge there might be some cases where the current approach makes things different. In #891 we have been gathering some feedback from the community and there are some nice code snippets that can be used as an example. I will close this issue for now, since I think the discussion in #891 already encompasses your suggestions here. Hope that sounds good!
