### ISSUE TITLE
HI i can not find the accept the agreement checkbox.. i need it.

### ISSUE THREAD

**Issue by CreativeArtDesign** [woocommerce/woocommerce-gutenberg-products-block#3504]
## What do you like about the Cart & Checkout blocks?
It is good better design but missing some functions.

## What do you think is missing from the Cart & Checkout blocks?
I can not find the accept the agreement checkbox.. i need it.
I can not add date and time delivery the plugins i have does not work

**Comment by Aljullu** [comment]
Hi @CreativeArtDesign,

> I can not find the accept the agreement checkbox.. i need it.

Right, the checkbox is not available in Blocks, we have an open issue to track its addition, you can find it here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3258.

 >  I can not add date and time delivery the plugins i have does not work

We are currently working on expanding extensibility options of WooCommerce Blocks, so it's to be expected that some extensions might not work yet.

Thanks for the feedback, I will close this issue because both of your concerns are currently under our radar.
