### ISSUE TITLE
Button Styles Conflicting with inline Link styling in the editor

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#3523]
I noticed that the buttons seem to be conflicting with link styles making the text invisible. This is only apparent in the editor. I tested this on Twenty Nineteen.

![Screenshot 2020-12-08 at 16 22 04](https://user-images.githubusercontent.com/90977/101510552-fe91fc80-3971-11eb-911a-bd2d3a2599e4.png)

I'm not sure why, but even though that link style is crossed out in the inspector, it's still the color being used. Browser bug?

**Comment by nerrad** [comment]
Mike can you add more details about your environment please?

- What WP version?
- Is the GB plugin active?
- is Twenty Nineteen up to date?

**Comment by mikejolley** [comment]
I seem to be on an old version of WP. Ill follow up and test this Monday.

**Comment by mikejolley** [comment]
- WP 5.6
- Latest 2019 theme
- No GB plugin active

Impacts a tags, not button elements. Caused by `.editor-styles-wrapper a` but for some reason even though that rule is applying, it's ruled out in the inspector. @Aljullu this happen for you as well?

**Comment by Aljullu** [comment]
I can reproduce the issue: some buttons of the product grid blocks have the same color for the text and the background, making the text invisible. The issue seems to be specific to editor with Twenty Nineteen, correct?

![imatge](https://user-images.githubusercontent.com/3616980/102087854-68028700-3e1a-11eb-9b8f-fc7f623668b8.png)

For this specific issue, we could try to upstream a fix to Twenty Nineteen. I feel it's "dangerous" that the theme sets a [background color to `.wp-block-button__link` in the editor](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-content/themes/twentynineteen/style-editor.scss#L378-L380) without specifying a text color. For example, the frontend styles [include a `color: $white` rule](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-content/themes/twentynineteen/sass/blocks/_blocks.scss#L187) to ensure the buttons' text is white. I think we need something similar in the editor.

In case it's not accepted or if we want to fix it quickly, we could fix it in our codebase writing some styles only targeting the Twenty Nineteen theme (`.theme-twentynineteen { ... }`).

Does that make sense @mikejolley?

> it's ruled out in the inspector

Looking at the screenshot you posted, the rule is ruled out because there is another ruleset with the `:visited` pseudoclass taking precedence, no? Is that happening to the button of all products? For me, depending on the button it was visited or it was not. However, I don't think that's related to the issue itself.
