### ISSUE TITLE
Run Woocommerce Blocks through filters

### ISSUE THREAD

**Issue by aguatye** [woocommerce/woocommerce-gutenberg-products-block#3549]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I add a filter but it doesn't seem to work on the All Products Block.

## Describe the solution you'd like
a) Allow Woocommerce Blocks to run through the existing filters. 
b) Supply new filters for Woocommerce Blocks.
c) Add excerpt & quantity options to the All Products block (and possibly other elements & blocks)

## Describe alternatives you've considered
Not using blocks and returning to using filters.

## Additional context
Nope

**Comment by nerrad** [comment]
Hi there @aguatye 👋 

Thanks for taking the time to create this issue. WooCommerce Blocks are not using WooCommerce templates or filters and actions because the content is being generated differently than existing WooCommerce views. In the case of the All Products block, the content is entirely rendered via React components and isn't even served from PHP.

For some explanation why the Blocks are not using the WooCommerce core templates (or filters and actions) please see #891.

_Extensibility_ is still something we have to build in more fully to the existing and new blocks and it is on our radar to provide a way for extension developers to customize some block output or provide options to merchants for enhancing the output using Gutenberg native UX. Currently our team is focusing on building in extensibility for the new Cart and Checkout blocks and we'll be able to apply much of what we learned there to the other blocks in the future.

As a part of that future work, our roadmap does include adding other product element blocks such as quantity etc, no ETA at the moment.

Since there is nothing actionable from this issue at the moment I'm going to close it, but rest assured your requests have been heard and we are aware 👍
