### ISSUE TITLE
Cart Block: Missing some styles and scripts

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#3563]
## Describe the bug
When a cart page is created using the Cart block, WordPress displays script and style issues (see screenshots below).

Script Handles:

1. wc-cart
2. selectWoo

Style Handles:

1. select2

## To reproduce

1. Create a page using the Cart block.
2. Set this page as a cart page in WooCommerce settings.
3. Open the cart page on your site.

## Screenshots

![Scripts issue](https://snipboard.io/0ogySZ.jpg)

![Styles issue](https://snipboard.io/TDunaz.jpg)

## Environment
* Core version: [5.7-alpha-49746]
* WooCommerce version: [4.8.0]
* WooCommerce Blocks version: [4.0.0]
* Theme: Storefront [3.0.0]

**Comment by nerrad** [comment]
Hmm, this _looks like_ it may be more of an issue with Storefront than the Cart block. The Cart block doesn't use `select2` and should [actually be `deregistering` those scripts](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/df7da548af75f31030e5f41eb2690965b6045556/src/BlockTypes/Cart.php#L54-L57).

**Comment by dashkevych** [comment]
Hmmm... it's strange. Personally, I do not think that it's an issue with Storefront because I am getting the same errors with other themes.

First, I've tested it with with the [Matthew](https://woocommerce.com/products/matthew/) theme. I've got the same issue. Then I've thought that it could be the theme issue. So, I've activated Storefront but I've got the same issues in Storefront.

I've just tested it with the Twenty Twenty theme, and I am still getting these issues:

![Script issue](https://i.snipboard.io/xg069L.jpg)

![Style issue](https://snipboard.io/iowEcf.jpg)

Could it be the WooCommerce issue?

**Comment by nerrad** [comment]
Yup it is strange. Blocks _is_ supposed to be de-registering those scripts. I see you're using Query monitor, it's not clear to me from the screenshot but is that notifying you about script handles being requested as dependencies of _other_ scripts that are registering that can't because of missing dependencies? If so, that would make sense. Either way, thanks for creating the issue, we'll look into it. The good news is this wouldn't really impact anything in the Cart block itself because it doesn't rely on WooCommerce core or select2 JavaScript (or styles).

**Comment by dashkevych** [comment]
Yes, I agree with you that it does not impact anything in the Cart block. At least, I've not seen any problems in the Cart block caused by this issue.

I have thought that you would like to know about this missing assets issue :)
