### ISSUE TITLE
When Checkout and Cart blocks are used instead of checkout flow shortcodes - SSR report shows error for relevant pages.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3565]
The Woo Site Status Report does checks on whether shortcodes for Checkout and Cart and will show an error if the designated page for those does not contain the relevant shortcode. However, with the advent of the Checkout and Cart blocks, it's entirely feasible for some stores to be using the blocks instead of the shortcodes and this error could be alarming to store merchants. It could also contribute to confusion for Woo HEs troubleshooting sites using the SSR.

Here's an example where I've replace the checkout shortcode on my store checkout page with the Checkout block:

![Image 2020-12-17 at 6.52.51 AM.jpg](https://images.zenhubusercontent.com/55c8bfc24f7a08fbb7f431bd/4f31027e-60a7-46cf-99f0-136a387c99c6)

We should be able to tweak the status report to detect if the block exists and update the messaging appropriately. This might need updated in Woo Core, I haven't looked yet.

**Comment by haszari** [comment]
See also https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3224 (I think same issue)

**Comment by haszari** [comment]
Adding info from the earlier issue (for visibility): 

## Describe the solution you'd like
Adjust this status item so it's happy if site uses blocks OR shortcodes. Optionally add a warning/danger state if blocks AND shortcodes are present.

If this info is included in the text status report (used in support tickets), we should fix that up too so it's all consistent.

## Additional context
We have some prior art for this in Woo core - in [wc_tracker we dig into the cart/checkout pages (code in Woo core)](https://github.com/woocommerce/woocommerce/blob/60d6510cb049836ae5c92482f0c8853436e42726/includes/class-wc-tracker.php#L738) to see if they contain shortcode or block. We might be able to adapt/reuse this code. The point is we should aim to use the same concept for the tracker prop and status page (even if they don't share code), rather than have two slightly different implementations.

I've logged the issue in blocks, but it may be cleaner to implement this in core.
