### ISSUE TITLE
Load theme-specific styles only if the theme is active

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce-gutenberg-products-block#3596]
I've noticed that some blocks [include styles](https://github.com/woocommerce/woocommerce-gutenberg-products-block/search?l=SCSS&q=.theme-twentytwenty) for default WordPress themes. Since not everyone who uses WooCommerce has an active default WordPress theme, these styles are useless.

It would be great if WooCommerce loaded just base styles needed for its core blocks by default, and additional style support for default WordPress themes would be loaded as a dependency only if a specific theme is active.

**Comment by senadir** [comment]
Hey there @dashkevych 
Thank you for your suggestion, on a personal note, I don't see much value in complicating the build process for very little gain, most extra styles are a single or double rule at best, meaning the added overhead is very negligible, and those styles are scoped so that they don't leak.

If we ever found ourselves doing full-fledged support for a theme ranging all of our components and blocks, we would consider moving them to a dedicated file.

We're dedicated to making our blocks very performant and lightweight, but we also try to balance that with our speed of delivering updates and improvements.

**Comment by nerrad** [comment]
At this point we're likely not going to address this in line with the points Nadir made in his reply.
