### ISSUE TITLE
Integration Tracking (WC Subscriptions): Allow zero orders to checkout without payment.

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3616]
It's very common of Subscriptions to be initially zero dollars, this happens if you crossgrade a subscription and your payment details and method is already saved.
This means checkout wouldn't have any totals ($0) and doesn't need to capture any payment method, checking out, in this case, would return an error (no payment method selected).

This is needed for Subscription and only happen there, if you try to checkout a zero dollar regular product, it would pass fine.

## Steps to reproduce
- In WooCommerce Settings, go to Subscriptions and scroll to Switching and check Allow Switching | Between Subscription Variations.
- Create a variable Subscription Product with two variations of the same price.
- Add the product to your cart and checkout.
- Go to `my-account/subscriptions` and view this new subscription.
- Scroll down to select Downgrade/Upgrade.
- Change the variation and go to checkout.
- Your checkout total is $0, so you don't get any payment methods, your payment method is already saved, so you don't need to add a payment method, placing the order fails with "No payment method provided."

## Expected Behavior
- Checkout should still proceed if no payment method is available

**Comment by opr** [comment]
I would be keen to avoid adding any subscriptions specific logic to blocks to handle this. I think the onus should be on extensions to set things up properly. During investigation I found the following information out. Everyone else might know this already but I want to document it for my benefit :) 

- When determining whether to show saved payment methods, we use [this criterion](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/b1fd4e51c3cbf5b155900eda7a5745484d1a7fd7/assets/js/base/context/cart-checkout/payment-methods/payment-method-data-context.js#L98) - Darren and I figured this was unnecessary and was preventing saved payment methods being chosen when buying subscriptions. I am going to remove this check in a future PR.
- When buying subscription products, it appears that the "purchased via" is always "Manual renewal" even when you use a payment gateway. That is because initially when creating a subscription with a £0 trial period, `order->needs_payment()` returns false and thus [this line](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/df7da548af75f31030e5f41eb2690965b6045556/src/StoreApi/Routes/Checkout.php#L422) sets the payment method to an empty string. I propose we change this so instead of setting the payment method based on whether the order needs payment or not, we can set the payment method based on whether it was supplied in the request. Maybe we can make a new method called `safely_get_request_payment_method` which would either return the payment method, or an empty string, but would not throw. (`get_request_payment_method` throws when payment method is not in the request). See #3686
- This is under investigation, but it seems that when crossgrading a subscription, a new draft order is created, this stops subscriptions from being able to check if an existing subscription is on the order because of the different order ID. The reason the draft order is different is because of a failing check in [`is_valid_draft_order`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/c4559c090fa659d33aaeea224dd30a7fb0c799c8/src/StoreApi/Routes/Checkout.php#L326). Related to #3614

This is not a comprehensive list of things I've found and I will add more to this or maybe make a P2 if it gets too lengthy.
