### ISSUE TITLE
Integration Tracking (WC Subscriptions): Provide a way for plugins to still capture and process payment even if cart value is $0

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#3617]
This is a second use case compared to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3616. It's very common for WCSubs to create an order with $0 value (free trial) and still capture payment for when a renewal date is up.

Currently in Checkout block, if the cart value is $0, you don't get any payment method (because `cart->needs_payment() = false`) but you still need to capture payment.
You also can't place the order because `order->needs_payment() = true` and so you get "No payment method provided." error.

## Steps to reproduce
- Create A Subscription Product with a free trial and no sign up fees.
- Add it to cart, the total should be 0.
- Checkout, you won't see any payment method.

## Expected Behavior
- Payment method should be visible.

Both this issue and https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3616 are two faces for the same coin, somehow, WCSubs changes the value of `order->needs_payment()` but doesn't do that for Cart and so we have this in which we decide if we want to capture payment using `cart->needs_payment()` and decide if we want to process payment using `order->needs_payment()`.
Ideally, we shouldn't jump to a solution before giving it a deep though first, should we switch both to use `cart` or `order`, or should we keep it as is and change WCSubs to also override `cart` value.
Not assigning this to you @mikejolley but just pinging you for some wisdom.

**Comment by mikejolley** [comment]
This might be tricky because some gateways are not going to allow a 0 payment - stripe for example has a min amount of 0.30p. Whilst we can work around this by using `needs_payment ` instead of the order total, I don't see how we can make gateways process the non-payment...

**Comment by senadir** [comment]
Subscription has a way around this I think, they sometimes charge and refund $0.5 or can disable completely if it doesn't work.
Core checkout allows this currently, so it's possible and we just need to allow payment collection.

**Comment by opr** [comment]
As mentioned in my PR #3670 the cart we send to the client on page load does not reflect the true state of the cart after the extension (subscriptions) has extended the API. So this is not a case of `cart->needs_payment` being false, but more like a problem that we're not seeing the complete picture when we load the page.

Because of Nadir's work in subs, we extend the API to return new data relevant to subscriptions, and during this there is a side-effect that updates the cart. I think this will be unavoidable. The methods relevant to this extension are executed inline, during the creation of the cart, so at this point, the response is already 99% created.

**Comment by opr** [comment]
This is closed by 3956-gh-woocommerce/woocommerce-subscriptions feel free to reopen if you disagree.
