### ISSUE TITLE
I need help on gutenberg 

### ISSUE THREAD

**Issue by 321-Soleil** [woocommerce/woocommerce-gutenberg-products-block#3649]
Hello the woocommerce checkout box is really nice but on the adress box there is written "adresse nbsp" and i would like to write only "adresse" is it possible ? here is the url so you can check the adress box to see : [https://321soleil.fr/checkout/](https://321soleil.fr/checkout/) please respond to me 
Best regards

**Comment by Aljullu** [comment]
Hi @321-Soleil, thanks for the feedback. It seems to be an issue with the French translation, which is something we don't control:

https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=578237&filters%5Btranslation_id%5D=42827627

https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/fr-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=578237&filters%5Btranslation_id%5D=72687823

I suggested them to remove the `&nbsp` part, but it's up to the localization community to accept it or not.

For now, I will close this issue in our repo since this is not something that depends on us.
