### ISSUE TITLE
Implement code needed for MailPoet integration

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3661]
From some conversations with the team, they shared the things they need for integrating and it looks like this is all server side.

The following hooks:
```
woocommerce_add_to_cart
woocommerce_cart_item_removed
woocommerce_after_cart_item_quantity_update
woocommerce_before_cart_item_quantity_zero
woocommerce_cart_emptied
woocommerce_cart_item_restored
```

And then this was also mentioned:

> I think all we really need is a hook, from which we can get an email entered in the checkout. If the above-mentioned hooks stay the same, we’ll use the new hook to update the email address to send abandoned cart to.

Once we work on this, we will need to clarify at what point they need the email, but I'm just documenting this for planning. I think most of the cart hooks should already be firing but we'll just need to confirm.

**Comment by mikejolley** [comment]
@nerrad I think this issue is unnecessary. Store API goes through the main core Cart class, so those (where applicable) hooks are already fired. I have confirmed this.

Regarding the second point:

> I think all we really need is a hook, from which we can get an email entered in the checkout. If the above-mentioned hooks stay the same, we’ll use the new hook to update the email address to send abandoned cart to.

Sad times if there is no opt-in? But billing email can be gathered from either the global customer object, or the draft order. These are updated "on the fly" as the user progresses through checkout. I don't know what point they'd want to collect this but I guess they could look at order status changes (draft for example) and capture data at that point, or using regular save_post hooks.

There is also the checkout event 'set-email-address' dispatched on the client side when this email is provided. Not sure if that is useful or not.

**Comment by nerrad** [comment]
Oh good, so based on that, there's no extra work needed for MailPoet to integrate with the new checkout flow, other than the ability to add a potential opt-in checkbox?

**Comment by senadir** [comment]
Email is not persisted if you don't enter your shipping address, so if they're looking for it on the server, it's not there. However, they can use `set-email-address` and dispatch the email to server, they can also wait for #3150 to do that for them.

**Comment by openmindculture** [comment]
Please reopen, there is still no MailPoet checkbox in the WooCommerce block checkout.
