### ISSUE TITLE
WOO blocks and advanced dynamic pricing.

### ISSUE THREAD

**Issue by 321-Soleil** [woocommerce/woocommerce-gutenberg-products-block#3681]
Hello I saw a little problem on woo blocks when i used the other plug in advanced dynamic pricing : 
Wiht the dynamic pricing plug in I made a gratis product for each order. Suppose that a guy buy a 15 dollar t-shirt on my website, he gets a gratis key ring that usually costs 3 dollars. The two plug ins work perfectly with each other BUT the problem is that AFTER proceeding to the checkout, my clients are debited for 18 Dollars !!!! And not 15 as it say because it is a gratis product.
Hope you understood me.
Best Regards
Tim

**Comment by nerrad** [comment]
Hi there @321-Soleil  👋 

Thanks for taking the time to make us aware that Advanced Dynamic Pricing isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks. 

We're currently working on adding extensibility for the blocks so extensions have a way to make sure they integrate with the new flows we're developing. Once that is done we'll have docs prepared and will be reaching out to Woo Extension developers to help them with getting their extensions integrated.

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/)

I'm going to close this issue because there's currently nothing actionable for us to do here and as noted we're already working on adding necessary extensibility to the blocks.
