### ISSUE TITLE
Investigate PHP test failures

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3688]
There are a couple of PHP tests which are failing both in GitHub actions and locally when running `npm run phpunit`.

After some investigation, it looks like the issue is that tests are running against an old version of our codebase (probably the one included in core).

Things we tried:
* Modifying `bin/install-wp-tests.sh` so it added `define( 'JETPACK_AUTOLOAD_DEV', true )` to `wp-config.php`. This didn't make any difference, `wp-config.php` seems to be ignored by tests.
* Modifying the WC version used to [download the zip in `bin/install-wp-tests.sh`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/tests/bin/install-wp-tests.sh#L153) to 4.8 seems to make our codebase to be used for tests, so the issue might have been introduced in WC 4.9.0-beta.1.

**Comment by opr** [comment]
Tests were failing before #3683 was merged.

During these tests failing, this change was made - https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3679/files#diff-5d8cf88af3d9be56abf0b110a7500b3711552009533d894e07f0e891b4af266eL317

Specifically the removal of the cast to object caused the unit tests to fail, but we didn't see this because of the Jetpack autoloader issue.

Re-adding the cast to object will fix this.

**Comment by nerrad** [comment]
I'm going to give a go at fixing this to get things ready for next week.
