### ISSUE TITLE
Replace DropdownSelector with FormTokenField from Gutenberg

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#3762]
Gutenberg has a component which is very similar to our `DropdownSelector`:

https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-token-field

This issue is about trying to completely remove `DropdownSelector` and instead use `FormTokenField` from Gutenberg.

In https://github.com/WordPress/gutenberg/pull/29110 some new props were added to that component so it's easier to match the behavior of the `DropdownSelector`.

**Comment by Aljullu** [comment]
Instead of creating a new component in Gutenberg, I'm currently taking another approach which consists on extending the `FormTokenField` component adding some new props. Those props will be useful to us if we ever replace our own implementation of `DropdownSelector` with `FormTokenField`. Progress can be seen in this PR: https://github.com/WordPress/gutenberg/pull/29110.

**Comment by Aljullu** [comment]
Now that https://github.com/WordPress/gutenberg/pull/29110 has been merged, I updated the title and description of this issue. We will no longer try to get `DropdownSelector` into Gutenberg but instead will try to replace the instances of `DropdownSelector` in our codebase with `FormTokenField`.

**Comment by ralucaStan** [comment]
I tried replacing the component and this is what I found while using [FormTokenField](https://github.com/WordPress/gutenberg/blob/086b77ed409a70a6c6a6e74dee704851eff812f2/packages/components/src/form-token-field/README.md#properties) :
- from a look and feel point of view we should not have any issues. We would need to decide if we want to keep the current design  or use the one from FormTokenField. The differences aren't that big:

    - Current implementation:
       <img width="304" alt="Screenshot 2021-04-26 at 15 34 00" src="https://user-images.githubusercontent.com/1628454/116091558-3ee5e300-a6a5-11eb-86d7-7f130c7b87b4.png">
     - With FormTokenField:
      <img width="531" alt="Screenshot 2021-04-26 at 15 34 16" src="https://user-images.githubusercontent.com/1628454/116091566-40afa680-a6a5-11eb-9480-0b991f3328c1.png">

- we will have to update @wordpress/components so that we can use `__experimentalExpandOnFocus` and `__experimentalExpandOnFocus` props on the component

While trying to adapt the Filter Products by Attribute Block, I've come across some issues:
- because for FormTokenField an array with all the selected values is passed to the callback `onChange` we can't use the logic we have in place for this event. With the current implementation we receive just the value selected/removed and we [announce](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/343f70d7af57f751c327349dec864f9e176d0f70/assets/js/blocks/attribute-filter/block.js#L247) it. I guess this is because we use the same change handler for the checkbox variant of the block. With FormTokenField I could not find out how to get only the value that caused the change event. 

- we can only pass a string for the suggestion, so this means styling the count would not be possible
<img width="300" alt="Screenshot 2021-04-26 at 15 19 43" src="https://user-images.githubusercontent.com/1628454/116089573-4b693c00-a6a3-11eb-827c-65aca0ea8279.png">

I think the replacement is possible, but we would need make some changes to the Filter Products by Attribute Block logic in order to accommodate the new component.

**Comment by ralucaStan** [comment]
The goal of this task is to have a component we could also use in other places, like the country dropdown. 
We wanted to support type and search not just select

**Comment by dinhtungdu** [comment]
@Aljullu @ralucaStan I tried to migrate the DropdownSelector to FormTokenField  [here](https://github.com/woocommerce/woocommerce-blocks/compare/fix/3762):

We need to load the whole style of the package (adding `wp-components` as the style dependency). Out of the box, the package doesn't provide individual block styles. We only use one component on the front end at the moment, so loading style for all blocks in the `wordpress-components` package isn't an option IMO.

> from a look and feel point of view we should not have any issues. We would need to decide if we want to keep the current design or use the one from FormTokenField.

@ralucaStan How did you load the style for this component on the frontend? I'm wondering if I'm missing something.

> we will have to update @wordpress/components so that we can use `__experimentalExpandOnFocus` and `__experimentalExpandOnFocus` props on the component

`__experimentalExpandOnFocus` and `__experimentalShowHowTo` are available in `wordpress-components` at the time of writing.


> because for FormTokenField an array with all the selected values is passed to the callback `onChange` we can't use the logic we have in place for this event.

I made a workaround for this issue by comparing the current checked value and the current tokens:  https://github.com/woocommerce/woocommerce-blocks/blob/d5958b07189df7e74a8efa78e2b61d342f720884/assets/js/blocks/attribute-filter/block.tsx#L598-L608


> we can only pass a string for the suggestion, so this means styling the count would not be possible

The styling is actually possible, but we will have an issue with tokens. In the image below, the token contains `[object object]` because the label is printed as a string at [here](https://github.com/WordPress/gutenberg/blob/c489f755eed1c6db6bad021562105caa19aad805/packages/components/src/form-token-field/token.tsx#L48-L54).

<img src="https://user-images.githubusercontent.com/5423135/175767534-7de5a4d3-89b6-4fe3-bffb-3ccdb7364032.png" width="600"/>

### Additional issues:
- `<FormTokenField>` causes layout shift. It doesn't use absolute position for suggestions, so it pushed below content down when expanded. It may be not a real issue, but HTML `<select>` and our `<DropdownSelector>` don't have this behavior. We can fix this by overriding the style for the suggestion.

https://user-images.githubusercontent.com/5423135/175768350-92b32adc-d373-4336-af22-6d5b29be4105.mov

_(Filter button style need some updates)_

### Possible actions
- Create a wrapper component for `FormTokenField` and add style for it there.
- Open an issue on Gutenberg to discuss using individual components of `@wordpress/components` on the front end.
- Add and additional prop `tokenDisplayTransform` to `<FormTokenField>` to avoid printing components as string.

The first one is probably the fastest one if we still want to fix this issue in the current sprint. But I don't think we should do that because we're creating another custom component. From this point of view, it's no different from using `DropdownSelector`.

**Comment by ralucaStan** [comment]
@dinhtungdu happy to see you picked this up. I still have my branch where I tried this out, I [started a PR](https://github.com/woocommerce/woocommerce-blocks/compare/add/3762-formtokenfield?expand=1) without saving it for you to see what changes I did 5 months ago, hope this helps. Let me know.

Nice workaround with having the lists of added and removed options 👏
