### ISSUE TITLE
Storefront child theme issue #1: Card number and Expiration date field not visible in Checkout

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#3828]
**I made a comprehensive analysis and tested all the themes listed in the [Storefront Themes ](https://woocommerce.com/product-category/themes/storefront-child-theme-themes/?categories=Themes&collections=theme&page=1&orderby=date) in WooCommerce website.**

You can check the [Issues map I've created in Figma](https://www.figma.com/file/vm7kZzr5uIFwacpKKZzMb5/Storefront-child-themes?node-id=1%3A142), where you will find all the issues divided by theme.

You will find in GitHub different issues where I grouped similar/ same problems and created different issues for each problem group.

__________________________________________________________________________________________________________

# Issue
The **Card number** and **Expiration date** field don’t have an outline to differentiate the input space. This issue is found across all themes. 

![Frame 119](https://user-images.githubusercontent.com/69914963/107649528-50018500-6c5c-11eb-9488-86053327372a.png)
![Frame 118](https://user-images.githubusercontent.com/69914963/107649533-5132b200-6c5c-11eb-85bb-acdfbe0987ca.png)

### Design example based on latest design
<img width="1176" alt="Screen Shot 2021-02-11 at 11 37 53" src="https://user-images.githubusercontent.com/69914963/107650799-9acfcc80-6c5d-11eb-9aa2-5ba4d2b63272.png">

**Comment by nerrad** [comment]
This doesn't look like a bug, but rather expected behaviour when the _inline credit card form_ option is set for the Stripe CC payment method in WooCommerce settings:

![Image 2021-02-12 at 2 18 11 PM](https://user-images.githubusercontent.com/1429108/107812201-561b6280-6d3d-11eb-988c-e3c1240b9b3d.jpg)

@Spacepol is that option checked on your test site?

**Comment by ghost** [comment]
@nerrad 

"Inline Credit Card Form" for Stripe is enabled, and on the Stripe payment method it works correctly. (if you don't have it enabled it shows the outline of the field nonetheless):

<img width="498" alt="Screen Shot 2021-02-15 at 11 44 15" src="https://user-images.githubusercontent.com/69914963/107960237-265d9c00-6f83-11eb-8185-f9ba4cfab609.png">

However, the issue appears in "WooCommerce payments - Credit Card", where we should have an outline for the field, because it looks like it's broken if we don't. We should show an input rectangle for the card number and the expiration date. 

<img width="1039" alt="Screen Shot 2021-02-15 at 11 50 44" src="https://user-images.githubusercontent.com/69914963/107960966-0d091f80-6f84-11eb-9952-d7c35f70497b.png">

**Comment by nerrad** [comment]
> However, the issue appears in "WooCommerce payments - Credit Card", where we should have an outline for the field, because it looks like it's broken if we don't. We should show an input rectangle for the card number and the expiration date.

I'm sorry Pablo, it's not clear to me what is being asked for here. Are you suggesting that Stripe CC needs to change how the fields appear or are you referring to something with WooCommerce payments? 

It appears to me that you are pointing out that with WooCommerce Payments, an outline (or border) isn't showing around the inputs. If I'm assuming correctly, I think this would be better fixed in the WooCommerce Payments repo so do you mind creating an issue there?
