### ISSUE TITLE
Include setBillingData in usePaymentMethod hook.

### ISSUE THREAD

**Issue by paymentplugins** [woocommerce/woocommerce-gutenberg-products-block#3962]
## Is your feature request related to a problem? Please describe.
The PaymentMethodInterface which is passed down to express payment methods and standard payment methods does not contain a setter for the billing address. Modern payment methods such as Apple Pay export billing and shipping data which can be used to auto-populate checkout fields. It is common for the billing and shipping address to differ so payment methods needs a way to populate the billing address. The ability to populate the billing address based on the exported data from the payment method will also ensure the address is accurate when used for fraud detection etc.

## Describe the solution you'd like
In `use-payment-method-interface.js` include the function `setBillingData` as part of the billing property in the `usePaymentMethodInterface` hook. The function `setBillingData` is available via the `useCustomerDataContext` hook.

Example: 

```
const {
    billingData,
    setBillingData,
    shippingAddress,
    setShippingAddress,
	} = useCustomerDataContext();

return {
    billing: {
        billingData,
        setBillingAddress,
    }
}
```

## Describe alternatives you've considered
I have not been able to find an alternative to updating the billing address. I looked in to importing the CustomerDataContext but it is not made available to external code via webpack config.

## Additional context
If possible, it would be helpful for extensibility to have the contexts available as an aliased import. For example, alias `@woocommerce/settings` allows external code to import the `getSetting` functions since it is available globally. This would ensure payment methods are not solely dependent on the props passed down to them via the `usePaymentMethod` hook.

**Comment by nerrad** [comment]
Hi there,

There are some setters we aren't going to be exposing on this API because we want to have some protection around how certain critical pieces of customer data are manipulated.

With that said, it is possible to have various pieces of data updated like shipping selections and billing address via the [checkout flow events system](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/checkout-flow-and-events.md#emitting-events) that payment methods can use.

As an example, you can look at how the [Stripe Payment Request API is interacting with this event system](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/b998f87b905c2d38bedd3a7a80273cf1ce170402/assets/js/payment-method-extensions/payment-methods/stripe/payment-request/use-checkout-subscriptions.js#L147-L164) to return billing data for the checkout to update prior to sending a request to the server (it's using the [`onPaymentProcessing` event](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/checkout-flow-and-events.md#onpaymentprocessing)).

I'm going to close this issue for now, but I'm open to discussing this further on the issue if needed.

**Comment by paymentplugins** [comment]
Hi @nerrad,

Thank you for providing that explanation and the example. After reviewing, it is now clear how payment methods can update the billing data etc without the need for the setters to be exposed.

Kind Regards,

**Comment by paymentplugins** [comment]
Hi @nerrad ,

There is still one thing that isn't 100% clear to me regarding this flow. The `onSubmit` function is provided to payment methods so they can trigger the Processing status. However, before the Processing status is set, the `CHECKOUT_BEFORE_PROCESSING` events are emitted which perform validation checks on the billing and shipping fields. If there are some fields that are invalid, then the Processing status is not set, thus `onPaymentProcessing` is not triggered. 

How can a payment method trigger `onSubmit` which would result in `onPaymentProcessing` being called if the validation never passes due to empty billing or shipping fields? By that logic it seems the shipping and billing fields must be pre-populated beforehand thus negating the efficiency of auto-populating using Apple Pay's address data.

Thank you for your time.

Kind Regards,

**Comment by nerrad** [comment]
It sounds like you are creating what we call an "Express Payment Method" (ApplePay) but might be registering it as "regular" payment method. Billing and Shipping address validation in the [checkout is skipped](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/00cf944485eb9e9ec7553035e48ba3daea796a67/assets/js/base/context/cart-checkout/checkout/processor/index.js#L71-L74) for express payment methods because it is assumed the express payment method is providing that validation (being they are usually hosted wallets). There is still validation that happens on the server though (in case the express payment method doesn't do validation!).

You are able to set the shipping address and selected shipping rates in the checkout since that will be needed for updating the amount charged. As an example you can see that being done in the setup for the [Stripe payment request API here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/payment-method-extensions/payment-methods/stripe/payment-request/use-initialization.js#L165-L181) (which is used for exposing ApplePay/ChromePay as express payment method options).

**Comment by paymentplugins** [comment]
Hi @nerrad,

Thank you for your reply. Yes, I was attempting to integrate an "Express Payment Method" in the regular payment method section to make it available in both Express and Regular sections. I did not realize that in the new opinionated design the Express method should not be included in the regular payment method section.

Thanks for the clarification.

Kind Regards,

**Comment by nerrad** [comment]
One other advantage of the express payment registration, is that automatically makes it available in the Cart context as well. Express Payments are intended to be used for Payment Methods that have their own self-contained billing/shipping/wallet type forms to help accelerate the checkout experience (which is also why they are the first thing the shopper sees in the checkout, and available in the cart).
