### ISSUE TITLE
WooCommerce Product Elements for production ( non for experimental use only )

### ISSUE THREAD

**Issue by grogou** [woocommerce/woocommerce-gutenberg-products-block#3965]
## Is your feature request related to a problem? Please describe.
It is not a problem but can be the solution for the one-page product presentation future for stores.

## Describe the solution you'd like
If we can use product elements without the All Products block, like now on the development version we can do single product presentation pages or templates with reusable blocks for that, it can be very helpful future.

## Describe alternatives you've considered
-

## Additional context
Or maybe it is a future update for you, I just need to understand is it possible or it shown only for development mode.

Very helpful plugin guys, thanks so much!!!

**Comment by nerrad** [comment]
Hi there @grogou,

It's definitely on our radar to continue development for Product Element blocks (and create more). This will be useful for eventual use with Full Site editing and Block based themes coming in the future for WordPress too!

Unfortunately, we've had to pause work on this temporarily and put our resources on the Cart and Checkout blocks. No ETA for when work will resume on the Product Element blocks.

I'm going to close this issue because there's nothing actionable at the moment. However, I'm very interested in what ideas you had around using these blocks (besides what you mentioned here for one page product presentation). If you want to expand on that please do leave additional comments.

**Comment by grogou** [comment]
Hi @nerrad.

Thank you for your response and sorry for the late from my side.

I am trying to create a single-page product presentation page with woo blocks like this.
https://www.xbox.com/en-US/consoles/xbox-series-x?xr=shellnav

So we have all the tools to create this page on WordPress editor, the only thing we need is atomic blocks, to show dynamic data from product, like price, title, description, etc.

I think it can be helpful for community, it is just idea from my side :) Thank you again and good luck!
