### ISSUE TITLE
Not Updating Product Quantities on Front-end [Basket] (Support for Woo Discount Rules extension)

### ISSUE THREAD

**Issue by EMBARKwebdesign** [woocommerce/woocommerce-gutenberg-products-block#3981]
Hey,

Using Woo Discount Rules, I am facing an issue in the basket where product quantities are not being reflecting accurately in a case where there is a relationship (promotion) between the two products.

I got this response from the Woo Discount Rules devs.

> Our developers had a check and here is the information:
> It seems that the updated quantity is getting in response.
> Attaching the screenshot for your reference: 
> See - https://nimbusweb.me/nimbus-screenshots/3792d34e2fcfb935feabfa877c3db228 
> But it haven't updated in cart layout. Please check with Woocommerce Blocks plugin regarding the same.

Hope you can help - thanks in advance!

**Comment by nerrad** [comment]
Hi there @EMBARKwebdesign  👋 

Thanks for taking the time to make us aware that Woo Discount Rules isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core might not work with the blocks. 

We're currently working on adding extensibility for the blocks so extensions have a way to make sure they integrate with the new flows we're developing. Once that is done we'll have docs prepared and will be reaching out to Woo Extension developers to help them with getting their extensions integrated.

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

I also appreciate you pasting the response got from the Woo Discount Rules team, however, the details are fairly sparse and the screenshot link doesn't resolve to a valid route (I can't see what they are referring to).  If you're able to share the screenshot or some more details on what they are referring to in the response that would be great, offhand I do wonder though if they are getting confused between the shortcode cart and the block cart since the blocks use new REST API endpoints that this team might not be aware of.

I am closing this issue because there's currently nothing actionable for our team here - please do update if you have any additional information to add, we do see it!

**Comment by senadir** [comment]
Hey @EMBARKwebdesign I actually fixed this issue a couple of weeks ago and it went out as part of 4.7.0 can you confirm if it was fixed or not?
https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3907
