### ISSUE TITLE
A feature request about new filter blocks for the shop/all products block.

### ISSUE THREAD

**Issue by B-Novembit** [woocommerce/woocommerce-gutenberg-products-block#4008]
Hi there,

## Is your feature request related to a problem? Please describe.
It is a feature request about new filter blocks for the shop/all products block. Currently, there are no options for 'filter by rating', 'filter by availability/stock status', or additional sorting options we can put elsewhere. We know it is still a work-in-progress so I want to understand how to approach this part.

## Describe the solution you'd like
We are about to start working on several shop filter blocks as described above.
Do you have plans to add these and other additional shop filters on your end in the near future? (so we don't do any duplicate work)
Also, is it possible to contribute to this repo, or we should try to create these blocks with my own plugin?

## Additional context
At NovemBit, we are building a great and professional eCommerce theme with Gutenberg. We have 10-years of experience in eCommerce working from smaller scale to enterprise-level projects with our 20-people team with WooCommerce and want to thank you for all the great work you are doing and, if possible, give back to the community. We're very excited about the transition to Gutenberg and wish you the best of luck with this.

Please, let me know how you see a solution to this and any plans you have with these shop-filter part blocks for the future.
Many thanks!

B.M.

**Comment by Aljullu** [comment]
Hi @B-Novembit thanks for your kind words!

> Do you have plans to add these and other additional shop filters on your end in the near future?

In the future we might add a Filter by rating block, similar to the widget in WooCommerce core with the same name. Unfortunately, I can't promise when this is going to be worked on since our current focus are the Cart and Checkout blocks.

AFAIK, there are no current plans to add other filter blocks like the one you described for stock status.

> Also, is it possible to contribute to this repo, or we should try to create these blocks with my own plugin?

It definitely is, but at the same time we can't promise we will merge all contributions. In general, if they are small code changes, I would tell you to directly open a PR and ping us for review. If you want to make bigger contributions (ie: adding new blocks like the ones you described), I would suggest to discuss first how you are planning to technically implement this so we can make sure we are on the same page.

A faster approach might be creating a separate plugin with those filters but make it so they can interoperate with the All Products blocks and the other filter blocks from this repo. I'm not 100% sure this is possible right now because extensibility for the All Products block has been focused on extending inner blocks. But it might be worth exploring it.

---

Looking forward to what you come up with. For now, I will close this issue until we have something more concrete to work on. Feel free to answer or reopen the issue to continue the discussion.
