### ISSUE TITLE
Translated Checkout: order-received endpoint always reverts back to default language

### ISSUE THREAD

**Issue by revpower** [woocommerce/woocommerce-gutenberg-products-block#4029]
## Describe the bug
When checking out in another language (using latest WPML plugin + WooCommerce Blocks 4.8), the order-received endpoints redirects to the default language order-received endpoint.  The order-received endpoint should remain in the same language as per the checkout language 

## To reproduce

1. Change language of site to any non-default language (i.e. /fr). 
2. Add any item to check and "Proceed to Checkout" page : www.examplesite.com/fr/checkout/
3. Fill out Checkout form and "Place Order"
4. User is then redirected to www.examplesite.com/checkout/order-received...

## Expected behavior
User should be redirected to the /order-received endpoint in the same language used during checkout. 
 
 www.examplesite.com/fr/checkout/ ->  www.examplesite.com/fr/checkout/order-received

### WordPress (please complete the following information):
* Core version: 5.7
* WooCommerce version: 5.1.0
* WooCommerce Blocks version: 4.8
* Site language: English (default), with other languages represented via WPML
* Any other plugins installed: WPML

**Comment by Aljullu** [comment]
Hi @revpower, thanks for opening this issue! I have been investigating how this work internally, and unfortunately I don't think we can do much to fix it, this needs to be handled by WPML.

All URLs generated by the Store API included in WC Blocks use the standard WP [`get_permalink()`](https://developer.wordpress.org/reference/functions/get_permalink/) function. It has a filter named `post_link` which is the one I think WPML is using, however, it looks like WPML only hooks into that filter on page load, not on API calls like the ones done in the Cart and Checkout blocks.

My suggestion would be to get in contact with WPML and explain the problem to them. Hopefully they will be able to take a look at it and eventually release a fix.

For now, I'm going to close this issue since there is not much we can do on our end.
