### ISSUE TITLE
Products by Category: element with wrong id in the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4070]
## Describe the bug
There is a `p` tag with an id which seems to be wrong when adding the Products by Category block: `undefined__help`.

## To reproduce

1. Add a Products by Category block.
2. Select a couple of checkboxes so the `Display products matching` select shows up.
3. With the browser devtools inspector, select the `Pick at least two categories to use this setting.` string.
4. Notice it's a `<p>` element with a wrong id: `undefined__help`:

<img src="https://user-images.githubusercontent.com/3616980/115010333-91f1b600-9ead-11eb-9ef6-c542a3bf0e75.png" width="202" alt="Screenshot" />

## Expected behavior
We should investigate why `undefined` shows up there.

**Comment by dinhtungdu** [comment]
This is a bug introduced in https://github.com/WordPress/gutenberg/pull/23802/ which was fixed by https://github.com/WordPress/gutenberg/pull/33696. This issue only occurs in the blocks editor shipped with Core. The ID is generated correctly with the latest Gutenberg plugin activated.

Closing this one because it's a bug of Gutenberg and it's been already fixed.
