### ISSUE TITLE
Checkout payment method `canMakePayment` applies to Gutenberg preview

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gutenberg-products-block#4101]
## Describe the bug

I'd like to always display an express payment method preview in the Gutenberg editor for the cart and checkout blocks, but sometimes not display it to the shopper (e.g when it should not be available due to product requirements).

From the [docs](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/main/docs/extensibility/payment-method-integration.md):

> canMakePayment (required): A callback to determine whether the payment method should be available as an option for the shopper.

The `canMakePayment` callback applies not only for the shopper, but also for the Gutenberg editor preview in wp-admin. I don't want to initialize the payment API in the blocks editor to confirm if the payment method should be available.

In my opinion, the `canMakePayment` callback should be dissociated from the Gutenberg preview. If I don't want to display the preview, I should simply be able to return `null` in the `edit` prop.

Am I missing something, or is that really how it's supposed to work?

Is there an easy way to return `true` in `canMakePayment` if the payment method is being rendered in the editor?

## To reproduce

Register an express payment method similar to this:

```JavaScript
registerExpressPaymentMethod(
    {
	name: 'my_payment_method',
	content: <div>A react node</div>,
	edit: <div>A react node</div>,
	canMakePayment: () => 'undefined' !== typeof enqueuedAPIObject,
	paymentMethodId: 'new_payment_method',
    }
);
```

As an example, note that I just want to make it available to shoppers when the `enqueuedAPIObject` global variable is defined, but as a result, `<div>A react node</div>` isn't displayed in Gutenberg

## Expected behavior

The `edit` preview is never visible in `wp-admin`. If I want to make it visible, I need to do some special logic there to tell if the component is being rendered in the editor.

## Additional context

I'm working on Apple Pay, and apparently, the problem exists in the Stripe integration as well. The preview is never visible.

**Comment by senadir** [comment]
Hey @ricardo, That’s a good point, this should be possible by checking the Editor context from our side. Just to understand, your point is that `canMakePayment` should always be true in the editor?

**Comment by ricardo** [comment]
@senadir Yes, sort of!

The `canMakePayment` nomenclature to me suggests it's a callback function used to decide whether or not to allow that payment method to be used in the payment page. 

It's important that the payment method is displayed in the editor context, but it shouldn't require me to add some extra logic in `canMakePayment`.

I guess, ideally, there could be two separate things for that. Maybe the editor context shouldn't take into account `canMakePayment`, or always be true behind the scenes, as you mentioned. And whatever is in the `edit` prop be used always for the editor context.

**Comment by nerrad** [comment]
This makes sense (to decouple `canMakePayment` from the editor context). It puts some onus on the payment method to provide signals to the merchant about the validity of the preview if there are conditions that prevent it behaving as expected for a shopper but I think that's okay?

**Comment by ricardo** [comment]
> It puts some onus on the payment method to provide signals to the merchant about the validity of the preview if there are conditions that prevent it behaving as expected for a shopper but I think that's okay?

@nerrad That would apply only for the placeholder cart data provided for the preview, right? Perhaps it could still be possible to disallow the payment method in some circumstances by passing `null` to the `edit` prop, or not registering the payment method, or some other way, but for our use case (Stripe and WC Pay), the relationship between the payment methods and the preview data is irrelevant.

**Comment by nerrad** [comment]
Oh when I wrote "validity of the preview" I'm talking about what gets displayed for the payment method in the editor context and not really anything to do with the preview data. As an example for express payment methods, you might want to only show Apple Pay preview if the browser is safari and otherwise show Chrome/GooglePay if the browser is chrome. Or you might want to show an appropriate message to the merchant if their payment method isn't configured right (doesn't have API keys set correctly) so they have an immediate signal something needs fixed. 

Currently, the built in Stripe integration (which is being migrated to the extension) is just using [an image rather than the actual element for the express payment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/792afe9a35d2aa2da5a291384ad7e0f56c112410/assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js#L64). So what I described above hasn't been implemented yet. Also, the registered `canMakePayment` callback is still validating the presence of the stripe client setup and [throwing an error if something is wrong](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/792afe9a35d2aa2da5a291384ad7e0f56c112410/assets/js/payment-method-extensions/payment-methods/stripe/payment-request/index.js#L40-L42) which gets picked up by error boundaries in the payment method interface and displayed to the merchant so they can handle (usually errors like missing API key or something like that).

In your case @ricardo, are you not wanting `canMakePayment` to appear in the editor because it applies to the merchant's context (since the merchant would be viewing the editor) and thus might not _get a preview_?

**Comment by nerrad** [comment]
To be clear, I'm okay with having `canMakePayment` only run outside of the editor context. I'm just also thinking what we should recommend from a ux perspective to payment method extension developers for what they show in the editor context when the merchant should be informed about something not configured correctly for their payment method since as a preview it's supposed to be representative of what the shopper would see in the checkout flow.

**Comment by ricardo** [comment]
> In your case @ricardo, are you not wanting canMakePayment to appear in the editor because it applies to the merchant's context (since the merchant would be viewing the editor) and thus might not get a preview?

Exactly 👍 

> I'm just also thinking what we should recommend from a ux perspective to payment method extension developers for what they show in the editor context when the merchant should be informed about something not configured correctly.

Maybe instructing developers that you could add some business logic to the preview component, so that it's rendered differently depending on settings or even browser context as you mentioned. In our use case, we could create a `<PaymentButtonPreview { ...settings } />` component which receives some settings props and renders the button differently depending on some sort of customization. That would be totally possible to do, but I don't think it's necessary in our use case.
