### ISSUE TITLE
Audit: MailPoet

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4104]
## MailPoet – emails and newsletters in WordPress

- **Author:** MailPoet
- **Website:** https://wordpress.org/plugins/mailpoet/
- **Repository:** https://github.com/mailpoet/mailpoet/

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by senadir** [comment]
# Extension Audit Template

## Functionality Review

Like Mailchimp, this plugin provides the ability to create mailing lists, send campaigns from your store, and other automated marketing features like abandoned carts and promotions.

This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart form
- [ ] My Account Page
- [ ] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [x] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [x] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Issues identified:
- The plugins add a marketing opt-in checkbox in Checkout, this is currently not visible in Checkout Block.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

The extension needs the ability to insert a marketing checkbox and to receive its value in the server.

This extension requires integration with: 

- [ ] Product Blocks
- [ ] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| Cart and Checkout adding inner block or custom checkbox | Component | It will be used to opt in users to Marketing |  *1*   |
| Store API | hook | Receive the marketing opt in and use it accordingly | *3* |
