### ISSUE TITLE
Audit: Product Bundles

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4107]
## Product Bundles

- **Author:** SomewhereWarm
- **Website:** https://woocommerce.com/products/product-bundles/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/premmerce-product-bundles

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by senadir** [comment]
# Extension Audit Template

## Functionality Review

*Install and activate the extension, then going by the documentation, review it's frontend functionality focussing on how it influences products, cart, and the checkout.*

The extension allows you sell products in a bundle, ofter discounted, but with certain restrictions on the quantity.

This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [x] Single Product Pages
  - [x] Product Details
  - [x] Product Prices
  - [x] Add to cart form
- [ ] My Account Page
- [x] Cart Page
  - [x] Product prices
  - [x] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [x] Custom functionality
- [x] Checkout Page
  - [ ] Checkout Fields
  - [x] Product prices
  - [x] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [x] Rest API
  - [x] Edits existing endpoint
  - [ ] Adds custom endpoint
- [x] Settings
  - [ ] WooCommerce settings
  - [x] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks


Issues identified:
- Product bundles are shown to be related on Cart block.
- You can't remove item from a bundle in Classic Cart but can do that in Cart block.
- Quantity is synced with all items in a bundle, it's not in Cart.
- Base Product price is all items + itself, in Cart, it's just itself.
- There's an option to disable an item pricing, in Cart, its shown as 0.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

- The extension needs the ability to manipulate related cart items and disable certain functionalities like updating quantity and removing items, it also needs the ability to sync several products together.

This extension requires integration with: 

- [x] Product Blocks
- [x] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| Cart items | hooks | Disable removing items, changing quantity, and changing several items quantity in sync |  *5*   |
| Store API | Cart Item ExtendRestAPI | add additional data to cart items | *1* |
| Cart items | filters | Change price display, classnames, and other text based things | *2* |
