### ISSUE TITLE
Audit: Memberships

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4108]
## WooCommerce Memberships

- **Author:** SkyVerge
- **Website:** https://woocommerce.com/products/woocommerce-memberships/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/woocommerce-memberships

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by senadir** [comment]
# Extension Audit Template

## Functionality Review

The plugins offers the ability to lock content from users and only grant it under certain conditions (buying a product, being in a list)...

This extension touches: *(mark all that apply)*

- [x] Product Grids (shop page)
  - [x] Product Details
  - [x] Product Prices
  - [x] Add to cart button
- [x] Single Product Pages
  - [x] Product Details
  - [x] Product Prices
  - [x] Add to cart form
- [x] My Account Page
- [ ] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [x] Settings
  - [x] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Issues identified:
- The extension limits the user ability to buy some products if you're not a member, on a shop page, those products don't have their prices visible, or you can't add them to cart, in All Product block, you can view the price and rating.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

The extension requires the ability to hide prices.

This extension requires integration with: 

- [x] Product Blocks
- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| Ability to hide the price from Store API | filter hook on the server side | Hide price |  *1*   |
|  |         |
