### ISSUE TITLE
Audit: Smart Coupons

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4111]
## Smart Coupons

- **Author:** StoreApps
- **Website:** https://woocommerce.com/products/smart-coupons/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/woocommerce-smart-coupons

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by senadir** [comment]
# Extension Audit Template

## Functionality Review

The extension allows the merchant to create a coupon for special products, store credit, and other marketing options.

This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart form
- [x] My Account Page
- [x] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [x] Notices
  - [x] Custom functionality
- [x] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [x] Notices
  - [x] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [x] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [x] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Issues identified:
- Store Credit not visible on Cart and Checkout
- Store Credit is a special code plus "Store Credit", the later is not visible on Cart and Checkout.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [x] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [x] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| ExtendRestAPI | Store API | Add store credit data and applicable coupons to cart |  *2*   |
| Cart/Checkout | SlotFills | The ability to insert a slot before Cart and Checkout to show the store credit selector |  *3*   |
| Cart/Checkout | Client API | The ability to add coupons by calling the store |  *1*   |
| Cart/Checkout | frontend filters | the ability to rename Coupons |  *1*   |

**Comment by joashrajin** [comment]
I'm aware that this is closed, but a customer was really unhappy that the compatibility issues have not been solved yet in 23111200-hc

**Comment by senadir** [comment]
Thank you @joashrajin Not much we can do here, we have several extensibility interfaces that can be used and are help to assist plugin developers if they're blocked, but we can't do the integration ourseleves.
