### ISSUE TITLE
Audit: Conditional Shipping and Payments

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4112]
## Conditional Shipping and Payments

- **Author:** SomewhereWarm
- **Website:** https://woocommerce.com/products/conditional-shipping-and-payments/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/woocommerce-conditional-shipping-and-payments

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by ralucaStan** [comment]
# Extension Audit Template

## Functionality Review

Conditional Shipping and Payments gives the store owner a streamlined way to creating conditional rules and restrict:
- [Shipping Methods](https://docs.woocommerce.com/document/woocommerce-conditional-shipping-and-payments/#section-6)
- [Payment Gateways](https://docs.woocommerce.com/document/woocommerce-conditional-shipping-and-payments/#section-5) 
- [Shipping Destinations](https://docs.woocommerce.com/document/woocommerce-conditional-shipping-and-payments/#section-7)

The customer can:
- Make _free shipping_ available per **product**, **category**, or **shipping class**.
- Restrict _shipping methods and live rates_ based on **package weight**, **item count**, or **cart total**.
- Prevent individual products or categories from being shipped to restricted countries, states, and zip codes.
- Limit shipping and payment options to specific customers and customer roles, such as membership holders or wholesale customers.
- Use specific payment gateways for purchasing subscriptions, or offer free shipping with subscription renewals.


This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart form
- [ ] My Account Page
- [x] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [x] Custom functionality
  The cart [shows notifications](https://user-images.githubusercontent.com/1628454/117179301-460e9e80-add3-11eb-8af1-9cd31b7b012d.png) is there are Shipping method restrictions in place, but they don't prevent the user from accessing the checkout.
  - [x] Shipping methods
- [x] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [x] Custom functionality
  The block shows notifications for all restrictions if the fields they apply to aren't hidden from the user.
  - [x] Payment Methods
  - [x] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [x] WooCommerce settings ([See image](https://woocommerce.com/wp-content/uploads/2015/03/csp_overview_19.png))
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

### Restrict Shipping Methods

- I've tested different rules and all worked as expected when the shipping method is hidden from the customer.
-It does not work if the restriction is set up to [show the excluded method](https://user-images.githubusercontent.com/1628454/117173719-5754ac80-adcd-11eb-972b-56aa576d4cd4.png), the restriction is disregarded completly and the customer can place an order using it. The expected behaviour is that the user should see:
    -  a [notification](https://user-images.githubusercontent.com/1628454/117174204-c4684200-adcd-11eb-9abf-069eddc62bf1.png) on submit
	- [a warning](https://user-images.githubusercontent.com/1628454/117174747-56704a80-adce-11eb-8cd8-c086066cfeb7.png) under the shipping option itself, when [Show static notices](https://user-images.githubusercontent.com/1628454/117174428-fda0b200-adcd-11eb-9b98-37c229b6ce0e.png) is selected

### Restrict Payment Gateways
- Does not work at all: The restriction for payment gateways is not applied at all, no matter the configuration.

### Create Shipping Country and State Restrictions
- Does not work as expected: The user [should see a detailed notification](https://woocommerce.com/wp-content/uploads/2015/03/csp_notice_19c.png) with the details about the restriction when trying to pay for the order. Instead he sees a notification saying "Something went wrong. Please contact us to get assistance."



Issues identified:
- *Summarize any issues you found with the extension*

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [x] Cart Block
- [x] Checkout Block
- [x] Payment Methods API
- [x] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| Cart| Component,  | Handle display of restricted shipping methods|  *?*   |
| Checkout| Component, maybe StoreApi | Handle all restrictions  |  *?*   |
