### ISSUE TITLE
Audit: Dynamic Pricing

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4114]
## Dynamic Pricing

- **Author:** Element Stark
- **Website:** https://woocommerce.com/products/dynamic-pricing/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/woocommerce-dynamic-pricing

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by ralucaStan** [comment]
# Extension Audit Template

## Functionality Review

Dynamic Pricing lets you define pricing rules based on products, order totals, roles, and product categories. See the [7 possible modes of discounts](https://docs.woocommerce.com/document/woocommerce-dynamic-pricing/#section-3).

The pages affected depend on the type of discount applied.
- For _Single Product quantity discount_, the only thing customers will see, is a difference in pricing in the Cart page. Other views are not affected.
In the example below, with an order total of $10 or more, the customer gets 20% off. What the extension touches is the price: ~~$18.00~~ $14.00.
<img src="https://docs.woocommerce.com/wp-content/uploads/2012/02/dynamicpricing-customerview.png" />
- Same behaviour for _Cart total based discounts_, the discount is visible only in the Cart.
- For _Category & Role based discount_ the customer will see discounted prices all over the shop for the products belonging to that Category

This extension touches: *(mark all that apply)*

- [x] Product Grids (shop page)
  - [ ] Product Details
  - [x] Product Prices
  - [ ] Add to cart button
- [x] Single Product Pages
  - [ ] Product Details
  - [x] Product Prices
  - [ ] Add to cart form
- [ ] My Account Page
- [x] Cart Page
  - [x] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [x] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks
I tested the extension with a rule based on the quantity of a product. If >= 10 items of the same products are added, apply a 15% discount.

The extension partly works with the Cart block.
- when the user adds 10 products from the All products block, the Cart block displays the discount as expected
    <img width="606" alt="Screenshot 2021-04-29 at 17 53 45" src="https://user-images.githubusercontent.com/1628454/116580676-dea8a880-a913-11eb-9aab-0493ece62f0d.png">
- if the user goes to the cart and removes on item the discount dissapears as expected, the total price on the right is correct
<img width="608" alt="Screenshot 2021-04-29 at 17 55 12" src="https://user-images.githubusercontent.com/1628454/116580864-1152a100-a914-11eb-8100-e4c6f5e0b787.png">
- if the user add back 1 item, the discount is not applied, although it should have been. The price on the right is correct.
<img width="606" alt="Screenshot 2021-04-29 at 17 56 38" src="https://user-images.githubusercontent.com/1628454/116581087-44953000-a914-11eb-96e2-082bc22fbdd5.png">

I also tested with a category based discount, -5$ for products in Tshirt category
The discount is applied per item price in All Products, Checkout and Cart blocks. But when the user changes the quantity the discount in the Cart Block is lost.


Issues identified:
- When the customer modifies the quantity in the Cart Block the discounts are lost, no matter the type of discount applied


*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [x] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [x] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| Cart  | Client API. | Quantity change request in Cart Block should take into consideration the extension settings  |  *?*   |
