### ISSUE TITLE
Audit: Pre-orders

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4115]
## WooCommerce Pre-Orders

- **Author:** Automattic
- **Website:** https://woocommerce.com/products/woocommerce-pre-orders
- **Repository:** (private) https://github.com/woocommerce/woocommerce-pre-orders

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by ralucaStan** [comment]
# Extension Audit Template

## Functionality Review

Sets up pre-orders in your WooCommerce store, so customers can order products before they're available.

The pre-orders are charged up front and upon release. With [supported payment gateway](https://docs.woocommerce.com/document/pre-orders/#supported-gateways-for-automatic-payments "supported payment gateway"), pre-orders can be charged upon release without the customer returning and paying for their order.

Pre-orders need to be ordered separately. Adding another product to an order is prevented. [See image](https://user-images.githubusercontent.com/1628454/116696686-85e41900-a9c2-11eb-9c71-d27082775d8b.png).

Pre-orders need to be ordered one at the time/separately.


This extension touches: *(mark all that apply)*

- [x] Product Grids (shop page)
  - [x] Product Details
  - [ ] Product Prices
  - [x] Add to cart button
- [x] Single Product Pages
  - [x] Product Details
  - [ ] Product Prices
  - [ ] Add to cart form
- [ ] My Account Page
- [x] Cart Page
  - [ ] Product prices
  - [x] Product meta
  - [x] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [x] Payment Methods
  - [ ] Shipping Methods
  - [x] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [x] Custom settings page
  - [ ] Customizer 
  - [x] Product settings page

## Compatibility with Blocks

*See how the extension does or does not work when using Product Blocks, Cart Block, and Checkout Block. Does it work as expected? Is functionality that works with the shortcodes broken in the blocks context?*

Issues identified:
- All products
    - No info displayed about the release date. [Shortcode](https://user-images.githubusercontent.com/1628454/116708564-1d9c3400-a9d0-11eb-9d49-3aa5da0ce0c8.png) | [Block](https://user-images.githubusercontent.com/1628454/116708668-3ad10280-a9d0-11eb-9b94-9db2944a55a5.png)
    - Adding a preorder product from All products to the cart does not update the mini cart. Removing the product from the mini cart does not update the product's text button
    - Adding from All products another product to a cart with a pre-ordered through a vague notification [Shortcode](https://user-images.githubusercontent.com/1628454/116696686-85e41900-a9c2-11eb-9c71-d27082775d8b.png) | [Block](https://user-images.githubusercontent.com/1628454/116708927-7a97ea00-a9d0-11eb-813f-a82242ac5eb9.png)
	- No notification is shown when adding a second pre-sale product to the cart.  [Shortcode](https://user-images.githubusercontent.com/1628454/116712213-e9c30d80-a9d3-11eb-8525-0a3cfd8db5ec.png) 
- Cart Block
   - it does not specify Total €106,00 charged June 1, 2021, if the shop owner sets charging for the product upon it's release. [Shortcode](https://user-images.githubusercontent.com/1628454/116709090-a1eeb700-a9d0-11eb-98d0-3c4bc06a3bc2.png) 
- Checkout Block
   - it does not add the extra pay method  [Shortcode](https://user-images.githubusercontent.com/1628454/116708145-b4b4bc00-a9cf-11eb-81ea-3bf9f8fc4b6b.png) 


*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [x] Product Blocks
- [x] Cart Block
- [x] Checkout Block
- [x] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| All products | Component and Store API | Display all info about the pre-sale, handle pre-sale calls corectly |  *?*   |
| Cart |   Component      | Display info about product availibility | ? |
| Checkout | Component, Store Api (?}, Payment integrations | Add support for charging on release day | ? |
