### ISSUE TITLE
Audit: All Products for Subscriptions

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4117]
## All Products for WooCommerce Subscriptions

- **Author:** SomewhereWarm
- **Website:** https://woocommerce.com/products/all-products-for-woocommerce-subscriptions/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/woocommerce-all-products-for-subscriptions

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by ralucaStan** [comment]
# Extension Audit Template

## Functionality Review

All Products for WooCommerce Subscriptions is an add-on extension for WooCommerce Subscriptions that lets you add subscription plans in two store areas: product page and cart. It's an essential complement to WooCommerce Subscriptions that lets you:

- Add subscription plans to existing products. (read [Product Subscription Plans](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#section-4))
- Sell any product one-time, or on subscription.(read [Product Subscription Plans](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#section-4))
- Add products to existing subscriptions. (read [Adding Products to Subscriptions](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#adding-products-to-subscriptions))
- Purchase entire carts on subscription. (read [Cart Subscription Plans](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#section-5))
- Create configurable subscription boxes using Product Bundles and Composite Products. (not documented)

As the extension creates a subscription, all the areas affected by WooCommerce Subscriptions will also have to be taken into consideration.
The extension also documents some [limitations](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#section-6) it has.

This extension touches: 

- [x] Product Grids (shop page)
  - [ ] Product Details
  - [x] Product Prices
  - [x] Add to cart button
- [x] Single Product Pages 
  - [ ] Product Details
  - [x] Product Prices
  - [x] Add to cart form
  - [x] Custom functionality
      - [Product Subscription Plans](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#section-4): [see image](https://docs.woocommerce.com/wp-content/uploads/2019/10/satt-product-with-subscription-options-v3.png)
      - [Adding Products to Subscriptions](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#adding-products-to-subscriptions): [see image](https://docs.woocommerce.com/wp-content/uploads/2019/10/apfs-add-product-to-subscription-v3.png)
- [x] My Account Page
- [x] Cart Page
  - [x] Product prices
  - [ ] Product meta
  - [x] Cart totals
  - [ ] Notices
  - [x] Custom functionality
     - [Cart Subscription Plan](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#section-5)
	 - [Adding Carts to Subscriptions](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#adding-carts-to-subscriptions)
- [x] Checkout Page
  - [ ] Checkout Fields
  - [x] Product prices
  - [ ] Product meta
  - [x] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [x] Thanks page ([See image](https://user-images.githubusercontent.com/1628454/117012861-a0363380-acef-11eb-91b7-3cfed6c73e85.png))
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [x] Settings
  - [x] WooCommerce settings 
    - [Add to Subscription ](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#adding-products-to-subscriptions)
	- [Subscribe to Cart](https://docs.woocommerce.com/document/all-products-for-woocommerce-subscriptions/store-owners-guide/#section-5)
  - [ ] Custom settings page
  - [ ] Customizer 
  - [x] Product settings page ([See image](https://woocommerce.com/wp-content/uploads/2019/03/satt-edit-product-with-subscription-options-v3.png))

## Compatibility with Blocks

Issues identified:

#### All Products

- A product with an added subscription does not look & work as expected. It does not display the item price and also the subscription price. Although the button shows the correct text, it does not take the user to the product detail page as expected, but it adds the simple product(without subscription) to the cart. [Shortcode](https://user-images.githubusercontent.com/1628454/117002952-87745080-ace4-11eb-9c9a-9136738ea098.png) | [Block](https://user-images.githubusercontent.com/1628454/117004541-74628000-ace6-11eb-8af6-d93123f6c173.png)

#### Cart block
- For a product with an added subscription, the cart block does not show information about the subscription, it only shows the reduced priced added by the subscription ([Shortcode](https://user-images.githubusercontent.com/1628454/117011911-a4158600-acee-11eb-8ca1-bf656fad4586.png) | [Block](https://user-images.githubusercontent.com/1628454/117011924-a5df4980-acee-11eb-8d3a-c861d644ba6a.png))
- The cart does not display `Cart Subscription Plan` section (See [Shortcode](https://docs.woocommerce.com/wp-content/uploads/2019/10/satt-cart-with-subscriptions-v3.png))
- The cart does not display `Adding Carts to Subscriptions` section (See [Shortcode](https://docs.woocommerce.com/wp-content/uploads/2019/03/satt-add-cart-to-subscription.png))

#### Checkout block
- The checkout block does not show information about the subscriptions created with the extension. It treats the products as normal products with one time payment ([Shortcode](https://user-images.githubusercontent.com/1628454/117010879-8dbafa80-aced-11eb-887b-c278b703dda9.png) | [Block](https://user-images.githubusercontent.com/1628454/117026737-50aa3480-acfc-11eb-9624-29801a3d87bd.png))

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [x] Product Blocks
- [x] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [x] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
|All products| component, client API | display product with subscription |  *?*   |
| Cart  | component, client API  | add cart subscription sections, treat products as subscription products |       *?* | 
| Checkout |  component, client API | treat products as subscription products |    *?*   |
