### ISSUE TITLE
Audit: Box Office

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4121]
## WooCommerce Box Office

- **Author:** Automattic
- **Website:** https://woocommerce.com/products/woocommerce-box-office
- **Repository:** (private) https://github.com/woocommerce/woocommerce-box-office

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by ralucaStan** [comment]
# Extension Audit Template

## Functionality Review

Box Office for WooCommerce allows the shop owner to create and sell tickets directly to customers. Have a loot at the [Feature Overview](https://docs.woocommerce.com/document/woocommerce-box-office/#section-1).

- The extension adds ticket settings to a product edit page. 
- Each ticket can have Ticket  Fields, questions for each ticket holder. On the single product page, a form is displayed based on ticket fields defined. Fields with auto-fill will already have data in them if the customer is logged in.
- Updating quantity also updates the ticket form. For example: Changing the quantity to 2 will display two ticket forms — Ticket 1 and Ticket 2. 
- After purchase, a list of tickets can be seen on:
    - Order complete page
    - Order complete email
    - My Account page
    - PDF invoice generated by WooCommerce PDF Invoices (separate purchase)

This extension touches: *(mark all that apply)*

- [x] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [x] Add to cart button
      _Button's text is "Ticket Detail" and it's a link to the Product view_
- [x] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [x] Add to cart form
      _A form with the defined Ticket  Fields are shown near the purchase button. [See image](https://docs.woocommerce.com/wp-content/uploads/2016/04/Screen-Shot-2016-04-20-at-2.30.15-PM.png)_
- [x] My Account Page
    - _A My tickets section is included._ [See image](https://user-images.githubusercontent.com/1628454/116527783-573f4300-a8db-11eb-8b29-f51459e51a06.png)
- [ ] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [x] Custom functionality
  _The customer can't update ticket quantity_
- [x] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [x] Thanks page
  _A Tickets section is displayed at the end of the page. [See image](https://user-images.githubusercontent.com/1628454/117297590-b1f61300-ae76-11eb-8a5b-2f8c4004744f.png)_
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [x] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

*See how the extension does or does not work when using Product Blocks, Cart Block, and Checkout Block. Does it work as expected? Is functionality that works with the shortcodes broken in the blocks context?*

All blocks work as expected when handling Ticket products. There are some small issues:

- All Product Blocks:
    - the product button adds the ticket to the cart. It should be a link to the product page, so that the customer can fill the Ticket Fileds.
- Cart Block
    - the customer can modify the quantity. In the short code cart the user is prevented from changing it, because each ticket should have unique Ticket Fields


Issues identified:
- For a Ticket product, the button displayed inside All Products block adds the product to the cart. It should be a link to the product page.
- The cart block allows the customer to modify the number of tickets. In the short code cart the user is prevented from changing it, because each ticket should have unique Ticket Fields

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [x] Product Blocks
- [x] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
|All products Block| Component |Ability to change the behaviour of the product button|  *?*      |
| Cart block | Component | Ability to prevent changing quantity |  *?*   |

**Comment by mss-souloftware** [comment]
Hello,

I'm using WooCommerce Box Office plugin and I want to customize this plugin according to my requirements for example I want to add another field option called 'file' so user can upload files as well while ordering product, I already add file type on the backend Here you can see:
![image](https://github.com/woocommerce/woocommerce-blocks/assets/97556179/265f74f7-830e-4671-b463-7cdeee5d4e5d)
And it's also showing on the frontend:
![image](https://github.com/woocommerce/woocommerce-blocks/assets/97556179/9e500ec4-f380-4ab7-b4de-7d7bad9e60a9)
But the issue is when I submit the form it's indicate the error called **_"File is a required field and can not be empty."_** I already try to attached different file type but the error remains the same so can someone help me with that it's gonna be a very much appreciating.

Thank you. 

Plugin url: https://woocommerce.com/products/woocommerce-box-office

**Comment by ralucaStan** [comment]
@mss-souloftware unfortunately we can't help you with your question, as it's not related to the WooCommerce Blocks plugin. 
I suggest trying out other public channels where you can get some community support, like the WooCommerce Community Slack or the forum.
