### ISSUE TITLE
Audit: MyWorks WooSync for Quickbooks Online

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4123]
## QuickBooks Sync for WooCommerce

- **Author:** MyWorks Software
- **Website:** https://woocommerce.com/products/quickbooks-sync-for-woocommerce/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/myworks-woo-sync-for-quickbooks-online

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

On the front-end this extension does nothing, it is a back-end plugin which syncs orders to the QuickBooks accounting software. The orders are captured by the extension then transmitted to QuickBooks via their API.

*Write a brief summary of the extension's functionality, *

This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart form
- [ ] My Account Page
- [ ] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Yes the plugin works fine, the orders made using the Blocks checkout were captured by the extension and could be transmitted successfully to Quickbooks with all of the correct data.

Issues identified:
- *Summarize any issues you found with the extension*

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| *Location of new integration point, or name of existing integration point.* | *Type e.g. client API, action or filter hook, component, or server side API.* | *Describe what the integration point will be used for.* |  *1*   |
|  |         |
