### ISSUE TITLE
Audit: Gravity Forms Product Addons

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4124]
## Gravity Forms Product Add-ons

- **Author:** Element Stark
- **Website:** https://woocommerce.com/products/gravity-forms-add-ons/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/woocommerce-gravityforms-product-addons

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

Gravity Forms product addons allows the merchant to add a Gravity form to a product page. Each field in the form will act as an addon to that product (the same way that Product Addons works). The merchant can build complex forms with conditional logic which result in detailed customisation flows.
![image](https://user-images.githubusercontent.com/5656702/116377419-12e37280-a809-11eb-97bc-ff4de80dd08f.png)


This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [x] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [x] Product Prices
  - [x] Add to cart form
- [ ] My Account Page
- [ ] Cart Page
  - [x] Product prices
  - [x] Product meta
  - [x] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [x] Product prices
  - [x] Product meta
  - [x] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

This product works well with Blocks, the form creator runs on its own page and is attached to the product through the edit product page. On the front end product page, the form is rendered and the totals are updated as the customer changes values in the form. When the customer has finished customising their product it can be added to the cart with the options selected added as meta data. Multiple different configurations of the same product can be added.

![image](https://user-images.githubusercontent.com/5656702/116377741-66ee5700-a809-11eb-862a-dcf08006a554.png)


Issues identified:
- *Summarize any issues you found with the extension*

*Select those that apply:*

- [x] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| *Location of new integration point, or name of existing integration point.* | *Type e.g. client API, action or filter hook, component, or server side API.* | *Describe what the integration point will be used for.* |  *1*   |
|  |         |
