### ISSUE TITLE
Audit: One Page Checkout

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4125]
## WooCommerce One Page Checkout

- **Author:** Automattic
- **Website:** https://woocommerce.com/products/woocommerce-one-page-checkout/
- **Repository:** (private) https://github.com/woocommerce/woocommerce-one-page-checkout

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

This extension allows merchants to create a "one-page checkout" where the customer can add products to their cart, and instantly check out without leaving the page. 

The merchant may enable the "One page checkout" option on the product page. This adds the checkout form at the bottom of the single product page.

There is also the option for the merchant to add a shortcode which allows them to define products to include on the one-page checkout. This creates a "pseudo-cart" allowing the customer to change product quantities.
![image](https://user-images.githubusercontent.com/5656702/116382969-57254180-a80e-11eb-8b43-9a3e77bf5c5b.png)
Below this is the normal shortcode checkout.

This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [x] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [x] Add to cart form
- [ ] My Account Page
- [ ] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

The extension itself uses the shortcode checkout, and has its own "pseudo-cart", it doesn't really interact with blocks insofar as its functionality is self contained.


Issues identified:
- The checkout offered by this extension is still the shortcode checkout. It could use the Blocks checkout.
- To add the one-page checkout to a page, you have to use a shortcode, the extension should create its own block to allow it to be added easily.
- If the extension used the cart block to display product quantities and prices, it would need the option to remove certain elements, for example the 'Proceed to checkout' button, the shipping calculator, and cart totals.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [x] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [x] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| Cart block/remove specific elements from the block | Component modification, change options in the cart block | The extension would need to be able to disable elements of the cart block, for example the proceed to checkout button, cart totals and shipping calculator. |  2  |
|  |         |
