### ISSUE TITLE
Audit: Fedex

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4126]
## FedEx Shipping Method

- **Author:** Automattic
- **Website:** https://woocommerce.com/products/fedex-shipping-module/
- **Repository:** (private) https://github.com/woocommerce/woocommerce-shipping-fedex

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review
The extension adds a shipping method, provided by FedEx - it communicates with FedEx via SOAP and provides live rates for shipping. These are viewable in the cart (after the user enters their address into the shipping calculator) and checkout.

This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart form
- [ ] My Account Page
- [ ] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [x] Notices
  - [x] Shipping Methods
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [x] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [x] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [x] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks
The extension adds the FedEx shipping methods correctly to the Blocks cart and checkout and updates them when the address changes. Totals are updated when the shipping method changes.

Issues identified:
- When running the extension in debug mode, notices are posted to the top of the shortcode cart and checkout pages, this does not happen in the blocks.
- 
*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*


This extension requires integration with: 

- [ ] Product Blocks
- [x] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| Needs a way to add and remove notices on the cart and checkout pages. Or it needs to find a way to display these notices to the customer outside of notices | Client API or Component | When running in debug mode, the extension shows information about the requests to the FedEx API in notices. |  *3*   |
|  |         |

**Comment by opr** [comment]
It turns out that the debug notices do appear in the blocks contexts. On first load they don't, but they do appear on subsequent loads.
