### ISSUE TITLE
Audit: Name your price

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4127]
## Name Your Price

- **Author:** Backcourt Development
- **Website:** https://woocommerce.com/products/name-your-price/
- **Repository:** (private) https://github.com/woocommerce/all-plugins/tree/master/product-packages/woocommerce-name-your-price

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

The extension modifies the product page and inserts an input field where the price would ordinarily be. This input field allows the customer to input the price they want to pay for an item.

The extension does not seem to interact any further with the store besides modifying the price of an item in the session cart. WooCommerce Blocks cart block simply receives the data with the customised price.

There is an option to change the text on the `Add to cart` button on the shop page, which works OK with the All Products block.

This extension touches:

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [x] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [x] Add to cart form
- [ ] My Account Page
- [ ] Cart Page
  - [x] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [x] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [x] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

This extension works as expected with WooCommerce Blocks - the changes to the Add to Cart button work in Product blocks, and the price the customer chooses is shown in the Cart and Checkout sidebars, and the cart totals are correct and reflect this.

Issues identified:
- None

*Select those that apply:*

- [x] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| *Location of new integration point, or name of existing integration point.* | *Type e.g. client API, action or filter hook, component, or server side API.* | *Describe what the integration point will be used for.* |  *1*   |
|  |         |
