### ISSUE TITLE
Audit: Cart Add-ons

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#4136]
## Cart Add-ons

- **Author:** Automattic
- **Website:** https://woocommerce.com/products/cart-add-ons/
- **Repository:** (private) https://github.com/woocommerce/woocommerce-cart-add-ons

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the Epic for the audit template](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4129) which should be completed and posted as a comment here once completed._

**Comment by ralucaStan** [comment]
# Extension Audit Template

## Functionality Review
The extension shows cross-sell items on cart views. [View image](https://woocommerce.com/wp-content/uploads/2012/07/addons.png?resize=958,1598)
The shop owner can [customize](https://docs.woocommerce.com/document/cart-add-ons/#section-1) the cross-sell section by:
- editing a Display title
- entering a Maximum products to show
- using Select Default Add-Ons setting
- using Select Category Matches setting
- using Select Product Matches setting



This extension touches: *(mark all that apply)*

- [ ] Product Grids (shop page)
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product Details
  - [ ] Product Prices
  - [ ] Add to cart form
- [ ] My Account Page
- [x] Cart Page
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [x] Custom functionality
  _Additonal cross-sell section with products is shown under the cart_
- [ ] Checkout Page
  - [ ] Checkout Fields
  - [ ] Product prices
  - [ ] Product meta
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Payment Methods
  - [ ] Shipping Methods
  - [ ] Thanks page
- [ ] Rest API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [x] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer
  - [x] Appearence > Widget

## Compatibility with Blocks

The extension does not work at well with the Cart block. The cross-sell section is not displayed.
However, the user ca add on the page a [shorcode block](https://docs.woocommerce.com/document/cart-add-ons/#section-2) for `[display-addons ...options]`. The shortcode works as expected, showing the products the shop owner has selected.

Issues identified:
- The Cart block does not show the cross-sell section

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Product Blocks
- [x] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                               | Type                                                                                  | Description                                           | Effort |
|----------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------|:------:|
| Cart block | Component | Display the cross sell section |  *?*         |
