### ISSUE TITLE
How can I change the design of the cart?

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4161]
This is what my cart page looks like right now.
https://i.imgur.com/x79gQ63.png

I want it to look like this
https://i.imgur.com/vpBFDxB.png

The "Quantity" column is shown here and in my cart it is not shown. The cart looks like I'm missing css.

**Comment by senadir** [comment]
Hey, this design update was introduced in version 4.4 ([issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3631), [pull request](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3734)) to fix some pain points in the previous design, therefore, there is no way to get that back because it's a big structural change.

I'm going to close this issue for now because there's nothing I can do, if you have any other questions or requests about this, feel free to comment here and I will open the issue.

Have a great day!
