### ISSUE TITLE
REST API: Add Changes to corresponding wc/v3 endpoints

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-gutenberg-products-block#426]
To prep for merge of the blocks logic into WooCommerce core, the additions to the REST API endpoints need to be migrated to cores `wc/v3` namespace.

- [x] [WGPB_Product_Attribute_Terms_Controller](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/includes/class-wgpb-product-attribute-terms-controller.php) => `WC_REST_Product_Attribute_Terms_Controller`
- [x] [WGPB_Product_Attributes_Controller](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/includes/class-wgpb-product-attributes-controller.php) =>`WC_REST_Product_Attributes_Controller`
- [x] [WGPB_Product_Categories_Controller ](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/includes/class-wgpb-product-categories-controller.php) => `WC_REST_Product_Categories_Controller`
- [x] [WGPB_Products_Controller](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/includes/class-wgpb-products-controller.php) => `WC_REST_Products_Controller`

**Comment by justinshreve** [comment]
I actually think this means that upon merge, these become `v4` and everything else in development gets bumped up to `v5`. Versioning in Woo Core is handled differently from WordPress.com.

I think this is the case even if these just add fields/endpoints and not just breaking changes.

cc @claudiosanches  / @peterfabian that is correct, right?

**Comment by peterfabian** [comment]
You're right, @justinshreve. This needs to be added as v4, then our current wc-admin work should become v5.

**Comment by claudiosanches** [comment]
This endpoints are used for internal use, since required different types of user capability when dealing with requests from the editor, we can't only accept high level users in those requests like we does in our regular endpoints, we also reduced the amount of data in each endpoint to just what is essential for each block.
So we could include this in core in 3.6, and also try block access from outside wp-admin, leaving way from our regular REST API.

**Comment by timmyc** [comment]
Hmm so I'm probably going about this the wrong way for the changes to the terms controller. @claudiosanches so are you thinking we can maybe create a new `context` specifically for use within blocks and just add the logic to the existing v3 endpoints?

**Comment by claudiosanches** [comment]
We can bump versions if you all prefer, but we can't just merge like suggested:

![screenshot from 2019-02-15 17-30-31](https://user-images.githubusercontent.com/1264099/52879851-6e087d80-3147-11e9-90c5-6fb0f9c8c0ba.png)

Those classes names should be new and probably indicating that is for internal use, something like `WC_REST_Blocks_Products_Controller` or `WC_REST_Editor_Products_Controller`.

**Comment by claudiosanches** [comment]
@timmyc we could create a new `context`, but we need to be careful how we handle authentication when checking for user level and context.

**Comment by timmyc** [comment]
Gotcha, so it seems like two routes here:

- Create new "internal" endpoints, with their own namespace, really kind of like what is already in place, just bring it into `wc/v3`
- Add a new context / auth and bump to `v4`

**Comment by ryelle** [comment]
It sounds like we should be using the view context for this kind of request anyway, perhaps we should update the endpoints to correctly use the view/edit distinction, and allow anyone with `edit_posts` to view data? (so we don't expose anything potentially sensitive, though I'm not sure what that might be off the top of my head)

**Comment by claudiosanches** [comment]
@timmyc 
Ohh yeah, there is also the possibly of a new namespace, instead of `wc/v3`, we could use a new one for it.

@ryelle 

>  and allow anyone with `edit_posts` to view data?

I just want to avoid expose any data before let people know about, if we are going to change this in our current endpoints, probably good to communicate before, and even let disable those endpoints and by consequence all blocks.

**Comment by ryelle** [comment]
> probably good to communicate before, and even let disable those endpoints and by consequence all blocks.

Either way we'll be opening this data for all edit_posts users, so won't we need to do this regardless?

**Comment by ryelle** [comment]
And by merging the endpoints & using context, we can keep all the product endpoint code in one place.

**Comment by timmyc** [comment]
@claudiosanches to get things rolling here I opened up a PR with the `/v4` approach:

https://github.com/woocommerce/woocommerce/pull/22793

Given this endpoint is already secured/restricted, it seems like this is a valid route to bring over the changes needed by blocks. I'm not certain if we need a new context or namespace, but I also get a bit confused on the version numbers of the REST API in core - like if we do a v4 for some endpoints, do we have to v4 them all? But anyhow I think this is an area of merging in blocks that we could really use your help with if you have some time since you know the ins/outs of the core REST API.

**Comment by claudiosanches** [comment]
@timmyc 

> Given this endpoint is already secured/restricted, it seems like this is a valid route to bring over the changes needed by blocks. I'm not certain if we need a new context or namespace

It's not secured/restricted like we need for blocks, note that all new permission checks is missing from woocommerce/woocommerce#22793 and it will bring back this issue: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/153

> but I also get a bit confused on the version numbers of the REST API in core - like if we do a v4 for some endpoints, do we have to v4 them all?

Yes, we need register all new routes on v4.

**Comment by claudiosanches** [comment]
Also [woocommerce/woocommerce#22793](https://github.com/woocommerce/woocommerce/pull/22793)  makes a little redundant our endpoint, including attribute name and slug, so all results from `wp-json/wc/v4/products/attributes/<id>/terms` will care the same data, since we already knows the attribute because the ID and we can fetch data from `wp-json/wc/v4/products/attributes/<id>`, but this has been implemented here just to avoid multiple calls into the REST API... Not sure if something for performance on blocks should be included for everyone in the regular REST API.
