### ISSUE TITLE
legacy handling for payment processing

### ISSUE THREAD

**Issue by tak-bull** [woocommerce/woocommerce-gutenberg-products-block#4283]
Hi
trying to work with blocks with our payment gateway (https://wordpress.org/plugins/takbull-gateway/) but its not showing in checkout
tried to register with Server Side Integration but still no success

**Comment by nerrad** [comment]
Hi there @tak-bull  👋 

Thanks for taking the time to leave an issue!

It's a bit unclear to me what you are requesting here but I'm assuming it has to do with some difficulty you are having with your payment gateway not working with the Cart and Checkout Blocks. 

There is some [documentation available](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) for integrating payment gateways with the blocks which [we also announced here](https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/). 

I'm going to close this issue because there's nothing actionable for it, however if you have additional questions please don't hesitate to continue the conversation. I do ask that you try to be specific though.
