### ISSUE TITLE
Ability to add custom checkout fields

### ISSUE THREAD

**Issue by pohlstrategic** [woocommerce/woocommerce-gutenberg-products-block#4288]
## What do you like about the Cart & Checkout blocks?

Love the functionality of the layout and simplicity of implementation.

## What do you think is missing from the Cart & Checkout blocks?

Ability to add custom checkout fields. Do you have any timeline for this feature, ability to integrate with an existing plugin or simple way to add a hook / custom code?

**Comment by senadir** [comment]
Hey, we're actively working on this, either via support from Checkout Field Editor, or via an integration point. We don't have a specific timeline for this because there're a lot of things that are still unknown, but expect more updates during the months as we tackle this issue.

For the time being, I'm going to close this issue because there's nothing actionable we can do on it. Thank you for your feedback.
