### ISSUE TITLE
Mercado Pago Integration?

### ISSUE THREAD

**Issue by pachajsc** [woocommerce/woocommerce-gutenberg-products-block#4296]
## What do you like about the Cart & Checkout blocks?

Its very intuitive.

## What do you think is missing from the Cart & Checkout blocks?

I cant integrate Mercado Pago en de checkout

**Comment by senadir** [comment]
Hey there @pachajsc 
What type of integration are you trying to do? and what kind of blockers are you seeing?
Can you also link to the plugin?

**Comment by nerrad** [comment]
Hi there @pachajsc - we'd love to see if we can help you with your issue but we're still waiting for answers to the questions @senadir asked above. I'm going to close this issue for now because there is nothing currently in this issue that we can act on. However, if you have additional information to offer, please do update the issue and if necessary we can reopen.
