### ISSUE TITLE
Add an action that checks for changes to any `*.asset.php` files and highlights them in the conversation of the PR

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#4399]
Following an incident report (pca54o-1Hq-p2) ~~I propose we add a GitHub action that checks for any changes to the `*.asset.php` files generated in the `build` directory when a PR is made.~~

Edited to include Darren's suggestion:

---
**So what this automation would have to do is:**

- Build a branch of current trunk and cache all *.asset.php files (or read from a cache artifact that is automatically created on every merge to trunk).
- Build a branch of the PR and compare the contents of each *.assets.php file generated from the PR build with the trunk build and make note of any changes to dependencies within the php file.
Note, the dependency extraction plugin has the ability to write dependencies to json files instead of PHP, so we could potentially create a Webpack config that does that on a special build for this check (to make the comparison a bit easier to do within a node script).

---

Based on the incident report, we should ensure that context is provided in the comment, explaining _why_ the change is being highlighted. Reviewers should be made aware that changes to dependencies should be discussed and find out why they're being made, the potential performance impact is discussed and weighed up, and any potential compatibility impact, especially in the case of the changes being moved into WooCommerce Core is well considered.

~~Right now I am not sure what actions (if any) we can use to make this easy, but it's essentially going to be a check to see if any files matching `*.asset.php` are present in the diff.~~

**Comment by nerrad** [comment]
> Right now I am not sure what actions (if any) we can use to make this easy, but it's essentially going to be a check to see if any files matching *.asset.php are present in the diff.

Just to clarify, that's not really what I was suggesting. Build files aren't committed to the repo. So what this automation would have to do is:

- Build a branch of current trunk and cache all `*.asset.php` files (or read from a cache artifact that is automatically created on every merge to trunk).
- Build a branch of the PR and compare the _contents_ of each `*.assets.php` file generated from the PR build with the trunk build and make note of any changes to dependencies within the php file.

Note, the dependency extraction plugin has the ability to write dependencies to `json` files instead of PHP, so we could potentially create a Webpack config that does that on a special build for this check (to make the comparison a bit easier to do within a node script).

**Comment by opr** [comment]
Ah right, of course they're not committed... Yes your suggestion is better. Perhaps a build of `trunk` each time would be better than a cache artefact, that way any PRs created immediately after a merge into `trunk` but before the creation of this artefact would be checked properly. It's an edge case but worth considering.

> Note, the dependency extraction plugin has the ability to write dependencies to json files instead of PHP, so we could potentially create a Webpack config that does that on a special build for this check (to make the comparison a bit easier to do within a node script).

This depends how in-depth we want to be with the comparison, if we just want to highlight files that have changed either will be fine, but if we want to specifically highlight the newly added/removed dependencies JSON would be better.
