### ISSUE TITLE
Respect `key` attributes in Cart Items meta over `name`

### ISSUE THREAD

**Issue by jamsheerkrd** [woocommerce/woocommerce-gutenberg-products-block#4400]
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/196a68a781b5ade93d6d42140f2a2165ed6cfae5/assets/js/base/components/cart-checkout/product-details/index.tsx#L46

Here it can see using "name" filed, whereas, in default cart shortcode (PHP), it is given preference for "key", instead of name

https://github.com/woocommerce/woocommerce/blob/d1f5784fa479078a375438adc961726158f7fafb/includes/wc-template-functions.php#L3669

**Comment by senadir** [comment]
`name` acts the same as `key`.
I did a search in [WPdirectory](https://wpdirectory.net/search/01F9EMXM9Q8G9M4D8W9CBMEPJM) and I see mixed usage but with the majority using key instead of name.
@Aljullu any reason why you defaulted to `name`?
I can see that for plugins like WC Subscriptions and Product Add-on, we use `name` but WooCommerce core uses `key` instead.

So this feels like a valid issue, feel free to contribute a solution @jamsheerkrd or wait until someone from the team picks this up.

**Comment by Aljullu** [comment]
> @Aljullu any reason why you defaulted to `name`?

Looks like an oversight from my part, so I agree this is a valid issue. :slightly_smiling_face:  When fixing it, we should make sure it doesn't break the display of variations, which if I'm not wrong use the same component.

**Comment by senadir** [comment]
A good approach is to follow WooCommerce Core of prioritizing `key` but still supporting `name`.
