### ISSUE TITLE
I have a pro with plugin, please can someone write to me back to solve it please

### ISSUE THREAD

**Issue by nerminnn** [woocommerce/woocommerce-gutenberg-products-block#4438]

**Comment by nerminnn** [comment]
first of all, I am using another plugin for an Egyptian payment gateway company and it supposed to offer the bank transfer, in their documentation the integration is compatible with WP, but one I made the settings it doesn't show that I have another payment method in the block plugin, please I need urgent help

**Comment by opr** [comment]
Hi there @nerminnn! Thanks for taking the time to submit this issue, in your message you wrote:

> in their documentation the integration is compatible with WP

Based on this, I'm making the assumption that you're using an extension provided by the payment gateway provider, and the rest of my response will be based on this, but please correct me if this assumption is wrong.

Which payment provider is it, and could you link to their plugin?

Are they specific about their integration working with _WooCommerce Blocks_ because this requires extra work by the extension author. Being compatible with WordPress usually does not guarantee compatibility with Blocks. 

There is some [documentation available](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) for integrating payment gateways with the blocks which we also [announced here](https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/) that could be useful to pass on to the developer of the extension.

I’m going to close this issue because there’s nothing actionable for it based on what I understand, however if you have additional questions please don’t hesitate to continue the conversation. I do ask that you try to be specific in what difficulties you're facing, though.

**Comment by nerminnn** [comment]
I am sorry but I was disappointed because I contacted the support team and they did really help, https://docs.paymob.com/docs/woocommerce
here is the link above, they didn't mention if it is working with blocks or not.

**Comment by opr** [comment]
Hi again @nerminnn - I had a look at the documentation for this plugin, and since they have not been explicit about their integration with WooCommerce Blocks, I think it's safe to assume that no integration work has been done by the extension developers.

You might wish to reach out to the extension developers and ask if they are considering adding support for Blocks, and perhaps send them the links to [our documentation](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) to help them get started.
