### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by bzzee** [woocommerce/woocommerce-gutenberg-products-block#4439]
## What do you like about the Cart & Checkout blocks?
looks great, easy to use

## What do you think is missing from the Cart & Checkout blocks?
can't integrate with some plugin (from woocommerce by the way: delivery slot and tips)

**Comment by opr** [comment]
Hi there @bzzee 👋🏼 

I think you're talking about: `Delivery Slots for WooCommerce` and `Tipping for WooCommerce` right?

Thanks for taking the time to make us aware that these extensions aren't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

We’re currently working on adding extensibility for the blocks so extensions have a way to make sure they integrate with the new flows we’re developing. Once that is done we’ll have docs prepared and will be reaching out to Woo Extension developers to help them with getting their extensions integrated.

Until then you can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

Since there's nothing actionable for us as a result of this issue, I'll go ahead and close it, but feel free to continue the discussion if there's any new information to add.
