### ISSUE TITLE
Cart & Checkout blocks doesn't work when Elementor Pro plugin is activated.

### ISSUE THREAD

**Issue by mescal01** [woocommerce/woocommerce-gutenberg-products-block#4506]
## What do you like about the Cart & Checkout blocks?
The clean layout but requires work to make it work properly. It doesn't play nicely with specific plugins, see below.

## What do you think is missing from the Cart & Checkout blocks? 

Cart & Checkout blocks doesn't work when Elementor Pro plugin is activated. Also, the Checkout block doesn't adjust to the page width (order summary bleeds over) and the Terms & Conditions and Privacy Policy links are not in alignment with each other.

**Comment by mikejolley** [comment]
Hi @mescal01 

Since Elementor Pro is premium software that requires a subscription to access, this isn't something we can test against. I'd recommend contacting Elementor premium support to see if they can offer a solution or workaround to any incompatibilities.

I was able to test against the free Elementor page builder plugin (https://en-gb.wordpress.org/plugins/elementor/). I found that simply the presence of Elementor did not break the Blocks, and pages edited with Elementor also worked. The Block didn't render in the Elementor editor, however, which appears to be due to frontend script dependencies not being loaded. This seems to be an Elementor problem in the way it tries to support Gutenberg blocks. I do not believe this is something we should fix in Blocks since it's Page Builder specific. 

> Also, the Checkout block doesn't adjust to the page width (order summary bleeds over) and the Terms & Conditions and Privacy Policy links are not in alignment with each other.

This is something we can look at because it sounds theme related. I request that you [submit a new issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/new/choose) specifically for this problem, and include screenshots of the problem as well as a link to the site. If it's styling related we can potentially fix this.

Thank you
