### ISSUE TITLE
woo-gutenberg-products-block plugin version differs from woo-gutenberg-products-block package on main plugin

### ISSUE THREAD

**Issue by fioa8c** [woocommerce/woocommerce-gutenberg-products-block#4523]
Hey there,

It was brought to my attention that `woo-gutenberg-products-block` plugin has its version updated to `5.5.1`, however, the package distributed along with `woocommerce` on `woocommerce/packages/woocommerce-blocks/woocommerce-gutenberg-products-block.php` still shows the vulnerable `5.3.3`.

I checked it is not vulnerable, but it is triggering some security tools that rely on version checking.

Could you adjust that?

Thank you.

**Comment by mikejolley** [comment]
@rodelgc I think the report was aimed at the tool stating that blocks is vulnerable (it's not), rather than reporting a bug with blocks itself.

5.3.3 is not vulnerable. The security fix was backported as a patch release on all previous minor versions. 5.3.2 had the issue, 5.3.3 is patched. 

I'm not sure where this was originally reported (GitHub doesn't show that info), so I am closing rather than moving. @fioa8c may need to reopen this in the original repository.

Thanks cc @nerrad

**Comment by nerrad** [comment]
It's also worth noting that the patches applied to WooCommerce core via WordPress.org did _not_ update package version for the included WooCommerce blocks package because the patches were directly applied to the Woo Blocks files in Woo Core. So automated tools looking at what version of Woo Blocks is on the patched versions of Woo Core (distributed on WordPress.org) could get false triggers.

**Comment by fioa8c** [comment]
@mikejolley, I reported this on `woocommerce/woocommerce`. I think @nerrad explained it perfectly.
