### ISSUE TITLE
How to extend "WOOCOMMERCE PRODUCT ELEMENTS"

### ISSUE THREAD

**Issue by larsenlarsson** [woocommerce/woocommerce-gutenberg-products-block#4554]
## Is your feature request related to a problem? Please describe.
Using the "All Products" block, there are several "inner blocks" available (WooCommerce Product Elements). 
We would like to develop an extension that adds its own additional element

![a](https://user-images.githubusercontent.com/2648926/128488466-b7eda4fb-4201-414c-ad07-e6c481d4fe3b.png)

## Describe the solution you'd like
Due to lack of documentation in the code and here on Github, we wanted to ask if there are any examples or guidance on how to implement this or if the possibility doesn't even exist.

## Additional context
Will these "WOOCOMMERCE PRODUCT ELEMENTS" be available for the other product blocks as well? The "All Products" block behaves completely different compared to the other blocks.

**Comment by mikejolley** [comment]
Hi,

This hasn't been documented in detail because they are experimental. They do not get displayed in the block inserter unless you're on a development build from Github.

When registering your blocks, ensure you set the correct parent and category (see https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/343f70d7af57f751c327349dec864f9e176d0f70/assets/js/atomic/blocks/product-elements/shared/config.js#L16).

Additionally, for the frontend rendering, a component needs to be defined: https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/89b5d3032aa9d8b7368ba4edd3da222d076fbcaa/assets/js/blocks/cart-checkout/checkout-i2/inner-blocks/register-components.ts#L12-L20 The lazy loading there is optional.

You can expect more documentation around `registerBlockComponent` to appear in the coming weeks as Checkout i2 develops (since this is going to use the same system).

Thanks

**Comment by nerrad** [comment]
Hi there @larsenlarsson I hope [MIke's comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4554#issuecomment-894337390) was helpful for you. I'm going to close this because there's nothing currently actionable for us to do here.

If you have additional questions or comments related to your initial post, please do add to the issue - we'll see them!
