### ISSUE TITLE
Access to additional block settings in the 'woocommerce_blocks_product_grid_item_html' hook

### ISSUE THREAD

**Issue by larsenlarsson** [woocommerce/woocommerce-gutenberg-products-block#4555]
We managed with some code to add additional properties to the product blocks (except "All products").

![Bildschirmfoto 2021-08-06 um 11 39 50](https://user-images.githubusercontent.com/2648926/128491224-429f9da9-d5eb-4493-89b9-32f89a1f5fbe.png)

Depending on whether our additional settings are enabled or disabled, we want to manipulate the output.

So far, this only works with the hook "woocommerce_blocks_product_grid_item_html". 
At this point, unfortunately, it is not possible to access the settings set in the block. 
Here it would be nice to pass the attributes to the hook as an additional parameter ($this->attributes), as this would give you access to the settings set.

```
return apply_filters(
			'woocommerce_blocks_product_grid_item_html',
			"<li class=\"wc-block-grid__product\">
				<a href=\"{$data->permalink}\" class=\"wc-block-grid__product-link\">
					{$data->image}
					{$data->title}
				</a>
				{$data->badge}
				{$data->price}
				{$data->rating}
				{$data->button}
			</li>",
			$data,
			$product,
			$this->attributes
		);
```

Otherwise, we have no way to find out if our set settings are set in the block to manipulate the content if necessary.

Could such a solution or in a similar form be integrated?

===

Thus, in generalized form, we have added the settings:

```

/**
 * Enqueue general editor scripts
 */
add_action('enqueue_block_editor_assets', function() {
	wp_enqueue_script('woo-blocks-edit', '/path-to-edit-js/edit.js', array( 'wp-blocks', 'wp-edit-post', 'jquery' ) );
});


/**
 * Add attributes to Woo Blocks
 * 
 * @param array $args
 * @param string $name
 * @return array $args 
 */
add_filter( 'register_block_type_args', function( $args, $name ) {

	$blocks = [ 
        'woocommerce/handpicked-products',
        'woocommerce/product-best-sellers',
        'woocommerce/product-category',
        'woocommerce/product-new',
        'woocommerce/product-on-sale',
        'woocommerce/products-by-attribute',
        'woocommerce/product-top-rated'
    ];

	if ( in_array( $name, $blocks ) ) {

		$args[ 'attributes' ][ 'option1' ] = array(
			'type' => 'boolean',
			'default' => false
		);

		$args[ 'attributes' ][ 'option2' ] = array(
			 'type' => 'boolean',
			 'default' => false
		 );

	}

	return $args;

}, 10, 2 );
```

```
**
 * Add attributes to blocks
 * 
 * @param {Array} settings 
 * @param {String} name 
 */
function addWooBlocksAttributes(settings, name) {

	var blocks = blocks = [ 
        'woocommerce/handpicked-products',
        'woocommerce/product-best-sellers',
        'woocommerce/product-category',
        'woocommerce/product-new',
        'woocommerce/product-on-sale',
        'woocommerce/products-by-attribute',
        'woocommerce/product-top-rated',
    ];

	if ( blocks.includes(name) ) {
		
		settings.attributes = Object.assign(settings.attributes, {
			option1: {
				type: 'boolean',
				default: false
			},
			option2: {
				type: 'boolean',
				default: false
			}
		});

	}

	return settings;
}
 
wp.hooks.addFilter(
	'blocks.registerBlockType',
	'myplugin/woo-blocks-custom-attributes',
	addWooBlocksAttributes
);

/**
 * Add additional Panels and Controls to blocks
 */
const wooBlocksInspectorControls = wp.compose.compose(
 
	wp.compose.createHigherOrderComponent((BlockEdit) => {
		return (props) => {
            
            var blocks = blocks = [ 
				'woocommerce/handpicked-products',
				'woocommerce/product-best-sellers',
				'woocommerce/product-category',
				'woocommerce/product-new',
				'woocommerce/product-on-sale',
				'woocommerce/products-by-attribute',
				'woocommerce/product-top-rated',
			];
            
			if ( ! blocks.includes(props.name) ) {
                return(<BlockEdit {...props} />);
            }
        
			const { Fragment } = wp.element;
			const { PanelBody, ToggleControl } = wp.components;
			const { InspectorControls } = wp.blockEditor;
			const { attributes, setAttributes, isSelected } = props;

			return (
				<Fragment>
					<div>
						<BlockEdit {...props} />
						{isSelected && (blocks.includes(props.name)) && 
							<InspectorControls>
                                <PanelBody
                                title={ 'Additional Settings' } >
									<ToggleControl
										label={ 'Option 1' }
										checked= { attributes.option1 }
										onChange={ (newval) => 
											setAttributes( { 
												option1: newval
											} )
										}
									/>
									<ToggleControl
										label={ 'Option 2' }
										checked= { attributes.option2 }
										onChange={ (newval) => 
											setAttributes( { 
												option2: newval
											} )
										}
									/>
                                </PanelBody>
							</InspectorControls>
						}
					</div>
				</Fragment>
			);
		};
}, 'wooBlocksInspectorControls'));
 
wp.hooks.addFilter(
	'editor.BlockEdit',
	'myplugin/woo-blocks-inspector-control',
	wooBlocksInspectorControls
);
```

We have created this code after researching the ticket https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891

**Comment by Aljullu** [comment]
Hi @larsenlarsson, thanks for using WooCommerce Blocks and opening this issue! As described in #891, product grid blocks don't have the same extensibility points as shortcodes & WC templates because they are intended to be customized with a different paradigm: customization will be done as much as possible from the block editor and will require less coding.

We are currently experimenting with WordPress' Query block as the new tech that might be powering our Product grid blocks. That will dramatically increase what's possible to customize from those blocks. We are still in early stages, so it's difficult to say if that's a viable path or whether this change will come some time soon.

I wonder if you could provide more details on what you are trying to achieve with _Option 1_ and _Option 2_. It would be great to hear about your use case to know if that's something that might be covered by a hypothetical refactor using the Query block or not.

**Comment by larsenlarsson** [comment]
Hey @Aljullu 

thanks for your response.

For instance, if _Option 1_ is avtivated, we would like to add some addional HTML-output after {$data->button}, but only if this option is activated. 

Or as another example, if _Option 2_ is enabled, we want to get outputs depending on meta-data of the product. For example, if _Option 2_ is active, output the tax class of the product.

**Comment by Aljullu** [comment]
Thanks for the details @larsenlarsson, I think the changes we are planning to explore in the following months will make it easier to implement something like what you described. As I said in the previous message, I can't be more specific given that there are still many unknows, but we are working on exploring the usage of the Query block in order to render Products (see https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4246), that would allow adding blocks after the button or adding a tax type block.

I'm going to close this issue given that there isn't anything actionable until we finish the exploration. But feel free to answer if you have something more to add.
