### ISSUE TITLE
Mini Cart block: after removing a product, drawer can't be closed clicking outside

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4618]
## To reproduce
In branch `add/drawer-component` (#4608):

1. Create a post or page and add a Mini Cart block.
2. Visit that post or page in the frontend and click on the Mini Cart button.
3. In the drawer that appears, remove one of the products from your cart.
4. Click on the overlay and notice the drawer doesn't close.
5. It can be workarounded clicking again somewhere inside the drawer and the outside again.

## Expected behavior
The drawer should close when clicking outside in all cases.

## Screenshots

https://user-images.githubusercontent.com/3616980/130471273-d7e7dbf0-a0e4-4713-925a-864505de6a2f.mp4

## Next steps

The Mini Cart block uses the [`Modal` Gutenberg component](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/modal), which internally uses the [`useFocusOutside()` hook](https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/src/hooks/use-focus-outside/index.js), so the issue might be there.

**Comment by gigitux** [comment]
I'm opening again this issue because we are still able to reproduce the problem.

Repro steps:
1. Create a post or page and add a Mini Cart block.
2. Add a Product to the cart.
3. Visit that post or page in the frontend and click on the Mini Cart button.
4. Remove the product.
5. Click on the overlay and notice the drawer doesn't close.

https://user-images.githubusercontent.com/4463174/152773953-990bb086-10d1-4f69-9cf6-eb99411c251e.mp4
