### ISSUE TITLE
Payment methods

### ISSUE THREAD

**Issue by Asterless1** [woocommerce/woocommerce-gutenberg-products-block#4654]
## What do you think is missing from the Cart & Checkout blocks?
Would be amazing to add different payment methods for the checkout and Cart page. Paypal is a must for most stores.

**Comment by nielslange** [comment]
Hello @Asterless1 ,
 
Thanks for taking the time to make us aware that PayPal isn't working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it's expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.
 
The WooCommerce Blocks plugin currently supports the following payment methods:

https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/#section-4

While this list also shows PayPal Standard, PayPal Standard had been hidden since WooCommerce 5.5.0. If it's crucial for your business to use both the WooCommerce Blocks and PayPal Standard, you can unhide PayPal Standard by adding the following code snippet to your site:

```
add_filter( 'woocommerce_should_load_paypal_standard', '__return_true' );
```

Once you added the code snippet to your site, you'll see the PayPal Standard payment option appearing within the WooCommerce payment settings, on the regular checkout page and within the checkout block of the WooCommerce Blocks plugin.

If using the WooCommerce Blocks and PayPal Standard is not crucial to your business, I suggest using the regular checkout page for the time being and switch to the checkout block, once the plugin supports one of the official PayPal extensions.

**Comment by ralucaStan** [comment]
According to this https://github.com/woocommerce/woocommerce-paypal-payments/issues/211#issuecomment-1551145433 a new pre-release for the next PayPal Payments 2.0.5 is available [on GitHub](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.5-rc1) with express payment methods support in the WooCommerce blocks.
