### ISSUE TITLE
Checkout Order Summary displays product's short description & removes/escapes embedded html

### ISSUE THREAD

**Issue by TomDeFord** [woocommerce/woocommerce-gutenberg-products-block#4706]
## Describe the bug
Checkout Order Summary displays product's short description & removes/escapes embedded html

## To reproduce
1. Add product to cart that has a short description, go to checkout
2. If short description contains raw html this is removed/escaped

## Expected behavior
1. Current core checkout does not show short description
2. Current core displays short descriptions without escaping them so simple html formatting can be used, say in the product quick view
3. Add option to checkout to show/not show short descriptions.
4. Do not escape html

## Environment
* Core version: 5.8.0
* WooCommerce version: 5.6.0
* WooCommerce Blocks version: 5.8.0

**Comment by nerrad** [comment]
Hi there @TomDeFord 👋🏻 

What you are describing is not the current behaviour I'm seeing. In fact we have an open issue (see #3142) for stripping images form the product summary shown in the Cart and Checkout blocks.

As a test I added a short description with bold text and an image to a product's short description field:

<img width="1430" alt="CleanShot 2021-09-16 at 07 41 37@2x" src="https://user-images.githubusercontent.com/1429108/133606154-e9510fc6-b655-44a5-b373-12c75c34a3bc.png">

On the frontend it appears like this:

<img width="553" alt="CleanShot 2021-09-16 at 07 41 50@2x" src="https://user-images.githubusercontent.com/1429108/133606011-559adaab-b3ec-4a85-860d-deb788bc6c4b.png">

If you could share with us some additional details on how to reproduce what you are reporting that will be helpful!

**Comment by TomDeFord** [comment]
Hi there, so there are 2 issues, the first is that the short description has been added to the cart & checkout, this is new functionality which will affect existing users unless a flag is added to disable (as discussed in  #3142).

The second is that the short description has some - but not all - html fields escaped. I use the Flatsome theme which allows me to create blocks of html that I reuse in product short descriptions by just referencing the shortcode. This theme shows the short description in the 'quick view' and so formatting is often required. As these are self contained blocks that only appear once on a page they may also sometimes include inline `<style>` tags to help with formatting. In the new cart & checkout these `<style>` blocks are removed, I assume that other html tags are also removed - but not all.

For example, use the following raw text in the short description:
`<style>.bold{font-weight:bold;}</style>a <span class="bold">bold</span> description.`

This works when viewing the product: 
![image](https://user-images.githubusercontent.com/63653103/133777708-a68c2513-3f78-47eb-9349-15fb1e5226fb.png)

It also works in the standard cart & checkout as the short description is not included: cart:
![image](https://user-images.githubusercontent.com/63653103/133777843-cc6e9971-bf1f-43f2-b346-3993638f230f.png)
checkout: 
![image](https://user-images.githubusercontent.com/63653103/133777887-e41a2448-10d7-4888-95e3-9bc617eb14cc.png)

It does not work in the new cart & checkout:
cart: 
![image](https://user-images.githubusercontent.com/63653103/133777993-103d67d4-3fab-4802-98e8-c37ba745e825.png)
checkout: 
![image](https://user-images.githubusercontent.com/63653103/133778022-755eb6b3-364f-4bc1-913a-a99da76265b2.png)

Both of these issues are seemingly rapped up with #3142 as users are already using the short description with html content;  utilising the short description in the new cart & checkout without it being an option (and also escaping some html fields) I see as problematic. #3142 also discusses that `<img>` tags also being used and 'should' be stripped/escaped - where does this end - except with broken sites :-( Hope this helps clarify the issue as I see it.

**Comment by nerrad** [comment]
Thanks for adding more context about the issues you are discovering. I agree this is something that will need addressed in some way and will be bringing it up for discussion with the team.

**Comment by nerrad** [comment]
Did some more testing and thought I'd add some clarification about how to reproduce this.

1. In any product, open the _text_ tab for the short description field and add some sample html and update the product.
<img width="1448" alt="CleanShot 2021-10-14 at 13 52 13@2x" src="https://user-images.githubusercontent.com/1429108/137370354-6606e855-88cd-4df6-be97-40a56725d03f.png">

2. When you view the single product page, the html is processed and the short description shows as expected.
3. When you view the product in the new Cart or Checkout block, the `style` tags have been escaped and output along with the content.
4. The same escaping occurs with the short description display for the product via the All Products block.

The reason for the inconsistency is because by default, WooCommerce is [not escaping the html saved](https://github.com/woocommerce/woocommerce/blob/trunk/templates/single-product/short-description.php) to the post_excerpt field on _output_, instead relying on any escaping done on the data when saved to the database. Whereas, the StoreApi is [executing `wp_post_kses` on the content](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/09630f218ec605bacf19d67b6b56dc4b537ceff7/src/StoreApi/Schemas/ProductSchema.php#L445) which in the context of the StoreAPI request results in only allowing a narrower set of HTML tags (and escaping the `style` tags).

@mikejolley What are your thoughts on this one. On the surface it appears that there might be too much escaping happening here and there is no trust in the way WP content traditionally works with this type of content in controlling the amount of escaping of post_content/post_excerpt on saving to the database and not when displaying the data. 

(as a sidenote, it looks like the current handling of escaping `short_description` and `description` on [product content in the StoreAPI](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/09630f218ec605bacf19d67b6b56dc4b537ceff7/src/StoreApi/Schemas/ProductSchema.php#L445) is running things through `wp_kses_post` twice... is that intentional?)

**Comment by mikejolley** [comment]
> (as a sidenote, it looks like the current handling of escaping short_description and description on product content in the StoreAPI is running things through wp_kses_post twice... is that intentional?)

@nerrad The outer kses is standard across all HTML responses. Looking at `wc_format_content` inside, it does run filters and produce untrusted output. https://github.com/woocommerce/woocommerce/blob/2cce7f3af89760dc89d96844c748ae646a658ceb/includes/wc-formatting-functions.php#L1090 So if we remove it, we have to accept that `wc_format_content` filters are "safe".

> The reason for the inconsistency

Also searching for more similar usage, some descriptions (terms) do get kses treatment, whilst product descriptions do not. https://github.com/woocommerce/woocommerce/search?q=wc_format_content

> What are your thoughts on this one. On the surface it appears that there might be too much escaping happening here and there is no trust in the way WP content traditionally works with this type of content in controlling the amount of escaping of post_content/post_excerpt on saving to the database and not when displaying the data.

Mixed feelings here. We regularly see the post_title XSS issue reported for the same reasons (lack of output escaping), and at the same time I don't feel it's appropriate to load short descriptions with a bunch of lengthy HTML. The UI in woo core is partly to blame for this and I'd bet that will be changed as it moves to the new editor.

If we do permit this and change the handling, it may have a decremental effect on the design of the new cart page where (as per the designs) short description really is a short (one paragraph/1 line) of text. I think under this context we're correct to truncate the text. If we do support unescaped output from the endpoint, we'll need to narrow the allowed tags in the cart context or disable it conditionally based on content.

**Comment by nerrad** [comment]
> The outer kses is standard across all HTML responses. Looking at wc_format_content inside, it does run filters and produce untrusted output.

I'm mostly referring to how `prepare_html_response` wrapping this invokes the HTMLFormatter class which also invokes `wp_kses_post`. Is that what you're referring to here as well?

> Mixed feelings here. We regularly see the post_title XSS issue reported for the same reasons (lack of output escaping), and at the same time I don't feel it's appropriate to load short descriptions with a bunch of lengthy HTML. The UI in woo core is partly to blame for this and I'd bet that will be changed as it moves to the new editor.

Yeah my feelings are somewhat similar. In the meantime what do you suggest we offer as a workaround for folks like the original reporter that are used to the current behaviour of `short_description` output elsewhere for their store? Use some custom css to hide the short description in block output?

**Comment by TomDeFord** [comment]
> Yeah my feelings are somewhat similar. In the meantime what do you suggest we offer as a workaround for folks like the original reporter that are used to the current behaviour of `short_description` output elsewhere for their store? Use some custom css to hide the short description in block output?

Putting to one side the 'escape or not' question, the unconditional addition of the short description to the checkout is a new feature that has the potential to affect many existing sites. Those that have used the short description but do not expect it to appear in the checkout will be forced into unnecessary content changes or site hacks to remove the offending text. In addition, arbitrary truncation has a 50/50 chance of looking good/bad and its appropriateness will vary on a per line-item basis. Using CSS to hide blocks of text that have never been there and shouldn't be there is neither clean nor ideal. A ‘Show Short Description’ option defaulting to ‘no’, leaves existing sites alone and allows the new feature to be used by choice.

**Comment by mikejolley** [comment]
> I'm mostly referring to how prepare_html_response wrapping this invokes the HTMLFormatter class which also invokes wp_kses_post. Is that what you're referring to here as well?

@nerrad yes this is what I'm referring to. We have the same handling for all strings which may contain HTML.

> In the meantime what do you suggest we offer as a workaround for folks like the original reporter that are used to the current behaviour of short_description output elsewhere for their store? Use some custom css to hide the short description in block output?

Short term, I think it's possible using CSS already (`.wc-block-components-product-metadata` class).

Medium-term, we could add it to the inner block options in cart i2.

Medium to long term, design should review again, and if we're sticking to a short description format (one-sentence summary) decide, for core, if this is how short descriptions are treated, or if we need a new field. That needs to be consistent inside core and across all products, as well as future edit product screens once they use the new editor.

> Putting to one side the 'escape or not' question, the unconditional addition of the short description to the checkout is a new feature that has the potential to affect many existing sites.

I'm not concerned with this short term because cart/checkout blocks are a new feature themselves, so the impact for existing stores is nominal.

**Comment by nerrad** [comment]
> @nerrad yes this is what I'm referring to. We have the same handling for all strings which may contain HTML.

I guess I'm still puzzled why we can just rely on the `wp_kses_post` that is executed as a part of `prepare_html_response` which is wrapping the entire value. So for example:

```
$this->prepare_html_response( wc_format_content( wp_kses_post( $product->get_short_description() ) ) )
```
Why can't we just do:

```
$this->prepare_html_response( wc_format_content( $product->get_short_description() ) )
```

`prepare_html_response` is effectively doing something like this:

```
wp_kses_post( trim( convert_chars( wptexturize( wc_format_content( $product->get_short_description() ) ) ) ) )
```

Leaving things as it is currently we are effectively doing this:

```
wp_kses_post( trim( convert_chars( wptexturize( wc_format_content( wp_kses_post( $product->get_short_description() ) ) ) ) ) )
```
So I guess I'm still not understanding why we're executing `wp_kses_post` twice here?

> I'm not concerned with this short term because cart/checkout blocks are a new feature themselves, so the impact for existing stores is nominal.

Keep in mind this also affects the All Products block (not just Cart and Checkout). Knowing that, does it change your thoughts at all Mike?

Also going back to an earlier statement:

> Mixed feelings here. We regularly see the post_title XSS issue reported for the same reasons (lack of output escaping), and at the same time I don't feel it's appropriate to load short descriptions with a bunch of lengthy HTML. The UI in woo core is partly to blame for this and I'd bet that will be changed as it moves to the new editor.

While the UI in Woo Core may be partly to blame for this, the reality is that right now in WordPress core, WordPress will accept _any_ html content just fine on saving `post_excerpt` if the user saving the content has `unfiltered_html` capabilities. Since the "product short description" is essentially just `post_excerpt` content, it's not really doing much different than what WordPress does for regular posts. So while it's completely possible for users with the right capabilities to XSS themselves, that's current expected WordPress behaviour (granting users with the right capabilities to display whatever they want on the frontend). BTW, possible to do right now with block editor for post content too :).

Whether or not this changes when a new Woo product editor is made available is kind of besides the point because there will still be a large number of sites that potentially have saved content with html that was saved by a user with `unfiltered_html` capabilities. However, going back to the issue at hand, this issue highlights the following:

1. Store owners with `unfilterd_html` capabilities, currently have the ability to save _any_ html for certain content fields in the product editor.
2. Woo Core does not escape that html for that content in existing core (non block) views on the frontend (eg shortcode powered checkout, single product pages, archives that display `post_excerpt` etc).
3. The Woo Blocks All products block _does_ escape this content along with Cart and Checkout which creates an inconsistent experience with Core.
4. While truncating the text would make things worse for long short descriptions, even without truncation this creates a problem in cases like what was raised here where a `<style>` tag is used and those tags are stripped leaving the inner contents displayed.

I agree with the proposed interim solutions, but I do think given what we know this does surface the importance of thinking through the Woo Product data model long term, particularly around clarifying:

1. Where we think it should diverge from how WordPress core treats the fields we're using for some product data (`post_content`, `post_excerpt`, `post_title`) and why we diverge.
2. Should we implement a specialized plain text only field for short descriptions (and maybe the current short description field becomes the product summary)? This would provide utility for anywhere product description is shared where only plain text is allowed (marketplace listings, cart and checkout items etc).
3. Future iterations of blocks/templates might consider ways of providing merchants to customize the display of these fields (i.e. show product summary or short description, or nothing).

Int the meantime, @TomDeFord, there won't be any immediate changes to existing blocks for handling this use-case. For now the best approach is to implement some custom CSS to hide any place short descriptions are escaped, or simply don't use html for short descriptions. I appreciate this might not be the ideal solution for you, but we do need to do some more thinking around this more holistically across WooCommerce before jumping to a solution.

**Comment by mikejolley** [comment]
> So I guess I'm still not understanding why we're executing wp_kses_post twice here?

I guess we can change that. I think we're just trying to keep the original function (the part within wc_format_content) the same as core where kses is used (see https://github.com/woocommerce/woocommerce/search?q=wc_format_content), although that again is inconsistent and not applied to post content. Let's change that part.

> Keep in mind this also affects the All Products block (not just Cart and Checkout). Knowing that, does it change your thoughts at all Mike?

The OP is referring to the use of short descriptions within cart block and how lengthy descriptions are not compatible with that block. My comment is not aimed at other blocks where the short description is optional.

Regarding your following comments @nerrad, should we throw this back to the design team? The inclusion of short description was a design decision, not a development decision. If the intention was to have a short one-line description and this cannot be made possible through the use of short description, we'll need buy-in from core before adding a new field.

**Comment by nerrad** [comment]
> Regarding your following comments @nerrad, should we throw this back to the design team? The inclusion of short description was a design decision, not a development decision. If the intention was to have a short one-line description and this cannot be made possible through the use of short description, we'll need buy-in from core before adding a new field.

I agree, this does need some broader discussion. I'm going to write something.

**Comment by nerrad** [comment]
See the internal post I published around this here: pcShBQ-8H-p2
