### ISSUE TITLE
Editing checkout fields

### ISSUE THREAD

**Issue by MathijsCraft** [woocommerce/woocommerce-gutenberg-products-block#4758]
Hello,

How can I edit the checkout fiekds? I want to remove some and add some.

We don't offer technical support on GitHub so we recommend using the following:

## Reading our documentation
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
 from a human being - submit a ticket via the helpdesk
https://woocommerce.com/contact-us/ 

## General usage and development questions
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The WooCommerce Help and Share Facebook group

**Comment by nerrad** [comment]
Hi @MathijsCraft 👋🏻 

I'm assuming you are referring to editing checkout fields in the Checkout block. Currently there is no explicit interface for adding additional checkout fields or removing existing ones within the block. That is on our radar to add some interfaces (both user and code based) for achieving this functionality.

Since there's nothing actionable with this issue at the moment I'm going to close it, but I do appreciate you taking the time to leave the issue. It's noted that there is desire for this functionality.
