### ISSUE TITLE
Improve error handling for express payment methods to prevent empty containers.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#4768]
## Describe the bug
A [report came in](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1877) for a bug with the Stripe payment method due to a uncaught Promise error. While the existing blocks code prevented cascading failure in the block, if the Stripe payment request buttons are the only registered express payment buttons, this will result in an empty container for the block.

While arguably the fault lies with the Stripe payment method extension registering the express payment method when it's not even configured to be active by the user, this does surface an area that we can improve should there be any payment method registered as an express payment method that throws a similar error preventing it from rendering. Ideally, it'd not only fail to render, but it would also be de-registered. This would ensure that we don't display any containing elements.

This seems like a fairly difficult thing to implement on the surface but would add additional resiliency to the checkout flow from a shopper perspective.

See [this comment](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1877#issuecomment-921101715) for more details on the resulting behaviour I'd like to protect against in the checkout block.

**Comment by mikejolley** [comment]
I did some digging into this and found that:

- Testing as far back as Stripe 5.4.1 (before the issue was reported), the wrappers no longer render. Neither does the `-- or --` line. This looks to have been something resolved in Checkout i2.
- There are no console errors reported or caught
- [This line is responsible for not adding methods where `canPay` is false](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/8ef356f341aadb0858b4325d4d05dc8e9f4a1ce9/assets/js/base/context/providers/cart-checkout/payment-methods/use-payment-method-registration.ts#L124-L133)

It looks like the original issue is resolved. With regards to the hardening and this point:

> While arguably the fault lies with the Stripe payment method extension registering the express payment method when it's not even configured to be active by the user, this does surface an area that we can improve should there be any payment method registered as an express payment method that throws a similar error preventing it from rendering. Ideally, it'd not only fail to render, but it would also be de-registered.

The largest red flag here is we're relying on the `canPay` callback to determine if the method should be rendered or not.  In Stripe's case, they are providing a valid callback, and this returns `false` which disables the payment method. 

If we were to deregister methods based on `canPay`, we'd run into issues where a methods `canPay` callback could change over time. For instance, if it's based on the order value, and the order value changes. For this reason, I don't think we should deregister the method.

Since the user-facing aspect of this is resolved, and it's an implementation error, I'm marking this closed. Let me know if I missed something.
