### ISSUE TITLE
WC core functions `is_cart()` and `is_checkout()` do not return `true` for pages with the cart or checkout block

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-gutenberg-products-block#4858]
As the title says, WooCommerce core functions `is_cart()` and `is_checkout()` do not return `true` for pages with the cart or checkout block included in them. It appears they should due to the functions themselves also search for the cart and checkout shortcodes in the content of the pages. 

Functions are here:
https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/wc-conditional-functions.php#L88-L114

Discussion in Slack:
p1632829526402000-slack-C8X6Q7XQU

**Comment by nerrad** [comment]
There are filters available that can be used here. For now, I think we should only hook in via the feature plugin for now until C&C blocks are the default experience in core.

**Comment by mikejolley** [comment]
@nerrad These functions make sense when you have a single checkout page and a single cart page, and where the shrotcode and current page are both tightly coupled, and rely on server-side rendering. 

With Blocks however, we're moving away from this:
- you can essentially have those Blocks anywhere on your store
- blocks can be reused on multiple pages
- blocks do not require special handling from the server-side because they are powered by the REST API

The original purpose of `is_cart` and `is_checkout` was to detect if you are on these pages:

![Screenshot 2021-10-05 at 11 39 22](https://user-images.githubusercontent.com/90977/136007922-25286890-e257-44ad-b2da-f7e314936a2c.png)

**I think we should maintain this**--matching page contents and looking for blocks seems expensive and a bad idea.

Also noting, if I recall correctly, the reason these functions search for shortcodes is a hack to ensure shortcodes do not break. The cart and checkout shortcodes do not work on other pages because they have script dependencies that only load when `is_cart` and `is_checkout` is true. Blocks do not share this limitation.

My vote would be to leave the conditional functions alone, and remove shortcode detection once blocks are the default.

_edit: made comment clearer_

**Comment by nerrad** [comment]
Fair points Mike,

@jessepearson can you expand a bit in here about why you need to know whether the Cart or Checkout blocks are on the page. I know there was some discussion in Slack but even if you'd be repeating some of what might have been said there it'd be useful to have it directly in the issue. It's possible we can help with whatever your needs are around that.

**Comment by jessepearson** [comment]
There's an issue with Product Add Ons displaying/using the proper prices if cart/checkout blocks are being used on non cart/checkout pages. It happens here: https://github.com/woocommerce/woocommerce-product-addons/blob/trunk/includes/class-wc-product-addons-helper.php#L170-L184

We worked around this in WCPay by using a filter when `is_checkout()` is called, but it's still an issue in Add Ons. What Mike said makes sense, and if there's been no other issues created, it may be better to just leave it as it is.

**Comment by nerrad** [comment]
I'm going to go ahead and close this, if we find more use case for a helper function for determining if the Cart or Checkout block is in use on a given view we can revisit.
