### ISSUE TITLE
Product price should inherit the 'Price display suffix' set in the Tax settings

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce-gutenberg-products-block#4860]
## Is your feature request related to a problem? Please describe.

Unsure if this is a bug or feature request, but.. when a 'Price display suffix' is set in WooCommerce's Tax settings: https://d.pr/i/4FSqwR – this is honored everywhere but in product blocks, such as 'All Products'.

## Describe the solution you'd like

I'd expect the 'Price display suffix' to display just as it would on a non-block product section.

**Price display suffix:**

![](https://d.pr/i/4FSqwR+)
_Direct link: https://d.pr/i/4FSqwR_

**'All Products' block:**

![](https://d.pr/i/ZyRhq1+)
_Direct link: https://d.pr/i/ZyRhq1_

**Normal Woo shop page:**

![](https://d.pr/i/X1lMRb+)
_Direct link: https://d.pr/i/X1lMRb_

## Describe alternatives you've considered

I tried inserting this with my own CSS or JS/jQuery, but it occurs too late on load.

## Additional context

Forum request: https://wordpress.org/support/topic/display-price-suffix-in-product-list/

**Comment by nerrad** [comment]
The price element block works as expected (I have set the suffix as +GST).

<img width="373" alt="CleanShot 2023-04-03 at 14 53 16@2x" src="https://user-images.githubusercontent.com/1429108/229600744-ec5417e0-4bf0-46e2-994f-71bc0ca632d6.png">

Which means that for the new Products Block or any block using the Price element block, this will work as expected. However, the All Products block still does not display the suffix.

The All Products block won't be receiving additional development at this time because we are focusing on the Products Block being the eventual replacement for it.

_Note: Existing usages of the All Products Block will still work when it is replaced._
