### ISSUE TITLE
Review and possibly Graduate `__experimental_woocommerce_blocks_hidden` PHP filter.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#4999]
This PHP filter [was added](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3732). This filter is used to allow for making some cart item data visible or hidden depending on whether it needs to be displayed in the Blocks or shortcode.

It appears to have a fairly narrow use-case and I'd like to explore what other ways there might be for solving [this issue](https://href.li/?https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3731). If there is no other better way, then we could probably go ahead and make this stable.

Things to do:

* [ ] Introduce a new action with the experimental prefix removed.
* [ ] Deprecate the old action (so it will still fire, but have it throw a deprecated developer notice pointing to the new name.
* [ ] Update inline code documentation.
* [ ] Update any other documentation.
* [ ] Check this action off in the list

**Comment by mikejolley** [comment]
I'm going to recommend we don't formalise this property (it's not an action/filter). Looking at [usage in Subscriptions](https://github.com/woocommerce/woocommerce-subscriptions/blob/dd6d52485cc0ef14a353468309f2691e6b574588/includes/class-wc-subscriptions-cart.php) and the [PR it was introduced](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3732), it exists for use cases where cart item meta needs to hidden in the core checkout, but shown in the block checkout. 

Reasons:

- There are potential alternatives to using this, such as inserting the data into the cart block via slot fill, or filtering using `woocommerce_get_item_data` considering the current context. 
- This exists due to the existence of core and block carts. When one goes away, only the original property (named `hidden`) would be needed. This is essentially an alias that only works for blocks.

That said, if we want to remove the prefix and support it anyway, we should probably rename it to reflect that it affects the Store API response rather than just "blocks". Perhaps we could adopt something like `show_in_rest`.

**Comment by nerrad** [comment]
I like the idea of changing it to `show_in_rest` as it's more explicitly related to surfacing in the REST API, but that makes me wonder if there's other ways to achieve the same thing using filters higher in the WP Rest Stack? If not, I do agree that this feels like something that might be better resolved other ways and might be reflective of the need of improvements to the data model. 

I guess my concern though, is if this is only intended to be a temporary affordance, the same rationale will exist when this comes up for review in the future, so I think we need to decide between:

- If this remains a temporarily thing and stays experimental, let's figure out what needs to happen to get to the point where we remove it.
- Recognizing it isn't the best solution, and assuming the public interface won't be problematic in the future (i.e. unexpected behaviour of response), we graduate this to stable, and change the name to reflect it's intended use case.

**Comment by mikejolley** [comment]
> Recognizing it isn't the best solution, and assuming the public interface won't be problematic in the future (i.e. unexpected behaviour of response), we graduate this to stable, and change the name to reflect it's intended use case.

I think the main justification for `__experimental_woocommerce_blocks_hidden` at the time was speed (to get an integration in place for subscriptions) and to avoid changing core designs.

If you compare the core design to the blocks design, you'll see core changes the prices via filters and hides the line item metadata, whereas blocks just shows the metadata.

Core:
![Screenshot 2021-11-15 at 15 50 34](https://user-images.githubusercontent.com/90977/141812066-188f9396-3e6b-4d8c-be9d-e10263342831.png)

Block:
![Screenshot 2021-11-15 at 15 50 59](https://user-images.githubusercontent.com/90977/141812173-afe23b80-c6d7-4493-9b53-cfff558cff30.png)

There are several ways we could remove the need for `__experimental_woocommerce_blocks_hidden` since so far, Subscriptions has been the only consumer. The first choice would just be to make core design consistent with blocks, so that would involve:

- Removing `__experimental_woocommerce_blocks_hidden` usage
- Setting `hidden` to false
- Removing the custom price display filter

Then core would display line items like blocks - with the metadata below the item name. If design approve this, it wouldn't involve extra work in blocks aside from deprecating the `__experimental_woocommerce_blocks_hidden` property.

If that is not possible and we want to maintain the two separate designs, we could decide between:

- Adding a slot fill within each line item to insert extra data, then removing `__experimental_woocommerce_blocks_hidden`
- Adding a filter to filter `hidden` per line item meta, then removing `__experimental_woocommerce_blocks_hidden`
- Filtering the price so the blocks design matches the current core design, and removing `__experimental_woocommerce_blocks_hidden`
- Renaming `__experimental_woocommerce_blocks_hidden` to something that makes a little more sense, even if the solution is not the best

Of that list, I think a slot fill could work well and have utility beyond this case, but some consistency would probably be better so filtering the price to match how core shows it might be better. That means the line items can stay `hidden`.

I'm cc'ing @senadir who worked on the integration, and @woocommerce/helix for feedback.

**Comment by haszari** [comment]
> @woocommerce/helix for feedback

@mattallan (porter) Can you take a look at this and feedback on behalf of Helix, or hand-over to someone as appropriate? Thanks 🙇

**Comment by mikejolley** [comment]
@haszari did anyone take a look at this?

**Comment by haszari** [comment]
> did anyone take a look at this?

Not that I'm aware of - will ping current porter. @shendy-a8c can you take a look and find out how we're using this hook in subscriptions, and how essential this is?

@mikejolley Would you mind logging an issue for this in WooCommerce Subscriptions repository? Reading through the comments above it seems likely we'd need to make a change there - e.g. to shift to a more recommended approach like using a slot-fill API.

**Comment by haszari** [comment]
Now I understand the details I'm keen to get to the bottom of whether we need this flag or whether it's better to change approach. 

I've logged an issue for this in subscriptions-core (library, where this code now lives), and also in WCPay and WC Subscriptions (products that would be impacted by the change). 

Aiming to have someone take a look at this in the next sprint.

**Comment by mikejolley** [comment]
Great news, thanks @haszari

**Comment by aprea** [comment]
Hi @mikejolley, apologies for the delay in providing feedback on behalf of Helix.

And thanks for listing the possible options in [your earlier comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4999#issuecomment-969059914).

Could you confirm whether or not Subscriptions is still the only consumer of the `__experimental_woocommerce_blocks_hidden` property?

If so, I like the idea of deprecating it in favour of one of your alternative solutions. I don't see any red flags in the approaches you have outlined. The slot fill option sounds promising!

Ultimately, I think yourself / Rubik are in the best position to decide on the final approach. We're happy to accommodate the chosen approach.

Feel free to include me or Helix in any eventual PRs for review and testing.

cc @haszari

**Comment by mikejolley** [comment]
Yeah I believe so - I see no other usages of `__experimental_woocommerce_blocks_hidden`. We will of course deprecate it rather than remove it straight away.

@senadir I guess you need to decide on this and prioritize accordingly if we're doing it.
