### ISSUE TITLE
Review `__experimentalOrderMeta`, `__experimentalOrderShippingPackages` and `__experimentalDiscountsMeta` slots.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#5001]
As a part of the extensibility interface audit, there has been some question around the necessity of these slot/fill interfaces with the availability of the inner blocks. So as a part of the review of these slots - we want to determine:

- Which of these slots _can_ reliably be replaced by usage of registering an inner block instead?
     - If this is possible, then deprecate the existing Slot with some direction (via link?) on implementing functionality via block instead.
- Which of these _could_ be replaced by usage of an inner block, but requires some more granularity of inner blocks in the existing structure of the block (i.e. Order Items List). This may be something we'll want to look into as part of some exploration around the Cart and Checkout block being constructed from template parts and blocks as a part of a template.
- Are we okay with graduating these slot/fills in the meantime as a supported way for implementing some extensibility (that is more controlled by the extension)? If so...
    - let's see if we can standardize on the data passed into each registered fill (and in a consistent shape).
- For any that we don't graduate, an outcome of this issue would be to arrive at some next steps for the Slot/Fill. This could include outlining a path towards graduation, a path towards replacement with some other interface, or some intermediary experiments/explorations that could be used to further guide a better decision.

**Comment by mikejolley** [comment]
These 3 Slot Fills are designed to allow content to be inserted within certain points of the main order totals Block. The main consumer of these blocks is currently Subscriptions.

| Slot Fill      | Usage |
| ----------- | ----------- |
| `__experimentalOrderMeta`      | [Used by Subscriptions to show recurring totals when subscriptions are in the cart. ](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/assets/src/js/index.js#L33-L35) |
| `__experimentalOrderShippingPackages`   | [Used by Subscriptions to show shipping options for future subscriptions.](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/assets/src/js/index.js#L30-L32)  |
| `__experimentalDiscountsMeta` | [Used by Points and Rewards to show redemption options.](https://github.com/woocommerce/woocommerce-points-and-rewards/blob/52615b621b0ff9028440d913ae12bf1fd0f05551/assets/js/index.js#L35-L41) |

Because this usage builds upon existing UI elements, new blocks wouldn't be suitable for these designs, unless potentially order totals was split into separate inner blocks so they could be inserted in-between or within.

## How could Order totals become multiple inner blocks?

The block in question is called `woocommerce/cart-order-summary-block` (and `woocommerce/checkout-order-summary-block` during checkout). This contains multiple `TotalsWrapper` components for each section, those sections being:

1. Subtotal
2. Total Fees
3. Total Discount
4. Coupons (and form)
5. `ExperimentalDiscountsMeta` Slot
6. Shipping totals (contains `ExperimentalOrderShippingPackages` slot)
7. Tax totals
8. Grand total
9. `ExperimentalOrderMeta`

There is also a heading in the cart order summary block, and a list of items in the checkout order summary block.

I think it's quite viable that each totals section *could* become an inner block that the merchant can move around or delete. So long as the default layout contains the above. This opens up several nice use cases such as:

- Moving coupon forms, or disabling them
- Rearranging how totals are displayed
- Hiding shipping from the cart

Some potential pitfalls:

- Removing a total could make the grand total confusing, if the other parts which made up this total were to be hidden.

## Inner block structure

Each totals block could have the same structure, similar to form steps, so you have:

- Heading (editable) and potentially sub-heading (like shipping row which shows the rate)
- Value 
- An inner block area where extra content could be added

Going back to the Slot Fills and where they would fit:

- `ExperimentalOrderShippingPackages` would be deprecated and replaced with the inner block area within Shipping Totals. This area needs to receive similar props so extra shipping rows could be added. Styling/collapsing rates may be a problem that we need to workaround or remove.
- `ExperimentalDiscountsMeta` would be deprecated - an inner block can just be inserted between the other totals.
- `ExperimentalOrderMeta` is deprecated - an inner block can just be inserted below the other totals.

## Next steps

I don't believe these slot fills need to graduate. Let's instead work on inner blocks.

- [ ] Investigate new inner blocks per total and create POC
- [ ] Design sign-off
- [ ] Export reusable totals block for others to consume
- [ ] Update subs/points and rewards with new structure to validate the approach
- [ ] Deprecate Slot Fills with no replacement.

cc @nerrad @senadir

**Comment by senadir** [comment]
I like this suggestion and believe it's the next logical evolution for Cart/Checkout.
One possible issue (that can be solved) is that totals items design is tightly coupled to line item cells (with borders and all), how would new blocks fit there? should we still enforce dividers from the top level block ([like tailwind `divide` utility for example](https://tailwindcss.com/docs/divide-color)).

**Comment by mikejolley** [comment]
@senadir I think we'd nest everything within a top level block and only add dividers between the top levels.

**Comment by senadir** [comment]
One other issue I think about is editing those things. Currently, Slot Fills work well with conditional content.
If your website sells subscriptions, pre-orders, points and rewards, just as an example, your editor would end up with all of those blocks present, while an edge case, it's still something to consider.

One possible solution is that we can encourage developers to implement a notice in the inspector control "This block is only visible if there's a subscription product in cart"

**Comment by mikejolley** [comment]
@senadir Can forced blocks be hidden in the editor?

**Comment by senadir** [comment]
No, that's the point of `useForceLayout` is to always show them. However, you can emit `force` from what you pass to registerBlockType and only pass it to `registerCheckoutBlock`, however, what would this solve?

**Comment by mikejolley** [comment]
@senadir It would allow you to have conditional, fixed position, forced blocks, using the same inner block structure, without adding too much within the editor view. But placeholders are ok also.

**Comment by ralucaStan** [comment]
We agreed that graduating these Slots without an alternative is not the way to move forward. 
p1643992862075089-slack-C8X6Q7XQU

We've added to the roadmap investigating new inner blocks for the Totals area, per total, just as Mike suggested in the next steps section from [his comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5001#:~:text=commented-,on%2018%20Nov%202021,-These%203%20Slot)
