### ISSUE TITLE
"By proceeding with your purchase [...]" Not Translated on Checkout Block

### ISSUE THREAD

**Issue by igotdes** [woocommerce/woocommerce-gutenberg-products-block#5005]
## Describe the bug
When using the Checkout block, "By proceeding with your purchase you agree to our Terms and Conditions and Privacy Policy" is not being translated even if translations for it exist.

## To reproduce

1. On WP Admin > Settings, set the Site Language to a language other than English like Español or Norsk bokmål.
2. Make sure to download any translation updates under My Home > Updates
3. Create a page, add the Checkout block to it, and save it
4. Add a product to cart and view the checkout page created previously

## Expected behavior
"By proceeding with your purchase you agree to our Terms and Conditions and Privacy Policy" should be translated.

## Screenshots

Español - [translation here](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/es/default/?filters%5Bterm%5D=By+proceeding+with+your+purchase+you+agree&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
![Translation-Checkout-Block-ES](https://user-images.githubusercontent.com/74066241/138988466-f70d2651-5507-441f-955a-fb97bc8475ff.png)

Norsk bokmål - [translation here](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/nb/default/?filters%5Bterm%5D=By+proceeding+with+your+purchase+you+agree&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc#)
![Translation-Checkout-Block-NO](https://user-images.githubusercontent.com/74066241/138988451-cbc0da34-4e87-4a71-b6c0-aab12945c4f5.png)

### WordPress:
* Core version: 5.8.1
* Gutenberg version: 11.7.1
* WooCommerce version: 5.8.0
* WooCommerce Blocks version: 6.1.0

### Desktop (please complete the following information):
* OS: macOS
* Browser: Chrome Version 95.0.4638.54 (Official Build) (x86_64)

## Additional context
Reported in #4406259-zen.

**Comment by nielslange** [comment]
Hello @igotdes 👋

Thanks for reporting this problem. I looked up this case and found out that the string in question was using the textdomain `woo-gutenberg-product-blocks` instead of the textdomain `woo-gutenberg-products-blocks` (note the missing s for products). Therefore, the available translations couldn't be picked up.

I created a fix for this problem with #5020. This fix needs to be reviewed first, then approved, then merged and finally shipped. I cannot give you an estimate yet, on when the fix will be shipped. However, in case the client is looking for a quick solution, you could suggest changing the string directly within the checkout block, as the string is editable:

<img width="510" alt="Screen Shot 2021-10-28 at 11 06 50" src="https://user-images.githubusercontent.com/3323310/139185197-6bbbfd2a-5061-46db-b65d-75721081bcec.png">

**Comment by nielslange** [comment]
@igotdes The problem you reported had been resolved. Would you mind informing the client accordingly?

**Comment by igotdes** [comment]
> @igotdes The problem you reported had been resolved. Would you mind informing the client accordingly?

Done! I've informed the user.

Thanks for working on this and for keeping me updated too, @nielslange!

**Comment by nielslange** [comment]
_Thank you_ for reaching out to the user, @igotdes! 🙌
