### ISSUE TITLE
Products by Attribute: Should show photos of the selected variation

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gutenberg-products-block#506]
[Reported by a user in the support forum](https://wordpress.org/support/topic/products-by-attribute-block-does-not-show-the-respective-attributes-thumbnail/) – they would like the product thumbnail image to reflect the attribute selected.

> When it is a variable product, the main product image is shown and not the one for the matching variation. I do think it would be a nice enhancement to show the actual variation image if it’s available.

There are a few steps to get this to work:

- [ ] The API will need to be updated to return the product thumbnails for each variation
- [ ] The preview component will need to know about the selected attribute, and get the correct thumbnail (falling back to the default)
- [ ] The shortcode will need to be updated to correctly render the right thumbnail on the front end

**Comment by mikejolley** [comment]
@ryelle This sounds like the user wants variations to display rather than parent products, something that is unsupported by core. 

Additionally:

1. Returning all variations/thumbnails is also something that will bring scaling issues in with it.
2. Variations are not associated with the attribute terms directly which adds an additional roadblock and an additional scaling issue because any matching would need to be done via complex meta queries.
3. Layered nav in Woo core, which also lets you filter by attribute, does not change thumbnails either.

Point 3 appears to be wontfix in core due to technical limitations (https://github.com/woocommerce/woocommerce/issues/21151).

**Comment by ryelle** [comment]
1. Makes sense.
2. Yeah, thought that would be a problem…

Sounds like this should be a wontfix here, as well, then. We'll have the ability to feature specific product variations in the Featured Product with #369, so at least people can select variations that way if they need. Going to close this– thanks for the background 🙂
