### ISSUE TITLE
Too few arguments to function _doing_it_wrong()

### ISSUE THREAD

**Issue by pluginslab** [woocommerce/woocommerce-gutenberg-products-block#5074]
## Describe the bug
The call to the function `_doing_it_wrong()` [at line 67 inside src/Integrations/IntegrationRegistry.php](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/bdf7ab73889d2ec12af5db82ecc7334c202f0152/src/Integrations/IntegrationRegistry.php#L67) has a missing parameter: $name.

## Expected behavior
A correct function call with 3 parameters is expected otherwise a PHP Fatal error is produced. 

### WordPress (please complete the following information):
* Core version: [e.g. 5.8.0]
* WooCommerce Blocks version: [e.g. 6.2.0]

**Comment by pluginslab** [comment]
It's actually not the $name that is missing, but [the version variable](https://developer.wordpress.org/reference/functions/_doing_it_wrong/), which hasn't a default so it must be provided. 

And I just noticed that all three calls to the function `_doing_it_wrong()` are missing their third parameter.

I got to this error when I was registering a payment method used on the checkout block twice, that is, with the same name.

**Comment by nerrad** [comment]
I'm guessing this is an `Uncaught ArgumentcountError` that gets thrown?

It looks like the `_doing_it_wrong` WordPress function [actually accounts for whether `$version` is present or not](https://github.com/WordPress/wordpress-develop/blob/2716cc52afce7c59cb470b8d587ae3e9ab75d76e/src/wp-includes/functions.php#L5710) so it appears that this may be a bug with the WP core function vs than our usage of it. At one point (I think prior to PHP 7.1), this would produce a PHP warning not an error.

We can eliminate this error (on evironments greather than PHP 7.1) by explicitly adding a `$version` value (eg `''` in order to satisfy the intentional falsey value) but that seems like a workaround for WP core not accounting for newer PHP version requirements and the implicit default for `$version` of empty string.
