### ISSUE TITLE
I can't Customize Text Field I Need

### ISSUE THREAD

**Issue by hellangel45236** [woocommerce/woocommerce-gutenberg-products-block#5090]

**Comment by mikejolley** [comment]
Hi there,

It would be great to know more about what you're wanting to customise and where since there are a number of fields in the Blocks Plugin so it's difficult to know which is being referred to here. More information about the use-case would also be welcome.

Since this issue lacks enough detail to action so I'm closing it, but feel free to reopen a new issue with more details and/or screenshots.

Thanks
