### ISSUE TITLE
Third party blocks can break cart/checkout

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#5101]
I noticed this when working on Mailpoet/AutomateWoo integration. Any errors or exception thrown in a third party block would break the Cart block, which is dangerous for us to allow.

### How to test
- Insert a third party block in Checkout/Cart like MailPoet, AutomateWoo.
- Load the block in incognito, it should load fine.
- Throw an error in your block.
- the whole cart/checkout should be down.

**Comment by alexflorisca** [comment]
Hey @senadir could you be a bit more specific about which blocks you tested with? I'm just trying to replicate this and I'm struggling to find any blocks registered with Automatewoo or Mailpoet. Mailpoet only has one block which is server side rendered. I've returned `<script>throw new Error()</script>` from this block on the server which kills the Mailpoet block but the Checkout seems unaffected.

**Comment by senadir** [comment]
Hey @alexflorisca, I think Thomas pointed you to using the newsletter plugin? try checking this branch https://github.com/woocommerce/newsletter-test/pull/6/

**Comment by alexflorisca** [comment]
Thanks @senadir, I'm using the newsletter-test component and I can throw an error inside it and you're right, it kills the whole checkout block. I've tried a few things and talked to @opr briefly but unfortunately couldn't find anything that works. but I'll leave my thinking here for discussion, maybe you have some ideas...

First I thought that if we could detect if the block errors before it's being registered, we could skip registering faulty components and leave a message in the console - or something along those lines. But I realised that the component could potentially error on user interaction or in a side effect not just on render so that won't work.

I then tried to see if we can wrap each sub-component within the checkout block in an `ErrorBoundary` component. This would work but it would stop the entire parent component of the third party block from rendering. For example, the "Subscribe to newsletter" block in the `newsletter-test` repo attaches to the `checkout-contact-information-block` component, so the entire contact information component wouldn't render if there was an error in the newsletter block. I don't think we want this. If any of the main sub-blocks of the checkout block don't render, it would ruin the checkout experience.
