### ISSUE TITLE
Disable Cart/Checkout forcing programmatically

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#5102]
All of Cart/Checkout inner blocks are forced by default, this will force render them on frontend and editor. They cannot be deleted or replaced or nested.

There might be some unique use cases in which a block should be deleted or nested inside another block, for that, we should allow forcing to be disabled programmatically.

One possible way to do it, while still preserving locking for default cases, is to change the default lock value to false, and make true on block initiation:

So this line:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/d761be12b8eba7e378df21baf037f7abd0ffb622/assets/js/blocks/cart-checkout/checkout/inner-blocks/checkout-fields-block/edit.tsx#L50

Would be like this:
```js
[
	'woocommerce/checkout-shipping-address-block',
	{ lock: { remove: true, move: true } },
	[],
],
```

And this line:
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/ddf77b02d7d39f814e9c13c6464845d676ec4647/src/BlockTypes/Checkout.php#L96

Would be like this:
```html
<div data-block-name="woocommerce/checkout-shipping-address-block" data-lock="{&quot;remove&quot;:true,&quot;move&quot;:true}" class="wp-block-woocommerce-checkout-shipping-address-block"></div>
```

Advanced users can then edit the saved HTML content to change forcing and delete the block from there.

However, this would disable auto reinsert that we have with `useForcedLayout`, and if we want to allow removing blocks, then that should be fine.

This should be up for debate before getting implemented.

cc @mikejolley  @nerrad

**Comment by nerrad** [comment]
What problem are we trying to solve here?

From what you've described, it sounds like we have default behaviour currently with the blocks for preventing removal/moving of specific blocks with no way to change that behaviour. Whereas there may be some use-cases where removing or moving blocks is needed.

Some further questions:

- What use-cases are there? Having a specific use-case to think through is helpful.
- Why do we have the current behaviour of locking or what problem does _that_ solve? 

For example, I think we have the current restrictions in place so that:

- We prevent accidental breakage of the cart/checkout flow by removing blocks that are _required_ to be present.
- We prevent changing the structure significantly in a way that potentially hurts conversion rate value in the flow (based on the research behind the current layout design). Further, if this is completely customizable, we can't really trust the conversion rate data we are getting from the checkout flow.

As a progression of thought around this. I think it'd be beneficial to zero in on thinking through the below two questions:

- What use-cases does the current structure prevent that we'd want to enable? The more specific we can get, the better.
- What alternative ways can we account for the reasons behind the current restrictions (that I outlined above)? For example, could there be some sort of block validation logic that ensures blocks of a certain type are in the inner block structure? Could we utilize block template parts and/or variations to allow for customized layouts?

**Comment by senadir** [comment]
We have two use cases in mind, both I think are for the hosted platform checkout team:
- The need to wrap a block inside another block, for example, having multiple address block would require you to create a new block that has all the radio buttons to select an address and would also show the core address block on demand if you need to. With our current system, there's no way to do that, you can wrap the block and it would work fine, but it would be inserted twice because it's not in its original position. (inside checkout-fields-block).
- There was a need to replace the Order Summary block with a stripped down version of it, (see thread p1636392440386500/1636389254.378400-slack-C8X6Q7XQU). Doing this is impossible as you cannot remove the block currently.

An alternative to this is to have an API to replace core blocks that meets X features (probably via props).
We need to also consider how strict are we with things, we know that having the contact step first is importing, and that a certain order is needed, but we also need to allow space for people to redefine some aspects, those preferably, are developers running custom use cases, and not the general public.

> Why do we have the current behaviour of locking or what problem does that solve?

It solves the problem of having a specific set of predefined steps in a specific order, it ensures those steps exist and are in the correct order. It was built with merchants in mind and with 95% of use cases in mind.
