### ISSUE TITLE
Missing possibility to hide the order message

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#5121]
## Describe the bug
Missing possibility to hide the order message.

## To reproduce
Try to remove the order message option, there is no opporunity.

## Expected behavior
The hiding of the order note should be possible as in previous versions.

## Screenshots
![1](https://user-images.githubusercontent.com/17782319/141084555-ade6f71c-c092-4669-8b1a-5d5673b100ee.PNG)
![2](https://user-images.githubusercontent.com/17782319/141084561-aa43920c-85e5-46cd-890b-7ac3cfa35d63.PNG)

### WordPress (please complete the following information):
* Core version: 5.8.1
* WooCommerce version: 5.9
* WooCommerce Blocks version: 6.2.0
* Site language: German

### Desktop (please complete the following information):
* OS: Windows, macOS
* Browser Chrome, Safari, Edge

## Additional context
In a previous version, the hide was still possible I do not know exactly from which version that was no longer possible.

**Comment by nerrad** [comment]
Hi @DarianDev, thanks for noticing and making us aware of this. It does look like a regression from previous behaviour.

@senadir or @mikejolley I'm assuming this is a block that should maybe be unlocked so that it can be removed? I tried doing so and was unable to.

Given this is a regression over previous behaviour, I'm going to mark as high priority.
