### ISSUE TITLE
Please add 'account creation' and 'sign in' function to this plugin

### ISSUE THREAD

**Issue by bruin2021** [woocommerce/woocommerce-gutenberg-products-block#5148]
Hi, your plugin is wonderful. However, there is no 'account creation' and 'sign in' functions like what the original Woo checkout has. 

Can you consider adding that? Thanks!

**Comment by Aljullu** [comment]
Hi there @bruin2021, thanks for sharing your feedback with us. The Checkout block already allows what you are looking for:

### Log in

* You need to go to WooCommerce > Settings > Accounts & Privacy and select the option _Allow customers to log into an existing account during checkout_.
* This will show a Log in link next to the _Contact information_ title:

![](https://user-images.githubusercontent.com/3616980/141993108-20a13a2f-abc1-4f5e-abbc-3e17d72706b1.png)


### Account creation

* You need to go to WooCommerce > Settings > Accounts & Privacy and select the option _Allow customers to create an account during checkout_.
* After that, you might need to enable the _Allow shoppers to sign up for a user account during checkout_ attribute in the Contact Information block, which can be found inside the Checkout block.

![](https://user-images.githubusercontent.com/3616980/141992635-98462a5e-a53f-447c-9548-92e15d3becad.png)

---

Hope that helps! For testing, you will need to test being logged out, otherwise the _Log in_ link and the _Create an account_ checkbox won't appear.
