### ISSUE TITLE
Fix issues with selecting the container width via the alignment toolbar button in the Cart Block

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#5204]
I was just running through some testing of the Cart block to prepare for an upcoming demo and I noticed some issues with setting the alignment for the block. I've recorded a video that demonstrates what I'm seeing:

https://user-images.githubusercontent.com/1429108/142727700-1eae0c38-bcc7-4b64-bf8c-c75fc0bde1f0.mp4

I suspect some of this is due to how the views are switched between empty and full cart, however, it'd be great to improve the following:

- There's a lot of nested containers that require clicking through (I realize this may be an issue at the GB level).
- Changing alignment for the parent block should be easier and provide better feedback around how the selection changes the current container.

**Comment by nerrad** [comment]
Another issue I'm spotting as I play around with this more is that if you click the alignment toolbar when the empty cart is the visible view and you are on the top parent block for the Cart (Document -> Cart), it will switch back to the Filled Cart view.

**Comment by senadir** [comment]
> Another issue I'm spotting as I play around with this more is that if you click the alignment toolbar when the empty cart is the visible view and you are on the top parent block for the Cart (Document -> Cart), it will switch back to the Filled Cart view.

This is a known bug on Gutenberg level https://github.com/WordPress/gutenberg/issues/35949, setting alignment from "none" to anything else wraps the block in a div, causing it to unmount/mount and local state to be lost.

We can use a non-persisted attribute to solve this, I will explore this solution later.

**Comment by senadir** [comment]
> There's a lot of nested containers that require clicking through (I realize this may be an issue at the GB level).
> Changing alignment for the parent block should be easier and provide better feedback around how the selection changes the current container.

Yes, this is an issue we discovered during Cart i2 migration (reported by Thomas [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4973#pullrequestreview-787895333)).

The issue is that Cart block is just a wrapper to accommodate for two inner blocks that are actually rendered. Ideally we want to either:
- Have Filled/Empty always stretch to Cart width (I believe Cart isn't rendered on frontend, so this would be an issue).
- Sync Cart, and Filled/Empty Cart alignment attributes, so changing one would change the rest, bit hacky, but can be explored.
