### ISSUE TITLE
Checkout: Selected payment method token gets out of sync with paymentMethodData

### ISSUE THREAD

**Issue by peterlama** [woocommerce/woocommerce-gutenberg-products-block#5296]
If the payment data context gets reset to pristine status after selecting a saved payment method option, the saved payment method option stays selected but the paymentMethodData sent to the server when submitting the checkout again remains empty.

## To reproduce

Note that I'm using the stripe payment method in this case, but it is the same with any gateway that saves the payment method token.

1. Log in with a user that has a saved credit card that is set as the default payment method
2. Go to checkout and the default saved payment method should be selected. All good so far, react state is in sync
3. Clear a required filed like the address post code
4. Click the place order button, which will run validation and highlight the required field that is empty. Fill in the required field.
5. The saved payment method should still be selected and all information is filled out now, so click place order again
6. API returns with an error processing payment because no payment method was included in the request

## Expected behavior
The saved payment method should be included in the place order request when it is selected.

## Screenshots
![image](https://user-images.githubusercontent.com/5176612/144457887-7fb68f76-699f-484b-aaa6-6a786ec39d2c.png)

## Environment
* Core version: 5.8.2
* WooCommerce version: 5.9
* WooCommerce Blocks version: trunk bf282a5c
* Any other plugins installed: Stripe
* Browser: Chrome 95

## Additional information
I have tracked this down to the fact that the selected saved payment method react state only sets the paymentMethodData on change: [blocks/cart-checkout/payment-methods/saved-payment-method-options.js#L53](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/cart-checkout/payment-methods/saved-payment-method-options.js#L53). The paymentMethodData gets cleared when set to pristine status [base/context/providers/cart-checkout/payment-methods/reducer.ts#L90](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/context/providers/cart-checkout/payment-methods/reducer.ts#L90), but saved payment methods are not part of the regular payment method processing here and it does not get set again: [payment-method-data-context.tsx#L252](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/context/providers/cart-checkout/payment-methods/payment-method-data-context.tsx#L252)

**Comment by Stella13x** [comment]
Similar issue with sales tax/Blocks. Is it related??

I'm still on Blocks 6.0.1 & Woo 5.8.0 specifically because of this CC issue. Thank you for solving it because people thought I was crazy for weeks!!!

Here's what I think may be a related issue because it happens apparently based on user behavior in their cart but I have yet to nail down how/what they are doing.

I just had a user check out twice for the exact same order because she thought it did not go through the first time but here is an example. The tax is different for two duplicate orders.

Her first order went through with no sales tax. It was calculated and it showed up in her cart but you can see that it was not added to her order total and her card was not charged the tax. This means I owe the tax and the buyer did not pay me for it. I have over $2000 in missing sales tax on tickets like this for various users. It all started on September 7th or 8th which I believe is when I transitioned to the Blocks plugin for cart & checkout. 

[1st order no tax](https://frameandthread.com/wp-content/uploads/2021/12/no-tax.jpg)

She then went in (still logged in as the same user) and created another duplicate ticket but, on this one, the tax is correct. The only difference I can see on this one is that she may have added her phone number on the second ticket. 

[2nd order with tax](https://frameandthread.com/wp-content/uploads/2021/12/tax.jpg)

I originally submitted this issue [here](https://wordpress.org/support/topic/tax-showing-on-the-orcer-but-not-getting-added-or-charged/)

If I'm way off here, I apologize but I've gone nowhere with both of these issues and this seems so similar.

**Comment by Stella13x** [comment]
@mikejolley Thank you so much! You have no idea how happy I am to see that.
