### ISSUE TITLE
ReadMore component missing reactivity

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#5299]
## Describe the bug
The `ReadMore` component is not reacting correctly to its props being changed, as some of them are transformed only once in `componentDidMount` but no update logic is there.

## To reproduce

1. Run `npm run storybook` (at the time of writing, you'll need to use branch on #5300)
2. Go to [ReadMore storybook entry](http://localhost:6006/?path=/story/woocommerce-blocks-base-components-readmore--default)
2. Try changing, e.g., `maxLines`
3. Nothing will update
4. Reload the page
5. The component will behave correctly

> ℹ️  Note: this is because Storybook saves the updated prop in the URL, so of course you can also just change the prop from there: e.g. http://localhost:6006/?path=/story/woocommerce-blocks-base-components-readmore--default&args=maxLines:10

## Next steps
Component was recently migrated to TS (see #5300), possibly the best next step is migrate it to hooks, since the component is still a class component.

**Comment by sunnyjain15699** [comment]
Hi @sunyatasattva . I would like to work on this issue. Can you guide me through it ?

**Comment by sunyatasattva** [comment]
Hello there @sunnyjain15699 ! Cool that you want to work on this issue.

In a nutshell, if you see the `ReadMore` component, you'll see that the clamping calculation is only done on `componentDidMount`:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/9a8f27fcd72ddfce7c75eaa681ac271732da5e94/assets/js/base/components/read-more/index.tsx#L113-L144

As such, whenever the properties get updated, the clamping will not be reflected in the actual component unless it is unmounted and mounted again. An example of this can be seen in the Storybook entry, by playing around with properties such as `maxLines`. However, this means that also such properties can't be changed dynamically by a user of this component.

That's what should be fixed basically.

The best path to do so, would be to migrate this Class component to React Hooks, if you are familiar with them. Otherwise, you'll have to use things like [`componentDidUpdate`](https://reactjs.org/docs/react-component.html#componentdidupdate) and such.

We'd really appreciate if you moved this to hooks, however.

---

Does this make sense? Any further questions?

**Comment by nielslange** [comment]
@sunnyjain15699 Are you still looking into this issue?

**Comment by tomasztunik** [comment]
Will be looking into this 🕵️ 

Noticed a couple of additional issues that I'll document here as I go and verify if they have been reported already, else will report them when done.

- `clampLines` util method miscalculates the length of the ellipsis string - it's using ligature that is 1 character long but when calculating length it's using the length of the HTML entity that represents it - `&hellip;` which is 8.

- calculating line-height/`maxHeight` doesn't take into account that content might have heading elements first that are higher than initial line height making nothing show up when `maxLines = 1` So for example if `H1` was first it takes `maxLines = 4` to show 2 lines of the header and `1` would not render anything etc. Also, it doesn't take paddings and margins into account.

- read more/less has no margin so it can glue to content above if the last content element has no margin - see storybook where it happens when expanded


Confirmed that the only not handled property was changing `maxLines`, as mentioned this was because the summary was calculated only once on componentDidMount will open PR with a fix.

**Comment by nielslange** [comment]
Thanks for taking over this one, @tomasztunik! 🙌
