### ISSUE TITLE
checkout route validating against existing payments, not available ones

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#5404]
When posting an order to checkout post, we run some schema validation for the payment method.
The route would validate against registered payment methods, which could differ from available payment methods:

```php
wc()->payment_gateways->get_payment_gateway_ids()
```

This means if a payment is removed via this filter, checkout will not catch and the order would process (a different bug, because `get_request_payment_method` isn't running).

I don't see a direct function in WooCommerce that returns available payment ids, so probably reducing `get_available_payment_gateways` to ids.

**Comment by mikejolley** [comment]
@senadir This is actually intentional. We want to accept all possible IDs via the API endpoint because `get_available_payment_gateways` may be influenced by certain contexts unavailable when doing the OPTIONS request to the Store API. For example, a payment method might be enabled for certain customer types.

Therefore, this should be left alone. What we need to do (and this is covered by the other issue, #5405) is validate again when the request is made to ensure what was requested is actually available when context is available.
