### ISSUE TITLE
Block options to choose order and limit product count

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-gutenberg-products-block#55]
Store owners should be able to choose the order products are listed in a block. Like the shortcode, that could by popularity, newness etc.

A use case could be the I want a unique landing page for a category, rather than the default archive you get with core. On that page, I only want to show my 3 best selling products.

It should also be more clear how you could limit the amount of products which should be displayed.

**Comment by claudiulodro** [comment]
@jameskoster @kellychoffman any thoughts for a good way of doing this? There used to be a [dropdown for picking the order](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/37) in the sidebar area and I can add it back, but there may be a smoother or more simple flow.

**Comment by jameskoster** [comment]
> There used to be a dropdown for picking the order in the sidebar area and I can add it back

I think that's the most appropriate place to add this setting. 

I'm just wondering about our "best rated" & "best sellers" scopes. Should we have ordering for those? I think and additional ordering would feel odd there because the order is already implied in the scope. We might consider `asc` and `desc` as options (so you can also display your worst selling/rated products, if you want to(?)), but tbh I think we can leave that out for v1 and just not have ordering for those scopes.

For the other scopes, what ordering are we thinking about offering?

* Alphabetical
* Chronological (default)
* Price asc
* Price desc
* Rating
* Sales

Those last two are tricky because if we include ordering by rating/sales, those options technically render the two aforementioned scopes redundant. You could just display `all products` ordered by `rating` and hey presto - you have your "best rated" products. I'm all for removing scopes where it's warranted but that flow would be less intuitive. I'm keen to hear @josemarques thoughts on this.

**Comment by josemarques** [comment]
I'm thinking if this order listing is something the store owner could force on to the user for curating purposes? Use case being a landing page with a specific purpose, the store owner might want to focus on displaying  specific set of products (top selling in a category).

@jameskoster are you thinking about letting the store owner decide which order to set for the list and providing a setting for show/hiding the ordering dropdown?

**Comment by jameskoster** [comment]
> the store owner might want to focus on displaying specific set of products (top selling in a category)

Correct.

> _and_ providing a setting for show/hiding the ordering dropdown?

I think enabling visitors to change the order on the frontend is a separate issue.

The main issue here is that if we allow store owners to display all products and order them by rating/sales then suddenly our "best rated" and "best sellers" scopes (https://cloudup.com/c0MI2Z1Fx7p) become redundant. You could just display all and order by rating. I'm not really keen on having two ways to do the same thing so we should either:

1. Include ordering by rating/sales and remove those scopes
2. Leave those scopes and not allow ordering by rating/sales

There are pros and cons to both approaches. Removing the scopes cleans things up a bit but does make displaying best rated/selling products less intuitive.

I just had a look at our data (p10gg3-8se).

* 3.7% of sites are using the current best-selling products shortcode.
* 2% of sites are using the current top-rated products shortcode.

That suggests they're not frequently used/needed. Based on that I think we could go with option 1.

**Comment by msdesign21** [comment]
> I just had a look at our data 

I'd be careful about relying on that data, knowing discoverability and UX of shortcodes is poor. I suspect the use case may be much higher as it can be built-in to the theme (in some cases maybe a deciding factor of a theme?) 

If it was easier for customers to implement what's best from an eCommerce/selling standpoint?

**Comment by jameskoster** [comment]
> I'd be careful about relying on that data, knowing discoverability and UX of shortcodes is poor.

That is true but it's still a significant amount of data and the discoverability is the same for all shortcodes. We know: Folks who use the products shortcode currently very rarely use it to display best-sellers or top-rated products. Very few people use the dedicated best-sellers or top-rated products shortcodes.

I agree the scope of this block goes beyond just replicating the products shortcode but when we start talking about theme devs, it's their responsibility to understand the possible implementations of this block in their templates.

> If it was easier for customers to implement what's best from an eCommerce/selling standpoint?

We don't know how easy or difficult this is until we test. I'll add to our script.

**Comment by msdesign21** [comment]
> We know: Folks who use the products shortcode currently very rarely use it to display best-sellers or top-rated products. Very few people use the dedicated best-sellers or top-rated products shortcodes.

Why?

**Comment by jameskoster** [comment]
> Why?

Because they don't want to?

If a user has done enough research to find the shortcode in the first place it's safe to assume they also know they can use it to display those products. They just choose not to. 

My hypothesis would be because the vast majority of stores don't get enough reviews to make displaying top rated products worthwhile. Or that sales volume isn't large enough to warrant displaying best-sellers.
