### ISSUE TITLE
`archive-product` block template doesn't correctly show its title

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#5564]
## Describe the bug
The slug `archive-product` does not get parsed into the correct human readable title.

## To reproduce

1. Go to Appearance → Editor → Browse all templates
2. Make sure you have `archive-product.html` in your theme's templates directory
2. Notice how the slug is not parsed into a title

## Expected behavior
Slug should read "Product archive" if language is set to English.

## Screenshots
<img width="1022" alt="Screen Shot 2022-01-13 at 23 47 44" src="https://user-images.githubusercontent.com/1847066/149421170-750d158b-8a7c-475d-b58e-516bf7214f51.png">

**Comment by Aljullu** [comment]
@sunyatasattva I thought that was expected if the theme doesn't define the template under `templates` in `theme.json`. Is it only happening for `archive-product` or for any other WC template?

**Comment by sunyatasattva** [comment]
@Aljullu Perhaps I'm wrong, but I think this is actually a bug in the way the strings are parsed, and I also might know where it stems from. This only happens for `archive-product` and, as you can see, the `Product Category` and `Product Tag` are correctly named (even though in the example above, they do not exist and are actually using the `archive-product` fallback).

Again, I might be wrong, but what would be the intent of leaving `archive-product` as a slug? I think I might have actually introduced this bug myself 😬

**Comment by tjcafferkey** [comment]
I think this is expected behaviour, it may seem to work for `Product Category` and `Product Tag` because of a side-effect of us duplicating the themes `archive-product.html` for those templates somehow.

If you add a `single-product.html` file to the theme without defining it in `theme.json` you get the same result.

![Screenshot 2022-01-25 at 08 42 09](https://user-images.githubusercontent.com/8639742/150942065-20841796-5f3a-4afb-8018-4d135d3f0d2f.png)

Still if we are able to fix it I don't see why not, however we need to be aware that if a title is defined in the themes `theme.json` that should superseed our naming convention.
