### ISSUE TITLE
Remove fields

### ISSUE THREAD

**Issue by ISY25** [woocommerce/woocommerce-gutenberg-products-block#5569]
## What do you think is missing from the Cart & Checkout blocks?
The capacity to remove or add fields. Even if we use woo plugin to remove it doesn't work

**Comment by nielslange** [comment]
Hello @ISY25 👋

Thanks for suggesting this enhancement. I see that this enhancement had been requested before in https://github.com/woocommerce/woocommerce-gutenberg-products-block/discussions/5483. Currently, it's indeed not possible to add/remove fields to/from the cart and checkout block. However, is is on our internal list of desired enhancements.

Since there's nothing actionable with this issue at the moment I'm going to close it, but I do appreciate you taking the time to leave the issue. It's noted that there is desire for this functionality.
