### ISSUE TITLE
Cross-Sells on the cart does not appear

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#5610]
I noticed that this feature is missing on your cart block...

![WooCommerce-Cross-Sells](https://user-images.githubusercontent.com/12650820/150565280-9b599a21-dad2-45d0-a019-575036a0f78d.png)

![woocommerce-linked-products-up-sells-cross-sells](https://user-images.githubusercontent.com/12650820/150565380-72ad9e22-6063-4ed3-a00d-4efe29c9491b.png)

It just doesn’t show up. It would be good to fix that.

**Comment by tarhi-saad** [comment]
Hello @msroky👋

Thanks for suggesting this enhancement. I see that it had been requested before in #5047. Currently, it's indeed not possible to display the Cross-Sells products using the Cart block. However, it is on our internal list of desired enhancements.

Since there's nothing actionable with this issue at the moment I'm going to close it, but I do appreciate you taking the time to leave the issue. It's noted that there is a desire for this functionality.
