### ISSUE TITLE
Remove dividing lines (Design)

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#5679]
## Describe the solution you'd like
Could we remove the horizontal dividing lines between products to align more with the designs and to keep the layout clean.

## Additional context
Just for clarity, here's an image indicating which line I'm referring to:

<img width="1251" alt="Screenshot 2022-01-31 at 14 42 55" src="https://user-images.githubusercontent.com/9888201/151814179-eb76b56b-ae61-432d-9d73-17ea473e8715.png">

**Comment by nielslange** [comment]
@vivialice Just to clarify, you only want us to remove the divider within the mini cart block, while the divider in the cart block will remain, correct?

Here's a screenshot of the cart block so that you know which divider I'm referring to:

![#5679](https://user-images.githubusercontent.com/3323310/151942952-3fe1ebc1-98d1-4e0a-af9c-c66c280ac43c.png)

**Comment by vivialice** [comment]
@nielslange Yes that's correct, I don't want to alter the main cart for now. Is it possible to remove only from the mini cart?

**Comment by nielslange** [comment]
> @nielslange Yes that's correct, I don't want to alter the main cart for now. Is it possible to remove only from the mini cart?

Absolutely, @vivialice. Thanks for confirming this. 🙌
