### ISSUE TITLE
Create testing directions

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#5703]
Examples can be found on:

- https://github.com/woocommerce/woocommerce-product-vendors/wiki/Testing-Directions
- https://github.com/woocommerce/woocommerce-box-office/wiki/Testing-Direction
- https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-Directions

**Comment by tarhi-saad** [comment]
# Testing directions
## Prerequisites
* WordPress 5.9+ version
* WooCommerce 6.2.0+ version
* Woo Blocks 7.0.0-dev+ version
* WooCommerce Payments 3.6.1+ version

## Tips
* Set the new created Cart & Checkout blocks as your Cart & Checkout pages   under the WooCommerce menu -> Advanced -> Page setup -> Cart page / Checkout page
* [WooCommerce Payments: Test Site Setup Guide](https://wooniversity.wordpress.com/payments/woocommerce-payments/woocommerce-payments-test-site-setup-guide/)
* [WooCommerce Payments Test Account Setup Guide](https://woocommerce.com/document/payments/testing/dev-mode/)
* [Setting up WooCommerce Payments for testing locally Via LocalWP](https://teamrubik.wordpress.com/team-handbook/engineering-process/tips/setting-up-woocommerce-payments-for-testing-locally/)

## Merchant in Cart 🛒
### Can add inner blocks

1. Create a test page
2. Add the Cart Block
3. Select an element of the Cart Block -> Click Options button on the block editor’s contextual toolbar -> Select “Insert before” or “Insert after” menu item

<img width="879" alt="Markup 2022-02-08 at 15 32 31" src="https://user-images.githubusercontent.com/14235870/153524667-53d382d6-071d-4dc4-92f7-d38324df2d05.png">

4. Add the desired block. (Note: The “Paragraph”, “Image”, and “Separator” are the only supported blocks in the version 7.0.0-dev)

### Can enable the shipping calculator

1. Create a test page
2. Add the Cart Block
3. Select the “Order Summary” item:
	* You can do that by selecting it directly by clicking on the correct Cart Item.
	* Or, you can toggle the “List View” on the top left of the page.

<img width="395" alt="Markup 2022-02-08 at 16 08 32" src="https://user-images.githubusercontent.com/14235870/153524724-71b95a9a-3d46-4857-89bb-35277f261e8a.png">

4. Open the Block Editor settings sidebar -> select the “Block” tab -> Toggle the “Shipping calculator” option under the “Shipping rates” section:

<img width="359" alt="Markup 2022-02-08 at 16 15 03" src="https://user-images.githubusercontent.com/14235870/153524748-af1f6234-b888-4a15-9c0e-b3628f1d2ad8.png">

## Shopper in Cart 🛒

### Can view cart block

1. Create a test page
2. Add the Cart Block
3. Publish page
4. Go to the newly created page. You should be able to see the Cart block

### Can view translated cart block

Note: This feature is not supported in the current version (7.0.0-dev).

1. Create a test page
2. Add the Cart Block
3. Publish page
4. Change Site Language: WordPress Settings -> General -> Site Language
5. Check the newly created page.

### Can update product quantity (and see updated prices)

1. Create a test page
2. Add the Cart Block
3. Publish page
4. [Add a product](https://woocommerce.com/document/managing-products/#adding-a-simple-product)
5. Visit your store and add the newly created product to the cart
6. Go to the newly created page (i.e., That contains the Cart Block)
7. Update the product quantity using the “quantity selector”. You should be able to see the price being updated accordingly

<img width="500" alt="Markup 2022-02-09 at 16 31 34" src="https://user-images.githubusercontent.com/14235870/153524784-38c27856-6868-406e-b628-7d16cf2feb17.png">


### Can remove a product (and see updated prices)

1. Create a test page
2. Add the Cart Block
3. Publish page
4. [Add more than one product](https://woocommerce.com/document/managing-products/#adding-a-simple-product)
5. Visit your store and add the newly created products to the cart
6. Go to the newly created page (i.e., That contains the Cart Block)
7. Remove an item from the list of added products. You should be able to see the price being updated accordingly.

<img width="709" alt="Markup 2022-02-09 at 16 47 21" src="https://user-images.githubusercontent.com/14235870/153524805-564e296e-d6e4-402d-81d0-23108fb1e8b9.png">

### Can apply single-use coupon once

1. Add a [single-use coupon](https://woocommerce.com/document/coupon-management/) (see [Usage Limits section](https://woocommerce.com/document/coupon-management/#usage-limits))
2. Follow steps 1 to 6 from [Can update product quantity (and see updated prices)](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20update%20product%20quantity%20%28and%20see%20updated%20prices%29)
3. Apply coupon once. The result should be successful.
4. Go to checkout and make the purchase. ([Setup Woo payments Dev Mode](https://woocommerce.com/document/payments/testing/dev-mode/) or [setup Stripe test mode](https://woocommerce.com/document/stripe/#test-mode))
5. Add a product to the cart and apply the same coupon via the Cart block. You should get the following error message: “Coupon usage limit has been reached.”

<img width="724" alt="Markup 2022-02-10 at 22 14 16" src="https://user-images.githubusercontent.com/14235870/153524825-964f1d67-dbb8-40c9-bdc7-e47d68bce263.png">

### Can apply multi-use coupon multiple times

1. Follow steps 1 to 4 from [Can apply single-use coupon once](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20apply%20single-use%20coupon%20once). But, instead of setting the usage limit of the created coupon to one, you can leave it empty for unlimited usage.
2. Add a product to the cart and apply the same coupon via the Cart block. The coupon should be successfully applied.

![Annotation on 2022-02-10 at 22-24-10](https://user-images.githubusercontent.com/14235870/153524839-dd6ee3b8-c6d4-4edd-a25a-54998572e07f.png)

### Can use express checkout

—

### Can proceed to checkout

1. Follow steps 1 to 6 from [Can update product quantity (and see updated prices)](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20update%20product%20quantity%20%28and%20see%20updated%20prices%29)
2. Click on the “Proceed to Checkout” button. You should be redirected to the “checkout” page.

## Merchant in Checkout 💳

### Can adjust shipping options

1. Create a test page
2. Add the Checkout Block
3. Scroll down to the “Shipping options” item
4. Click on the “Configure Shipping Options” button. You should be redirected to the shipping settings within the WooCommerce plugin

<img width="768" alt="Markup 2022-02-11 at 00 39 54" src="https://user-images.githubusercontent.com/14235870/153524862-8ffb94f8-6f35-4f93-992f-95200716e441.png">

### Can adjust payment options

1. Create a test page
2. Add the Checkout Block
3. Open the “List View” and select the “Payment options” item
4. Open the Block Editor settings sidebar -> select the “Block” tab -> under “Methods” you will be able to access and manage your payment methods

<img width="297" alt="x1y2GJ" src="https://user-images.githubusercontent.com/14235870/153524882-d1d4776b-a7b6-46f9-aa69-dd7d66cf2830.png">

### Can adjust T&S and Privacy Policy options

1. Create a test page
2. Add the Checkout Block
3. Open the “List View” and select the “Terms and Conditions” item
4. Setup your T&S by following the links on this item

<img width="762" alt="6ZD3K7" src="https://user-images.githubusercontent.com/14235870/153524909-02b5e766-f24f-4a04-9a4b-608a754659c2.png">

### Can allow guest checkout

1. Enable guest checkout if necessary. Go to WooCommerce > Settings > Accounts & Privacy > Guest checkout > Check “Allow customers to place orders without an account”
2. ??

## Shopper in Checkout 💳

### Can view checkout block

1. Create a test page
2. Add the Checkout Block
3. Publish page
4. Go to the newly created page. You should be able to see the Checkout block

### Can view translated checkout block

Note: This feature is not supported in the current version (7.0.0-dev).

1. Create a test page
2. Add the Checkout Block
3. Publish page
4. Change Site Language: WordPress Settings -> General -> Site Language
5. Check the newly created page.

### Can see warnings when the form is incomplete

1. Create a test page
2. Add the Checkout Block
3. Publish page
4. [Add a product](https://woocommerce.com/document/managing-products/#adding-a-simple-product)
5. Visit your store and add the newly created product to the cart
6. Go to the newly created page (i.e., That contains the Checkout Block)
7. Clear the form if necessary
8. Scroll to the bottom and click on the “Place Order” button. You should see warnings for required fields

<img width="922" alt="bwakqs" src="https://user-images.githubusercontent.com/14235870/153524940-f04db17a-0c96-4dfd-b416-934579bb7605.png">

### Can see the correct tax in the Checkout block

1. [Set up Taxes in WooCommerce](https://woocommerce.com/document/setting-up-taxes-in-woocommerce/)
2. 1. Create a test page
3. Add the Checkout Block
4. Publish page
5. [Add a product](https://woocommerce.com/document/managing-products/#adding-a-simple-product)
6. Visit your store and add the newly created product to the cart
7. Go to the newly created page (i.e., Containing the Checkout Block).
8. Check the tax displayed.

### Can apply single-use coupon once

1. Add a [single-use coupon](https://woocommerce.com/document/coupon-management/) (see [Usage Limits section](https://woocommerce.com/document/coupon-management/#usage-limits))
2. Follow steps 1 to 7 from [Can see the correct tax in the Checkout block](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20see%20the%20correct%20tax%20in%20the%20Checkout%20block)
3. Apply coupon once. The result should be successful.
4. Make the purchase. ([Setup Woo payments Dev Mode](https://woocommerce.com/document/payments/testing/dev-mode/) or [setup Stripe test mode](https://woocommerce.com/document/stripe/#test-mode))
5. Add a product to the cart and apply the same coupon via the Cart block. You should get the following error message: “Coupon usage limit has been reached.”

<img width="724" alt="Markup 2022-02-10 at 22 14 16" src="https://user-images.githubusercontent.com/14235870/153524969-437fb84f-11f7-466c-bae8-8e6b45db64e5.png">

### Can adjust shipping address using the calculator

1. Set up [Shipping in WooCommerce](https://woocommerce.com/document/setting-up-shipping-zones/)
2. Follow steps 1 to 7 from [Can see the correct tax in the Checkout block](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20see%20the%20correct%20tax%20in%20the%20Checkout%20block)
3. Adjust shipping Address

### Can have different shipping and billing addresses

1. Set up [Shipping in WooCommerce](https://woocommerce.com/document/setting-up-shipping-zones/)
2. Follow steps 1 to 7 from [Can see the correct tax in the Checkout block](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20see%20the%20correct%20tax%20in%20the%20Checkout%20block)
3. Uncheck the “Use same address for billing” option. The “Billing Address” section” should be displayed
4. Fill in the second address

### Can use express checkout

—

### Can create an account

—

### Can log in to an existing account

—

### Can choose a shipping option

1. Set up [Shipping in WooCommerce](https://woocommerce.com/document/setting-up-shipping-zones/) (Add more than one shipping option)
2. Follow steps 1 to 7 from  [Can see the correct tax in the Checkout block](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20see%20the%20correct%20tax%20in%20the%20Checkout%20block) 
3.  Scroll down to the “Shipping options” section and choose another shipping option. You should be able to see changes reflected in the price

<img width="866" alt="fYeD8Q" src="https://user-images.githubusercontent.com/14235870/153524991-2fd5f3e4-0f38-46e9-9c99-a22757761459.png">

### Can choose a payment option

1. Set up multiple payment options using [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/)
2. Follow steps 1 to 7 from  [Can see the correct tax in the Checkout block](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20see%20the%20correct%20tax%20in%20the%20Checkout%20block) 
3. Scroll down to the “Payment options” section and choose another payment option, then place an order.  ([Setup Woo payments Dev Mode](https://woocommerce.com/document/payments/testing/dev-mode/) to test payments)

### Can place an order as a guest

1. Enable guest checkout if necessary. Go to WooCommerce > Settings > Accounts & Privacy > Guest checkout > Check “Allow customers to place orders without an account”
2. Follow steps 1 to 5 from  [Can see the correct tax in the Checkout block](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20see%20the%20correct%20tax%20in%20the%20Checkout%20block) 
3. Visit your store in incognito mode (or log out from your WordPress website) and add the newly created product to the cart
4. Go to the newly created page (i.e., Containing the Checkout Block) and place an order.

### Can place an order as logged in user

—

### Can see the order confirmation page

1. Follow steps 1 to 5 from  [Can see the correct tax in the Checkout block](bear://x-callback-url/open-note?id=BB93E3AD-2544-4BFC-93E8-4C2780241269-18762-0000007D883CD82B&header=Can%20see%20the%20correct%20tax%20in%20the%20Checkout%20block) 
2. Place your order. You should be redirected to the order confirmation page:

<img width="1100" alt="hus64P" src="https://user-images.githubusercontent.com/14235870/153525017-3109653d-f3cf-4b85-8bc7-5fd5936a5c98.png">

**Comment by tarhi-saad** [comment]
The above comment is a suggestion for testing directions!

**Comment by tarhi-saad** [comment]
We can find the wiki page at this link: https://github.com/woocommerce/woocommerce-gutenberg-products-block/wiki/Critical-Flows-Testing-Directions.
