### ISSUE TITLE
Store Editing Templates: Clearing customizations requires a refresh.

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5704]
## Describe the bug
If you customize a block template, and then via the "Browse All Templates" view, clear those customizations when you click the block template they still exist in the Editor and require a browser refresh to clear. At first I thought this was a Gutenberg issue, but this issue does not occur when disabling WooCommerce & WooCommerce Blocks.

## To reproduce

1. With WP 5.9 + WooCommerce activate go to Appearance > Site Editor
2. Go to "Browse all templates" and select a template to make customizations to.
3. Save the customizations, go back to "Browse all templates" view and clear the customizations via this view.
4. Aftering clearing the customizations, click into the block template again and see that your customizations are still there.
5. Refreshing the browser here fixes the problem.

## Expected behavior
On step 4 I expect that the customizations will have cleared.

### WordPress (please complete the following information):
* Core version: 5.9
* WooCommerce version: 6.1.1
* WooCommerce Blocks version: 6.8.0

**Comment by tomasztunik** [comment]
Easier steps to reproduce:

- Go to template editor
- Add a block to any page template (Woo or not)
- Open dropdown with area/template switcher
- Hit "Clear customisations"
- Changes are persisted

Confirmed that with WooCommerce disabled this path works fine as well.

**Comment by tomasztunik** [comment]
I've found that reverting this change #5342 fixes the issue. 

Problem here is that we alter behaviour of the `get_block_file_template` and instead of allowing it to retrieve the original theme for given template or part when it's called explicitly we return current state.

When reverting theme to get the original state we call the [WP_REST_Templates_Controller->get_item](https://github.com/WordPress/wordpress-develop/blob/a5c59978a2cd459604710a86d5106cb540fea434/src/wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php#L240-L243) where ` $request['source'] === 'theme' `. Without WooCommerce installed it goes through that method and returns it with `get_block_file_template`, and as desired returns original theme state of the template.

When WooCommerce is enabled BlockTemplatesController will capture this action with `maybe_return_blocks_template` hooked on `pre_get_block_file_template`. Instead of using the `get_block_file_template` it either falls back to [gutenberg_get_block_template](https://github.com/WordPress/gutenberg/blob/7628871fb78b85f5f2adac10a80ad7dda7246b4a/lib/compat/wordpress-5.9/block-template-utils.php#L784) which returns database version and original only as a fallback, or if `gutenberg_get_block_template` is not present will return get_block_template which which works same as above - will return latest version and original as fallback.

I'm not aware of all possible implications reverting #5342 can bring so will leave it at this - Hopefuly we can wrap it up on Monday 🚀 

cc: @Aljullu

**Comment by tjcafferkey** [comment]
Thanks @tomasztunik! Reverting https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5342 will fix the "Clear Customisations" functionality accessed from inside the Site Editor (see screenshot below) although will reintroduce the bug which is described here https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5272. I believe these are separate issues that we have been looking into.

![Screenshot 2022-02-08 at 15 11 24](https://user-images.githubusercontent.com/8639742/153015765-e3672311-c685-4d15-87f8-8b7bbce58ac7.png)

The more I look into the issue _described in the reproduction steps_ the more I think it's an issue with the Site Editor, perhaps some frontend caching between route changes that is incorrectly persisting between the All Templates list and the Site Editor view. There is some real funny business going on. Even though the below videos show two _slightly_ different issues I suspect these are symptoms of the same underlying problem.

**With WooCommerce & WooCommerce Blocks installed:**

https://user-images.githubusercontent.com/8639742/153003283-49d01db9-72b4-4b6b-a0da-6ce705d552ee.mp4

**Without WooCommerce & WooCommerce Blocks installed:**

https://user-images.githubusercontent.com/8639742/153003371-3f3ce679-1327-436d-8328-07244dd47943.mp4

For reference this is the package we use for routing: [history](https://www.npmjs.com/package/history)
