### ISSUE TITLE
Woo Customized templates are styled differently

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#5715]
## Describe the bug
In the Site Editor, when a template from a theme gets customized, you can see the following indicators:

1. A three dots menu item is added to the right-most cell
2. Hovering over the `addedBy` icon will display a popover saying “This template has been customized”
3. A small blue dot will appear over the `addedBy` icon.

(3.) is missing from templates added by Woo, making it harder for users to spot customized templates.

Likely, we just need to add the `is-customized` class name to the container element.

## To reproduce

1. Go to Appearence → Site Editor → Templates
2. Select a template from a theme and customize it, and save it
3. Notice the blue icon and the other two indicators mentioned above
4. Do the same with a block from Woo (e.g. “Single Product”)
5. Notice the blue dot is missing

## Expected behavior
Blue dot and element class should be there

## Screenshots
<img width="879" alt="Screen Shot 2022-02-03 at 21 47 09" src="https://user-images.githubusercontent.com/1847066/152426052-daa49aca-372c-46b4-b33d-0398bb802649.png">

**Comment by tjcafferkey** [comment]
This has been fixed by @Aljullu recently in Gutenberg, it is likely that you do not have the plugin installed but [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/list/added-by.js#L103) is where the class gets added and [here is the commit](https://github.com/WordPress/gutenberg/commit/51454d4ef88680d3479518b057883cbf06d2a833#diff-83460fae5e961b737d3c89d22a7bfdd0e7dbbdb5b4b55b2d736deb07de07b6d5) in Gutenberg.

I will close this issue but feel free to reopen if the issue persists.

**Comment by sunyatasattva** [comment]
@tjcafferkey Yea my problem here was specific to E2E tests, since we do run them without Gutenberg installed. I guess I'll have to wait until v. 12.5.3 gets added to core then :)
