### ISSUE TITLE
Filter Products by Attribute block in Dropdown display mode fails search because of input case sensitivity handling

### ISSUE THREAD

**Issue by luanluta** [woocommerce/woocommerce-gutenberg-products-block#5718]
## Describe the bug

Searching on a mobile browser (Chrome and Safari) in the **Filter by Attribute** block the selections disappear as soon as you start typing.

## To reproduce

1. Visit [a page with a **Search by Attribute**](https://luanwootesting.mystagingwebsite.com/custom-shop/) block on an mobile device with the Chrome or Safari browser.
2. Start typing in the search field.

## Expected behavior

The search results should display and be clickable.

## Screen recordings of the issue

Safari (iPhone): https://d.pr/v/JROW4M
Chrome (Android): https://d.pr/v/jSdrRb

### WordPress (please complete the following information):
* Core version:  5.9
* WooCommerce version: 6.0.0
* WooCommerce Blocks version:  6.3.3

## Additional context

This issue isn't present in a mobile Firefox browser.

Video: https://d.pr/v/mYCucQ

**Comment by luanluta** [comment]
Originally reported: 4748011-zen

**Comment by tomasztunik** [comment]
Confirmed ✅ 
  
Issue affects mobile and desktop and is caused by input case sensitivity mismatch and component will accept only lower case text as valid input. 
  
ie. if attribute is called "Large" it will find it only if we type "large", if we type "Large" with capital letter - no results are returned.

**Search should be case insensitive.**
