### ISSUE TITLE
Twenty Twenty-Two: WooCommerce templates might not take the full width in certain circumstances

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5863]
## To reproduce

1. Go to Site Editor > Templates and edit any WooCommerce template (Product Tag, for example).
2. Edit the Group block that wraps the Legacy Template block. Set it not to Inherit default layout and to have a background color.
<img src="https://user-images.githubusercontent.com/3616980/154245993-499811fc-0c08-4e90-983b-edcee705373c.png" alt="" width="285" />

3. Visit the product tag page in the frontend.
4. Notice the contents are aligned to the left.

## Expected behavior

Contents should take the entire width.

## Screenshots

![imatge](https://user-images.githubusercontent.com/3616980/154246108-ea36c61c-63b4-46a4-9e7c-170d52da6c4f.png)

## Additional context

I think the issue comes from this line in WC core:

https://github.com/woocommerce/woocommerce/blob/265be6b51440b1d88d945234dc076487031a63f0/plugins/woocommerce/legacy/css/twenty-twenty-two.scss#L71

That means the fix might need to be done in WC core.

**Comment by frontdevde** [comment]
Looking into this, it seems to me that it was an intentional decision to not have the top-level group blocks' width run wider than 1000px ([related WooCommerce core discussion here](https://github.com/woocommerce/woocommerce/pull/31536#pullrequestreview-843819297)). Without the 1000px limit, the content gets stretched out over the entire viewport which leads to user interface elements being very far apart on large screens. Not certain about that though, so pinging @vedanshujain @jeffstieler who discussed this on the PR that introduced the 1000px limit. Can you clarify if we should change this behavior and allow for folks to go full width with top-level group blocks? Or should we keep it as is?

That said, something else is definitely broken here and needs to be fixed. When changing the background color, without even touching the "Inherit default layout" switch, the layout suddenly becomes left-aligned. This seems to be because Gutenberg sets inline styles for `.wp-site-blocks > .wp-block-group.has-background` with high specificity and `!important` for the margins that aren't accounted for in the WooCommerce styles for Twenty Twenty-Two.

**Comment by Aljullu** [comment]
Right... That's a tricky issue. I took a quick look and there are a couple of things that I consider we should do:

1. Investigate if we can [add back the content wrappers](https://github.com/woocommerce/woocommerce/blob/11fa76e447a7bbc19ba133cc69f426792096c117/plugins/woocommerce/includes/theme-support/class-wc-twenty-twenty-two.php#L23-L25). Not sure why they are removed, but they break wide/full alignment of the Legacy Template block (pull were aligment was added: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5433).

2. Remove the [1000px max-width](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/legacy/css/twenty-twenty-two.scss#L71) from Group blocks. Instead of doing that, we should make it so the Legacy Template block defaults to wide width (which is exactly 1000px) in TT2. I don't know if that's possible thought (maybe with `theme.json`?). But that seems to be the "block-theme-way" of solving this issue.

**Comment by dinhtungdu** [comment]
> Investigate if we can add back the content wrappers. Not sure why they are removed, but they break wide/full alignment of the Legacy Template block (pull were aligment was added: Add wide and full alignment support for legacy template block #5433).

I don't see any issue adding the content wrapper back. By adding it back for Twenty Twenty-Two, we will treat that theme the same way as other block themes.

> Remove the [1000px max-width](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/legacy/css/twenty-twenty-two.scss?rgh-link-date=2022-03-03T14%3A49%3A38Z#L71) from Group blocks.

In addition to the group, we also need to remove the hard-coded width for inner blocks [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/legacy/css/twenty-twenty-two.scss#L61-L68).

> Instead of doing that, we should make it so the Legacy Template block defaults to wide width (which is exactly 1000px) in TT2. I don't know if that's possible thought (maybe with theme.json?)

I think we can even set the default alignment for Classic Template blocks to `wide`.

**Comment by Aljullu** [comment]
> I think we can even set the default alignment for Classic Template blocks to `wide`.

Do you think that should be done for all themes or only when TT2 is active?

**Comment by dinhtungdu** [comment]
> Do you think that should be done for all themes or only when TT2 is active?

I mean setting the default value of the block for all themes. The content size and wide max width are [used interchangeably](https://github.com/WordPress/gutenberg/blob/e7fbb88180f53acc77acf4c0c3859e81675ab4de/lib/block-supports/layout.php#L44-L45) when only one of them is set. And I think wide width is the appropriate default value for product grid and Single Product. We also should provide a fallback value when none of those widths is set.

**Comment by dinhtungdu** [comment]
Reopen for https://github.com/woocommerce/woocommerce/pull/32840
