### ISSUE TITLE
WooCommerce Bocks throws a fatal error if WooCommerce Brands is active on the site.

### ISSUE THREAD

**Issue by raifd** [woocommerce/woocommerce-gutenberg-products-block#5988]
## Describe the bug

If both [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/?aff=10486&cid=1131038) and [WooCommerce Brands](https://woocommerce.com/products/brands/?aff=10486&cid=1131038) are active on a site and you try to change anything about a product a Fatal Error is thrown:

`There has been a critical error on this website. Please check your site admin email inbox for instructions.`

I have tested with the following versions of [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/?aff=10486&cid=1131038): 

- 6.8.0
- 6.9.0
- 7.0.0
- 7.0.1

The issue affects the last two only (v7.0.0 & 7.0.1)

## To reproduce

1. Install [WooCommerce Brands](https://woocommerce.com/products/brands/?aff=10486&cid=1131038) (the last version)
2. Install [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/?aff=10486&cid=1131038) (v7.0.0 or 7.0.1)
3. Head to **Products** and try to: _Add a new product_ or _Edit_ an existing product
4. `There has been a critical error on this website. Please check your site admin email inbox for instructions.`

## Expected behavior

Compatability issues!

### WordPress (please complete the following information):

-   Core version: [e.g. 5.9.1]
-   Gutenberg version (if installed): not installed
-   WooCommerce version: [e.g. 6.2.1]
-   WooCommerce Blocks version: [e.g. 7.1.0]
-   Site language: English
-   Any other plugins installed: [WooCommerce Brands](https://woocommerce.com/products/brands/?aff=10486&cid=1131038)

## Additional context

Here are the logs that get generated with this error:

[logs.txt](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/8178677/logs.txt)

**Comment by raifd** [comment]
10987371-hc

**Comment by ralucaStan** [comment]
Thank you @raifd for opening this. I was able to reproduce this.

**Comment by ralucaStan** [comment]
Hi @raifd,
we got a chance to look into this and it seems that the error is caused be the rename of the `gutenberg_build_template_result_from_file` method made in [this PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5746), included indeed in the v7.0.0.

As `BlockTemplateUtils` methods aren't part of the public API, issues like this is something to be expected when reaching for undocumented functions from WooCommerce Blocks, that are prone to change.

So in order to fix this the WC Brands will need to update their code. 

As there is nothing actionable on our side and I can't transfer this issue to their repo, I am going to close this issue and kindly ask you to reopen this on the WC Brands repo.

**Comment by puntope** [comment]
Howdy @raifd and @ralucaStan 

We pushed a patch for this in [WooCommerce Brands 1.6.28](pb0Spc-2lA-p2). 

Basically, we duplicated `BlockTemplateUtils` to prevent this in the future until all the Gutemberg/Blocks related functions get more stable. 

cc: @tjcafferkey @sunyatasattva

**Comment by sunyatasattva** [comment]
Thanks @puntope for being so responsive! We understand that's not the ideal solution, but we hope to come with something more stable and consumable soon! :)

**Comment by puntope** [comment]
> Thanks @puntope for being so responsive! We understand that's not the ideal solution, but we hope to come with something more stable and consumable soon! :)

Ping us when that happens  :)

**Comment by raifd** [comment]
Thanks folks 👍
