### ISSUE TITLE
Page reloads twice when the shopper sets a price filter and attribute filter using blocks in a PHP template.

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6330]
When Filter Products by Price and Filter Products by Attribute are used in the Product Catalog template and the shopper selects both filters, the page reloads twice.

## To reproduce

1. With a block theme, go to Appearance > Site Editor.
2. Go to Templates and edit the Product Catalog template.
3. Above the WooCommerce Classic Template block, add the Filter Products by Price and Filter Products by Attribute blocks.
4. In the frontend, filter by price and let the page reload.
5. Now, filter also by attribute.
6. Notice the page reloads twice.

## Expected behavior

The page should only reload once.

## Screenshots

https://user-images.githubusercontent.com/3616980/165425137-34a877d9-f74f-436e-9a2a-7a8131817727.mp4

**Comment by tjcafferkey** [comment]
For more information on this, the page reloads twice here because once you activate the Price Filter to for example $60, and then activate an Attribute Filter, if the products returned never exceed above $50 then the price filter is now redundant. And because of this, the price filter resets itself and subsequently triggers another reload as it removes its own parameters from the URL.

To prevent this, we need to ensure the price filter does not reset itself unless the user intentionally triggers it themselves via the Active Filters block or the Price Filter block.

**Comment by dinhtungdu** [comment]
> To prevent this, we need to ensure the price filter does not reset itself unless the user intentionally triggers it themselves via the Active Filters block or the Price Filter block.

This actually the behavior of the widgets version. The price filter doesn't update itself when the price range changes.
