### ISSUE TITLE
Fatal Error with PHP Templates when All Products block is added to the Mini Cart.

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#6383]
## To reproduce

1. Activate Twenty Twenty-Two.
2. Edit the Mini Cart template part.
3. Add the All Products block to the empty view.
4. Add the Mini Cart block to the header if haven't.
5. Go to the Shop page.
6. See the error.

Tracing down the bug, the duplicate data registration for `has_filterable_products` causes the issue.

## Expected behavior

No fatal error.

## Screenshots
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/5423135/167366434-3de055ac-4b7a-4adf-8627-81044d660166.png">

**Comment by jhotadhari** [comment]
Hi,
I get the same error. Because I use the `all-products` block to render the product archive template within a classic theme.

### Some bakground 

When WooCommerce bootstraps, it initializes the `ClassicTemplatesCompatibility` class. This will register the `has_filterable_products` data early during `template_redirect` hook. 
Later, when the `all-products` is being rendered, the block tries to register `has_filterable_products` data again and causes the error.

### Workaround

In `src/BlockTypes/AllProducts.php`, when the data gets registered, I changed the `$check_key_exists` parameter from `null` to `true`. So duplicate data will be ignored if the key exists.
From: `$this->asset_data_registry->add( 'has_filterable_products', true, null );`
To: `$this->asset_data_registry->add( 'has_filterable_products', true, true );`

**Comment by tjcafferkey** [comment]
Hey @jhotadhari we've just merged a fix for this in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6384 which will be getting released today. Thanks!
