### ISSUE TITLE
Document best practices for writing REST endpoints.

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#6432]
Part of pca54o-9i-p2

**Comment by mikejolley** [comment]
Reopen if I'm mistaken, but we have since covered extending the API in https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility#rest-api This does not extend to "general" tips on writing REST endpoints because we inherit from the WP system - developers can reference the REST API Handbook here: 

https://developer.wordpress.org/rest-api/
