### ISSUE TITLE
Call `prime_post_caches` in `get_store_pages` method.

### ISSUE THREAD

**Issue by spacedmonkey** [woocommerce/woocommerce-gutenberg-products-block#6498]
## Describe the bug

In `AssetDataRegistry` [get_store_pages](https://github.com/woocommerce/woocommerce-blocks/blob/83a3e648834ee400db41281e5cdff6d3c118b490/src/Assets/AssetDataRegistry.php#L141), an array of posts objects are loaded using array map. This results in a single database query per post. Instead of doing it this way, call the [_prime_post_caches](https://developer.wordpress.org/reference/functions/_prime_post_caches/). This can be done simple like this.

```
	protected function get_store_pages() {
                $page_list = [
				'myaccount' => wc_get_page_id( 'myaccount' ),
				'shop'      => wc_get_page_id( 'shop' ),
				'cart'      => wc_get_page_id( 'cart' ),
				'checkout'  => wc_get_page_id( 'checkout' ),
				'privacy'   => wc_privacy_policy_page_id(),
				'terms'     => wc_terms_and_conditions_page_id(),
		];
                 $post_ids = array_values( $page_list );
                 _prime_post_caches( $post_ids );
		return array_map( [ $this, 'format_page_resource' ], $page_list);
	}
```

### WordPress (please complete the following information):

-   Core version: [e.g. 5.9]
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: [e.g. 6.1]
-   WooCommerce Blocks version: [e.g. 7.0.0]
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by dinhtungdu** [comment]
@spacedmonkey I tested your suggestion and found an interesting result. Here are what I did:

1. Update `get_store_pages()` to the following:
```
	protected function get_store_pages() {
		$store_pages = [
			'myaccount' => wc_get_page_id( 'myaccount' ),
			'shop'      => wc_get_page_id( 'shop' ),
			'cart'      => wc_get_page_id( 'cart' ),
			'checkout'  => wc_get_page_id( 'checkout' ),
			'privacy'   => wc_privacy_policy_page_id(),
			'terms'     => wc_terms_and_conditions_page_id(),
		];

		$non_cached_ids = _get_non_cached_ids( array_filter( array_values( $store_pages ) ), 'posts' );

		return array_map(
			[ $this, 'format_page_resource' ],
			$store_pages
		);
	}
```
2. Start a Redis server, install and configure [Redis Object Cache](https://wordpress.org/plugins/redis-cache/).
3. Create a new page and add the `<Cart>` block to the page.
4. Flush the Redis cache.
5. Log/observe the value of `$non_cached_ids` using `error_log()` or XDebug.
6. Load the page created above in incognito mode.
7. On the first load, the `$non_cached_ids` value is a non-empty array => there are some pages missing in the cache.
8. On the next loads, the `$non_cached_ids` value is always empty => all store pages are cached without using `_prime_post_caches()`.

So I don't think we need to use `_prime_post_caches()` here because all pages are cached without it.

What is missing from my argument is I haven't figured out exactly when the pages are cached. So there may be a scenario my argument is wrong. Can you take a look when you have time?

cc @Aljullu 

Screencast: https://user-images.githubusercontent.com/5423135/181572956-fc1657f0-b4de-4c53-bdda-4d9821120a27.mov

(I'm sorry for the low resolutions 😅) (I'm not sure why it isn't embeded :/ )

**Comment by spacedmonkey** [comment]
_prime_post_cache will load all posts cache in a single request as it uses wp_cache_get_multiple. It is not able if it comes from cache, it will, it is able priming in a single request.

**Comment by dinhtungdu** [comment]
@spacedmonkey can you explain your point further? I don't think I fully get it.

AFAIK, `_prime_post_caches` will check for the pages that don't exist in the cache among the pages passed to its first argument. From my test, all store pages are cached in subsequent requests without using `_prime_post_caches` so I don't think we need it.

**Comment by spacedmonkey** [comment]
I am on holiday atm, when I am back in front on my keyboard I will share my details. 

To see the issue, if you install query monitor plugin, you will see the calls to WP_post::get_instance.

**Comment by dinhtungdu** [comment]
I tested with Redis, in the subsequent requests to the Cart page (containing the Cart block), there isn't any call to `WP_Post::get_instance()`.

![image](https://user-images.githubusercontent.com/5423135/182058672-ed9eabe9-f54e-4dd9-bc3b-e79aa9e4b244.png)

On the first load, on the same page, `_prime_post_caches` reduces two calls to `WP_Post::get_instance()` but creates two different queries that make the total number of queries unchanged.

<table>
<tr>
	<td> trunk (without `_prime_post_caches`)
	<td> with `_prime_post_caches`
<tr>
	<td> <img width="1256" alt="image" src="https://user-images.githubusercontent.com/5423135/182060581-1636895e-f664-4e9a-9839-691002a13e51.png">
	<td> <img width="1257" alt="image" src="https://user-images.githubusercontent.com/5423135/182061277-f8127cc0-8eff-4501-b470-b9d58184fd43.png">

</table>

**Comment by spacedmonkey** [comment]
It is still worth calling, as with wp_cache_get_multiple this primes caches in a single call.

**Comment by dinhtungdu** [comment]
Thanks for your explanation! Also, thank you @peterwilsoncc for pointing out that using `prime_post_caches()` here will add benefit to sites that don't have persistent cache installed. A PR for this issue is coming.
