### ISSUE TITLE
Audit the current behavior of WooCommerce with a range of block themes

### ISSUE THREAD

**Issue by frontdevde** [woocommerce/woocommerce-gutenberg-products-block#6527]

**Comment by colorful-tones** [comment]
I'm currently in the midst of discovery on adding WooCommerce to a large internal project at Extendify. I.e. this is _very relevant_ to my day-to-day and happy to help out in any way.

**Comment by frontdevde** [comment]
@colorful-tones Great to hear! Our goal with this effort is to ensure that WooCommerce works well with block themes (that aren't optimized for WooCommerce) out of the box. Would love to hear about any visual issues you come across that might generally be affecting block themes and could/should be resolved in Woo Core.

PS: extending this as a general invitation for input from anyone in the community who might be reading this! :)

**Comment by colorful-tones** [comment]
@frontdevde my biggest sadness 😢  came from seeing these variables being output by WooCommerce, but not being able to modify them in my theme, because from what I can tell those variables are not used anywhere in WooCommerce?

![Screen Shot 2022-06-09 at 1 11 11 PM](https://user-images.githubusercontent.com/405912/172905379-e0178c9b-ee3c-4ed6-90ba-6995a01e8bff.png)

I would be happy to contribute to a project where we rewrite Woo's CSS to leverage CSS vars.

**Comment by Marc-pi** [comment]
Hi,
i would say the highest need is to make **all shortcodes** available through blocks
i.e finish "WC blockification", especially for : 
- categories cards, actually there is only category list
- featured products (with a s), actually it is only with a one product display

The same for widgets.
This will also be a nice showcase for the Gutenberg transition as well
Actually we are in a "in between" situation, it slows down the adoption of blocks / blocks themes, due to fragmentation.

**Comment by frontdevde** [comment]
Closing this issue as the goal was to audit the current behavior of WooCommerce with a range of block themes. The work as it pertains to the audit / this issue has been completed.
