### ISSUE TITLE
Checkout page doesn´t show integrated payment medhods (PayPal)

### ISSUE THREAD

**Issue by jennifervivien99** [woocommerce/woocommerce-gutenberg-products-block#6606]
Although Paypal is successfully integrated it doesn't show as payment option in the checkout page.
If used the default shortcode [woocommerce_checkout] the payment methods are all showing in the fronted.

## To reproduce

1. Add the checkout block to a post or page.
3. Activate PayPal payment option and connect it to business account.
5. Visit the checkout page in the frontend.
6. See that Paypal payment is not showing.

## Expected behavior

I expect PayPal payment method to show up in the checkout page.

## Screenshots
<img width="734" alt="default shortcode" src="https://user-images.githubusercontent.com/107916703/174759134-b7e5d550-81c8-414e-bddd-c3f581c293a2.png">

<img width="998" alt="woocommerce blocks" src="https://user-images.githubusercontent.com/107916703/174759199-c58319b2-643b-4dd6-b915-978c1641cd80.png">

### WordPress (please complete the following information):

-   Core version: [6.0]
-   Gutenberg version (if installed): 
-   WooCommerce version: [e.g. 6.6.0]
-   WooCommerce Blocks version: [7.8.3]
-   Site language: german 
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: 
-   Browser [chrome]
-   Version 

### Smartphone (please complete the following information):

-   Device: [huaweip30]
-   OS: 
-   Browser [chrome]
-   Version

**Comment by senadir** [comment]
Hey @jennifervivien99! We currently don't support PayPal payments plugin, we only supported the now deprecated PayPal standard method. Rest assured that supporting PayPal payments is within our immediate plans and something we will tackle soon. Keep an eye on PayPal payments release notes for this integration.

For now, I'm going to close this issue because there's nothing actionable from WooCommerce Blocks side toward this issue, it must be solved on PayPal codebase.

If I'm wrong and this issue is around the PayPal gateway shipped by default previously in WooCommerce, do open this issue back.
