### ISSUE TITLE
Update billing address when shipping address gets change in Cart block

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#6653]
## Describe the bug

If we change the shipping address in the cart block, it doesn't update the billing and shipping address in the Checkout block when flat rate shipping is selected.

Parent issue: #5970

### Screen recording

https://user-images.githubusercontent.com/11503784/177339513-a4cd8f97-4c16-4f17-9565-f9ed81818ef3.mp4

**Comment by Marc-pi** [comment]
I do confirm such issues with cache between cart and checkout blocks during a back and forth
We changed settings to activate debug mode for shipping, but we still have the issue
1. Go to cart, set delivery city/country
2. Go to checkout : it is correctly displayed
3. Go back to cart, change delivery city/country
4. Go to checkout : it is correctly changed
5. Go back to cart : the destination from step 1 is back !!!

Explanation : if you refresh cart page, it works. That because when coming back at step 1, ajax shpiping zone is not refreshed.
Would be better to auto refresh the shipping zone

**Comment by senadir** [comment]
So this issue only happens if you hit the back button on the browser? not when visiting the normally (so it loads fine?).

**Comment by Marc-pi** [comment]
> So this issue only happens if you hit the back button on the browser?

yes. You can be sure "hesitant customers" will face such an issue. Maybe with a refresh button on cart page ? I don't know if we can autorefresh with the true cookie value (that was set at checkout on change)... Maybe make use of browser session data storage ???
