### ISSUE TITLE
convert `usePaymentMethods` & `useExpressPaymentMethods` into payment methods data selectors

### ISSUE THREAD

**Issue by tarhi-saad** [woocommerce/woocommerce-gutenberg-products-block#6665]
The `usePaymentMethods` & `useExpressPaymentMethods` hooks return the list of available payment methods & express payment methods respectively. And, since the payment data store state already contains the list of available payment methods of both types (normal & express payments), it will make more sense to share this data using selectors instead!

https://github.com/woocommerce/woocommerce-blocks/blob/d944a03302b10da4d7011f97c3e7058e19f50c56/assets/js/base/context/hooks/payment-methods/use-payment-methods.ts#L57-L59

https://github.com/woocommerce/woocommerce-blocks/blob/d944a03302b10da4d7011f97c3e7058e19f50c56/assets/js/base/context/hooks/payment-methods/use-payment-methods.ts#L60-L61

**Comment by alexflorisca** [comment]
I've looked into this and I don't think it's a good idea to turn these into selector. For a couple of reasons:

1. These hooks filter and return the actual payment method objects stored in the registry (not the data store). We're using some data from the store, like the `availablePaymentMethods` in order to filter the registered payment methods. The difference here is that the registeredPayment methods contain event handlers and complex data that can't be stored in the data store, so we store them in the [payment registry](https://github.com/woocommerce/woocommerce-blocks/blob/74dd439d3d7efa8c1614ddf20c5ac0c3f67b5458/assets/js/blocks-registry/payment-methods/registry.ts#L4). So these hooks are still useful as they let us interact with the payment methods stored in the registry.
2. The hooks have some caching in place using a ref to prevent unnecessary re-renders.

I think this is ok as it, so I'm closing this issue. @tarunvijwani I know you were going to work on this, apologies for jumping in here, I'd be happy to get your opinion on this and talk you through my thinking here.
