### ISSUE TITLE
Getting empty variation array when adding a variation item without providing attributes using the `/cart/add-item` endpoint

### ISSUE THREAD

**Issue by TatjanaDjurdjevic** [woocommerce/woocommerce-gutenberg-products-block#6774]
## Describe the bug

When adding a variation item with default attributes (see image below) to the `Cart Block` via the `/cart/add-item` endpoint without providing the `variation` attribute we get a [Cart Response](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md#cart-response) instead of an [Error Response](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/cart.md#error-response) and the variation field of the `Cart Response` is empty.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/14235870/185721372-c39ffe36-275d-4c9a-ba13-778ff5230bae.png">

## To reproduce

I created a new local WordPress environment and imported the WooCommerce sample products.

1. Via a rest client, make request for your store with` /wp-json/wc/store/v1/cart` in order to fetch valid Store nounce (or [Disable Nonces for Development](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/nonce-tokens.md#disabling-nonces-for-development))
2. Copy the ID of a variation from `the Hoodie` variable product.
3. Add variation item to cart with:
```
/wp-json/wc/store/v1/cart/add-item?id=31&quantity=1&variation[0][attribute]=Logo&variation[0][value]=No
```

4. You will get a `Cart Response` containing the item with a correct variation field:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/14235870/185719492-8baa023a-fa8f-42e8-9e06-b57b16df645c.png">

5. Add the same item, but this time without providing its attribute:

```
http://dev-store.local/wp-json/wc/store/v1/cart/add-item?id=31&quantity=1
```

7. You will get `Cart Response` (success), but with missing variation info:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/14235870/185719595-fd403752-ec4e-4043-b1a1-351781e1fc4c.png">

8. We end up with two different cart items with the same ID. One has variation info, and the other doesn't! 

## Expected behavior

If it is possible to add item to cart only by product id (no matter if it is variation or not), then Cart Response should return valid information about that product (eg. return product variation info), or add item to cart should not work for ID's of variation. 
I expected Cart Response to return valid information, or Error Response.

**Comment by nielslange** [comment]
Hello @TatjanaDjurdjevic 👋

Thanks for reaching out. I tried to reproduce this case, but wasn't able of doing so. I created a new local WordPress environment and imported the WooCommerce sample products. I then grabbed the blue variation of the `V-Neck T-Shirt`. The parent ID is 13 and the variation ID is 29.

Running the following query, works as expected:

```sh
http://store.local/wp-json/wc/store/cart/add-item?id=29&quanitiy=1&variation[0][attribute]=Size&variation[0][value]=Small
```

<img width="1512" alt="Screenshot 2022-07-28 at 12 08 08" src="https://user-images.githubusercontent.com/3323310/181480451-2bb0a931-db2c-4267-b32f-57d59b830f7b.png">

Calling that query without the attributes leads to an error on my end:

```sh
http://store.local/wp-json/wc/store/cart/add-item?id=29&quanitiy=1
```
<img width="1512" alt="Screenshot 2022-07-28 at 12 09 32" src="https://user-images.githubusercontent.com/3323310/181480662-76b28def-0a26-43ca-b8cf-f85c13f3224d.png">

Can you provide further testing steps so that I'm able to reproduce what are seeing on your end?

**Comment by Colir** [comment]
Same here...

calling
`/wp-json/wc/store/v1/cart/add-item?id=VARIATION_ID&quantity=1`

add the product to the cart but WITHOUT variation information

Calling
`WC()->cart->add_to_cart(VARIATION_ID, quantity);`

add the product to the cart but WITH variation information

**Comment by wavvves** [comment]
Note: there is a typo in the issue description `quanitiy` -> `quantity`

**With valid store nounce add variation item to cart with /wp-json/wc/store/v1/cart/add-item?id=VARIATION_ID&quanitiy=1**

@TatjanaDjurdjevic can you please test this step again making sure the typo gets replaced?

I am going to reproduce @nielslange testing without the typo.

**Comment by TatjanaDjurdjevic** [comment]
Hey @wavvves 👋 
It was just a typo I made while describing the issue.
the call is `/wp-json/wc/store/v1/cart/add-item?id=VARIATION_ID&quantity=1`

I reproduced it again.
I went over all mentioned steps above (step 1 to 8)
At the end i got two different cart items in the cart even though the have the same id.  The only difference is that one product is missing variation info.

**Comment by tarhi-saad** [comment]
Hello @TatjanaDjurdjevic! I was able to reproduce the bug. I followed the steps you mentioned and ended up with two different cart items with the same ID. One has variation info, and the other doesn't! There is only one small detail to reproduce this bug successfully; the attributes shouldn't be required! When I tested with the variation of the `V-Neck T-Shirt` from the WooCommerce sample products, I got an error when calling the query without the attributes.

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/14235870/185717777-22ebb01b-a563-4a84-a92d-f5a387cfcabe.png">

Then I tried with the variation of the `Hoodie` instead. And by providing the attributes we get the variation info:

```
http://dev-store.local/wp-json/wc/store/v1/cart/add-item?id=31&quantity=1&variation[0][attribute]=Logo&variation[0][value]=No
```

<img width="813" alt="image" src="https://user-images.githubusercontent.com/14235870/185719492-8baa023a-fa8f-42e8-9e06-b57b16df645c.png">

And without attributes, we have missing variation info:

```
http://dev-store.local/wp-json/wc/store/v1/cart/add-item?id=31&quantity=1
```

<img width="828" alt="image" src="https://user-images.githubusercontent.com/14235870/185719595-fd403752-ec4e-4043-b1a1-351781e1fc4c.png">

I updated the issue description and title!

**Comment by wavvves** [comment]
Hi @TatjanaDjurdjevic, I linked a [PR](https://github.com/woocommerce/woocommerce-blocks/pull/8226) with a possible resolution. The response was always mirroring the request and not correctly populating the variation data (as it does, for instance, generating the item title on the cart eg: "Hoodie - Red, No" ).

Feel free to try it out, as I'm interested in seeing if I understood the issue correctly. The same applies to you @tarhi-saad since you already managed to reproduce the error 😉
