### ISSUE TITLE
Coupons DELETE should return the full cart

### ISSUE THREAD

**Issue by sitver** [woocommerce/woocommerce-gutenberg-products-block#6879]
For the Store API: Right now, deleting a single coupon returns the full cart (as do most cart actions), but deleting all coupons just returns an empty array. It's no big deal, but it would seem to make more sense just to return the whole cart when you delete all coupons, so behaviour is consistent.

**Comment by sunyatasattva** [comment]
Thank you for reporting that @sitver, I've made a draft PR to address this issue, you can find it here: https://github.com/woocommerce/woocommerce-blocks/pull/6880

However, this is unlikely to get merged as it is a breaking change, unfortunately. I'll discuss it with my team.

**Comment by ralucaStan** [comment]
Internal conversation p1660195800385199-slack-C02UBB1EPEF

**Comment by mikejolley** [comment]
> deleting a single coupon returns the full cart (as do most cart actions)

There are 3 types of "delete" operations in this API. Deleting a single resource, deleting a collection of resources, and the "remove-x" endpoints.

Removing something from the cart via the `/cart/remove-coupon` endpoint is actually a POST request, not a DELETE request. That is why it returns the full cart object. This includes:

- `/cart/remove-coupon`
- `/cart/remove-item`

The actual DELETE requests include:

- DELETE /cart/coupons
- DELETE /cart/coupons/code
- DELETE /cart/items
- DELETE /cart/items/key

These ones should have more appropriate handling. For a single resource, no response with a 204 code is intentional. For the collections, they currently return `[]` and code 200. This could be replaced with 204, but for clients there won't be much difference. 

Either way, I don't think we should return a full cart instance here. cc @senadir

**Comment by ralucaStan** [comment]
I think we can close this ticket, as there seems to not be anything actionable on our side. @sitver do reach out if you have extra questions.

**Comment by sunyatasattva** [comment]
Shouldn't this be closed as Won't Fix instead than as completed?
