### ISSUE TITLE
Feedback on ./src/StoreApi/docs/checkout.md

### ISSUE THREAD

**Issue by sitver** [woocommerce/woocommerce-gutenberg-products-block#6884]
Note on the docs: Some additional clarity on what to send in payment_details for different popular payment methods (Stripe, Paypal, etc.) would be supremely useful here. 

Note on the endpoint itself: Why do the docs call for addresses to be sent as arrays for this endpoint (/checkout) when for all other endpoints they are sent as objects (which seems more logical)?

EDIT: This may just be an error in the documentation. The official announcement blog post includes an example where addresses are sent to the checkout endpoint as objects https://developer.woocommerce.com/2022/03/25/store-api-is-now-considered-stable/

**Comment by tarunvijwani** [comment]
@sitver Thank you for bringing our attention to this.

>Note on the docs: Some additional clarity on what to send in payment_details for different popular payment methods (Stripe, Paypal, etc.) would be supremely useful here.

We can't say for sure because this is usually provided by the payment method client code. You check this example of [WooCommerce Stripe work.](https://github.com/dechov/headless-woocommerce/blob/1e359f97d2f1312cf92aac5a26acbfe870cb67b2/components/checkout/stripe.js#L47-L52)

>Note on the endpoint itself: Why do the docs call for addresses to be sent as arrays for this endpoint (/checkout) when for all other endpoints they are sent as objects (which seems more logical)?
EDIT: This may just be an error in the documentation. The official announcement blog post includes an example where addresses are sent to the checkout endpoint as objects https://developer.woocommerce.com/2022/03/25/store-api-is-now-considered-stable/

Yes, it is returning an object. We have created a [PR](https://github.com/woocommerce/woocommerce-blocks/pull/6974) to update the document.
