### ISSUE TITLE
Pressing Ctrl+Z behaves different than clicking 'Undo' inside a block search input

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#690]
![Peek 2019-07-04 19-19](https://user-images.githubusercontent.com/3616980/60681740-a4ddf680-9e90-11e9-96d5-c21774263135.gif)
_(after writing `lorem` the second time, I pressed <kbd>Ctrl</kbd>+<kbd>Z</kbd>)_

**To Reproduce**
1. Create a post and add a _Feature Product_ block.
2. Write something in the search input.
3. Open the context menu and click _Undo_.
4. Notice it clears the search input field.
5. Repeat the process but instead of undoing the action using the context menu option, press <kbd>Ctrl</kbd>+<kbd>Z</kbd>.
6. Notice instead of clearing the search input it removes the block.

**Expected behavior**
The behaviour of _Undo_ and <kbd>Ctrl</kbd>+<kbd>Z</kbd> should be the same.

**Comment by nerrad** [comment]
I was able to reproduce with both the GB editor included with WP core (5.2.2) and the GB plugin active (6.2.0).  I think the problem here is upstream in the block editor itself because Gutenberg overrides undo/redo functionality in the editor context maintaining it's own history state.  There are a number of in progress pulls and issues related to undo/history functionality  - [here is the undo search via the history label](https://github.com/WordPress/gutenberg/labels/History).  I don't see anything that is _specifically_ the same as this issue, but there's enough variation in reports to correlate to the fact it's still a bit buggy in instances.

All that to say, I don't think this is something specific that can be fixed in our repo, definitely does need addressed, but probably best addressed in the Gutenberg repository?

**Comment by Aljullu** [comment]
Right, Gutenberg's undo feature seems to be a bit unreliable in some edge-cases yet. I'm ok leaving this issue for the future, but do you think we should already close this issue? There is no guarantee that this issue will be fixed in a future update of Gutenberg so maybe it might make sense leaving it open just to remember this issue exists.

**Comment by nerrad** [comment]
> There is no guarantee that this issue will be fixed in a future update of Gutenberg so maybe it might make sense leaving it open just to remember this issue exists.

I agree.

**Comment by ellatrix** [comment]
https://github.com/WordPress/gutenberg/pull/16989 fixes this, but not in all browsers.

**Comment by ellatrix** [comment]
Would be nice to create an upstream issue and close this one I guess?

**Comment by nerrad** [comment]
I revisited this with the following test environment:

- Latest Woo Blocks (master)
- The GB Branch (https://github.com/WordPress/gutenberg/pull/16989) by @ellatrix rebased on top of the latest GB master.
- Latest Google Chrome Browser.

Now, choosing undo from the context menu or clicking `ctrl-z` will reset to the state before the block was selected (or from the shortcut selection).  So at least now the behaviour is consistent, but it is a bit jarring if the expectation is that the input will clear.

**Ctrl-z**

![ctrl-z example](https://cl.ly/b74700cdec63/Screen%252520Recording%2525202019-09-26%252520at%25252009.27%252520AM.gif)

**Context Selection**

![context selection](https://cl.ly/a846a30f309b/Screen%252520Recording%2525202019-09-26%252520at%25252009.28%252520AM.gif)

**Comment by nerrad** [comment]
Since this is primarily a GB issue, I'm going to close this.
