### ISSUE TITLE
Shipping package names in checkout block do not render HTML

### ISSUE THREAD

**Issue by NTShop** [woocommerce/woocommerce-gutenberg-products-block#6903]
## Describe the bug

When using the checkout block any modified package names do not render HTML content, instead any HTML is rendered as HTML entities. _This does not occur when using the checkout shortcode._

## To reproduce

1. Create a page using the checkout block.
2. Add the following code to the theme's functions.php file: 

```
add_filter( 'woocommerce_shipping_package_name', 'test_package_name', 1, 3 );
function test_package_name( $title, $index, $package ) {
	return $title . '<br/>test<br/>test2';
}
```

3. Put something in the cart and go to checkout. You will see the HTML entities near the shipping package name. 
4. Replace the checkout block with the checkout shortcode [woocommerce_checkout]
5. View the checkout page. You will see the HTML rendered as expect with HTML line breaks.

## Expected behavior

HTML should be rendered and not converted to HTML entities.

## Screenshots
**Checkout block:**
![checkout-block](https://user-images.githubusercontent.com/6944811/184676320-92f32621-b6fc-4865-a847-961514bcb601.png)

**Checkout shortcode:** 
![checkout-shortcode](https://user-images.githubusercontent.com/6944811/184676279-627ca563-233e-493e-918c-3fc0e98c8247.png)

### WordPress (please complete the following information):

-   Core version: 6.0.1
-   Gutenberg version (if installed): 
-   WooCommerce version: 6.8.0
-   WooCommerce Blocks version: 8.2.1
-   Site language: English
-   Any other plugins installed: None

**Comment by tarhi-saad** [comment]
Thank you, @NTShop, for reporting this bug! I was able to reproduce it.

Woocommerce uses the function `wp_kses_post` to output the `package name` in the page in this [line of code](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cart-shipping.php#L28). This function keeps HTML tags and attributes intact. On our end, we are rendering the `package name` using React (see [line of code](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx#L74)) that's why it doesn't render HTML. We may need to use the `dangerouslySetInnerHTML` DOM attribute to fix it.

**Comment by opr** [comment]
Let's also ensure they apply the `itemName` filter.  (Like they do in the Cart/Checkout order summary here: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/components/cart-checkout/order-summary/order-summary-item.tsx#L71-L76)
