### ISSUE TITLE
Global styles don't work in the Featured Product and Featured Category blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#6988]
## To reproduce

1. Install a block theme.
2. Open Appearance > Site Editor.
3. Add a Featured Product and a Featured Category block.
4. Customize the global styles related to those blocks (click on the styles button on the top toolbar and then the _Blocks_ section).
<img src="https://user-images.githubusercontent.com/3616980/186676876-6f498f89-f0b6-4124-81c3-38cdeb7c222d.png" alt="" width="273" />
5. Notice the styles aren't applied.

## Expected behavior

Global styles should work for those two blocks.

## Additional context

According to [this comment](https://github.com/WordPress/gutenberg/issues/40808#issuecomment-1225975167) from @oandregal, the issue might be that we are not adding the correct class name to the blocks.

**Comment by danielwrobert** [comment]
Continuing to explore this but I'll share some initial findings after a first pass:

[This comment](https://github.com/WordPress/gutenberg/issues/40808#issuecomment-1225975167) from @oandregal (also linked above) states that these blocks use the `wc-block-featured-product` instead of the expected `wp-block-woocommerce-featured-product` class. What I'm seeing is that they use _both_ classes - which is also consistent with the other blocks.

There are two key differences I've found with these two blocks and, for the sake of comparison, the Mini Cart block:

1. The structure of the blocks - these Featured blocks apply the `wc-block-featured-product` class to a child element of the main block container and the `wp-block-woocommerce-featured-product` class to the main container. The Mini Cart block applies both classes to the main block container.
2. There seems to be a missing CSS selector on these Featured blocks of `.editor-styles-wrapper .wp-block-woocommerce-featured-product`. Both of the classes are applied individually but they are not applied together, which is the selector that the Global Styles seem to use to apply the changes.

To give an example of the second point above, adding the following CSS block in Dev Tools will apply the expected Global Style visual adjustments in the editor:

```
.editor-styles-wrapper .wp-block-woocommerce-featured-product {
    background-color: var(--wp--preset--color--light-green-cyan);
    border-radius: 5px;
    border-color: #cf2e2e;
    border-width: 2px;
    border-style: solid;
    color: var(--wp--preset--color--vivid-purple);
}
```

I was viewing this with the following versions:

- WP             6.0.1
- WC             6.8.2 (also tested with 6.9.0 Beta 2)
- WC Blocks 8.4.0-dev (also tested with 8.3.1)

In my findings, this only seems to be an issue in the Editor (Beta) part of the admin. When adding the block to a Post or Page, you can see the applied Global Styles, as expected. I'm also seeing the styles applied on the frontend, when saved. See the following screenshots for additional details.

Frontend view of block added via Editor (Beta) vs via Page:

| Template (Home) | Page |
| ------ | ----- |
|  ![CleanShot 2022-08-25 at 22 11 41](https://user-images.githubusercontent.com/481776/186921815-5902d46b-555f-4354-8826-3903a958fb2d.png)  |  ![CleanShot 2022-08-25 at 22 11 50](https://user-images.githubusercontent.com/481776/186921835-fa2b4bc8-4b0d-4717-9038-b2d3b7de8648.png)  |

Admin/editor view of block added via Editor (Beta) vs via Page:

| Template (Home) | Page |
| ------ | ----- |
|  ![CleanShot 2022-08-25 at 22 17 22](https://user-images.githubusercontent.com/481776/186922272-80731072-18b9-4cb7-8175-5e77d163cd14.png)  |  ![CleanShot 2022-08-25 at 22 05 34](https://user-images.githubusercontent.com/481776/186922322-240da3cc-8727-4095-a2bc-2c72f0ed3ef6.png)  |

Editor (Beta) Template with CSS (added via Dev Tools) vs Mini Cart Block (for comparison):

| Featured Product (modified) | Mini Cart (current state) |
| ------ | ----- |
|  ![CleanShot 2022-08-25 at 22 05 03](https://user-images.githubusercontent.com/481776/186922854-c96f3613-a4c8-4b0f-9cad-7577e2cd6453.png)  |  ![CleanShot 2022-08-25 at 22 13 39](https://user-images.githubusercontent.com/481776/186922781-e1d73090-6e45-4822-914a-7d7a9b3a7090.png)  |

**Comment by danielwrobert** [comment]
After further exploration, it seems that the culprit is the `__experimentalDuotone` property on the `Supports` attribute for these blocks.

After removing the property, everything seems to work as expected.

I'm not sure if it's the direction we want to go but I've made a PR (#7000) to remove this property from both of the impacted blocks.

Note that these were the only two blocks in the repository using this experimental property.
