### ISSUE TITLE
Move ProductsControl to @woocommerce/components

### ISSUE THREAD

**Issue by alexsanford** [woocommerce/woocommerce-gutenberg-products-block#709]
**Is your feature request related to a problem? Please describe.**

I would like to use the `ProductsControl` component within my plugin. See https://github.com/Automattic/sensei-wc-paid-courses/pull/127 (note that this repo is private to Automattic).

**Describe the solution you'd like**

Ideally, the `ProductsControl` component would be available from the `@woocommerce/components` package.

**Describe alternatives you've considered**

In the PR linked above, I've added a gulp task which copies the component and its dependencies into my plugin's codebase. This is ok as a workaround, but it would be better to be able to import the component from a package instead.

**Comment by mikejolley** [comment]
@alexsanford This is probably harder than it seems because this component uses a private API endpoint (https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/components/product-control/index.js#L104). The Blocks endpoint makes product data available to authors. WC core API requires admin/edit product permissions.

**Comment by alexsanford** [comment]
Ah, gotcha.

To clarify, I'm actually talking about [`ProductsControl`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/components/products-control/index.js) (plural). But I believe it has the same problem as per [this code](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/components/utils/index.js#L14).
