### ISSUE TITLE
Filter Block margin inconsistencies

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7117]
The margin top of the `Products by Attribute` block doesn’t match `filter by price` and `filter by stock`. 

See examples below. 

You can see the margins are inconsistent when the blocks are positioned in a row:

<img width="1909" alt="Screenshot 2022-09-09 at 11 43 47" src="https://user-images.githubusercontent.com/9888201/189682643-c648fddc-8816-4bb4-a232-28450e34294d.png">

Filter by Attribute using the dropdown style option uses another margin:

<img width="914" alt="Screenshot 2022-09-12 at 15 49 33" src="https://user-images.githubusercontent.com/9888201/189685340-143e213e-3bff-4c80-8862-f3add1dd6149.png">

<img width="304" alt="Screenshot 2022-09-12 at 15 53 23" src="https://user-images.githubusercontent.com/9888201/189686268-3396c7f2-7030-4c40-a988-ab589e3cb3b2.png">

Is it possible to have all match the 'Active filters' example?

**Comment by Aljullu** [comment]
Related: #7018.

**Comment by imanish003** [comment]
Hi @vivialice @Aljullu,

I believe this issue is fixed in [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/7226).

Also, I think you are already aware of this but I just wanted to communicate that you will need to use Align top option for vertical alignment as shown in the image below:
![image](https://user-images.githubusercontent.com/16707866/192282306-c476a7e7-e109-44b3-aae3-c1068c1f05d9.png)

After that filter blocks should be aligned perfectly to the top as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/16707866/192282799-e5bb4075-5224-4d08-a5d5-426a7e58efc2.png)

**Note**: If your filter blocks are not perfectly aligned to the top, this might be related to [this issue](https://github.com/WordPress/gutenberg/issues/41324) on Gutenberg. Try using the Gutenberg plugin.

**Comment by vivialice** [comment]
Yep I think it's fixed now. Thanks @imanish003 !
