### ISSUE TITLE
Panel toggle descriptions 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7129]
For the inline input fields, the toggle description remains the same for both states. 
<img width="282" alt="Screenshot 2022-09-12 at 18 16 48" src="https://user-images.githubusercontent.com/9888201/189716154-5ecba684-6cec-4151-9b14-e1f386d6070f.png">

For the apply filters toggle, the description changes on the selection. 
View 1:
<img width="274" alt="Screenshot 2022-09-12 at 18 17 16" src="https://user-images.githubusercontent.com/9888201/189716247-b4552f8c-507c-409c-9958-53615b97b796.png">
View 2: 
<img width="281" alt="Screenshot 2022-09-12 at 18 17 26" src="https://user-images.githubusercontent.com/9888201/189716267-a699db3c-380e-482a-b09e-aebba0df7fe9.png">

I know there has been prior discussions for these but I think we need to stick with one rule for all of our toggles. What have we gone with on other toggles cc any thoughts @ifinoi @sunyatasattva ?

**Comment by sunyatasattva** [comment]
Hey @vivialice thanks for tagging me.

In the interest of not getting our conversation buried in a random Google Doc, I'll write my two cents here. Though perhaps, if we agree, it would be best to write some guidelines in P2.

In my opinion, the most common pattern is that **toggle descriptions should indicate what the setting does, not what it's currently doing** (if need be because of brevity, I believe descriptions should state what the switch will do when it is in its _on_ position).

If dynamic state descriptors are to be provided, they should be provided on the correct sides of the toggle. Those are, however, usually relatively redundant and perhaps should be taken on a case-by-case basis.

Here is a link to an authoritative source on these suggested guidelines: https://www.nngroup.com/articles/toggle-switch-guidelines/

**Comment by vivialice** [comment]
> toggle descriptions should indicate what the setting does, not what it's currently doing

I agree with this as well. It means the user doesn't need to interact with it to discover the result, nothing is hidden. Let's also do as you suggested and add some guidelines in our P2/any other documentation where relevant for future block development.

I will rewrite the apply filters toggle and add my suggestion to this issue for review.

**Comment by vivialice** [comment]
> I will rewrite the apply filters toggle and add my suggestion to this issue for review.

Right after I commented I realise that the existing copy is fine, we just don't need the second line. 

`Products will update when the button is pressed.`

**Comment by imanish003** [comment]
Hi @vivialice,
My understanding based on the above comments is that we want the same UI with the same message when the switch is off i.e. 
![image](https://user-images.githubusercontent.com/16707866/192749789-b1fefae5-217e-413f-99c1-f61ff92d4403.png)

But we don't want the message when the switch is `On`. Something like this screenshot below:
![image](https://user-images.githubusercontent.com/16707866/192749421-a9246c6c-9b78-4977-acfa-17be64ad07c6.png)

Is that correct?

**Comment by vivialice** [comment]
👋  @imanish003 The copy should remain the same for both states. The goal is for toggles to be for turning a feature on or off.

For both states, let's keep the subtext like this: 

<img width="546" alt="Screenshot 2022-11-16 at 17 16 46" src="https://user-images.githubusercontent.com/9888201/202248696-24d4fa88-e664-4029-8af7-107abf3fe436.png">
