### ISSUE TITLE
Confirm new local pickup functionality work well with multiple packages

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7164]
WooCommerce Core supports packages, this can be seen in WooCommerce Subscriptions for example, this issue's goal is to make sure local pickup works smoothly with that feature (all packages are fetched).

This can be done once https://github.com/woocommerce/woocommerce-blocks/issues/7160 is merged.

**Comment by mikejolley** [comment]
I did some preliminary testing of this to see what happens now, and the interface does work in both places:

![Screenshot 2022-10-10 at 14 44 06](https://user-images.githubusercontent.com/90977/194880387-3db79228-f50f-4348-9f7b-f19ba634b7ff.png)

The package naming however is geared toward shipping ([see get_package_name](https://github.com/woocommerce/woocommerce-blocks/blob/b8c07c0b048da379250bce73a4a259cabfb6143d/src/StoreApi/Utilities/CartController.php#L853-L876)). I don't know if we can make this more generic or make use of the filter in the context of shipping. 

What didn't work was when rates were not available for certain packages:

![Screenshot 2022-10-10 at 14 53 49](https://user-images.githubusercontent.com/90977/194882532-0ede837e-eb6f-4d4e-b7c9-54e0d4ea1589.png)

I was able to place an order here which is a bug. It may have been because the original shipping rate was still selected, just not displayed.

So It looks like the problems we need to work out are:

1. How to handle packages when some are shippable, and others only allow pickup.
    - Disable the collection blocks?
    - Show collection AND show shipping address?
2. When a package has no rates, do we skip? Similar to above.
3. We need to either improve validation or handle rate selection/available rates depending on shipping or collection being selected.
4. Label for packages is currently "Shipping Method". Needs to be changed, hidden, or made generic.

cc @senadir
