### ISSUE TITLE
Performance: Only load `cart-fragments.js` when needed.

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#7168]
When a store is using the Cart and Checkout blocks and the Mini Cart Block, I'm assuming there is no need to load the `cart-fragments.js` script. Currently, that script loads on every page and has a performance hit on stores (because of the refresh Ajax requests). I did a _really brief_ experiment disabling the loading of the script on a store that has all the above blocks active and as far as I can tell, nothing was broken. However, this will require more extensive testing on any implementation.

Given articles [like this](https://wpengine.com/support/how-to-disable-cart-fragments-for-woocommerce/) out there, as well as solutions [like this](https://wpengine.com/blog/solving-cart-fragment-dilemma-introducing-live-cart/), I think it'd be a great optimization to implement this. Especially given the mini-cart block already has lazy-loading in place for performance.

**Comment by mikejolley** [comment]
Cart Fragments is designed to update static displays of cart items (e.g. lists of items in the cart, cart totals, etc etc) rendered by themes, plugins, and core (namely, the cart widget).

There are 2 events that trigger a fragment request (found in core's `add_to_cart.js` script) which are:

- added_to_cart 
- removed_from_cart

These occur on the "shop" page where there are AJAX powered add to cart buttons. I believe the other place these events can occur is from product shortcodes.

Removing fragments has no effect on blocks, just legacy things. 

Given the existence of the mini cart, I think we can remove our handling, in blocks, for triggering fragment requests. Mini Cart should be the preferred method of showing carts going forward. **This is part 1 of the issue.** By removing this, we'll be able to reduce AJAX requests on the page, even if the fragments script is present on the page.

Part 2 of the issue is how to safely dequeue the fragment script for performance reasons. This might not be possible without a core change. We'd also need to work out under which circumstances if it safe to dequeue. Until the core Shop page is replaced with blocks, this might not yet be possible.
