### ISSUE TITLE
Delete Summary

### ISSUE THREAD

**Issue by CSPoirier** [woocommerce/woocommerce-gutenberg-products-block#7170]
## What do you like about the Cart & Checkout blocks?
The checkout being a block is great for adding it to pages/post for a quick checkout.
## What do you think is missing from the Cart & Checkout blocks?
More customization in general but even now when attempting to delete the summary section it continually comes back after being deleted multiples times.

**Comment by opr** [comment]
Hi there @CSPoirier thank you for using WooCommerce Blocks and taking the time to leave some feedback on it!

Could you clarify that you're trying to remove the Order Summary Block, i.e. the sidebar of the Checkout block that is highlighted in blue in the image below?

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/5656702/190817337-8865eb21-2455-4352-a9af-89f45e03111c.png">

This is a critical part of the Checkout block as it contains the cart totals/prices (taxes, shipping, fees, etc.) and the place order button, please could you help us understand your use-case a little better? Why do you need to remove this?

Thank you!

**Comment by CSPoirier** [comment]
Thanks for the quick reply!
My instance I was attempting to do was to have a free appointment that the user would pick a date and then enter their details without having to feel like they were checking out.  I'm able to do a plain form bu for the customer to pick a date I have that going through woocommerce and would of liked not to show the pricing details.  Wordpress allows the option to remove this block so when it comes back automatically it's a confusing user experience I guess is all I'm trying to convey.

**Comment by opr** [comment]
@CSPoirier thank you for clarifying - I can see how the block returning after deletion would be confusing. The reason this happens is because it's a "locked" inner-block (because it's a critical part of the main checkout block.) so it has to appear in the main Checkout block's children.

I'll make an issue (#7227) in this repository to track the behaviour and see if it's something we can add a notice for, explaining why it's happening. I don't think allowing the full removal of this inner block is something we plan on doing, though.

As a workaround, would hiding the summary with CSS work for you?

```css
.wc-block-checkout__sidebar {
    display: none;
}
```

**Comment by nielslange** [comment]
Hello @CSPoirier 👋 As we haven't heard back from you for a while, I'm closing this issue now. That said, please don't hesitate to create a new issue if you have further questions or suggestions.
