### ISSUE TITLE
Respect Settings Tax Name in Cart & Checkout 

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gutenberg-products-block#7246]
## Describe the bug
In WooCommerce we have a tab tax (/wp-admin/admin.php?page=wc-settings&tab=tax)
On tax name you can set your custom tax name as  on my example.
![image](https://user-images.githubusercontent.com/6242098/192885957-e1389846-acd4-4a6f-b31f-0d1ca4c28097.png)

The old shortcode checkout respects this setting and shows the value set in the settings on both cart and checkout, see
![image](https://user-images.githubusercontent.com/6242098/192886053-018897ea-133a-4ea0-8165-62963e684d07.png)
![image](https://user-images.githubusercontent.com/6242098/192886100-5ecc2835-dd0c-47d1-8178-11050502026c.png)

When using WooCommerce Blocks thats differnet. Cart and Checkout shows this
![image](https://user-images.githubusercontent.com/6242098/192886359-ea9c5a8c-5d1a-4b6c-a84d-d464b522d036.png)
![image](https://user-images.githubusercontent.com/6242098/192886373-18d86a1d-3750-42c9-ad1b-68abdbbe2866.png)

Seems WooCommerce Blocks uses the translation and ignores the custom text set in settings.

## To reproduce
1. Go to woo settings, turn on tax
2. Click on tax tab and standard tax group
3. put in a tax percentage and add a custom tax name - save
4. go to your block cart and checkout and see if the tax name is shown

## Expected behavior
The tax name can be left blank. In this case, an automatic translation should take place as its done now.
If however the tax name was overwritten in the settings it should be displayed in cart and checkout as on the old shortcode way.

## Screenshots
see above

## Environment
newest wp version
newest version of woo blocks and woocommerce
no other plugins run

**Comment by tarunvijwani** [comment]
@masteradhoc  Thank you for reporting this issue! I'm adding this to our backlog.

**Comment by tarhi-saad** [comment]
Hello @masteradhoc! 👋 Thank you for reporting this bug! 🙌 I followed the testing instructions, and I got different results. On both the shortcode and block versions of the Cart & Checkout, a "tax summary" is displayed above the "Total" section instead of the `(includes [tax_value] [tax_name])`. See the following screenshots for more details:

### Shortcode version

| Cart | Checkout |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/14235870/202526317-3cc5a4c3-c8ac-4056-9970-fa9a0e766ac2.png) | ![image](https://user-images.githubusercontent.com/14235870/202526509-ed9c3606-80ba-4794-b655-d8c178521db0.png) |

### Blocks version

| Cart | Checkout |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/14235870/202526853-162be58e-fd1d-43cd-b6c5-0150c565efaf.png) | ![image](https://user-images.githubusercontent.com/14235870/202527000-7d1e319e-713f-4aba-847e-1e78eee08a19.png) |

Could you test again using a fresh installation? @tarunvijwani, were you able to reproduce this bug last time? Could you see double-check and if the tax summary block is displayed instead?

**Comment by nielslange** [comment]
@tarhi-saad and @tarunvijwani A while ago, I had a chat with @masteradhoc in https://wordpress.slack.com/ and asked him to report this issue here. I just looked it up, and I'm still able to reproduce the issue.

These are the steps I did:

- Go to `/wp-admin/admin.php?page=wc-settings&tab=general` and enable to the option `Enable taxes`.
- Go to `/wp-admin/admin.php?page=wc-settings&tab=tax&section=standard` and add the following tax rate:
<img width="1265" alt="Screenshot 2022-11-21 at 12 16 51" src="https://user-images.githubusercontent.com/3323310/202971089-880e51e1-42fa-4e5d-8e4b-6c3e8d1d682c.png">

- Go to the shop and add a product to the cart.
- Go to the classic cart and verify that the total price contains the tax label `Foo Bar`.
- Go to the cart block and verify that the total price does not contain the tax label `Foo Bar`.
- Go to the classic checkout and verify that the total price contains the tax label `Foo Bar`.
- Go to the checkout block and verify that the total price does not contain the tax label `Foo Bar`.

## Cart

<table>
<tr>
<td>Before:
<br><br>

![classic-cart](https://user-images.githubusercontent.com/3323310/202972422-efe25000-347a-4303-8e14-3c7ea09a4846.png)
</td>
<td>After:
<br><br>

![cart](https://user-images.githubusercontent.com/3323310/202972427-b8fe946b-988f-4db8-8578-b1934190ea3f.png)
</td>
</tr>
</table>

## Checkout

<table>
<tr>
<td>Before:
<br><br>

![classic-checkout](https://user-images.githubusercontent.com/3323310/202972437-389cd1f4-f2b6-4608-be4b-9524fe5502d8.png)
</td>
<td>After:
<br><br>

![checkout](https://user-images.githubusercontent.com/3323310/202972444-2ef5561c-4a80-4e4b-93c1-3f1ed1b7f065.png)
</td>
</tr>
</table>
