### ISSUE TITLE
Notice: Undefined property: stdClass::$area in BlockTemplatesController.php

### ISSUE THREAD

**Issue by ohfuchs** [woocommerce/woocommerce-gutenberg-products-block#7299]
just stumbled across this notice when using get_block_templates with an 'area" query

> Notice: Undefined property: stdClass::$area in BlockTemplatesController.php

https://github.com/woocommerce/woocommerce-blocks/blob/c4d4a31b3af8ab1e81cd5efc0af7f34285b1266f/src/BlockTemplatesController.php#L213

it's caused by a missing $area property in objects created by create_new_block_template_object
https://github.com/woocommerce/woocommerce-blocks/blob/c4d4a31b3af8ab1e81cd5efc0af7f34285b1266f/src/Utils/BlockTemplateUtils.php#L224

### Reproduction Steps

Use get_block_templates like this

```php
add_action( 'wp', function(){

	$header_template_parts = get_block_templates( array( 'area' => 'header' ), 'wp_template_part');
});
```

**Comment by sunyatasattva** [comment]
Hey @ohfuchs !

Thank you for your report! Would you mind adding some reproduction steps to the description of the issue so that people can immediately see what's going on?

Also, it seems a relatively straightforward issue, so if you feel comfortable contributing, we'd be really happy to accept contributions!

Let me know if I can help you in any way.

**Comment by ohfuchs** [comment]
Hey @sunyatasattva! 

I tried my hardest. Please let me know if I have done something wrong, this is my first PR.

I have added reproductions steps as you asked.
