### ISSUE TITLE
Cannot dequeue wc-blocks-checkout-style-css found in footer

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gutenberg-products-block#7349]
[Issue](https://github.com/Automattic/woocommerce-payments/issues/4861) created by @rlmajcom in the [WooCommerce Payments repository](https://github.com/Automattic/woocommerce-payments).

I moved the issue here, because it's related to the way WooCommerce Blocks enqueues scripts. WooCommerce Payments only registers the necessary scripts for the checkout block. 

---

### Describe the bug

I have the following WooCommerce Payments stylesheet being loaded in my tag and have not been able to find out how to remove it:

<link rel='stylesheet' id='wc-blocks-checkout-style-css'  href='https://www.example.com/wp-content/plugins/woocommerce-payments/dist/upe-blocks-checkout.css?ver=1.0' media='all' />
(I only use WooCommerce on certain pages so therefore do not need all of the files to be loaded on most pages)

I removed the stylesheet from loading in the header successfully within the wp_enqueue_scripts action hook using:

wp_dequeue_style('wc-blocks-checkout-style');

However, wc-blocks-checkout-style-css still loads in the footer ( /wp-content/plugins/woocommerce-payments/dist/upe-blocks-checkout.css )

### To Reproduce

Have WooCommerce Payments intstalled and View source code and/or Network tab in Chrome dev tools
/wp-content/plugins/woocommerce-payments/dist/upe-blocks-checkout.css will be loaded in the footer even though 
wc-blocks-checkout-style has been dequeued

### Actual behavior

upe-blocks-checkout.css gets loaded

### Expected behavior

I should be able to use 
wp_dequeue_style('wc-blocks-checkout-style-css'); or wc-blocks-checkout-style
within the within the wp_enqueue_scripts hook to prevent this stylesheet from being loaded

### Desktop (please complete the following information):

* OS: [e.g. iOS] Windows 10
* Browser [e.g. chrome, safari] chrome 
* Version [e.g. 22] latest

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by opr** [comment]
Hi @RadoslavGeorgiev thanks for taking the time to report this.

I investigated this today and I don't believe this is a WooCommerce Blocks issue. In https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-blocks-payment-method.php#L38-L69 it looks like you're calling `wp_enqueue_style` which will register the style to be output onto the page, however this method (`get_payment_method_script_handles`) is called several times, and probably should _not_ have side-effects, it is supposed to return the handles of _registered scripts_ 

If you want to enqueue a style specifically for use on the Cart/Checkout blocks, I would recommend using the [`IntegrationInterface`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/integration-interface.md#integrationinterface-methods) which would let you register the style and only enqueue it when rendering one of the Cart/Checkout blocks.

I'll move this back to WooCommerce Payments as I think the fix needs to be made there. Thanks!

Edit: turns out I cannot move the issue, so I'm going to re-open [the original issue](https://github.com/Automattic/woocommerce-payments/issues/4861) with a comment!
