### ISSUE TITLE
Is there a possibility to override the output of the blocks or use the default WooCommerce product template?

### ISSUE THREAD

**Issue by gdarko** [woocommerce/woocommerce-gutenberg-products-block#739]
I tried using the blocks and they seems to be working OK but there is one huge drawback.

Actually there is no chance to use them in production since they are inconsistent with the normal WooCommerce product template. The output is so much different. Is there no way to use the default woocommerce content-product template?

I found that there is filter called `woocommerce_blocks_product_grid_item_html` which is workaround for now but those blocks should use the default WooCommerce  content-product template.

**Comment by mikejolley** [comment]
`woocommerce_blocks_product_grid_item_html` is the correct hook to use. Going forward, most new blocks will have some kind of custom filter on their HTML for customisations. The main reason for this, and the reasons why they do not use the core WooCommerce templates, is that:

- Blocks need to work standalone (as a plugin) and work without relying on changes/styling/templates in core.
- Blocks need to be styled consistently between the editor and the frontend - using templates hinders this and conflicts arise due to theme styling.
- Core templates contain legacy code and are not always suitable for our needs.
- Core templates would require CSS style resets so we can re-style elements, or override styles in themes. For example, the product blocks use flexbox, whereas core templates use floats.

If you need to customise some output from blocks and a hook is not present, please log a feature request (or PR) and we'll look into this.

Thanks!

cc @Aljullu

**Comment by mikejolley** [comment]
I've consolodated all related issues to extending blocks into https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891 until a decision is made. Please see that issue and add feedback there if relevant. 

Thanks
