### ISSUE TITLE
Disable Checkout Route if Guest Checkout is disabled

### ISSUE THREAD

**Issue by artbotguy** [woocommerce/woocommerce-gutenberg-products-block#7409]
An attempt to change the permission_callback for a route (e.g. Checkout GET) was not successful. Overriding the regiser_rest_route() method with the override flag does not give the desired result - some properties for the third argument obtained from the Checkout object are not public.
Extending and redefining classes in order to extend the Checkout class is also not possible (that is, it is possible, but quite a lot of classes that use StoreApi will have to be rewritten) - without this, it is impossible to easily extend the RoutesController class - action in StoreApi:: init() uses an anonymous function callback that is passed directly.

In Woocommerce, I extended a couple of classes without any problems: with the remove_action('init', (\WooCommerce::instance(), 'load_rest_api')) function and then adding a new action with the extended Automattic\WooCommerce\RestApi\Server class, in which I overridden the method for controllers by adding new extended ones.

I did not have time to thoroughly study all the classes and the hierarchy, but I would like to be able to allow - in my case it is necessary that only registered users have the ability to make a /checkot request.
Thanks in advance!

**Comment by opr** [comment]
Hi there @ArtemAnonov, thank you for posting this issue. I can see the problem here is that you can't register a custom callback for the `permission_callback` part of a REST route in StoreApi.

I will ask the team about this and see if we can give any advice.

**Comment by ralucaStan** [comment]
Internal conversation p1666119776888919-slack-C8X6Q7XQU

**Comment by mikejolley** [comment]
Rather than focus on messing with permission callbacks and existing routes, we should probably instead focus on the problem trying to be solved. 

>  in my case it is necessary that only registered users have the ability to make a /checkout request.

So what we need to do here is:

1) Ensure that disabling guest checkout also disables the checkout endpoint (require an account to post)
2) Offer a hook to disable the checkout endpoint. Not required as it could cause serious breakage, but something to consider if point 1 is not enough.

@ralucaStan I'm moving this to the backlog.

**Comment by mikejolley** [comment]
I assigned this to myself to go over my initial assumption about removing endpoints and I wanted to address this again:

> Ensure that disabling guest checkout also disables the checkout endpoint (require an account to post)

This is not a feasible approach thinking more about the problem because in future cases we may want to allow registration via these endpoints (so that a guest customer can become registered in the process). Therefore I retract my earlier suggestion—we shouldn't disable the endpoint under these circumstances.

> Offer a hook to disable the checkout endpoint. Not required as it could cause serious breakage, but something to consider if point 1 is not enough.

I think we should go with this option; either a hook on the permission callback, or at Store API level. It would be a use-at-your-own-risk thing however, so we'll document inline.

**Comment by mikejolley** [comment]
It seems that there are concerns from the team that a permission callback could cause endpoints to become unexpectedly unavailable to extensions and blocks with no real way to detect the problem, causing more serious breakage. With that in mind, I've decided to close the PR with the permission callback.

https://github.com/woocommerce/woocommerce-blocks/pull/8948

There is an alternative solution for this use case however, and that would be to use one of the other actions fired during the checkout request e.g. `woocommerce_store_api_checkout_update_customer_from_request`

This hook fires during the request to the checkout endpoint and would be a suitable time to reject the request if the customer is not logged in. e.g. (untested)

```
add_action( 'woocommerce_store_api_checkout_update_customer_from_request', function( $customer ) {
  if ( ! $customer->get_id() ) {
    // Guest user
    throw new \Automattic\WooCommerce\StoreApi\Exceptions\RouteException( 'woocommerce_rest_checkout_require_account', 'You must be logged in to checkout', 400 );
  }
} );
```

So something along those lines would prevent checkout for users without an account. Adapt to the user case accordingly.
