### ISSUE TITLE
Update auto assignment workflow to use Fine-grained personal access tokens from the woocommercebot user

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#7473]
We need to update the auto assignment workflow used in WC Blocks repo to assign PRs to the rellevant teams to use Fine-grained personal access tokens from the woocommercebot user.

Additional info:
 
* Initial discussion: pdqwkG-r3-p2#comment-342
* Fine-grained personal access tokens documentation: https://github.com/settings/tokens?type=beta

**Comment by ralucaStan** [comment]
Internal discussion pdqwkG-r3-p2#comment-340

**Comment by alexflorisca** [comment]
I've looked into this and at the moment, we cannot add fine grained personal access tokens to any repositories that belong to the WooCommerce organisation on Github, because it's disabled at the organisational level. There is a discussion (  pdqwkG-r3-p2#comment-386) about whether we want to enable this or not, so waiting for a decision there before continuing with this ticket
