### ISSUE TITLE
Improve add to cart behaviour option selector for Mini Cart

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#7517]
The following selector is used to pick between two behaviour options for the mini cart when something is added to the cart:

<img width="379" alt="CleanShot 2022-10-27 at 14 57 48@2x" src="https://user-images.githubusercontent.com/1429108/198568511-19d2c4cd-feb9-46f2-ab28-381066bc35ce.png">

Given there are only two options, this would work better by using options. 

As far as design/component usage, consideration should be given to whether we use:

- `RadioControl` ([storybook](https://wordpress.github.io/gutenberg/?path=/story/components-radiocontrol--default))
- `ToggleControl` ([storybook](https://wordpress.github.io/gutenberg/?path=/story/components-togglecontrol--default)) - Assuming there will only ever be two options.
- `RadioGroup` ([storybook](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-radiogroup--default))
- `ToggleGroupControl` ([storybook](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-togglegroupcontrol--default)).

cc @vivialice - this will need your input before it's worked on.

**Comment by vivialice** [comment]
My preference is the toggle option. Specifically [this](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-togglegroupcontrol--default) one: 

<img width="275" alt="Screenshot 2022-10-31 at 12 51 51" src="https://user-images.githubusercontent.com/9888201/199012112-54463a5a-a0e3-41ab-8cb1-d4ebba660c66.png">

We might need to change it if we end up with more options, but it's nicer than the stacked radios.

**Comment by shaunandrews** [comment]
I see we've gone ahead and used a toggle for this control, but with the wording the label ends up wrapping:

<img width="265" alt="CleanShot 2023-04-03 at 17 38 22@2x" src="https://user-images.githubusercontent.com/191598/229633305-d7d87b20-b82d-4b24-a2e7-065c7db58a02.png">

Since this is a binary choice — it's either on or off — I imagine it would work better as a switch. Something like this:

<img width="604" alt="CleanShot 2023-04-03 at 17 40 41@2x" src="https://user-images.githubusercontent.com/191598/229633698-ded80ef8-3a68-45ef-9a7f-cfd668a3f19d.png">
