### ISSUE TITLE
Split frontend styles per each block and load them dynamically when required

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#752]
Now that the number of blocks is increasing, we want to build a single CSS file for each block instead of creating a big `style.css` file which includes styles of all blocks.

Once we build separate CSS files for each block, we want to load them dynamically, so we only load it when the block is rendered in the current page.

**Comment by mikejolley** [comment]
@Aljullu How much of a benefit do you see this being? Whilst the CSS files would be smaller, thats potentially more requests per page (if using multiple blocks). Since the CSS is already minified, I'm not sure how worth it this would be?

**Comment by Aljullu** [comment]
@mikejolley that's a good point. Actually I think this issue should actually be two:

* Loading styles dynamically only when a block requires them: I think we would like to implement this doesn't matter if we split the styles or not. A store having WooCommerce Blocks installed but not using any block, shouldn't have any frontend dependencies loaded at all.
* Splitting styles per block: that's how it's implemented in Jetpack and I think it makes sense if styles are heavy. Right now, the CSS file is only 25.99KB so I'm ok keeping it as it's right now, but maybe at some point in the future when the CSS file keeps growing, we might want to change this.

If that sounds good, I will update the issue title & description so it's only about loading styles dynamically.

**Comment by mikejolley** [comment]
@Aljullu So I've done some experiments here and here are my findings:

- WP doesn't predict what blocks will show and thus has to enqueue registered block styles in the `<head>` even if a block isn't used.
- The same scripts are used in the editor and on the frontend
-Splitting the CSS is easy enough, however, you need to manually enqueue each stylesheet; this is extra work, and despite doing this, due to the above points ^ loading is not conditional.
- Inline output is a viable alternative (read CSS via PHP and render inline as needed) however, this too has drawbacks:
  1.  PHP has the read the file so that's more overhead server side
  2. Inline CSS is harder to override and customise
  3. Rendering inline CSS is easy on the frontend, but we still have the problem of needing to get that CSS also in the editor which is a problem I wasn't able to solve.
- Outputting the scripts inline would be render blocking and is discouraged.

With all this in mind I'd recommend we abandon this idea and enqueue styles as WordPress expects; as part of `register_block_type`. This ensures styles work in the editor and on the frontend without manual intervention.

And given that, I'd also recommend we keep the styles in one shared CSS file. Since they are all going to be enqueued anyway it is more efficient to do it in one request than several.

**Comment by Aljullu** [comment]
Those are all valid points, I agree inline output might bring more issues than anything, and big stylesheets would increase page weight significantly while blocking render.

I checked how Jetpack deals with this. They seem to enqueue styles directly on block render:
https://github.com/Automattic/jetpack/blob/master/class.jetpack-gutenberg.php#L466
(it's called here: https://github.com/Automattic/jetpack/blob/master/extensions/blocks/slideshow/slideshow.php)

Then those scripts are rendered on the footer. In the beginning I thought that might not be a good idea but maybe it's worth trying it out? My main reason to pursue this is to avoid loading the stylesheets in pages that contain no blocks.

Regarding splitting or not splitting the stylesheets, it sounds good to me keeping all of them in one file. I agree with your point that making several small requests is worst than making a big one.

**Comment by mikejolley** [comment]
> Then those scripts are rendered on the footer. In the beginning I thought that might not be a good idea but maybe it's worth trying it out?

@Aljullu That wouldn't be render blocking (well, it could delay some scripts), but it would do what you said on Slack; there may be a brief period whilst blocks are not styled. I'm not sure what is best here or if there would be benefits, especially if we keep the one style file.

**Comment by mikejolley** [comment]
Any thoughts on this @nerrad @pmcpinto? I'm still in the abandon camp.

**Comment by nerrad** [comment]
This to me is the key observation here (and one I've made as well):

> WP doesn't predict what blocks will show and thus has to enqueue registered block styles in the <head> even if a block isn't used.

It looks like the jetpack reference Albert linked to is still enqueuing the style in the head, it's just the scripts being enqueued in the render callback.

I think the approach for css styles right now should be (in aligning with what Mike has suggested):

- keep all styles in one file for now.
- enqueue them as a part of register_block_type.

Should be noted that this _does_ mean that styles will be enqueued on every route in the frontend because there's no WP core mechanism yet for deriving what blocks are on a given route (especially in the case of archive loops).  So I do think we'll need to keep an eye on the stylesheet size and re-evaluate (having bundlesize will help us with that, we should set a target we're comfortable with and it can start warning when we hit it).

With that said, I vote abandon too.

**Comment by pmcpinto** [comment]
Based on the comments it seems that abandon it's the best option.

**Comment by mikejolley** [comment]
👍
