### ISSUE TITLE
Filter control blocks in the editor reload every time they are selected

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#7676]
## Describe the bug

Every time the merchant selects the _Filter by Price Controls_, _Filter by Attribute Controls_, _Filter by Stock Controls_ and _Filter by Rating Controls_ in the editor, it causes the block to go into a loading state (displaying the placeholders) unnecessarily.

## To reproduce

1. Add the Filter by Price block to a post or page.
2. Click on the Filter by Price Controls block.
4. Notice it shows the loading state for a few seconds.
5. Click on the Filter by Price title and back into the controls block. Notice every time you select the controls block, it shows the loading state.

## Expected behavior

From a user perspective, there is no need for the block to go into a loading state when selected.

## Screenshots

[Enregistrament de pantalla des de 14-11-22 13:32:44.webm](https://user-images.githubusercontent.com/3616980/201661118-2e91c6c6-9289-49f2-9727-be763ea8b590.webm)

**Comment by Aljullu** [comment]
I don't know whether it's the same issue or not, but this is affecting _Featured Product_ and _Featured Category_ as well.

**Comment by nefeline** [comment]
Sharing here a few of my findings/experiments while working on this issue today:

* The block-editor documentation [regarding performance](https://developer.wordpress.org/block-editor/explanations/architecture/performance/#key-performance-decisions-and-solutions) states that, by default, the editor canvas only renders the selected block in synchronous mode, with all the remaining blocks rendered asynchronously. This may explain why, even though all blocks are re-rendered when a single one is selected in the editor, the loading state is visible only on the ones we are clicking on.

* One avenue explored to solve this was to switch the data module component rerendering from Sync to Async mode by using the Context Provider Component [AsyncModeProvider](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#asyncmodeprovider) for the selected block, so it behaves as all others on click, but I'm not sure about unintended/unnexpected side-effects of having these components always running asynchronously.

* Considering that all components are inevitably re-rendered in the editor when at least one is selected, a possible workaround could be to temporarily store the relevant data for each one of the components in the local storage for caching. This way, whenever the component is selected (& syncronously re-rendered), the initial information served is from cache (the localStorage) and updated later in the process, eliminating the loading state in the editor altogether. I have a working solution following this approach but would like to hear other opinions on this first, in case there's an alternative path we can follow to solve this that I didn't explore here yet.

@dinhtungdu tagging you here since you are my onboarding buddy :) What do you think? Any ideas/suggestions?

**Comment by dinhtungdu** [comment]
@nefeline Excellent research! TIL about Async mode, thank you 🙇🏽 !

> switch the data module component rerendering from Sync to Async mode by using the Context Provider Component [AsyncModeProvider](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#asyncmodeprovider) for the selected block, so it behaves as all others on click

Can you explain this more? I'm not sure I fully get it. AFAIK, when the block is selected, the `isSelected` prop will be updated, which causes the block to rerender; with our current codebase, the `displayedOptions` will always be reset to `[]` and then set again, which causes the notice to display on selected. So I'm not sure how to make `it behaves as all others on click`. 

> , a possible workaround could be to temporarily store the relevant data for each one of the components in the local storage for caching.

I also think `localStorage` is a good solution to this problem.

**Comment by dinhtungdu** [comment]
We have a `usePrevious` hook (https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/hooks/use-previous.ts), I'm wondering if we can utilize that hook to solve this issue 🤔

**Comment by nefeline** [comment]
> We have a usePrevious hook (https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/hooks/use-previous.ts), I'm wondering if we can utilize that hook to solve this issue

Thanks for the suggestion! I gave it a try, sharing all the gory details bellow.

> Can you explain this more? I'm not sure I fully get it. AFAIK, when the block is selected, the isSelected prop will be updated, which causes the block to rerender; with our current codebase, the displayedOptions will always be reset to [] and then set again, which causes the notice to display on selected. So I'm not sure how to make it behaves as all others on click.

In this case, I was referring to making the selected component also load async, the same way all other components are reloaded in the editor whenever a selection occurs, although I'm not sure about the unintended consequences of following this route, so I parked the idea (for now) and started to explore a few different avenues. 

Here's a summary of the findings:

Using the `rating-filter` block [as an example](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/rating-filter/block.tsx#L92-L96): what is triggering the loading state in the editor is the `useCollectionData` hook.

Currently, we have a chain of React hooks here:

* `rating-filter/block.tsx` calls the `useCollectionData` hook.
* The `useCollectionData`  hook returns the results of another hook, `useCollection`
* The `useCollection`  hook results come from `useSelect` , from [WordPress data](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#useselect).

Based on your recommendation @dinhtungdu , I've explored using `usePrevious`. Still, the problem is, due to the re-run of the `useCollectionData` hook multiple times, at some point in execution, the previous value is undefined, so it is not possible to rely on that to ensure the loading state is not triggered:

(To generate the output on the screenshot, I've added the following to the `rating-filter/block.tsx` component):

```js
const previousFilteredCounts = usePrevious( filteredCounts );

console.log({previousFilteredCounts, filteredCounts});
```

<img width="800" alt="Screenshot 2022-12-14 at 11 24 51" src="https://user-images.githubusercontent.com/15730971/207571631-d342ca3d-1c4d-4e54-a3a6-49da69341e35.png">

Additionally, due to the [rules of hooks](https://reactjs.org/docs/hooks-rules.html), I'm not allowed to use conditionals to control the results, so this turned out to be a challenge. It is unclear why `previousFilteredCounts` is returning as undefined at this point.

Currently, I'm tracking down what dependencies are changing to trigger `useCollectionData` in the first place (if any), or if there's something in the body of the hook (outside of the `useEffects`) that might be triggering the re-runs. If we track down the root cause of the re-runs for this hook, we might solve the problem. I believe that, ideally, we should not be re-fetching filteredCounts just because the component was selected (and consequently re-rendered) in the editor, considering nothing has changed. 

The initial idea of using the `localStorage` might still be a valid one to give users the impression that no re-render is happening under the hood. Still, if we can do something to prevent the `useCollectionData` hook from re-running when not needed (if that's the case), perhaps we can have some extra wins in terms of performance as well.

Do you have any additional thoughts? If an alternative avenue can be explored, I'm open to any and all ideas!

I'm also increasing the estimate for this issue since this work is spamming through a few days of work already 👍 .

**Comment by dinhtungdu** [comment]
> we should not be re-fetching filteredCounts just because the component was selected (and consequently re-rendered) in the editor, considering nothing has changed.

We won't re-fetch the data in terms of creating new network requests, subsequence requests will use the data from cache. But I guess that it still takes time to retrieve the cache, and we set the initial display options to `[]`, which explains the notice flashing.

> The initial idea of using the localStorage might still be a valid one to give users the impression that no re-render is happening under the hood.

I agree. I think it's the way to go for this, at least for now. :)

**Comment by nefeline** [comment]
I've opened a PR that addresses the reload for all filter blocks affected that were listed here, including:

- Filter by Rating
- Filter by Price
- Filter by Attribute
- Filter by Stock

The fix for the featured product and category blocks is coming next, as part of a separate PR.

Thank you so much for your input here @dinhtungdu, I really appreciate it!

> We won't re-fetch the data in terms of creating new network requests, subsequence requests will use the data from cache. But I guess that it still takes time to retrieve the cache, and we set the initial display options to [], which explains the notice flashing.

I made some interesting findings in this area: added more details on #8002 . In the end, the usage of the localStorage wasn't required.
