### ISSUE TITLE
Updating checkstyle.xml break GitHub Actions

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#7689]
## Describe the bug

GH Actions workflows are broken across our PR after the commit that updates checkstyle.xml. 

![image](https://user-images.githubusercontent.com/5423135/202068155-969894ed-a469-492a-a739-f3ac84a850af.png)

**Comment by gigitux** [comment]
Thanks for opening the issue.

The issue is that GitHub doesn't trigger CI when the commit is done with [GITHUB_TOKEN secret](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) ([source](https://github.com/EndBug/add-and-commit#the-commit-from-the-action-is-not-triggering-ci)). To fix this issue, we should migrate to a PAT token. I'm checking it!

**Comment by gigitux** [comment]
This issue is not valid anymore thanks to this refactor https://github.com/woocommerce/woocommerce-blocks/pull/7717.
