### ISSUE TITLE
Add a cart update button

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#7691]
Hello !
Thanks a lot for your job !

## What do you think is missing from the Cart & Checkout blocks?
Maybe a cart update button would be great, or permit to refresh cart when there is an add by the cart cross-sells product. Currently, when somebody select a product to this area, the product is correctly added to the cart, but coupons about the cart aren't applied, because the cart is'nt reloaded.

**Comment by ralucaStan** [comment]
Hello @Cellophile thank you as well for your feedback.

I tried to replicate your issue, but for me, the coupon code was applied correctly. 
1. I added a coupon code with Fixed product discount
2. I added a cross-sell for a product
3. I added that product to the cart and went to the Cart block page
4. I then applied the coupon
5. I added the cross-sell suggestion as well
6. The coupon was applied correctly for the new product added 

Would you mind sharing some testing steps so that we make sure we are testing the same thing?

**Comment by ghost** [comment]
Hi @ralucaStan !
Yes sure, if you want, you can see it on that website : https://sandrarity.com.
If you add a face soap for example, and go in your cart, and add the two products suggested, normally, automaticaly you have a massage candle free. But if you just add them without refresh your page, candle doesn't appears. But if you refresh page, it appears fine. 

On this website, we use advanced coupon for wordpress plugin. Maybe that require a particular refresh ?
Thanks a lot for your attention !

**Comment by ralucaStan** [comment]
Hey @Cellophile,
yes, it looks like Advanced Coupon for WordPress does not react to the changes to the cart made from the Cart Block. 

The extension developers must ensure the extension is fully compatible with the block-based experience. 

Please get in touch with them and let them know that you would like to use the new, block-based checkout. To assist developers in this effort, we have published [documentation](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and [resources](https://href.li/?https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) on integrating existing plugins with the Cart/Checkout Blocks and Store API.

There isn't anything actionable on our side.

**Comment by ghost** [comment]
Ok ! Thanks for your time, I send it to plugin developpers.

Thanks !
