### ISSUE TITLE
Remove Hardcoded Notices: "There are no shipping options available. Please check your shipping address."

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#7730]
In the shipping control, the notice that reads:

> There are no shipping options available. Please check your shipping address.

Should be converted to text. 

> To make things less overwhelming this could easily be a simple text string informing the user, “Add a shipping address to view shipping options.” or something like that. I don’t think it needs to be an error at all.

**Comment by opr** [comment]
@mikejolley this error happens when the store doesn't ship to certain addresses (basically it shows when no shipping packages are found).

You mentioned changing the error to"Add a shipping address to view shipping options." or similar, but this may show even if they have entered one.

I think just removing the notice state is OK:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/5656702/211358059-c66f83f7-acf5-417a-9753-ab9cac267c97.png">

What do you think?

**Comment by mikejolley** [comment]
Yeah that would be better than an error, unless it would be better to have a non-error notice? We should make the description clearer with obvious steps to fix it. I wonder if we can determine why the address was invalid too and offer something more descriptive.

**Comment by tarunvijwani** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce-blocks/pull/8141
