### ISSUE TITLE
Product Query: Unify data structure for `tax_query` and `meta_query`

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#7745]
## Is your feature request related to a problem? Please describe.
In Product Query, we're using different data structures for partial `tax_query` and `meta_query` objects:

In `get_stock_status_query()` and `get_filter_by_price_query()`, the `meta_query` key holds an array containing query data (key, value, compare).
https://github.com/woocommerce/woocommerce-blocks/blob/9b79613f65f6138ccd6774df0b63b94980e05bbc/src/BlockTypes/ProductQuery.php#L258-L266

https://github.com/woocommerce/woocommerce-blocks/blob/9b79613f65f6138ccd6774df0b63b94980e05bbc/src/BlockTypes/ProductQuery.php#L401-L407

Same for tax_query in `get_filter_by_attributes_query()`:
https://github.com/woocommerce/woocommerce-blocks/blob/9b79613f65f6138ccd6774df0b63b94980e05bbc/src/BlockTypes/ProductQuery.php#L450-L455

---

But in `get_filter_by_stock_status_query()`, the `meta_query` key holds an array containing **a nested array** which contains query data:

https://github.com/woocommerce/woocommerce-blocks/blob/9b79613f65f6138ccd6774df0b63b94980e05bbc/src/BlockTypes/ProductQuery.php#L481-L492

## Describe the solution you'd like
We should unify the way we return `tax_query` and `meta_query` data. We could go either way but should use only one.

## Additional context
This will be solved by #7697. I raise this issue to explain the reason for returned data changes in #7697. cc @gigitux @sunyatasattva

**Comment by sunyatasattva** [comment]
Correct me if I'm wrong here, but I think the odd one out is `get_stock_status_query()`, right? Because `get_filter_by_price_query()` contains the `relationship` key at the top level, but then has nested arrays, as it should be. Or am I missing the point here? I think the wrong one is `get_filter_by_price_query()` (which, incidentally, I wrote 😬 ) and we should fix and change that. I agree that we should have a consistent shape.

**EDIT:** Ok I checked #7697 and I understand what you mean with `get_filter_by_price_query()`. I agree with the approach you took there. We should however think about a top-level `relationship` key at some point. But that's more a design discussion.

**Comment by dinhtungdu** [comment]
> We should however think about a top-level relationship key at some point. But that's more a design discussion.

I agree. For now, in https://github.com/woocommerce/woocommerce-blocks/pull/7697, we simply merge them, and each partial query (meta, date, tax) will be encapsulated inside an array.
