### ISSUE TITLE
Display Recently Viewed Products

### ISSUE THREAD

**Issue by spencerfinnell** [woocommerce/woocommerce-gutenberg-products-block#78]
Much like the Recently Viewed widget. Very useful on homepages for returning customers.

**Comment by jameskoster** [comment]
Thought about the design for this and I'm not sure we need anything new. 

Filtering by category, ordering and layout options can be replicated from our existing blocks.

The only potential _new_ setting I can think of is some kind of 'expiration' to give context to recency. For example; If you viewed a product 6 months ago should it really appear in a "Recently viewed products" block? But I think we could probably just change the block to be "Last viewed products" rather than "Recently viewed products" which would mean we don't need that setting. The block would simply always show the last X viewed products.

The only tricky thing is how to handle the preview in the editor if the author hasn't actually viewed any products before. I'll stew on that some more and come back with a solution.

As for the icon, let's use the [Material visibility icon](https://material.io/tools/icons/?icon=visibility&style=baseline).

**Comment by jameskoster** [comment]
Spoke about this with some other designers and we decided that we could move ahead using the Recent Comments block as inspiration.

When no products have been viewed, the placeholder text could read something like: 

> You haven't viewed any products. [Go shopping](#)

**Comment by spencerfinnell** [comment]
@jameskoster I assumed the logic for finding products would be based on https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-recently-viewed.php

It would be cool to use Block Styles to be able to toggle between a full grid layout (`content-product.php` and mini list (`content-widget-product.php`) which would lend itself nicely to Phase 2 of Gutenberg.

**Comment by jameskoster** [comment]
So, for the next phase of this project (after 2.0 and the core merge for WC 3.6), we intend to evaluate all of the WooCommerce core widgets and convert them in to block equivalents. Some may include enhancements like the one you mention (Block Styles). At the moment we aren't 100% clear on when that phase will be complete, though. 

My suggestion above would serve as an interim, baseline solution in case we wanted to include this block in version 2.0 of the WooCommerce blocks plugin and WooCommerce 3.6.

**Comment by ryelle** [comment]
This block will be created in the next batch of blocks, and a new issue will be opened with the design when it's ready.
