### ISSUE TITLE
Proceed to Paypal button on checkout page

### ISSUE THREAD

**Issue by hhhitzeman** [woocommerce/woocommerce-gutenberg-products-block#7860]
## What do you think is missing from the Cart & Checkout blocks?
The Proceed to Paypal button on checkout page has white text on black background, covered by a dark sliding shade, so text is not clearly visible until hover. Please allow color and onhover choices for the button.  thankyou

**Comment by mikejolley** [comment]
Hi @hhhitzeman 

Would you please let us know the theme you're testing with, and/or provide a screenshot? Buttons by default are white text on black so this may be a CSS conflict we need to work around.

![Screenshot 2022-12-13 at 14 14 54](https://user-images.githubusercontent.com/90977/207356774-67b132a1-1d67-4ab2-9bee-56a829f473c9.png)

Thanks

**Comment by hhhitzeman** [comment]
The theme is Hotel Xenia.

Thank you 😊

**Comment by mikejolley** [comment]
Since this is a paid theme, if you could provide a link to your site I can inspect the CSS directly. is that possible?

**Comment by hhhitzeman** [comment]
The website is https://saltcreekbutterflyfarm.com.

Thank you Mike.

**Comment by mikejolley** [comment]
I took a peek at the CSS on the page. This doesn't look like something we need to fix on our side due to the theme's CSS using `!important` for the button colour (this makes it tricky to resolve without also resorting to `!important`, which could cause conflicts with other buttons and themes).

To point you in the correct direction, there are two ways in which you can fix this.

1. Inform the theme author that the button styles (the `button:not([class*="btn-"])` rules) apply `!important` to the button text `color`, but not the button `background-color`. They may want to fix this on their side by using `!important` on the button background color too.

2. Add some custom CSS to your site. This varies between themes (some allow CSS customisations from the admin area) but you'd need to add a rule like this:

```
.wp-block-woocommerce-checkout-actions-block button {
    color: #fff !important;
}
```

This will force the button text white. 

Hope that helps. I'm marking this closed because we don't need to take any action in the codebase.

Thanks
