### ISSUE TITLE
Local Pickup: Align Cart packages to Checkout packages when local pickup is present

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#7897]
In Checkout, we tend to merge and sync up packages when we have multiple packages, we're not doing anything right now in Cart, which means a customer sees multiple packages with both pickup and regular shipping in it, resulting in mixed selection before said selection is aligned in Checkout.

We should either:
1. Merge all packages into a single package in Cart.
2. Leave packages but remove the local pickup options from them in Cart.
3. Do nothing, possibly allowing mixed selection in Cart, that will get overridden back in Checkout

**Comment by mikejolley** [comment]
To demonstrate the issue take this example where I have used an extension to split the cart contents into multiple packages. This shows the traditional shipping section in cart and checkout blocks:

| Cart      | Checkout |
| ----------- | ----------- |
| ![Screenshot 2022-12-09 at 12 58 54](https://user-images.githubusercontent.com/90977/206707890-084a929b-6f9d-4a82-ba4d-18b61c38320f.png) | ![Screenshot 2022-12-09 at 12 59 12](https://user-images.githubusercontent.com/90977/206707935-9d1b6cf3-4e8b-44c0-97ee-1018e16ba076.png)       |

Notice on the checkout we've already split out the local pickup methods, so they are not selectable there.

If you use the Local Pickup toggle, we see the pickup section as so:

![Screenshot 2022-12-09 at 13 00 05](https://user-images.githubusercontent.com/90977/206708057-e9bb6924-d548-4600-8a66-6a81dd443c64.png)

You can see we've combined both packages so we have:

1. A single UI to select a single location for all packages
2. Grouped costs

We don't want to show multiple packages here because:

1. We don't want to mix and match pickup with shipping
2. We don't want to allow the user to select multiple different pickup locations

[This prevents issues with taxes as documented here](https://woocheckout.wordpress.com/2022/10/20/local-pickup-tax-issue-with-multiple-packages).
 
So the issue here is that on the cart view you currently have the option to:

1. Mix and match pickup and shipping
2. Mix and match pickup locations

When you go through to checkout, these selections would be ignored in favour of the new UI.

—

As for the technical solutions @senadir listed, from low to high effort:

#### Do nothing, possibly allowing mixed selection in Cart, that will get overridden back in Checkout ❌

This option leaves it as is. Any selections in cart might not persist to the checkout. So more annoyance than anything.

#### Leave packages but remove the local pickup options from them in Cart. ❓

This would mitigate the issue because the customer would only see shipping options and would not be able to choose from pickup options.

The downside here is that it might not be obvious that local pickup is available. Maybe solved with a new element to show that its an option during checkout?

#### Merge all packages into a single package in Cart. ❌

Solves the multiple package part of the problem by only allowing 1 selection, but it would cause a mismatch between checkout and cart shipping option sections.

#### Show the toggle UI (like Checkout) ❓

I think this was the original plan but has been lost for some reason @senadir? If you show the toggle UI (shipping vs local pickup) the UIs should mostly be the same. But it's more confusing in the cart, and may conflict with the shipping calculator option if you need to input an address to see the available options.

#### Alternative?

A design solution to that problem would be to show some text indicating that local pickup would be available during checkout - and make it more obvious that other methods exist.

1. A message along the lines of "Shipping will be calculated during checkout" by default
2. A message along the lines of "or choose Local Pickup (from $xxx)"
3. Alongside that, if enabled, the option to calculate shipping by pressing a button. This shows the address form and displays rates once available.
4. If the shipping calculator is used, show shipping rates. Not local pickup rates.
5. Do not show the pickup location UI. Leave this for the checkout.

Quick mockup before calculation:
![Screenshot 2022-12-09 at 13 23 06](https://user-images.githubusercontent.com/90977/206712005-2e5a8c6e-d87a-43cf-b983-1e5dbdfe8ac7.png)

After calculation:
![Screenshot 2022-12-09 at 13 24 15](https://user-images.githubusercontent.com/90977/206712214-a802f4fc-f40d-4e44-b669-417059dfdd33.png)

The _after calculation view_ is pretty much what we have now.

**Comment by elizaan36** [comment]
hey @senadir @mikejolley Thanks for pointing me to this issue and for providing the context.

I'd like to suggest a 4th (5th?) alternative, which would maintain the existing UI with a slight change - let the user know that multiple packages must have the same shipping method, either in microcopy or by presenting a notice.

I'll share a sketch here for the order summary section on the Cart block (with a new design for the notice, TBD based on another stream of work).
![Uploading Screen Shot 2022-12-12 at 12.16.00 PM.png…]()

To encourage the user to proceed with the order, this direction reduces confusion/the number of questions they may have. 
- All available shipping methods are shown
- Shipments are clearly split into two as per user expectations
- A notice is shown above the shipments indicating that multiple packages must use the same shipping method

When user tries to change the shipping method, it would change on both shipments. Let me know what you think of this alternative.

**Comment by ralucaStan** [comment]
Looks like this has been closed in https://github.com/woocommerce/woocommerce-blocks/pull/7958. Please reopen if not the case.
