### ISSUE TITLE
Flow: Inline editing

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#80]
After products have been selected and while in preview mode it should be possible to edit data like product prices and have those update store-wide on save.

**Comment by spencerfinnell** [comment]
@jameskoster Personally I think this seems outside of the scope of this block. It would be like if you could edit the post titles in the "Recent Posts" block. 

There is already an inherit disconnect between this block and the frontend output because the grid is defined by the block, not the theme (hopefully this can be changed with https://github.com/WordPress/gutenberg/pull/5602). Allowing the editing of these predefined items might cause further confusion if the theme doesn't output one of the elements that was changed. 

There is also the never ending rabbit hole this will open up: "If I can edit the price why can't I edit X?"

Beyond that the UI for doing the editing seems like it would be extremely complex. Are there any mockups of what this might look like?

**Comment by jameskoster** [comment]
> Personally I think this seems outside of the scope of this block

I'm curious to hear your reasoning for that opinion? Given the infancy of Gutenberg I'm not sure we're in a position to definitively make this judgement just yet.

> Are there any mockups of what this might look like?

Absolutely nothing yet, this isn't really on our radar right now, just something we've observed in our tests. 

I totally agree this is a difficult concept to design, particularly for products compared to something like posts / forms / whatever. But right now it looks to be a feature that folks will expect / appreciate, so we need to keep it in mind.

**Comment by spencerfinnell** [comment]
> Given the infancy of Gutenberg I'm not sure we're in a position to definitively make this judgement (either way) just yet.

You're right; things are still changing a lot. I am just going off the functionality provided by the current generation of core blocks.

Another thing to think about: After watching the confusion with Reusable Blocks it seems like this may introduce another level of "what is this actually changing?"

But like you said it's something that will likely be asked about so no reason not to start thinking about it -- in whatever form it ends up taking.
