### ISSUE TITLE
Add product ID into the rendered HTML of each product

### ISSUE THREAD

**Issue by alewolf** [woocommerce/woocommerce-gutenberg-products-block#8008]
## Is your feature request related to a problem? Please describe.

I am the developer of the [Pixel Manager for WooCommerce](https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/) (available [here](https://woocommerce.com/products/pixel-manager-pro-for-woocommerce/) and [here](https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/)). The Pixel Manager sends certain tracking events only when a product becomes visible in the viewport. For that, the Pixel Manager uses an intersection observer that extracts the product ID for each visible product. With the current templating engine, that is usually possible because either the product ID is already in there in the product `div`, or the Pixel Manager adds additional HTML output for each rendered product that contains the product ID (using a  hook). 

However, with the Gutenberg blocks, that's not possible. 

A) The Gutenberg blocks (e.g., all-products block) don't output the product ID anywhere in the rendered HTML.
B) The product ID is set on the react DOM for each rendered product as a key. However, that key is not publicly accessible. Maybe with some hack, but that would likely not be future-proof. 
C) There is no way to add some output, script, HTML element, or HTML data attribute containing the product ID (to each rendered product), which could be extracted with JavaScript. 

## Describe the solution you'd like

There are several ways how that could be approached. This is by no means a complete list. It's just what I could come up with. 

**Adding HTML elements to each rendered product**
With the current templating engine, we can add any type of HTML to the product templates using action hooks. The Pixel Manager for instance, uses the `woocommerce_after_shop_loop_item` hook and a few others to achieve that.

**Adding data-attributes to each rendered product**
I found that data-attributes are already part of Gutenberg blocks. Still, there is no standardized way to add **custom** data-attributes to any rendered product using a filter or a hook (or at least I was unable to figure that out).

 **Add the product ID as a default data-attribute to all rendered products**
Make the product ID a mandatory data-attribute that has to be added to all product block templates, ready for consumption by third-party tools. 

**Implement a native intersection observer and emit an event for each product that becomes visible**
Maybe a Gutenberg block native intersection observer could be implemented that emits an event for each product that becomes visible in the viewport. This might work globally, also with third-party blocks. However, we would lose configuration flexibility. Users of the Pixel Manager can adjust the minimum time how long a product needs to be visible and how much of a product needs to be visible before an event is emitted ([using the view_item_list trigger filter](https://sweetcode.com/docs/wpm/developers/filters#view-item-list-trigger-filter)). By default, no visibility event is emitted if a visitor scrolls quickly through the products or if a product is only partially visible. But if the product is entirely visible for more than a second, product visibility events are emitted. 

One problem that remains is standardization for WooCoommerce and/or third-party developers. Ideally, the solution should work with any WooCommerce product blocks developed by third-party developers. I have no clue how that could be enforced.

**Comment by masteradhoc** [comment]
+1 👍🏻

**Comment by opr** [comment]
Thanks for bringing this up, you've made some really interesting suggestions. My preference would probably be to add the ID as a data attribute to the product's top-level container.

I will leave this discussion open for now to allow other members of the community and our team to give their opinions, then we can decide on some actions to take!

**Comment by kmanijak** [comment]
Thanks for raising this issue, it's an interesting use case!

We're currently working on a _Products_ block that's available in a beta version since WooCommerce Blocks 9.1.0. The progress around that block can be tracked through this issue: https://github.com/woocommerce/woocommerce/issues/42616. The plan is to migrate the existing product grid blocks (including _All Products_) to the new _Products_ block.

One of our focus points on improving _Products_ block is to investigate how to support several existing PHP filters and actions, including `woocommerce_after_shop_loop_item`. Your use case is a good addition to that investigation (cc: @dinhtungdu for awareness).

Given the direction towards the _Products_ block, your suggestions don't fit with our current priorities/strategy for the project. This doesn’t mean what you are suggesting isn’t a good idea or doesn’t make sense – it’s just that we have limited time to work on various projects and bringing _Products_ block to its full capacity is a top priority.

The progress on _Products_ block can be followed through the Store Editing Snaps series that we publish every other week. Here's a [link to the latest edition](https://developer.woocommerce.com/2023/01/05/store-editing-snaps-december-19-30/).

I'll go ahead and close this issue for now, but it does not mean that we didn't note the suggestions from this issue. Also, please be aware that closed issues can also still be commented on.
