### ISSUE TITLE
cart/checkout blocks feedback

### ISSUE THREAD

**Issue by jjbbrr** [woocommerce/woocommerce-gutenberg-products-block#8057]
## What do you like about the Cart & Checkout blocks?
Ease of configurability without having to go to functions.php
Ability to edit headings etc so we can make it our own

## What do you think is missing from the Cart & Checkout blocks?
ability to really reduce it down to super-minimalist i.e. name, email, credit card. forcing us to collect address is unnecessary these days.
ability to edit the number of each item in the cart - this would mean it's just a one-page cart/checkout which would be ideal.

**Comment by tarhi-saad** [comment]
Hello, @jjbbrr! 👋 Thank you for taking the time to help us make the Cart & Checkout Blocks a better experience! 🙌 

> ability to really reduce it down to super-minimalist i.e. name, email, credit card. forcing us to collect address is unnecessary these days.

Thanks for suggesting this enhancement. I see that this enhancement had been requested before in https://github.com/woocommerce/woocommerce-blocks/discussions/5483. Currently, it's indeed not possible to add/remove fields to/from the cart and checkout block. However, is on our internal list of desired enhancements.

> ability to edit the number of each item in the cart - this would mean it's just a one-page cart/checkout which would be ideal.

It's not possible to change quantities on the Checkout Block, but it should be working on the Cart Block. We understand the value of a one-page checkout experience, which is why we're thinking about making our [WooCommerce One Page Checkout](https://github.com/woocommerce/woocommerce-one-page-checkout) plugin compatible with the Blocks. This is something to anticipate in the future!
