### ISSUE TITLE
Individual product scope: search results occasionally bug out

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#81]
This doesn't seem to happen locally but it did happen quite frequently during our user tests. Wondering if it's a network issue. Ping me on Slack for log in details to our demo store if required.

**Comment by jameskoster** [comment]
A little more info on this; it only seems to happen the first time you perform a search. All subsequent searches return the expected results.

It's weird cause the correct results seem to flash up initially then just seem to be replaced by an random set of products.

![gif](https://cldup.com/jwI253eCJX.gif)

**Comment by claudiulodro** [comment]
This seems to be something with the core Gutenberg `withAPIData` class.

You can see when the API request for a search `'cat'` goes out no products are found:
<img width="647" alt="screen shot 2018-06-04 at 11 03 16 am" src="https://user-images.githubusercontent.com/7317227/40933763-56dc46fc-67e7-11e8-9768-c7bf3632cd15.png">

However the Gutenberg response for this API (using `withAPIData`) returns a full slate of products:
<img width="843" alt="screen shot 2018-06-04 at 11 02 50 am" src="https://user-images.githubusercontent.com/7317227/40934006-35879c6c-67e8-11e8-9c01-6f25b0e8e1e1.png">

The issue seems to be something from within `withAPIData`, possibly related to doing a bunch of API requests in quick succession. I'll leave this open so I can remember to investigate it on gberg's side if I get a chance.

**Comment by claudiulodro** [comment]
Fixed in #107
