### ISSUE TITLE
Not Working - Allow shoppers to sign up for a user account during checkout

### ISSUE THREAD

**Issue by ignusvermaak** [woocommerce/woocommerce-gutenberg-products-block#8142]
Hello

Enabled. "Allow customers to log into an existing account during checkout" 
Disabled. "Allow customers to place orders without an account"

Using the Checkout block, in "Contact Information", I have enabled, "
Allow shoppers to sign up for a user account during checkout"

However users are not given the chance to create an account.

We are using the Sensei Course theme, but we also tested the Storefront theme and it doesn't work for either.

**Comment by senadir** [comment]
Hey! Because you have `Allow customers to place orders without an account` as disabled, customers are forced to either login or create an account, in this case, there's no choice to be had, so the checkbox is implicitly checked and hidden, an account will be created and the user will receive an email to set his password.

I hope this helps.

In the latest verion, the checkout block setting is removed and all settings are centralized in the admin setting page.
