### ISSUE TITLE
Product Type templates for Single Product views

### ISSUE THREAD

**Issue by gigitux** [woocommerce/woocommerce-gutenberg-products-block#8146]
The outcome of this issue is to have a specific template depending on the type of the product (not its category or tag). Ie, having a different template for Single products, Variable products, Grouped products, Subscriptions, etc.

**Comment by nefeline** [comment]
@gigitux , @kmanijak , @albarin, and I collaborated on this issue, and the outcomes are as follows:

- Investigation about Product Type Templates for single product views: per0F9-ci-p2
- Discussion ref. https://github.com/woocommerce/woocommerce-blocks/discussions/8475

**Comment by nefeline** [comment]
Update following up on the [discussion](https://github.com/woocommerce/woocommerce-blocks/discussions/8475) opened yesterday:

Based on Darren's comment on https://github.com/woocommerce/woocommerce-blocks/discussions/8475#discussioncomment-5063048 , sounds like this issue is complete as the primary outcome of this cycle was to get a better understanding of what would take to implement product type specific templates and if there are any technical hurdles requiring work upstream. As documented in the discussion, these are the long-term solutions proposed:

https://github.com/WordPress/gutenberg/issues/48264

https://github.com/WordPress/gutenberg/pull/46362

I'm marking this issue as complete, but if you think there's anything else pending, please let us know @nerrad!
