### ISSUE TITLE
Automate the update of since TBD tags

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#8150]
With #8031 the usage of `@since` tags is now part of our validation. When introducing new hooks in the codebase it is a common practice to add a `@since TBD` to the docblock which is then searched and replaced later on with the correct version number when it is time to release. 

Per @Aljullu 's recommendation, opening this issue so we can investigate a good way to automate this search-replace on every release.

**Comment by mikejolley** [comment]
I believe this can be closed due to pca54o-6Dz-p2 

Post-merge, every PR will need to be feature complete and will target a specific version of WooCommerce. Therefore the TBD would need to be replaced before the PR is merged, and the version would be known at that point. This does not require automation now.
