### ISSUE TITLE
Style Book: Mini Cart Contents block displays a white box without content

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8177]
## To reproduce

0. With WordPress 6.2 (or a previous version with GB installed) and a block theme like [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) enabled.
1. Go to Appearance > Editor and edit a template.
2. In the toolbar, select Styles (black and white circle) and then, Open Style Book (eye icon).
3. Go to the WooCommerce tab.
4. Notice the Mini Cart Contents block displays a white box without content.

![Mini Cart Contents block in Style Book](https://user-images.githubusercontent.com/3616980/212303698-dd79721a-6b33-4255-9a0c-f9a932afec0e.png)

## Expected behavior

The block should display placeholder data so it can be previewed.

**Comment by nefeline** [comment]
This block is failing to load on Style Books as a consequence of an `“Uncaught RangeError: Maximum call stack size exceeded”` error caused by the `useForcedLayout` hook: more specifically, [`replaceInnerBlocks`](https://github.com/woocommerce/woocommerce-blocks/blob/6f637dbbd9a00c2c911c73d6298d232fe7115f23/assets/js/blocks/cart-checkout-shared/use-forced-layout.ts#L134).

<img width="1995" alt="Screenshot 2023-01-23 at 01 59 26" src="https://user-images.githubusercontent.com/15730971/213953568-33a96dca-11a3-4ac2-b762-cf14857bbc6f.png">

As a quick test [`replaceInnerBlocks`](https://github.com/woocommerce/woocommerce-blocks/blob/6f637dbbd9a00c2c911c73d6298d232fe7115f23/assets/js/blocks/cart-checkout-shared/use-forced-layout.ts#L134) was commented out, confirming the error is gone and the contents properly displayed:

<img width="1216" alt="Screenshot 2023-01-23 at 02 53 15" src="https://user-images.githubusercontent.com/15730971/213953854-1dbd6cb2-68f0-4311-bbaa-85978117ad04.png">

We will continue to work on this within the next few days and share the solution as soon as it is ready.

**Comment by Aljullu** [comment]
Thanks for your research, @nefeline! It looks like this one will be fixed with #8243. :slightly_smiling_face:
