### ISSUE TITLE
Store API still return item URL even if catalog visibility is hidden

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#8192]
Currently, in classic cart/checkout, if a product has its catalog visibility as hidden, its link is not visible and you can't click it, this is done via the checkout `$product->is_visible()`, Store API seems to ignore that and return the link regardless.

### Reproduce steps
1. Add item to cart.
2. Change its catalog visibility to "hidden"
3. Visit Cart block, the item link is still clickable, it's not clickable on Cart shortcode.

**Comment by mikejolley** [comment]
I'm going to suggest we leave this link intact for the following reasons:

1. Catalog visibility does not prevent items being purchased
2. Presumably the customer already accessed the product page in order to add the product to the cart in the first place
3. Preventing a link back would prevent the customer checking product details
4. Setting wording (below)

> This setting determines which shop pages products will be listed on.

This is how it is worded. The options are to hide products from archives and search results. The cart is neither.

Suggest we leave current behaviour as-is.

**Comment by senadir** [comment]
This behavior is however inconsistent with core, which is fine.

Another use case for hidden products are products that are added programmatically or by access certain links.
