### ISSUE TITLE
Product Elements: Add to Cart button doesn't work when AJAX is disabled

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#8213]
## Describe the bug

When the user disables the setting from “Products > Enable AJAX add to cart buttons on archives”, the add to cart button doesn't do anything.

## To reproduce

1. Go to Settings > Products > Enable AJAX add to cart buttons on archives and disable this checkbox.
2. Add a “Products (Beta)” block.
3. Notice that on the front-end, “Add to cart” doesn't do anything.

## Expected behavior

Add to cart should work with or without AJAX enabled.

## Screenshots

<img width="864" alt="212226409-6d0b95d1-67f5-4f73-a2e0-6e3d61fdd334" src="https://user-images.githubusercontent.com/1847066/212741082-a700b4c8-0481-4400-82d9-76e7b795d011.png">

**Comment by danieldudzic** [comment]
@sunyatasattva With AJAX disabled on archives, should the **Products**' Add to Cart button behave as currently the **All Products** block does (regular AJAX behavior) or the same as classic WooCommerce archives (page reload)?

**Comment by sunyatasattva** [comment]
I would say it doesn't make much sense to have a page reload in this day and age. I am not sure we should respect this setting. What we should do, is make sure we degrade gracefully to a normal non-AJAX request in case someone has JS disabled, I think.

@nerrad, @Aljullu, @danielwrobert, what are your opinions here?

**Comment by Aljullu** [comment]
I don't have a strong opinion, but I lean towards respecting that setting.

I agree that nowadays this setting might feel a bit outdated in some cases, but at the same time, I guess there are some use cases for disabling AJAX add to cart. Ie, a store with only one product which has a redirect to the Checkout page after the product is added to the cart.

In any case, IMO this should be discussed at the WC core level.

**Comment by nerrad** [comment]
I think it's kind of a given for commerce in the modern world to have JS enabled. I suspect this setting has been around for a long time and has never been examined how relevant it is to still have it. With that said, Amazon does seem to support having JS turned off completely (and it actually is a pretty nice experience imo). So I agree, we should probably degrade gracefully.

Before dedicating time to addressing this (at the core level or otherwise), I'd like to get a sense of how much of an issue this is at the moment. Lucio, is this something you just discovered due to reviewing various things in WooCommerce or did this get reported by a user somewhere?

**Comment by sunyatasattva** [comment]
> Lucio, is this something you just discovered due to reviewing various things in WooCommerce or did this get reported by a user somewhere?

Discovered while fixing [this bug](https://github.com/woocommerce/woocommerce-blocks/issues/8147). No user has complained about this yet. Do WooCommerce snapshots in Looker contain information about this setting, to get an idea on who uses that?

**Comment by nerrad** [comment]
I don't think so. Given this has been present for a while (I'm assuming "All Products" implementation hid the bug because it completely ignores it) and we don't have any indications this is a _severe_ issue for stores at the moment, I don't think it's high priority. We can add it to the backlog for now.

**Comment by sunyatasattva** [comment]
Gotcha!

**Comment by danielwrobert** [comment]
Chiming in a little late here but I'm also in favor of degrading gracefully. While it maybe more rare for folks to have JS disabled nowadays, if the setting is already in place and isn't causing any serious issues, it seems better to respect it. That offers a better experience for the folks who, for whatever reason, may have JS turned off.
