### ISSUE TITLE
Products Block: Filtering by Category or Tag doesn't Work

### ISSUE THREAD

**Issue by druesome** [woocommerce/woocommerce-gutenberg-products-block#8249]
## Describe the bug

Filtering products by category or tag in the Products block doesn't work.

## To reproduce

1. Insert the Products (Beta) block in a post or page
2. In the block settings, enter a product category or tag under Filters
3. Update the post or page

## Expected behavior

For the post or page to display products belonging to the specified category or tag

## What happened

The block does not respect the filter and displays all products on the live post or page.

## Ticket

5877934-zd

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   WooCommerce version: 7.3.0

**Comment by imanish003** [comment]
There is [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/7867), according to which Filtering by Category or Tag works on frontend but not in Editor. That issue is there in `Query Loop` itself. For more info: https://github.com/WordPress/gutenberg/issues/29438#issuecomment-1413572661

But it looks like there is a regression because of which now filters don't work on front-end either. I will look into it.
