### ISSUE TITLE
You cant remove payment method using filter woocommerce_available_payment_gateways

### ISSUE THREAD

**Issue by rajeshsingh520** [woocommerce/woocommerce-gutenberg-products-block#8322]
## Describe the bug

woocommerce_available_payment_gateways filter do not remove the available payment gateway on the checkout page when you use woocommerce checkout block

## To reproduce
Enable Cod backment option in woocommerce 

after that add this code in your theme functions.php file this will remove the cod payment option
for normal checkout page
`
add_filter('woocommerce_available_payment_gateways', function( $payments){ 
unset($payments['cod']);
return $payments;
});
`

but when you make the checkout page using Block the payment option is shown on the checkout page 

## Expected behavior

Payment option should get removed with this filter

**Comment by mikejolley** [comment]
Looked into this and there is a function in woo core that runs the `woocommerce_available_payment_gateways` hook called `get_available_payment_gateways`:

https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/class-wc-payment-gateways.php#L163

This is however not suitable for API usage because it runs various checks also that require a cart and other session based data. In the API we use `WC()->payment_gateways->payment_gateways()` which returns active payment methods. [They are however blocked when used because of this line.](https://github.com/woocommerce/woocommerce-blocks/blob/3c9f4a9697e1bce50b5373f40e38abd70f75477b/src/StoreApi/Routes/V1/Checkout.php#L545)

I'd suggest keeping our current code in place and just wrapping calls to `WC()->payment_gateways->payment_gateways()` with the filter. That should be the path of least resistance. If it causes issue or conflicts, we can introduce a new filter with a store_api prefix instead.

**Comment by ralucaStan** [comment]
I'm closing this issue as there was no answer for 2 weeks. @rajeshsingh520 feel free to comment on this ticket if you need to add extra details

**Comment by mikejolley** [comment]
@ralucaStan we should implement the `woocommerce_available_payment_gateways` filter hook in the store api. That was a suggestion for us, not the OP.

**Comment by PanosSynetos** [comment]
I'm also facing a similar issue when using the `woocommerce_available_payment_gateways` filter.

@rajeshsingh520 I managed to disable COD using the following snippet, in case it helps

```php
		add_filter( 'option_woocommerce_cod_settings', function ( $value ) {

			$value['enabled'] = 'no';

			return $value;
		}, PHP_INT_MAX );
```

**Comment by rajeshsingh520** [comment]
Hi, at present you cannot disable payment option conditionally in the checkout Block 

For example in normal checkout page we can disable payment options based on the selected shipping zone or country using custom code (we have a plugin using that we can disable them based on multiple such conditions)

but we cant do the same with Checkout block as

**Comment by mikejolley** [comment]
This could use testing/feedback: https://github.com/woocommerce/woocommerce-blocks/pull/8441 It's a potential solution.
