### ISSUE TITLE
Featured Product/Category: clicking outside the block when modifying the image gets out of the editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8327]
When editing the images of the Featured Product or Featured Category blocks, clicking outside or the block causes it to lose focus and the image editor is closed. That's specially problematic if you try to scroll with the scrollbar and you lose any changes you made.

## To reproduce

1. Add the Featured Product or Featured Category to a post or page.
2. Click on the button to edit the image (the one before _Replace..._).
3. Change something of the image (ie, orientation).
4. Click outside the block and notice changes are not persisted.

## Expected behavior

The image editor should not close when clicking outside the image, so changes are not lost.

## Screenshots

[Enregistrament de pantalla des de 2023-01-30 15-38-53.webm](https://user-images.githubusercontent.com/3616980/215507402-14f147e8-2815-4be5-94f3-2e89d27f28e6.webm)

**Comment by roykho** [comment]
I've looked into this and to me it seems like the expected behavior? Because when you go and edit the image, a `apply` button shows up. Only if you click on this button is when it will save the image changes. So if I click away, I am expecting it to not save the changes.

If you try adding the Gutenberg core `image` block, it behaves the same way.

**Comment by Aljullu** [comment]
You are right, @roykho, the Image block works the same. I have to say it's a bit confusing to me, but yeah, let's be consistent with GB. Thanks for investigating it!
