### ISSUE TITLE
Using standard product loop

### ISSUE THREAD

**Issue by EddyFK** [woocommerce/woocommerce-gutenberg-products-block#833]
Right now the html output of the product lists has a custom markup. Would it be possible to reflect whats in woocommerce/content-product.php ? I would suggest to stick to one markup rather creating new ones, as in a normal situation the styling etc has already been done globally, so why invent a new one, right?

**Comment by mikejolley** [comment]
Hi @EddyFK 

We're using custom markup to avoid inheriting styles which can break layouts. Blocks for example uses more modern CSS for product grids, whereas the old markup/styles uses floats. 

Additionally, styles added on the frontend should also be added to the editor. Not all themes currently handle this. By adding dedicated block styles, the editor and frontend are more closely matched.

This was changed in 2.2 and won't be reverted (which would also break things for everyone who has styled the new blocks markup since it's introduction).

> so why invent a new one

It's also possible as designs are updated, new markup is required anyway.

Eventually, markup rendered by blocks will be filterable in a similar fashion to Woo core (see https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/766) - when this is implemented, if you did want to change markup to match other places you could do so. In the meantime, extra styles need adding if you don't like the defaults.

Hope this makes sense.

Thanks

cc @Aljullu

**Comment by EddyFK** [comment]
I understand the problems described above but i think semantically it's wrong. Eg i have a theme that has a really specialised styling, hover effects on product lists, additional wrappers inside the list item etc. The current block markup won't reflect anything of that, which doesn't make sense in 99% of all cases. Why would i create multiple product list styles? Maybe we add a toggle that makes it possible to use the default markup? Would it be possible to combine the php templates with blocks?

**Comment by mikejolley** [comment]
@EddyFK I think the plan should be to modernise the templates used in blocks and eventually (long term) replace what is in core, not keep the old style markup around forever. Blocks is a chance to start anew without breaking compatibility of existing templates.

**Comment by EddyFK** [comment]
I honestly disagree, i think these markups should be defined by the mother, not the kiddo :) I also don't see how the website should break by this. The output is a simple products list used everywhere in WC. So compatibility is given, or? As i said i would aim for an option to use basic markup. The user can than check if there are any problems with the theme. I agree that we should push for new things but i think also we should 100% support what's given and make anything else optional. I see the WC Blocks in that case not as a new thing, but rather an extension of what's already there. Does that make sense?

**Comment by mikejolley** [comment]
>  i think these markups should be defined by the mother, not the kiddo

Core cannot change markup without breaking backwards compatibility. Blocks can. Blocks is also part of core, it's just developed here first.

> The output is a simple products list used everywhere in WC. So compatibility is given, or?

Not given; styling can be missing in the editor, conflicting float styles impacting css grid styles. Before 2.2, the editor did not match the frontend at all.

> I see the WC Blocks in that case not as a new thing, but rather an extension of what's already there.

I see blocks as the evolution, not an extension. More things will be converted over time to blocks, and as that happens, markup will be modernised and changed.

**Comment by mikejolley** [comment]
I've consolodated all related issues to extending blocks into https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/891 until a decision is made. Please see that issue and add feedback there if relevant. 

Thanks
