### ISSUE TITLE
Unable to checkout with AutomateWoo and Mailpoet marketing block

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gutenberg-products-block#8333]
## Describe the bug

Both AutomateWoo and Mailpoet contain a marketing block which asks whether a user wants to signup to updates during checkout:

![image](https://user-images.githubusercontent.com/11388669/215516679-6f872a52-d4b7-49a3-a661-4cbbd6bd9b5d.png)

If we interact at least once with the AutomateWoo checkbox "I want to receive updates about products and promotions" then we can proceed without errors. However if we do not interact with these checkboxes the initial state updates don't seem to go through correctly (if we active each extension separately then it does work).

The same problem is also reproducible if a user already opted in to AutomateWoo. In that case the checkbox from AutomateWoo shouldn't be shown, but it should still send the value in extensions since they are required properties being added here: https://github.com/woocommerce/automatewoo/blob/5.6.5/includes/WooCommerce_Blocks_Integration.php#L71

From my testing it seems there is some kind of race condition, or each extension is getting an older version of the state when they call setExtensionData. I tracked it in a debugger and setExtensionData is called first by AutomateWoo where the initial state data is still `extensions: {}`, which is expected. However when setExtensionData is called the second time round by MailPoet it doesn't get the updated state and the data for extensions is still `extensions: {}`.

I tested by delaying the call in [AutomateWoo to setExtensionData](https://github.com/woocommerce/automatewoo/blob/5.6.5/assets/js/marketing-optin-block/block.js#L22) by 3 seconds, doing so allows it to work without issues. Is there a better way to ensure that both extensions can set the initial value without conflicts, it seems [this is the relevant code that's being called by both extensions](https://github.com/woocommerce/woocommerce-blocks/blob/v9.4.1/assets/js/base/context/hooks/use-checkout-extension-data.ts) in the same way.

## To reproduce

1. Activate both AutomateWoo and Mailpoet
2. Go through a checkout flow with blocks
3. Confirm that both checkboxes are present
4. Do not interact with the checkboxes but fill out all other form fields to complete checkout
5. Click the checkout button
6. Confirm that the request to the store endpoint `wc/store/v1/checkout` fails:
```json
{
    "code":"rest_invalid_param",
    "message":"Invalid parameter(s): extensions",
    "data":{
        "status":400,
        "params":{
            "extensions":"extensions > automatewoo is not of type object."
        },
        "details":{
            "extensions":{
                "code":"rest_invalid_type",
                "message":"extensions > automatewoo is not of type object.",
                "data":{
                    "param":"extensions > automatewoo"
                }
            }
        }
    }
```
The payload should contain only the extension data for mailpoet:
```json
{
    "shipping_address":{"....."},
    "billing_address":{"....."},
    "customer_note":"",
    "create_account":false,
    "payment_method":"cod",
    "payment_data":[
        {
            "key":"wc-cod-new-payment-method",
            "value":false
        }
    ],
    "extensions":{
        "mailpoet":{
            "optin":false
        }
    }
}
```

## Expected behaviour

For both extensions to be included in the list of extensions, when the form is initially loaded.

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): version included with WP 6.1.1
-   WooCommerce version: 7.4
-   WooCommerce Blocks version: Version included with WC 7.4
-   Site language: Default US english
-   Any other plugins installed: AutomateWoo and Mailpoet

**Comment by eason9487** [comment]
Hi, I'd like to add some findings.

This issue is probably caused by the processing of merging the `extensionData` state of the **wp-data** store (`@wordpress/data`).

After the checkboxes of AutomateWoo and Mailpoet are mounted, they both immediately call to `setExtensionData` to initial their opt-in state. The [synchronization of `extensionData` in the `useCheckoutExtensionData` hook](https://github.com/woocommerce/woocommerce-blocks/blob/v9.4.1/assets/js/base/context/hooks/use-checkout-extension-data.ts#L29-L35) is handled by useEffect, which makes it so that when `setExtensionData` is called multiple times in an instant, the [state merge](https://github.com/woocommerce/woocommerce-blocks/blob/v9.4.1/assets/js/base/context/hooks/use-checkout-extension-data.ts#L39-L46) behind the first time is referencing data that is not yet synchronized with **wp-data** store. Therefore, the result of the last call to `setExtensionData` will overwrite all the previous ones.

📹 Inspecting the runtime states of the two calls with DevTool shows this situation:

https://user-images.githubusercontent.com/17420811/215932712-0090098c-0755-4728-a1b9-4579d2f14068.mp4

📷 It's also possible to find that the `extensionData` state in **wp-data** store is overwritten via the Redux DevTool:

1. The first call sets an extension property.
   ![2023-01-31 19 46 30](https://user-images.githubusercontent.com/17420811/215932728-4751925b-e589-4b25-83ee-8462ae88ce30.png)
2. The second call overwrites the extension property set in the first call.
   ![2023-01-31 19 46 47](https://user-images.githubusercontent.com/17420811/215932737-16f7c767-c9b9-4e53-aa0e-a3e7f9cf350f.png)

---

Hence, this issue occurs when the call from AutomateWoo is earlier than Mailpoet. Perhaps the state merge of `extensionData` could be moved to the [reducer of  **wp-data** store](https://github.com/woocommerce/woocommerce-blocks/blob/v9.4.1/assets/js/data/checkout/reducers.ts#L149-L158), which should make it always refer to the latest synced state.

**Comment by mikejolley** [comment]
On my install I get the `automatewoo` key rather than the MailPoet one, so I cannot replicate the error. However I understand the conflict here and yes, those extensions will be fighting for control (thanks @eason9487).

I think given the issue yes, we'll need to move some of this logic to prevent it overwriting. I'll take a brief look into this to see how complex this will be, otherwise I'll move it to the backlog. I suspect this is more of an edge case since it would mean using multiple marketing opt-ins on a single store.

Edit: I reproduced this by swapping the position of the opt-ins on checkout. Depending which extension was enabled first will determine whether or not this step is needed.
