### ISSUE TITLE
Missing support for Marketing opt-in checkbox AND AutomateWoo - Birthdays Add-on

### ISSUE THREAD

**Issue by grand-lotus-iroh** [woocommerce/woocommerce-gutenberg-products-block#8405]
I noticed in options for AutomateWoo that if you enable "Marketing opt-in" the checkbox isn't checked by default. Also, if you navigate to the block there is no option to "default check" the box.

![image](https://user-images.githubusercontent.com/1291364/217905575-6e5825fe-6c90-4ce6-aaf9-fa72b856f8b5.png)

If you have "AutomateWoo - Birthdays Add-on" plugin activated, it does not show in the field even though in the options it's enabled. Also, the supported plugin list has AutomateWoo in there, but I guess it does not apply to addons?

* https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-8
* https://woocommerce.com/products/automatewoo-birthdays/

**Comment by opr** [comment]
Hi there @grand-lotus-iroh, thank you for opening this issue.

>  Also, the supported plugin list has AutomateWoo in there, but I guess it does not apply to addons

That's true, technically speaking it's a separate plugin, so support would need to be declared for that separately.

As for the marketing opt-in checkbox's default state, I don't believe this is something that can be automatically checked, but I have asked the AutomateWoo team to confirm this.

**Comment by opr** [comment]
Hi there, I just heard back. There is an opt-in/opt-out setting in the AutomateWoo settings, but opt-out doesn't mean it's checked by default, it means it won't be shown and users will need to click an opt-out link afterwards. So, there isn't really a setting to always have it pre-checked. You could probably figure out a way to have it checked using JS on page load, but please note that there may be some legal concerns about doing that in some jurisdictions.

Since there is nothing actionable here, I will close the issue, but please feel free to reopen it if you need further help.
