### ISSUE TITLE
Add to Cart Form Block naming discussion

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#8453]
On #8284 we started a conversation around the naming for the add-to-cart form block, with different opinions shared by many different folks:

https://github.com/woocommerce/woocommerce-blocks/pull/8284#discussion_r1093221190
https://github.com/woocommerce/woocommerce-blocks/pull/8284#issuecomment-1415999934

We ended up having to merge that PR for unblocking the work on the compatibility layer for this and other single product template blocks, but the discussion is still pertinent, so I'm opening this issue for us to follow up and keep track.

**Comment by Aljullu** [comment]
I originally posted this in https://github.com/woocommerce/woocommerce-blocks/pull/8284, but moving it here. :slightly_smiling_face: 

To provide some screenshots, this is the Add to Cart button and Add to Cart form (or however ends up being named :smile: ) of a variable product:

Add to Cart button | Add to Cart form
--- | ---
<img src="https://user-images.githubusercontent.com/3616980/219339326-c512d115-ce12-4e45-b566-cf1883a19491.png" alt="" width="368" /> | <img src="https://user-images.githubusercontent.com/3616980/219339397-a5fa683c-3505-438f-83ed-928652927f61.png" alt="" width="425" />

They serve two different purposes, the button is useful in product grids and contexts where the entire form would crowd the layout too much, while the form is useful in contexts where the customer is expected to finalize the selection and add the product to the cart.

Currently, the _Add to cart button_ is only available inside the Products block and the _Add to cart form_ will only be available inside the Single Product template. So right now, there is no confusion between the two. But in the future, we might introduce a _Product_ block which will allow showcasing products in the front page, for example. In that case, I envision there might be use cases for both blocks: some stores might want to add the _Add to cart button_ block so customers get redirected to the Single Product page (assuming it's not a simple product), and some other stores might want to add the _Add to cart form_ block, so customers can choose between the options right in the front page without having to visit the Single Product page.

That's why I think it's important for us to make a clear distinction of the two blocks. I don't have strong opinions about the specific names, but as I mentioned in my previous comment, I do think they need different names. I'm also inclined to avoid the _Add to Cart_ name for one of them because I think it will make it difficult to distinguish which of the two blocks it is.

**Comment by helgatheviking** [comment]
Thank you for the clarity about the distinction between the two "add to cart" elements. I've seen a lot of confusion about this over the years with respect to the add to cart shortcode... which is just a button and therefore cannot add any complex products to the cart at all. 

In the first screenshot we see that the button doesn't add the item to the cart (b/c the product has options and doesn't support it). Would it make sense to call that the "call to action" button? I know it will add to cart for products that require no configuration.... not sure i have the answer but glad there's a discussion about how to best distinguish the two things.

**Comment by shaunandrews** [comment]
My suggestion is **Add to Cart with Options**; While long, its rather descriptive and I think its important to keep the "add to cart" bit as it connects with our **Add to Cart Button** block.
