### ISSUE TITLE
Tax line remains after changing to a country with no tax rule

### ISSUE THREAD

**Issue by fetenlakhal** [woocommerce/woocommerce-gutenberg-products-block#8469]
## Describe the bug

You have a 10% tax for UK and 0% for the rest of the world. You add a UK address in the checkout, you see the taxes. If you change the country to Poland, the tax is stuck there. It disappears on the order confirmation page. 

## To reproduce

1- Add the latest version of [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/) on your website
2- Add the [check-out block](https://woocommerce.com/document/cart-checkout-blocks-support-status/) on your check-out page.
3- Create a 10% tax for UK
4- Add a product to the cart and go to checkout
5- Change country to UK, for example, with the zip code W1J 8ET
6- See the taxes
7- Change country to Poland with zip code 00-024

## Expected behavior

Normally, it has to show 0% tax for Poland.

## Screenshots

Link to the gif: `d.pr/i/xm1qsw`

## Environment

Environment
WordPress (please complete the following information):
WordPress version: 6.1.1
WooCommerce version: 7.1.0
WooCommerce Blocks version: 9.5.0
Site language: English

## Additional context

They have already reverted back to PHP 7.4. It's not related to this issue: https://github.com/woocommerce/woocommerce-shipping-fedex/issues/221

**Comment by nielslange** [comment]
Hello @taftina 👋

Thanks for reporting this. I also saw the discussion in p1676388875303829-slack-C7U3Y3VMY. For transparency-reasons, let's proceed with the discussion here. I just tried to reproduce this problem, based on the testing steps, but wasn't able to reproduce the error. I did use Germany instead of Poland, for the screen recording, but I wasn't able to reproduce the error when switching from UK to Poland either. Please find below the screen recording I created:

![Screen Capture on 2023-02-20 at 14-00-09](https://user-images.githubusercontent.com/3323310/220035834-2a9f4755-3d63-4357-bfc3-94caed22c993.gif)

Can your test environment be accessed publicly or is it a local test site? Would you have time for a Slack call so that you can show me the error on your end?

**Comment by fetenlakhal** [comment]
Hello @nielslange.

Sorry for my late answer! I didn't see your ping! (I don't receive them by email, I don't know why)

Here is my test website: https://test2website.mystagingwebsite.com/checkout/. 

I couldn't reproduce the problem either :/. But still, there is a problem with the tax. Here is a link to the gif I made: [d.pr/i/CB6TyY. ](![CB6TyY.gif](https://user-images.githubusercontent.com/7060575/222533448-63eae87e-b724-45cb-8560-a76b1d099809.gif))

I can give you access to my website if you want :) 

And I can be available for a Slack call in 2 weeks (I'll be AFK next week)

**Comment by nielslange** [comment]
Hello @taftina,

Your screen recording shows an error related to the postcode. As long as there's an error in the checkout, the data won't be pushed to the server. I see that you're using the following address data:

```
country: United Kingdom
city: London
postcode: W1J 8ET
```

On my end, I do not see the postcode validation error when using these credentials. Are you using the latest version of WooCommerce Blocks? You can also just ping me once you're back from AFK, so that we can look at this problem together.

**Comment by ralucaStan** [comment]
Hey @taftina,
as there hasn't been any answer on the ticket for 2 weeks I am going to close it. Feel free to comment on it if you are still dealing with the issue.

Thank you so much for taking the time to get in touch with us!
