### ISSUE TITLE
WC-blocks dutch checkout

### ISSUE THREAD

**Issue by Moosinams** [woocommerce/woocommerce-gutenberg-products-block#8531]
## What do you like about the Cart & Checkout blocks?
Realy better as standard woocommerce
## What do you think is missing from the Cart & Checkout blocks?
I miss a few Dutch translations, Add a coupon=Kortingscode , Please enter a valid=Vul a.u.b. juist in:
And City names in Holland kan start with a ' , like 's-Hertogenbosch.

**Comment by nielslange** [comment]
Hello @Moosinams 👋

Thanks for reaching out! _(Oftewel bedankt voor je bericht! 😁)_ I'll switch back to English, so that others can follow the conversation. 

> Realy better as standard woocommerce

That's great to hear. Is there any specific you like better with the new Cart and Checkout blocks? I'm just curious.

> I miss a few Dutch translations, Add a coupon=Kortingscode , Please enter a valid=Vul a.u.b. juist in:

Please note that translations are handled by volunteers. Looking at https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/, you can imagine why it's almost impossible for us to translate WooCommerce Blocks into every language. That said, the Dutch translators are usually rather quick in providing translations. In addition, to relying on someone else to provide a translation, you can also become a translation contributor. On https://make.wordpress.org/polyglots/handbook/translating/glotpress-translate-wordpress-org/#getting-started you can find information on how to get started. Once you've submitted translations, they need to be approved by a translation editor. 

> And City names in Holland kan start with a ' , like 's-Hertogenbosch.

I just ran a quick test and saw that it's possible to place an order when using the city name 's-Hertogenbosch. That said, when placing a second order, I see that 's-Hertogenbosch changed to &#8216;s-Hertogenbosch. That's indeed not the correct city name. I created https://github.com/woocommerce/woocommerce-blocks/issues/8533 to track this issue.

I'll close this issue for now, as there are no action points, but you are welcome to create another issue if you have any more questions or suggestions. We always welcome any kind of feedback! 😀

**Comment by Moosinams** [comment]
Hi Niels,

Thank you for your quick reaction. Regarding the apostrophe, I had the
same, maybe I had to fill in a new address to check better, thnx for
starting 8533.

I will have a look, to help in the translations.

Have a nice weekend.

Grtz
Moos


Op vr 24 feb. 2023 om 13:05 schreef Niels Lange ***@***.***>:

**Comment by nielslange** [comment]
Hi Moss,

> Thank you for your quick reaction. Regarding the apostrophe, I had the same, maybe I had to fill in a new address to check better, thnx for starting #8533.

I believe that the apostrophe should be kept, as it's part of the official name. That said, I started a discussion within our team to discuss this.

> I will have a look, to help in the translations.

That's great to hear. I'm actually one of the Translation Editors for Dutch and can approve translations. I'll keep an eye on translation submissions so that they can go live as soon as possible.

I also wish you a great weekend, Moos! 🙌

**Comment by Moosinams** [comment]
Hi Niels,

Ik zag al mooi vertalingen langskomen, geweldig !

Mag ik je nog een vraagstellen over de blocks. Ik krijg bijgevoegde
foutmelding bij het invullen. Weet jij hoe dit komt?

Groet
Moos


Op vr 24 feb. 2023 om 13:35 schreef Niels Lange ***@***.***>

**Comment by nielslange** [comment]
Hi Moos,

> Mag ik je nog een vraagstellen over de blocks. Ik krijg bijgevoegde
foutmelding bij het invullen. Weet jij hoe dit komt?

Let's try to communicate in English, so that others, that might face the same problem, can follow the discussion. You were asking if you can ask another question regarding the blocks and that you're seeing an error message. It appears that the error message hasn't been transferred to GitHub. I assume that this issue is unrelated to this issue. Could you go ahead, create a new issue, describe the problem you're facing and add steps on how to reproduce the problem?

**Comment by Moosinams** [comment]
Tnx Niels, I will try 👍

Op vr 24 mrt. 2023 om 11:08 schreef Niels Lange ***@***.***>

**Comment by nielslange** [comment]
Thanks, Moss! 🙌
