### ISSUE TITLE
cant translate "Add a coupon" string in the cart page via loco translate

### ISSUE THREAD

**Issue by GuyAckerman** [woocommerce/woocommerce-gutenberg-products-block#8637]
Hi, in the cart page it seems that "Add a coupon" cannot be translated.
need a fix asap thanks :)

**Comment by tarhi-saad** [comment]
Hello, @GuyAckerman! 👋 Thank you for reporting this translation bug! 🙌 Could you please complete the following information:

- WordPress version: (e.g., 6.1.1)
- WooCommerce version: (e.g., 7.4.1)
- WooCommerce Blocks version: (e.g., 9.4.4)
- Site language:

**Comment by GuyAckerman** [comment]
Hi, thanks for the reply.
WordPress version 6.1.1
WooCommerce version: 7.4.1
WooCommerce Blocks version 9.7.2
site language: hebrew

**Comment by tarhi-saad** [comment]
Hello, @GuyAckerman! 👋 The text `Add a coupon` [isn't translated on the latest version of WooCommerce](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/he/default/?filters%5Bterm%5D=Add+a+coupon&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc). But, we can find the translation in [the development version of WooCommerce](https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/he/default/?filters%5Bterm%5D=Add+a+coupon&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc). This means that it'll be fixed in the next release! 

The reason for the temporary missing translation of the text `Add a coupon` is that it was recently changed from `Apply a coupon code`.

**Comment by GuyAckerman** [comment]
great! thanks a lot :)
ill make sure to keep an eye out for the update
