### ISSUE TITLE
"Filter by attribute" blocks shown on category pages when attribute not present on products

### ISSUE THREAD

**Issue by paulostp** [woocommerce/woocommerce-gutenberg-products-block#8706]
## Describe the bug

If I'm viewing a product category page and I have a few **Filter by attribute** blocks on the sidebar, all the filters will always show even if one of the attributes doesn't exist on the group of products I'm looking at.

## To reproduce

1. Create two products, with one product category for each and also one attribute for each;
2. Add "Filter by attribute" blocks to the sidebar for each attribute;
3. Go to one of the category pages and notice that both filters are shown;
4. Filtering by the attribute that we know doesn't exist on that category will show that no products exist with that filter.

## Expected behavior

If an attribute doesn't exist on the group of products being shown, then the respective "Filter by attribute" block should be hidden. This can result in a confusing and frustrating experience for the customer. 

## Environment

WooCommerce core 7.4.1

## Additional context

Reported by 6015243-zen.

**Comment by kmanijak** [comment]
@paulostp, thanks a lot for raising this issue!

This issue is known and is tracked within https://github.com/woocommerce/woocommerce/issues/42542.

To keep the backlog clean I'll go ahead and close this issue, but please follow https://github.com/woocommerce/woocommerce/issues/42542 for further updates.

Keep in mind closed issues can still be commented on! 🙌
