### ISSUE TITLE
Ensure Cart block supports the theme-level global styles for `Typography » Headings`

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8711]
Currently, the Cart block partially supports the default theme-level global styles for `Typography » Headings`. This issue aims to ensure that the Cart block fully supports the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Typography » Headings` settings.
4. Adjust the settings `FONT`, `APPERANCE`, `LINE HEIGHT`, `LETTER SPACING` and `LETTER CASE`.
5. See that some settings are not supported.

## Screenshots

<table>
<tr>
<td>Cart:
<br><br>
<img width="2879" alt="Typography-Headings-Cart" src="https://user-images.githubusercontent.com/3323310/224685498-a1422560-9cc4-4e75-9c82-b4e41b318fe4.png">
</tr>
</table>

**Comment by tarunvijwani** [comment]
We are currently discussing the semantics to follow in pdFofs-SY-p2 p2. 

Based on the discussion so far, we will not change anything in the `Products` and `Totals` table headings. We will use the `CART TOTALS` with `<span>` and `<div>` so that it will adopt the global styles of the text (Global styles -> Typography -> Text).

**Comment by tarunvijwani** [comment]
Changed headings to span in #8976. Closing the issue in favor of #8976.
