### ISSUE TITLE
E2E tests: Split tests by block-specific labels

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8748]
During the Woo Division Meetup in Vienna, we talked about potential improvements to the E2E tests. One of the concerns was, that the current E2E tests take a long time to execute. A potential idea was to split the E2E tests by block-specific labels. 

## Who’s maintaining WooCommerce Blocks and the E2E tests?

Currently, the WooCommerce Blocks are maintained by three teams:

1. Team Rubik (@woocommerce/rubik), who takes care of the Cart and the Checkout blocks
2. Team Kirigami (@woocommerce/woo-fse), who takes care of all blocks apart from the Cart and the Checkout blocks
3. Team Origami (@woocommerce/woo-fse), who takes care of all blocks apart from the Cart and the Checkout blocks

### How could E2E tests be split?

The E2E tests could be split based on block-specific labels. Currently, we have 35 block-specific labels. The following table shows which team is affected by which label:

<table>
    <tr>
        <td>Team Rubik</td>
        <td colspan="2">Team Kirigami & Team Origami</td>
    </tr>
    <tr>
        <td valign="top">
            <ul>
                <li>◼️ block: cart</li>
                <li>◼️ block: checkout</li>
                <li>◼️ block: cross-sells</li>
            </ul>
        </td>
        <td valign="top">
            <ul>
                <li>◼️ block: active filters</li>
                <li>◼️ block: add to cart form</li>
                <li>◼️ block: all products</li>
                <li>◼️ block: all reviews</li>
                <li>◼️ block: best selling products</li>
                <li>◼️ block: catalog sorting</li>
                <li>◼️ block: customer account</li>
                <li>◼️ block: featured category</li>
                <li>◼️ block: featured product</li>
                <li>◼️ block: filter by attribute</li>
                <li>◼️ block: filter by price</li>
                <li>◼ block: filter by rating</li>
                <li>◼️ block: filter by stock</li>
                <li>◼️ block: hand-picked products</li>
                <li>◼️ block: mini cart</li>
                <li>◼️ block: newest products</li>
                <li>◼️ block: on sale products</li>
            </ul>
        </td>
        <td valign="top">
            <ul>
                <li>◼️ block: product categories list</li>
                <li>◼️ block: product details</li>
                <li>◼️ block: product image gallery</li>
                <li>◼️ block: product meta</li>
                <li>◼️ block: product price</li>
                <li>◼️ block: product results count</li>
                <li>◼️ block: product search</li>
                <li>◼️ block: product</li>
                <li>◼️ block: products by attribute</li>
                <li>◼️ block: products by category</li>
                <li>◼️ block: products by tag</li>
                <li>◼️ block: reviews by category</li>
                <li>◼️ block: reviews by product</li>
                <li>◼️ block: store breadcrumbs</li>
                <li>◼️ block: top rated products</li>
                <li>◼️ block-type: templates</li>
            </ul>
        </td>
    </tr>
</table>

### How are E2E tests currently triggered?

Currently, the E2E tests are triggered as follows:

- When creating or updating a PR, the entire E2E test suite runs.
- When creating the nightly build, the entire E2E test suite runs.

### How could E2E tests be triggered in the future?

In the future, the E2E tests could be triggered as follows:

- If the nightly build is created, then run the entire E2E test suite.
- If the corresponding PR contains the label that related to team Rubik, then run the E2E tests that are related to the Cart and Checkout blocks.
- If the corresponding PR contains a label related to team Kirigami or team Origami, then run E2E tests that are unrelated to the Cart and Checkout blocks.
- If the corresponding PR does not contain a block-specific label, e.g. when updating the documentation, the E2E tests will not be triggered.

### Benefits

* Faster execution time: By splitting the E2E tests based on block-specific labels, we can run only the relevant tests for each specific block, reducing the total execution time of the E2E test suite.
* Improved focus: By separating the E2E tests based on block-specific labels, we can improve the focus of each team on their specific areas of responsibility, allowing them to focus on their specific blocks more effectively.

### Drawbacks

* Increased complexity: Splitting the E2E tests based on block-specific labels will require additional configuration and setup, which can add complexity to the E2E testing process.
* Potential maintenance overhead: Maintaining multiple sets of E2E tests can be challenging and require additional effort, which could potentially lead to maintenance overhead for the teams.
* Increased test suite fragmentation: Splitting the E2E tests based on block-specific labels can lead to fragmentation of the test suite, which could make it harder to manage and maintain over time.

**Comment by samueljseay** [comment]
I'm not sure I understand the block labels approach here. Are these labels applied by CI based on file changes? If not, it seems prone to error if we accidentally forget to add a label. Team name seems not robust enough imo since responsibilities might change over time. But I could be misunderstanding the label based approach here. A quick search didn't immediately reveal to me some automated labelling that would solve this issue right now. e.g. my PR here: https://github.com/woocommerce/woocommerce-blocks/pull/10787 does not get assigned any kind of automated label right now.

I wonder, what if e2e tests were located alongside the blocks they are for, then we could quite easily detect what files are being changed in the PR and run the appropriate e2e tests for the block being changed?

This still has risk in my opinion that we will accidentally miss how one piece of code affects another. 

We should also ask if we can speed up the e2e tests instead. For example playwright supports sharding. It's possible that sharding will improve test run times as the set of tests inevitably gets larger.

**Comment by opr** [comment]
> Are these labels applied by CI based on file changes? If not, it seems prone to error if we accidentally forget to add a label.

They are manually added, it's not always done sometimes it is missed, so you're right.

> This still has risk in my opinion that we will accidentally miss how one piece of code affects another.
 
Exactly, E2E tests test the functionality of a few different components working together, so locating them next to the code is not really possible, and it's likely that some file changes will affect a test, but won't trigger them due to not being alongside.

> We should also ask if we can speed up the e2e tests instead. For example playwright supports sharding. It's possible that sharding will improve test run times as the set of tests inevitably gets larger.

I like the idea of sharding, we currently have a matrix set up to run each "project" (classic theme, block theme, and "side-effects") wonder if we could further shard these so they run even quicker 🏃🏼‍♂️ 

Looking at the [playwright sharding docs](https://playwright.dev/docs/test-sharding#sharding-tests-between-multiple-machines) it seems we just pass a command line argument and playwright takes care of it?

**Comment by gigitux** [comment]
I agree with @opr and @samueljseay!

> We should also ask if we can speed up the e2e tests instead. For example playwright supports sharding. It's possible that sharding will improve test run times as the set of tests inevitably gets larger.

Great idea! 💪

**Comment by nielslange** [comment]
Thanks for your feedback, @samueljseay. As @opr already mentioned, you are correct that splitting the tests based on labels is error-prone. Similar to @opr and @gigitux, I also like your suggestions of looking into [Playwright Sharding](https://playwright.dev/docs/test-sharding). I wasn't aware of that. Thanks for sharing this. 🙌

**Comment by dinhtungdu** [comment]
> Looking at the [playwright sharding docs](https://playwright.dev/docs/test-sharding#sharding-tests-between-multiple-machines) it seems we just pass a command line argument and playwright takes care of it?

It's similar to how we're running Jest E2E tests, but yeah, simpler. We then need to rethink our current setup. Looks like we should only use shard for the normal setup (which will be run in parallel locally in future).

**Comment by gigitux** [comment]
>Looks like we should only use shard for the normal setup (which will be run in parallel locally in future).

Why? Each shard will have its WordPress website, no?

Should we close this issue?

**Comment by dinhtungdu** [comment]
> Why?

Because we have three PW test suites right now: Normal, Side Effect, and Classic. If we use shard by adding another matrix, then we will have 12 test workflows if we use 4 shards.

I was also thinking, if we use shards, then do we need to split our tests into three test suites like current? On the CI we use 1 worker anyway. But I don't think we should merge them back to one test suite because we want to run our normal tests in parallel locally.

**Comment by gigitux** [comment]
>Because we have three PW test suites right now: Normal, Side Effect, and Classic. If we use shard by adding another matrix, then we will have 12 test workflows if we use 4 shards.

I don't think that it is an issue, or does GH set some limits?

**Comment by opr** [comment]
> I don't think that it is an issue, or does GH set some limits?

We should be mindful of sustainability when it comes to our CI jobs too.

The setup time of each of these WordPress sites, building the project takes roughly 5 minutes per run (~2.5 mins for building and ~2.5 for wp-env setup) so we should consider if using this extra compute power is really worth it. Maybe we can start with fewer shards and define a maximum amount of time we're comfortable with the jobs running for? E.g. the job should not exceed 10 minutes. If we notice the jobs taking longer than this, we could add an additional shard.

**Comment by dinhtungdu** [comment]
> We should be mindful of sustainability when it comes to our CI jobs too.

💯. At least for now, the Side Effect and Classic ones are pretty small.

> ~2.5 mins for building

What do you think about using the zip file we build for each PR to cut off this step?

**Comment by nielslange** [comment]
Closing due to pca54o-6Dz-p2
