### ISSUE TITLE
Ensure Cart block supports the theme-level global styles for `Colors » Headings`

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#8751]
Currently, the Cart blocks partially support the theme-level global styles for `Typography » Headings`. This issue aims to ensure that the Cart block fully supports the theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Colors » Headings` settings.
4. Adjust the color settings.
5. See that some headlines do not reflect the color.

## Screenshots

<table>
<tr>
<td>Cart:
<br><br>

<img width="2879" alt="Colors-Headings-Cart" src="https://user-images.githubusercontent.com/3323310/225236607-06b3b47e-3bfb-4afb-8dca-68647824af19.png">
</td>
</tr>
</table>

**Comment by tarunvijwani** [comment]
We are currently discussing the semantics to follow in pdFofs-SY-p2 p2. 

Based on the discussion so far, we will not change anything in the `Products` and `Totals` table headings. We will use the `CART TOTALS` with `<span>` and `<div>` so that it will adopt the global styles of the text (Global styles -> Color -> Text).

**Comment by tarunvijwani** [comment]
Changed headings to span in #8976. Closing the issue in favor of #8976.
