### ISSUE TITLE
Basket block coupon entry requires login

### ISSUE THREAD

**Issue by davidhealey** [woocommerce/woocommerce-gutenberg-products-block#8782]
## Describe the bug

When trying to enter a coupon into the basket/cart block's input the user will get a "You are not currently logged in." message. 

## Expected behavior

Users should be able to enter a coupon without an account.

## Screenshots

![image](https://user-images.githubusercontent.com/14021202/226104810-335d4879-120c-413c-b73b-aed98c6be2dd.png)

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed): 15.3.1
-   WooCommerce version: 7.5.0
-   WooCommerce Blocks version: 9.6.5
-   Site language: English
-   Any other plugins installed: Yes

### Desktop (please complete the following information):

-   OS: Tested with Linux/Windows
-   Browser Test with Firefox/Chrome

## Additional context

I'm not using the checkout block, only the basket/cart block. With the default checkout page it is possible to enter a coupon without being logged in.

**Comment by davidhealey** [comment]
Related to this: It's also not possible to remove an item from the cart unless you're logged in.

**Comment by mikejolley** [comment]
This issue does not occur for me, and I'm fairly certain it would have been picked up by the end-to-end test suite if it was a bug because those run without using a logged in user.

I suspect it's a plugin on your site; either security related, or something specifically designed to restrict access to the WordPress Rest API. The Store API which powers these blocks requires access to the REST API to function.

Take a look at what you have installed, and disable those plugins to test for conflicts. Let us know what you find.

**Comment by davidhealey** [comment]
Ah okay, that's probably it. I have the REST API disabled because I wasn't using it (or at least I didn't think I was). I'll take a look and report back.

**Comment by davidhealey** [comment]
Yep that was the issue. I had a function setup to require all REST requests to be authenticated except for logged in users. I'll try to filter out the basket page.
