### ISSUE TITLE
Ensure Checkout block supports the theme-level global styles for `Colors » Links`

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#8807]
Currently, the Checkout block partially supports the default theme-level global styles for `Colors » Links`. This issue aims to ensure that the Checkout block fully supports the default theme-level global styles.

## Steps to reproduce

1. Go to `WP Admin » Apperance » Editor`.
2. Open the `Styles` sidebar.
3. Open the `Colors » Links` settings.
4. Adjust the color settings for `Default` and `Hover`.
5. See that the `Default` color is not reflected.

## Screenshots

<table>
<tr>
<td>Checkout:
<br><br>

<img width="2874" alt="Colors-Links-Checkout" src="https://user-images.githubusercontent.com/3323310/225235676-fae1a589-0450-425a-9473-b61df93e6ead.png">
</td>
</tr>
</table>

**Comment by nielslange** [comment]
While looking into this issue, I noticed that the problem only appears when using [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/), but not when using [Twenty Twenty-Two](https://wordpress.org/themes/twentytwentytwo/), [Adventurer](https://wordpress.org/themes/adventurer/), [Beaumont](https://wordpress.org/themes/beaumont/), [Björk](https://wordpress.org/themes/bjork/) or [Tove](https://wordpress.org/themes/tove/).

While investigating [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/), I noticed that the  [theme.json of Twenty Twenty-Three](https://github.com/WordPress/twentytwentythree/blob/11440a5b38bae6882fc2c00b703d4bb95420a0f5/theme.json#L325-L333) contains the following definition:
```json
"core/post-content": {
  "elements": {
	  "link": {
      "color": {
		  "text": "var(--wp--preset--color--secondary)"
		}
	  }
  }
},
```

This definition results in the following CSS code:
```css
.wp-block-post-content a:where(:not(.wp-element-button)) { 
  color: var(--wp--preset--color--secondary);
}
```

While the Global Styles CSS looks like this:
```css
a:where(:not(.wp-element-button)) {
  color: var(--wp--preset--color--vivid-red);
}
```

Due to [Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity), the CSS code of the Twenty Twenty-Three theme overwrites the Global Styles CSS code. Given that this problem not only affects the link colors within the Checkout block, but all link colors, this problem should be addressed [within the Twenty Twenty-Three theme](https://make.wordpress.org/core/reports/) itself. Therefore, I created https://core.trac.wordpress.org/ticket/57968.
