### ISSUE TITLE
Mini Cart: allow customizing the drawer width

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#8814]
Currently, the Mini Cart block drawer has a width of 480px (or less if the viewport is not that wide). As a user, I would like to be able to customize this width.

**Comment by dinhtungdu** [comment]
I think at least, if we can make it easier for developers to change the width of the Mini Cart, that will be good enough. 

Currently, to change the width, developers has to override CSS in some places:

```
.wc-block-components-drawer {
    ...
    transform: translateX(-480px);
    width: 480px;
}
```
```
@keyframes slidein {
   ...

    to {
        transform: translateX(-480px)
    }
}
```

What do you think about using a CSS variable and use that variable in those places above? By doing so, developers just need to override the CSS variable instead of hard coding it. It's aslo easier if we later want to add a block option enabling using to change the width.

**Comment by albarin** [comment]
@dinhtungdu @Aljullu Do you imagine this setting being part of the `Mini cart` block or the `Mini cart contents` inner block? Would it appear on the setting sidebar of the `Mini cart` or the `Mini cart contents`?
| Mini-cart | Mini-cart contents |
|--------|--------|
| <img width="851" alt="Screenshot 2023-03-23 at 16 29 34" src="https://user-images.githubusercontent.com/186112/227253818-1a30aa0e-ea06-4a71-a33c-bc657abf4941.png"> | <img width="1227" alt="Screenshot 2023-03-23 at 16 29 43" src="https://user-images.githubusercontent.com/186112/227253833-a3093367-e7cb-4256-ab92-3638aeb9bf78.png"> |

**Comment by Aljullu** [comment]
@albarin good question. IMO it would make more sense as part of the Mini Cart Contents block, but I don't have a strong opinion.

**Comment by dinhtungdu** [comment]
> IMO it would make more sense as part of the Mini Cart Contents block

Place the setting under the MIni Cart Contents block also makes more sense to me.
