### ISSUE TITLE
dispatchCheckoutEvent contains stale Cart

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#8863]
it seems that the Cart value associated with dispatchCheckoutEvent is one event stale, this seems to be case for `useStoreCart` in general, so even if you include it directly into the `dispatchCheckoutEvent` call, it's still stale.

Reaching out directly to the data store works fine.
### Steps to reproduce

In console, run this
```
wp.hooks.addAction(
	"experimental__woocommerce_blocks-checkout-set-email-address",
	"test-plugin",
	({storeCart}) => {
		console.log("set-email-address", storeCart.billingAddress.email);
	}
);
```
- Start typing, you can see that on each event, you get the previous value.
This is problematic because you can no longer track the actual email.

### Workaround

```
wp.hooks.addAction(
	"experimental__woocommerce_blocks-checkout-set-email-address",
	"test-plugin",
	({storeCart}) => {
		const { billingAddress: { email } } = wp.data.select('wc/store/cart').getCartData()
		console.log("stale address", storeCart.billingAddress.email);
		console.log("up to date address", email);
	}
);

**Comment by opr** [comment]
Hey @senadir what do you think about getting the cart from the data store within the callback?

Like so:

```ts
	const dispatchCheckoutEvent = useCallback(
		( eventName, eventParams = {} ) => {
			const storeCart = select( 'wc/store/cart' ).getCartData();

			try {
				doAction(
					`experimental__woocommerce_blocks-checkout-${ eventName }`,
					{
						...eventParams,
						storeCart,
					}
				);
			} catch ( e ) {
				// We don't handle thrown errors but just console.log for troubleshooting.
				// eslint-disable-next-line no-console
				console.error( e );
			}
		},
		[]
	);
```

I could open a PR with this change if you think that would be a good approach.

**Comment by senadir** [comment]
Getting it from inside the callback is not needed, it can happen outside the callback, but that would be hiding the actual issue here of having a stale cart, is it expected? if yes, can we chain the checkoutEvent so its triggers after we persist the value to the store?

**Comment by opr** [comment]
When `useStoreEvents` is called ([here](https://github.com/woocommerce/woocommerce-blocks/blob/9e1b443c436198510ab939664ffbb4b78a17db5d/assets/js/blocks/checkout/inner-blocks/checkout-contact-information-block/block.tsx#L36)) the cart data is stored there. It will only be re-fetched from the data store when the hook is run again.

Because we immediately [`dispatchCheckoutEvent`](https://github.com/woocommerce/woocommerce-blocks/blob/9e1b443c436198510ab939664ffbb4b78a17db5d/assets/js/blocks/checkout/inner-blocks/checkout-contact-information-block/block.tsx#L40) after [`setEmail`](https://github.com/woocommerce/woocommerce-blocks/blob/9e1b443c436198510ab939664ffbb4b78a17db5d/assets/js/blocks/checkout/inner-blocks/checkout-contact-information-block/block.tsx#L39) - there is no chance for the hook to re-run and re-fetch the cart data from the store.

I believe this is why we _do_ need to select from the store within the callback.

**Comment by senadir** [comment]
Even having useStoreCart inside didn’t help for my case

**Comment by ralucaStan** [comment]
What is the impact of this bug?

**Comment by opr** [comment]
> What is the impact of this bug?

It means anything listening to these checkout events can never have correct, current data of the cart/checkout state. I am not sure of the implications of the bug though.

I'm struggling to think, but one contrived example is if you had an analytics goal that wanted to trigger when shopper's entered "Greece" as the country on checkout, you could use the `set-shipping-address` and `set-billing-address` checkout actions. When these events happened, you could check the country, and dispatch an analytics event if it matched "Greece".

With this bug, the country will only ever match "Greece" if the user selects that, and then makes further changes to the Checkout form, it will _not_ match "Greece" immediately after selecting it in the form.

@senadir, please could you provide a more realistic example?

**Comment by mikejolley** [comment]
I think the expectation is to trigger the action with current data. The ref here prevents that. @opr's code makes sense. Ill check it works with the provided use case and if there are any other issues with the approach.
