### ISSUE TITLE
Blockified Product Archive: Move the surrounding blocks outside of Products block

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-gutenberg-products-block#8872]
### Description
When converting the Classic Template to Blockified template the surrounding blocks (Btreadcrumbs, Store Notices, Product Result Count and Catalog Sorting) were included as inner blocks of Products block. But that has a consequence that if user changes pattern of Products block, the other blocks are removed.
To avoid this confusing behaviour, surrounding blocks should be moved outside of the Products block.

### Notes
Change must be applied in:
- [Product Archive conversion](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/classic-template/archive-product.ts)
- [Product Search Result conversion](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/classic-template/product-search-results.ts)
- [Product Archive Template](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/templates/templates/blockified/archive-product.html)
- [Product Search Results Template](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/templates/templates/blockified/product-search-results.html)

**Comment by nerrad** [comment]
One thing I didn't think of when I brought up this issue is that there _may_ be cases where patterns explicitly utilize these blocks too (which could result in the reverse, we end up with duplicate blocks if such a pattern is used). 

For now, I don't think the above needs to change the direction of this issue, but I did want to raise it as an additional consideration that will have to be addressed if/when we have product block patterns down the road that include these blocks.

**Comment by kmanijak** [comment]
> One thing I didn't think of when I brought up this issue is that there may be cases where patterns explicitly utilize these blocks too (which could result in the reverse, we end up with duplicate blocks if such a pattern is used).

Good point! 👍 

I think, when we got to that point, we could potentially implement additional logic that checks if these blocks appear in the tree and try to come up with some rules on when to inject new ones or remove the existing ones so there's no duplication or the opposite - unnecessary removal.
