### ISSUE TITLE
Filter data count mismatch > Create End to End tests for the Filter Data Counts

### ISSUE THREAD

**Issue by nefeline** [woocommerce/woocommerce-gutenberg-products-block#8873]
Create new tests so we can monitor the attribute counts for regressions. We can, for example, ensure the attribute counts match the number of filtered products displayed on the page with:

- Only one attribute filter
- Two different attribute filters
- One attribute filter used alongside the price filter
- One attribute filter used alongside the stock filter
- One attribute filter used alongside the rating filter

**Comment by roykho** [comment]
I tried diving into this however I am not able to get the tests to run locally. Sometimes they work and other times not so much.

I would get random errors like:

* `Error: The site you have requested is not installed. Run "wp core install" to create database tables.`.
* `ProtocolError: Protocol error (Page.captureScreenshot): Not attached to an active page`

They seem to be related to the setup phase. Since there are on-going discussion on fixing/improving the e2e tests, I would suggest we re-visit this after when the tests are more stable.
