### ISSUE TITLE
Bug: Can't use query filter hook to control display of products in "All Products" block

### ISSUE THREAD

**Issue by melberthrymera** [woocommerce/woocommerce-gutenberg-products-block#8973]
## Describe the bug

We can't use existing query filters in WordPress or woocommerce hook to modify the display of items using the "All Products" block.

## To reproduce

1. log in to your store as admin.
2. Create any type of multiple products.
3. Go to pages and add a new page.
4. Use Gutenberg editor and select "All Products" block.
5. Visit new added "All product" page.
6. Try to modify the products list display with any of the hooks below.
```
 - woocommerce_product_query hook in WooCommerce allows you to modify the product query arguments used to retrieve products from the database.
 - woocommerce_products_widget_query_args hook in WooCommerce allows you to modify the query arguments used to retrieve products in the WooCommerce Products widget.
 - parse_query is a WordPress hook that is triggered after the main query variables have been parsed. It allows you to modify the main query variables before the actual query is executed.
```

## Expected behavior

It should allow us to display products with custom query hooks using the filters stated above.

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): Built-in WordPress
-   WooCommerce version: 7.5.1
-   WooCommerce Blocks version: Built-in woocommerce plugin
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: macOS, Windows
-   Browser: All browser

### Smartphone (please complete the following information):

-   Device: Any device
-   OS: [e.g. iOS8.1]
-   Browser: All browser

## Additional context

The purpose of this is to control the visibility of products in every store.

**Comment by gigitux** [comment]
The `All Products` block doesn't support any filter/hook. For this reason, we are focusing on the `Products` block that also provides compatibility with filters and hooks of WC Core and performs better.

Is there a particular use case that you want to cover using the `All Products` block?

**Comment by jkohlbach** [comment]
Hi @gigitux, it would be for the same reasons listed here: https://github.com/woocommerce/woocommerce-blocks/issues/8972#issuecomment-1502459810

Hope this helps!

**Comment by gigitux** [comment]
Thanks for giving me context.

We're currently working on a Products block that's available in a beta version since WooCommerce Blocks 9.1.0. The progress around that block can be tracked through this issue: https://github.com/woocommerce/woocommerce/issues/42616. The plan is to migrate the existing product grid blocks (including All Products) to the new Products block.

One of the major point to use the Products block is that it supports the hooks of WC Core.

Given the direction towards the Products block, your suggestions don't fit with our current priorities/strategy for the project. This doesn’t mean what you are suggesting isn’t a good idea or doesn’t make sense – it’s just that we have limited time to work on various projects and bringing Products block to its full capacity is a top priority.

The progress on Products block can be followed through the Store Editing Snaps series that we publish every other week. Here's a [link to the latest edition](https://developer.woocommerce.com/2023/03/31/store-editing-snaps-march-13-24/).

The plan is that this block will in future start to replace other blocks such as All Products, but don't be alarmed these blocks will continue to work but we just won't be actively supporting them and will instead start to encourage the adoption of the Products block once it's come out of the Beta phase.

I'll go ahead and close this issue for now, but it does not mean that we didn't note the suggestions from this issue. Also, please be aware that closed issues can also still be commented on.
