### ISSUE TITLE
Audit: AutomateWoo – Birthdays

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9208]
## AutomateWoo – Birthdays

- **Author:** WooCommerce
- **Website:** https://woocommerce.com/products/automatewoo-birthdays/
- **Repository:** (private) https://github.com/woocommerce/automatewoo-birthdays

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

Adds a field to the Checkout form to capture the customer's birthday. This can then be used to send the customer a coupon on their birthday.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [x] Checkout fields
  - [x] Express checkout
  - [x] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
  - [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

*See how the extension does or does not work when using Product Blocks, Cart Block, and Checkout Block. Does it work as expected? Is functionality that works with the shortcodes broken in the blocks context?*

Issues identified:
- The birthday fields do not render on the Checkout Block.
- If the user is checking out with an Express Payment Method the birthday field will not be shown in the modal.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [x] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| Checkout Block | Inner block | Add an inner block that contains the birthday fields, make it a child of the Contact Information block. |  _2_   |
| API | Store API  | Add `IntegrationInterface` to extend the checkout endpoint. The customer's birthday should be passed in the `extensions` key. The integration should hook into one of the checkout hooks (`woocommerce_store_api_checkout_update_customer_from_request`) to handle writing the birthday to the customer record. |  _2_   |
|                                                                             |                                                                               |
```
