### ISSUE TITLE
Audit: AutomateWoo – Refer a Friend

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9209]
## AutomateWoo – Refer a Friend

- **Author:** WooCommerce
- **Website:** https://woocommerce.com/products/automatewoo-refer-a-friend/
- **Repository:** (private) https://github.com/woocommerce/automatewoo-referrals

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

Adds a form on the order complete page that asks users to recommend the store to a friend, the person being referred will then be given a coupon code to use on the site, and a successful sale will give the referrer (advocate) some store credit.

There is also a widget that can be added to show the coupon code that the advocate can manually give to their friend for referral attribution. There is also a widget that displays the link that the advocate can give to their friend which also ensures referral attribution.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [x] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

*See how the extension does or does not work when using Product Blocks, Cart Block, and Checkout Block. Does it work as expected? Is functionality that works with the shortcodes broken in the blocks context?*

Issues identified:
- *Summarize any issues you found with the extension*

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [x] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [x] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| Order Complete Page | Custom/Inner block | Currently the widget displays fine on the non-blockified Order Complete Page, but when we blockify it we will need to make sure that the ability to show custom content is enabled |  _5_   |
| Widgets/Blocks | Anywhere | The current shortcodes for the advocate link/advocate coupon could be updated to be blocks |  _5_   |
|                                                                             |                                                                               |
