### ISSUE TITLE
Audit: Back in Stock Notifications

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9210]
## Back in Stock Notifications

- **Author:** WooCommerce
- **Website:** https://woocommerce.com/products/back-in-stock-notifications/
- **Repository:** (private) https://github.com/woocommerce/woocommerce-back-in-stock-notifications

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

When an item is out of stock, the product page will show a button that lets the user sign up to be notified when it's back in stock.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [x] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [x] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [ ] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Using the Single Product template the field appears and works correctly when the product is out of stock.

Issues identified:
N/A

*Select those that apply:*

- [x] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| _Location of new integration point, or name of existing integration point._ | _Type e.g. client API, action or filter hook, component, or server side API._ | _Describe what the integration point will be used for._ |  _1_   |
|                                                                             |                                                                               |
