### ISSUE TITLE
Audit: Gifting for WooCommerce Subscriptions

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9211]
## Gifting for WooCommerce Subscriptions

- **Author:** WooCommerce
- **Website:** https://woocommerce.com/products/woocommerce-subscriptions-gifting/
- **Repository:** (private) https://github.com/woocommerce/woocommerce-subscriptions-gifting

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

This extension adds a checkbox to cart and checkout items to signify that it's a gift. When the checkbox is checked, a text field appears where the recipient's email can be entered.

| Cart | Checkout | Single Product |
| ------ | ----- | ----- |
| <img width="630" alt="image" src="https://user-images.githubusercontent.com/5656702/234832118-aaa6a18d-434a-4dd4-b334-b9989748f8d2.png"> | ![image](https://user-images.githubusercontent.com/5656702/234832160-46c0668b-4372-4c5e-b1a4-e9bfe9281303.png) | <img width="861" alt="image" src="https://user-images.githubusercontent.com/5656702/234832728-c70d2f7b-1ad2-4f1b-a740-25e35e5a7d91.png"> |

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [x] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [x] Add to cart form
- [x] Cart Page
  - [x] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [x] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

In the Single Product Template, this extension works as intended.

Issues identified:
- In the Cart and Checkout blocks, the checkbox to mark a subscription is not present.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

We would need a way to add content after each cart/checkout item, another great argument for having a Slot/Fill there.

It would need to send the data to the API when checking out or modifying the item on the Cart page to associate the recipient's email address with the subscription item. We could have this run as an AJAX request to the store API (using `extensionCartUpdate`) _before_ the checkout is posted.

This extension requires integration with: 

- [x] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [x] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| Cart/Checkout item summary | Unsure right now, but most sensible options seems to be adding a Slot and Filling it with a component | Add the checkbox/input field on each cart item that is a subscription  |  _8_   |
| Plugin's `IntegrationInterface` | API | Add an endpoint callback using [`register_update_callback`](https://github.com/woocommerce/woocommerce-blocks/blob/00a1174aebefae2b37178a3ded68cc6c8d56bbf4/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md#L3) which would update the session data with the recipient's email address  |  _7_   |
|                                                                             |                                                                               |
