### ISSUE TITLE
Audit: Google Listings & Ads

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9212]
## Google Listings & Ads

- **Author:** WooCommerce
- **Website:** https://woocommerce.com/products/google-listings-and-ads/
- **Repository:** (public) https://github.com/woocommerce/google-listings-and-ads

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by opr** [comment]
# Extension Audit Template

## Functionality Review

Allows merchants to automatically list their products on Google shopping and integrates Google Ads and Google merchant centre. It also adds analytics and fires events for some WooCommerce actions

This extension touches: *(mark all that apply)*

- [x] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [x] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [x] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

- Single Product Template - works OK, fires `form_start` and `form_submit` just like the regular PHP template based product.
- Single product Block - same as above.

Issues identified:
- 🚫 Products (Beta) - Does not fire the `add_to_cart` action like the shortcode products block does.
- ⚠️ Order confirmation page - works ok for now, in most cases (sometimes it doesn't fire, but I don't think that's blocks specific) however be careful when the order confirmation page is blockified, we should ensure the action still fires.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

When the order confirmation page is blockified, we should ensure the action still fires.
In the Products (Beta) block, we should ensure the add_to_cart event is fired.

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| Products (Beta) | Client API | Ensuring the `add_to_cart` event is fired when adding an item via this block |  _2_   |
| Checkout (Order confirmation) | Client API | Ensuring the `purchase` event is fired when checking out with the blockified order confirmation page |  _2_   |
|                                                                             |                                                                               |

**Comment by pmcpinto** [comment]
@jconroy just a heads up that the GLA extension has a compatibility issue with the Products (Beta) block.

**Comment by findingsimple** [comment]
Thanks @pmcpinto 

@mikkamp can you review and follow up with the team please? @puntope might be a good candidate for addressing.

**Comment by puntope** [comment]
> @mikkamp can you review and follow up with the team please? @puntope might be a good candidate for addressing.

If @mikkamp agrees, I can handle this in my porter next week. 👌

**Comment by mikkamp** [comment]
The `add_to_cart` hook is only used for analytics tracking and already has an alternative for blocks: https://github.com/woocommerce/google-listings-and-ads/blob/2.5.0/js/src/gtag-events/index.js#L18-L25

We can double check it though to make sure there wasn't any changes since we use the hook prefix `experimental__woocommerce_blocks` in case that's no longer experimental.

As for the Order Confirmation page, at the time of creating this wasn't fully "blockified" yet and was using a separate WP page which would call the hook. We can recheck this to make sure it's still valid.

> ⚠️ Order confirmation page - works ok for now, in most cases (sometimes it doesn't fire, but I don't think that's blocks specific) however be careful when the order confirmation page is blockified, we should ensure the action still fires.

@pmcpinto Do we have any details on which scenarios it doesn't fire even if it's not block specific?

@puntope I created a separate issue for it [here](https://github.com/woocommerce/google-listings-and-ads/issues/2020) which you can pick up during porter week.

**Comment by ralucaStan** [comment]
> When the order confirmation page is blockified, we should ensure the action still fires.
In the Products (Beta) block, we should ensure the add_to_cart event is fired.

@mikejolley could you check this one when you get the chance?

**Comment by puntope** [comment]
> > When the order confirmation page is blockified, we should ensure the action still fires.
> > In the Products (Beta) block, we should ensure the add_to_cart event is fired.
> 
> @mikejolley could you check this one when you get the chance?

I was testing this again with Products (Beta) and Checkout Block

Both Add to Cart event and purchase were showing up in the GA Debugger

**Add to Cart**

https://github.com/woocommerce/woocommerce-blocks/assets/5908855/f0ad8199-472f-4371-af75-7bb4d0f42e80

**Purchase** 

https://github.com/woocommerce/woocommerce-blocks/assets/5908855/44cfe725-dd57-4401-90ec-95713ac9013a

We will be happy if @mikejolley  can confirm.
