### ISSUE TITLE
Audit: Pinterest for WooCommerce

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9213]
## Pinterest for WooCommerce

- **Author:** WooCommerce
- **Website:** https://woocommerce.com/products/pinterest-for-woocommerce/
- **Repository:** (public) https://github.com/woocommerce/pinterest-for-woocommerce

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by message-dimke** [comment]
# Extension Audit Template

## Functionality Review

*Install and activate the extension, then going by the documentation, review it's frontend functionality focussing on how it influences products, cart, and the checkout.*

Sends events to Pinterest (init, page view, add to cart, checkout) so the merchants could see corresponding events under Ads > Conversions tab.

This extension touches: *(mark all that apply)*

- [x] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [x] Add to cart button
- [x] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [x] Add to cart form
- [ ] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [x] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

*See how the extension does or does not work when using Product Blocks, Cart Block, and Checkout Block. Does it work as expected? Is functionality that works with the shortcodes broken in the blocks context?*

Issues identified:
- For Products (Beta), Products by Category and Product by Attribute blocks there is a problem with AddToCart event - it is missing value attribute value (which is a product price).

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

*If the extension requires integrating with blocks, (mark all that apply) then summarize what is needed.*

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| _Location of new integration point, or name of existing integration point._ | _Type e.g. client API, action or filter hook, component, or server side API._ | _Describe what the integration point will be used for._ |  _1_   |
|                                                                             |                                                                               |

**Comment by message-dimke** [comment]
A corresponding Issue has been created https://github.com/woocommerce/pinterest-for-woocommerce/issues/761
