### ISSUE TITLE
Audit: Afterpay

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9224]
## Afterpay

- **Author:** Afterpay
- **Website:** https://woocommerce.com/products/afterpay/
- **Repository:** n/a

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by nielslange** [comment]
Tried to audit this extension, but we don't have a company account and Afterpay is not available for my location, leading to the fact that I cannot create an account for testing purposes.

**Comment by tarhi-saad** [comment]
# Extension Audit Template

## Functionality Review

> Afterpay allows customers to receive products immediately and pay for purchases over four installments, always interest-free.

This extension touches: *(mark all that apply)*

- [x] Products (Beta)
  - [x] Product template
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [x] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [x] Related products
  - [x] Product template
  - [ ] Product image
  - [ ] Product title
  - [ ] Product price
  - [ ] Add to cart button
- [x] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [x] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [ ] Shipping address
  - [ ] Billing address
  - [x] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

### The Cart Block

The express checkout is missing from the Cart Block:

| Short code version of the Cart                                | Cart Block                                                                 |
| ------------------------------------------------ | -----------------------------------------------  |
| <img width="633" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/6d57d6b3-1163-47e5-9ef6-84f7d4b42ab9"> | <img width="775" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/d39b1e24-9db3-4171-8c32-d3e0f803959c"> |

### The Products Block (Beta)

In the default shop page it shows the Afterpay information paragraph under the price of each product, but it's missing the Products Block version:

| The classic shop page                                | The Products Block (Beta)                                                                 |
| ------------------------------------------------ | -----------------------------------------------  |
| <img width="600" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/f921988f-b3ab-430a-a37f-da22a2448ed0"> | <img width="600" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/3c530a4c-aa57-4b50-87e0-d2152c6031e8"> |

### Single Product Block

Instead of displaying the Afterpay information paragraph under the product price, it's placed below the header of the page:

| The classic single product page                             | The Single Product Block                                                                 |
| ------------------------------------------------ | -----------------------------------------------  |
| <img width="1050" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/6cb7b8b5-ce48-4c01-8871-66279e3b7b72"> | <img width="1103" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/2d166a4c-c484-47b8-9499-8f3ef0fd5d0e"> |

### Related products Block

The Afterpay paragraph is missing in the Related products Block:

| The classic related products                            | The Related products Block                                                               |
| ------------------------------------------------ | -----------------------------------------------  |
| <img width="854" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/014dc294-89f3-470d-8775-e17e1c8454b1"> | <img width="983" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/160c9fb9-5259-48da-a213-fa575929fb09"> |

Issues identified:

- [ ] Extension is already fully compatible with Blocks
- [ ] Extension requires integration with Blocks
- [x] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

The payment method needs to be correctly registered in the blocks' context.

This extension requires integration with: 

- [ ] Cart Block
- [x] Checkout Block
- [ ] Payment Methods API
- [ ] Store API
- [x] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| Checkout block client | Registering the payment method with the block | Ensure the content property of the method contains the correct information, and the components required to load the modal also work correctly. | unknown |

**Comment by chesterz-afterpay** [comment]
Hi @nielslange @tarhi-saad ,
Looks like the Cart block and the group of similar Product blocks are relatively new. We managed to add Afterpay to the WC Checkout block only last year.
We have been reading through your [WooCommerce Blocks Handbook](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs), but could not seem to find any detailed implementation guide on how to inject code under the price tag in the Product blocks or under the total amount in the Cart block.
Could you please share more development guide with us? We would love to show our Afterpay messaging and add support for these new blocks.
Thank you in advance.

**Comment by tarhi-saad** [comment]
Hello, @chesterz-afterpay! 👋 Thank you for your comment! 🙌 

For the integration of the express payment methods, it can be found in the following links:

- [Client Side Integration: Express payment methods - registerExpressPaymentMethod( options )](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#express-payment-methods---registerexpresspaymentmethod-options-)
- [Server Side Integration](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#server-side-integration)

> We have been reading through your [WooCommerce Blocks Handbook](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs) but could not seem to find any detailed implementation guide on how to inject code under the price tag in the Product blocks or under the total amount in the Cart block.

We are reviewing our extensibility points. This audit was part of this work! I also suggest that you open a new ticket highlighting this specific extensibility request!

**Comment by senadir** [comment]
Hey @chesterz-afterpay do you happen to know if Aftepay figured out the integration with the remaining points? mainly Cart block? and if it's fully integrated with Checkout block?

**Comment by chesterz-afterpay** [comment]
> Hey @chesterz-afterpay do you happen to know if Aftepay figured out the integration with the remaining points? mainly Cart block? and if it's fully integrated with Checkout block?

Hi @senadir ,
Yes, the Afterpay plugin is fully integrated with Checkout block, and has added support for the Cart block since v3.7.0 of the plugin, which was release on 31 Oct 2023.
