### ISSUE TITLE
Audit: Envia Shipping and Fulfillment

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#9233]
## Envia Shipping and Fulfillment

- **Author:** Envia Shipping and Fulfillment
- **Website:** https://woocommerce.com/products/envia-shipping-and-fulfillment/
- **Repository:** n/a

_This issue is to track compatibility testing between this extension and the Cart and Checkout blocks. [See the epic for the audit template](https://github.com/woocommerce/woocommerce-blocks/issues/9206) which should be completed and posted as a comment here once completed._

**Comment by tarhi-saad** [comment]
# Extension Audit Template

## Functionality Review

> Parcel, courier and consolidated cargo shipments at the best price.

This extension touches: *(mark all that apply)*

- [ ] Products (Beta)
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart button
- [ ] Single Product Pages
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Add to cart form
- [x] Cart Page
  - [ ] Cart items
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product quantity
  - [ ] Cart totals
  - [ ] Notices
  - [ ] Custom functionality
- [x] Checkout Page
  - [ ] Checkout fields
  - [ ] Express checkout
  - [ ] Contact information
  - [ ] Shipping method
  - [ ] Pickup method
  - [x] Shipping address
  - [ ] Billing address
  - [ ] Payment options
  - [ ] Checkout totals
  - [ ] Product title
  - [ ] Product price
  - [ ] Product meta
  - [ ] Product meta
  - [ ] Notices
  - [ ] Custom functionality
  - [ ] Order received page
- [ ] My Account Page
- [ ] Store API
  - [ ] Edits existing endpoint
  - [ ] Adds custom endpoint
- [ ] Settings
  - [ ] WooCommerce settings
  - [ ] Custom settings page
  - [ ] Customizer 

## Compatibility with Blocks

Issues identified:

The **Envia Shipping and Fulfillment** extension isn't compatible with the Cart & Checkout Blocks. Even though we can see the list of Envia's shipping options under their shipping sections (see the images below), some critical functionalities don't work as expected.

| Cart Block — Shipping section | Checkout Block — Shipping section |
| ------------------------------ | ----------------------------------- |
| <img width="598" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/96a64abd-9408-47d4-9d15-799e059be088"> | <img width="652" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/97e0b2f8-183f-45e4-bd33-c8ae5b2c9a99"> |

### We can't change the shipping option on the Cart & Checkout Blocks

If we try to select another shipping option on the Cart or Checkout Blocks, our choice won't be registered, and an error message will be displayed on the page:

<img width="595" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/54ba44a3-3870-4d9b-b17f-2a6785082c27">

### We can't place an order in the Checkout Block

In the Checkout Blocks, if we click on the "Place Order" button, the following error message is displayed on the page:

<img width="765" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/d80d7f6a-43d5-42c9-abcd-d9da92e43da8">

And if we check the Network tab in the Browser's console we have the following body as a response:

```JSON
{
    "code": "woocommerce_rest_invalid_shipping_option",
    "message": "Sorry, this order requires a shipping option.",
    "data": {
        "status": 400
    }
}
```

This means, Envia's shipping options aren't recognized by the Cart & Checkout Blocks.

*Select those that apply:*

- [ ] Extension is already fully compatible with Blocks
- [x] Extension requires integration with Blocks
- [ ] Extension requires fixes in the blocks context
- [ ] Extension could be further enhanced to take advantage of Blocks

## Integration Required

This extension requires integration with: 

- [ ] Cart Block
- [ ] Checkout Block
- [ ] Payment Methods API
- [x] Store API
- [ ] Other

### Integration Points

*List specific integration points you think the extension will need in order to be supported in the Blocks context.*

| Location                                                                    | Type                                                                          | Description                                             | Effort |
| --------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------------- | :----: |
| API | Store API | Envia's shipping methods should be correctly registered on the Store API  |  _2_   |
