### ISSUE TITLE
Single Product Block Causing Fatal Error on Product Pages For Logged Out Users When Jetpack woocommerce-analytics Module is Active

### ISSUE THREAD

**Issue by katiebethbrown** [woocommerce/woocommerce-gutenberg-products-block#9453]
## Describe the bug

When using the Single Product Block, single product pages return a fatal error for logged out users when the Jetpack `woocommerce-analytics` module is active.

## To reproduce

1. Enable the WooCommerce Analytics Jetpack module.
2. Use the single product block on the single product template.
3. Create a product.
4. Visit the product page on the front end when logged out.
5. See fatal error.

## Expected behavior

For the single product page to load for logged out users.

## Error

```
[11-May-2023 23:26:28 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_id()on string in /wordpress/plugins/jetpack/12.2-a.5/modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-universal.php:264
Stack trace:
#0 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): Jetpack_WooCommerce_Analytics_Universal->capture_product_view('')
#1 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/plugins/woocommerce/7.7.0/packages/woocommerce-blocks/src/Templates/AbstractTemplateCompatibility.php(196): do_action('woocommerce_aft...')
#4 /wordpress/plugins/woocommerce/7.7.0/packages/woocommerce-blocks/src/Templates/SingleProductTemplateCompatibility.php(106): Automattic\WooCommerce\Blocks\Templates\AbstractTemplateCompatibility->get_hooks_buffer(Array, 'after')
#5 /wordpress/plugins/woocommerce/7.7.0/packages/woocommerce-blocks/src/Templates/SingleProductTemplateCompatibility.php(39): Automattic\WooCommerce\Blocks\Templates\SingleProductTemplateCompatibility->inject_hook_to_first_and_last_blocks('\n\t\t\t\t<div class...', Array, Array)
#6 /wordpress/plugins/woocommerce/7.7.0/packages/woocommerce-blocks/src/Templates/AbstractTemplateCompatibility.php(71): Automattic\WooCommerce\Blocks\Templates\SingleProductTemplateCompatibility->inject_hooks('\n\t\t\t\t<div class...', Array)
#7 /wordpress/core/6.2/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Blocks\Templates\AbstractTemplateCompatibility->Automattic\WooCommerce\Blocks\Templates\{closure}('\n\t\t\t\t<div class...', Array)
#8 /wordpress/core/6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters('\n\t\t\t\t<div class...', Array)
#9 /wordpress/core/6.2/wp-includes/class-wp-block.php(293): apply_filters('render_block', '\n\t\t\t\t<div class...', Array, Object(WP_Block))
#10 /wordpress/core/6.2/wp-includes/blocks.php(1051): WP_Block->render()
#11 /wordpress/core/6.2/wp-includes/blocks.php(1089): render_block(Array)
#12 /wordpress/core/6.2/wp-includes/block-template.php(240): do_blocks('<!-- wp:templat...')
#13 /wordpress/core/6.2/wp-includes/template-canvas.php(12): get_the_block_template_html()
#14 /wordpress/core/6.2/wp-includes/template-loader.php(106): include('/wordpress/core...')
#15 /wordpress/core/6.2/wp-blog-header.php(19): require_once('/wordpress/core...')
#16 /wordpress/core/6.2/index.php(17): require('/wordpress/core...')
#17 {main}
  thrown in /wordpress/plugins/jetpack/12.2-a.5/modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-universal.php on line 264
  ```

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): 15.7.1
-   WooCommerce version: 7.7.0
-   WooCommerce Blocks version: 10.2.0
-   Site language: English
-   Any other plugins installed: WordPress.com eCommerce plan managed plugins
-   Jetpack version: 12.2-a.5

## Additional context

We're running into this on a Team51 partner site. Per the dev:

> The problem is the plugin woo-gutenberg-products-block at woo-gutenberg-products-block/src/BlockTypes/AddToCartForm.php Line 52

> The function access global $product

https://github.com/woocommerce/woocommerce-blocks/blob/cde9117c9d57fe9a4c81501214d837e984a6c76a/src/BlockTypes/AddToCartForm.php#L27-L28

> Then overwrites it

https://github.com/woocommerce/woocommerce-blocks/blob/cde9117c9d57fe9a4c81501214d837e984a6c76a/src/BlockTypes/AddToCartForm.php#L45-L56

Related issue in the JP repo:
https://github.com/Automattic/jetpack/issues/11301#issuecomment-1544826870

**Comment by otakupahp** [comment]
I know hot to solve this, so I would like to do it. But I don't know how to :p

**Comment by nerrad** [comment]
cc @danielwrobert and @tjcafferkey - this should be prioritized by the team when folks come online next. The code shouldn't be overwriting the global here. It'd be good to review other blocks and ensure there are no other incorrect global overwrites.

**Comment by nerrad** [comment]
Yah there are other places too:

- [Product Image Gallery Block](https://github.com/woocommerce/woocommerce-blocks/blob/cde9117c9d57fe9a4c81501214d837e984a6c76a/src/BlockTypes/ProductImageGallery.php#L42-L43)
- [Single Product Block](https://github.com/woocommerce/woocommerce-blocks/blob/cde9117c9d57fe9a4c81501214d837e984a6c76a/src/BlockTypes/SingleProduct.php#L124-L149) - might be okay but needs a closer look - at a minimum it looks like the code can be cleaned up a bit. This is also might be a place where the Block Context API can be used instead of global manipulation.

**Comment by thealexandrelara** [comment]
> * [Single Product Block](https://github.com/woocommerce/woocommerce-blocks/blob/cde9117c9d57fe9a4c81501214d837e984a6c76a/src/BlockTypes/SingleProduct.php#L124-L149) - might be okay but needs a closer look - at a minimum it looks like the code can be cleaned up a bit. This is also might be a place where the Block Context API can be used instead of global manipulation.

Regarding the Single Product block currently we have to overwrite the `global $post` variable because some of the inner blocks that are being used, are variations of the Post Excerpt and Post Title blocks that were not consuming the `postId` from the context. There were two PRs created and merged in Gutenberg that addressed this issue:

- [[Post excerpt > Ensure the postId from the block context is used to get_the_excerpt](Post excerpt > Ensure the postId from the block context is used to get_the_excerpt](https://github.com/WordPress/gutenberg/pull/49495)
- [Post Title: Peformance: render_block_core_post_title - Use post object instead of id](https://github.com/WordPress/gutenberg/pull/48001/files)

As soon as these changes are merged in the core of WP we can get rid of that piece of code, because we can rely on the `postId` being consumed from the context.

**Comment by nefeline** [comment]
Hi there!

The Add to Cart Form block and the Product Gallery Block fixes are available over here (with a topic open for discussion):

* https://github.com/woocommerce/woocommerce-blocks/pull/9457
* https://github.com/woocommerce/woocommerce-blocks/pull/9475

Regarding the Single Product block, complementing @thealexandrelara 's response:

As he mentioned, we have already upstreamed changes to the core of Gutenberg to prevent the global variable overwrite; the only problem is that those are not yet part of the core of WordPress (WP is currently running [GB version 15.1](https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/): the fix for the post title comes with GB 15.2 & the fix for the excerpt is on GB version 15.6), so we've decided to keep the "hacky" approach in place until they do. 

It is also important to mention that this block (the Single Product block) [is experimental](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/bin/webpack-entries.js#L68), available only on dev builds as it is still not ready for usage by the general public.

**Comment by katiebethbrown** [comment]
> It is also important to mention that this block (the Single Product block) [is experimental](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/bin/webpack-entries.js#L68), available only on dev builds as it is still not ready for usage by the general public.

@nefeline Circling back to note that we're showing the option to convert to the blockified single product template in the site editor on WPcom Commerce sites (where I ran into this) with no warning or notice that this shouldn't be used on production sites.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/42279181/3b04d4ab-7414-43f0-ac8c-04c348fb10cd)

Is that expected?

EDIT:
Ah, I realize now that I added the additional blocks plugin to use the mini cart and hadn't realized that this behavior was stemming from it instead of core. 

Given the experimental status of this (and potentially all other components in the plugin?) would you suggest we avoid the blocks plugin completely on production Team51 sites?

**Comment by nerrad** [comment]
Hi Katie, it's no longer experimental :)

**Comment by nefeline** [comment]
Hi there @katiebethbrown !

> Circling back to note that we're showing the option to convert to the blockified single product template in the site editor on WPcom Commerce sites (where I ran into this) with no warning or notice that this shouldn't be used on production sites.

As Darren already highlighted, this is not an experimental feature anymore :) 

The Single Product block became [available for general usage](https://github.com/woocommerce/woocommerce-blocks/pull/9714) on June 8th (release [10.4.0](https://github.com/woocommerce/woocommerce-blocks/releases)).

> Given the experimental status of this (and potentially all other components in the plugin?) would you suggest we avoid the blocks plugin completely on production Team51 sites?

It is now available for usage on production sites: looking forward to hearing your thoughts/experience with it!

**Comment by katiebethbrown** [comment]
> As Darren already highlighted, this is not an experimental feature anymore :)

@nefeline - Ah, I missed this. Thank you!

> It is now available for usage on production sites: looking forward to hearing your thoughts/experience with it!

So far all good other than the analytics issues! We ran into something similar to this issue (a fatal for logged out users) when enabling the Google Analytics enhanced ecommerce option, but that was earlier and it seems likely that the fix for this issue also resolved that one. 

Thanks again!

**Comment by nerrad** [comment]
@katiebethbrown the GA issue came up in another project as well on WPcom (GG) and it is related to customized single product templates where there is no post content block in the template. GA makes an assumption about the `$product` global always being present and that isn't always the case. This is a separate issue and won't be fixed by what was reported here.

**Comment by katiebethbrown** [comment]
Ah, that's really helpful info. Thank you @nerrad!
