### ISSUE TITLE
Blockified Single Product Template: Modify the default header level for the product title from h2 to h1

### ISSUE THREAD

**Issue by xristos3490** [woocommerce/woocommerce-gutenberg-products-block#9695]
### Description

The product title block in the single product template currently utilizes an 'h2' heading level, which seems not semantically accurate. It would be more appropriate to use an `h1` level instead.

**Comment by Sadaf-A** [comment]
Greetings @xristos3490, I would love to work on this!

**Comment by gigitux** [comment]
Hi @xristos3490,
Thanks for opening this issue! Great observation!

@Sadaf-A, thanks for proposing to work on it. It is necessary to update [this line](https://github.com/woocommerce/woocommerce-blocks/blob/843633041e6a497b21f551283ff06694c973ca31/templates/templates/blockified/single-product.html/#L18-L19) adding `"level":1`. Keep in mind that we have some time constraints since we want to include this change in the next release (next week), so I could open a PR before my EOD if you can't do it.

**Comment by Sadaf-A** [comment]
@gigitux I'm a beginner so I'm not sure if I can finish it within the given timeframe.
you could open a PR.

**Comment by gigitux** [comment]
@Sadaf-A If you want to contribute to WooCommerce Blocks, we have several issues labeled as "good first issue". You can check them [here](https://github.com/woocommerce/woocommerce-blocks/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). 
For any questions, you can add a comment on the specific issue!
