### ISSUE TITLE
Condensed Address Forms for returning shoppers

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#9787]
For returning customers we'd like to hide the full address form and instead present their previous address. Editing should be possible, but in most cases we believe the customer will keep whatever they used previously. 

## Expected result

- Guest customers, or registered users with no address saved, coming to the checkout should see the whole checkout form
- Returning customers that have address information saved should see an address summary
<img src="https://user-images.githubusercontent.com/5121465/256912043-7b694667-fcf0-4d96-b360-af571f071bc3.png" />
- On “Change” link click the shopper will see the standard form
- Changing the option for same billing/shipping addresses shows the forms as well

https://github.com/woocommerce/woocommerce-blocks/assets/1628454/b6b8c37c-317b-4c0d-8842-b68cad8e4b6a

A POC exists for this functionality already here:
https://github.com/woocommerce/woocommerce-blocks/pull/8559

More context about the implementation in this comment pdFofs-JJ-p2#comment-753
Design file: Xcn9ZirCFwU451IQZxMAcb-fi-4749%3A91188

**Comment by masteradhoc** [comment]
@mikejolley great idea and well done. Would love to see and test this in an upcoming release.

**Comment by pmcpinto** [comment]
@shaunandrews can you take a look at how the condensed address is displayed for returning shoppers? Thanks

**Comment by ralucaStan** [comment]
Having a condensed address is a good solution for the use case of shops that don’t want to allow users to change their billing and/or shipping addresses. More info pdFofs-19d-p2

**Comment by pmcpinto** [comment]
@elizaan36 just to confirm: are you going to propose a design for the condensed address UI or should we assign someone else?

**Comment by elizaan36** [comment]
Yes, we already have the design for this. It looks like we've gone back and forth on the final solution in the POC already. Could you share the demo site again to test this out? I'll also share a P2 with the collapsed components system and other design details.

**Comment by ralucaStan** [comment]
@elizaan36 you can use the archive from [this comment ](https://wcblocks.wpcomstaging.com/wp-content/uploads/woocommerce-gutenberg-products-block-8559.zip) on [the POC](https://github.com/woocommerce/woocommerce-blocks/pull/8559) PR to have a zip of the plugin with this work included. You can swap your current Blocks plugin with the one in the comment.

**Comment by pmcpinto** [comment]
> Yes, we already have the design for this. It looks like we've gone back and forth on the final solution in the POC already. Could you share the demo site again to test this out? I'll also share a P2 with the collapsed components system and other design details.

@elizaan36 thanks. I'm looking forward to seeing the P2.

**Comment by elizaan36** [comment]
hey team, I'll share the design for condensed address component here since the scope of the p2 is getting bigger. :)

Video: https://www.loom.com/share/796b8612eda44d8196a658a04040514b?sid=7a6eb689-1980-4b58-bff6-c51b7397dcba

<img width="1439" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/7b694667-fcf0-4d96-b360-af571f071bc3">

There are some inconsistencies we need to unify on the checkout block overall, regarding border corner radius and padding mainly. Will share more details soon.

This component uses the lighter border color used for the payment methods to indicate that it's saved and there's an edit link that expands the form. I intentionally removed icons for this version but we have an option with icons as well since this could be a nice future enhancement for the checkout block.

Let me know if you have any questions.

**Comment by pmcpinto** [comment]
@elizaan36 thanks for sharing the design 🙌  I'd like to clarify some details:

- Do we keep the Edit button on the top right corner when the shopper is on a mobile device?
- If the shopper selects the new local pickup option, the billing address defaults to the existing shipping address. Should we apply the condensed address component in this option or show the input fields (current behavior)?

**Comment by elizaan36** [comment]
> Do we keep the Edit button on the top right corner when the shopper is on a mobile device?

I think we could, but we'd need to reduce the padding so that the address column has enough width to appear alongside the edit link and not overlap. It would be odd for the link to move to a different location, however transitioning to an icon is also a possibility. Thoughts?
<img width="780" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/e28ebad4-6d19-46d7-b794-e3843c731947">

> the billing address defaults to the existing shipping address. Should we apply the condensed address component in this option or show the input fields (current behavior)?

Oh interesting. I think there it may be more prone to error in this case if the billing address is collapsed. The user may not expect this change, whereas if the form is shown they have a sense that it's still in progress and may be more likely to check/edit.

**Comment by pmcpinto** [comment]
> I think we could, but we'd need to reduce the padding so that the address column has enough width to appear alongside the edit link and not overlap. It would be odd for the link to move to a different location, however transitioning to an icon is also a possibility. Thoughts?

Both options seem a good solution for mobile.

> Oh interesting. I think there it may be more prone to error in this case if the billing address is collapsed. The user may not expect this change, whereas if the form is shown they have a sense that it's still in progress and may be more likely to check/edit.

👍 let's keep the form for billing address in this use case.

**Comment by ralucaStan** [comment]
With this change, we are introducing an animation. Is there any information you can export about the parameters of the animation @elizaan36?

**Comment by elizaan36** [comment]
Hi @ralucaStan, let me know if the info I shared in Slack is sufficient. (I can't find that thread now😆)

**Comment by ralucaStan** [comment]
Info about the animation p1691528764489189/1691421203.288889-slack-C8X6Q7XQU

Looks like Figma only exports this code for the animation. @elizaan36 I propose we sync once we have a working POC to tweak the animation.

```css
animation-timing-function: ease-out;
animation-duration: 300ms;
```

**Comment by ralucaStan** [comment]
Please see this comment on the PR before starting work on this https://github.com/woocommerce/woocommerce-blocks/pull/8559#issuecomment-1699306662

**Comment by passatgt** [comment]
This looks nice. What about compatibility with local pickup?

**Comment by ralucaStan** [comment]
@passatgt We're happy you like the condensed address. Could you extend your question about the compatibility with local pickup?
